makeplane/plane

- apps/app/components/analytics/scope-and-demand/leaderboard.tsx
- apps/app/components/analytics/scope-and-demand/scope-and-demand.tsx
- apps/app/components/core/activity.tsx
- apps/app/types/analytics.d.ts
chore: 
- user redirection functionality added in issue activity and analytics leaderboard.
> chore: issue activity user redirection added

- apps/app/components/core/image-picker-popover.tsx
- apps/app/pages/[workspaceSlug]/me/profile/index.tsx
- apps/app/types/users.d.ts
chore: 
- profile cover photo option added in profile setting
> chore: profile cover photo

- apps/app/pages/[workspaceSlug]/projects/index.tsx
chore: 
- project search added in project list page
> chore: project search added in project list page

- apps/app/components/command-palette/change-interface-theme.tsx
fix: 
- cmdk not changing theme if the active theme is custom-theme
> fix: cmdk not changing theme if active theme is custom-theme

- apiserver/plane/api/views/issue.py
fix:
- sub issue done count 
Fixes: #1803
> fix: sub issue endpoint for state distribution

- apps/app/components/labels/create-label-modal.tsx
- apps/app/components/labels/create-update-label-inline.tsx
- apps/app/constants/label.ts
- apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/labels.tsx
feat: 
- a random color is picked on 'create label' instead of a hard-coded value.
Before:
After:
fix: 
- form-data in 'create label' persist values from 'edit label' on the project settings page. 
Before:
https://github.com/makeplane/plane/assets/65905942/71c65193-c26e-4b74-a5fc-ad7075d8688b
After:
https://github.com/makeplane/plane/assets/65905942/aaa99a0f-0a03-4a35-825c-509c66d3ddad
> feat: randomize color on label create

- apps/app/components/workspace/delete-workspace-modal.tsx
- apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/index.tsx
- apps/app/pages/[workspaceSlug]/settings/index.tsx
chore: 
- user permissions for project and workspace update and delete actions have been updated.
> chore: updated user permission for project and workspace settings

- apps/app/components/issues/sub-issues-list.tsx
fix: 
- sub issue progress indicator fix
> fix: sub issue progress indicator fix

- apps/app/components/core/views/spreadsheet-view/single-issue.tsx
- apps/app/components/issues/view-select/start-date.tsx
- apps/app/constants/spreadsheet.ts
chore: 
- start date option added in spreadsheet view
> chore: start date option added in spreadsheet view

- package.json
Fix "MIT" to "AGPL-3.0" along with `LICENSE` file.
> package.json: fix license

- apps/app/components/cycles/cycles-list-gantt-chart.tsx
- apps/app/components/gantt-chart/helpers/draggable.tsx
- apps/app/components/gantt-chart/hooks/block-update.tsx
- apps/app/components/modules/modules-list-gantt-chart.tsx
https://github.com/makeplane/plane/assets/65252264/ae494141-ff1b-4641-8854-c628ba6acce6
Other changes-
- refactor draggable component code structure.
> fix: gantt chart block left drag flicker

- apps/app/components/workspace/sidebar-quick-action.tsx
- apps/app/pages/[workspaceSlug]/me/profile/activity.tsx
This PR addresses the loading issue in the profile activity section and resizing of sidebar quick action icon.
Before the fix:
After the fix: 
Before the fix:
After the fix:
> style: profile activity loader

- apiserver/plane/api/views/integration/slack.py
fix: 
- slack queryset to list and retrieve slack connected projects
> fix: slack queryset

- apiserver/plane/bgtasks/export_task.py
chore: file name changed for exported issues
> chore: file name changed for exported issues

- apiserver/plane/api/serializers/project.py
- apiserver/plane/api/views/project.py
chore: 
- status for deployed projects in project list and retrieve endpoint
> chore: deploy board status for project

- apiserver/plane/api/views/project.py
- apiserver/plane/api/views/workspace.py
fix: members list filtering for workspace and projects to remove bot accounts
> fix: members list filtering for workspace and projects

- apiserver/plane/bgtasks/issue_activites_task.py
Enhancement: Implemented comprehensive validation for issue activity for the tracking the issue descriptions.
> fix: validation for issue activity description

- setup.sh
Modified `setup.sh` script to take `TipTap Pro Extensions` Auth Token on the file and generate a new `.npmrc` file.
> chore: Edited Setup Script to take TipTap Auth Token and Generate .npmrc

- apiserver/plane/api/views/workspace.py
chore: renamed target date to start date in the upcoming issues in workspace
> chore: renamed target date to start date

- apiserver/plane/db/migrations/0041_cycle_sort_order_issuecomment_access_and_more.py
- apiserver/plane/db/models/module.py
chore: updated title field in module link model
> chore: module link model

- apps/app/components/workspace/issues-list.tsx
- apps/app/types/issues.d.ts
> fix: dashboard upcoming issues list

- apiserver/plane/api/views/workspace.py
> fix: priority ordering

- apps/app/components/workspace/create-workspace-form.tsx
chore:
- update restricted workspace slugs.
> chore: update restricted workspace slugs

- docker-compose.yml
fix: plane space start up command
> fix: plane space start up command

- apiserver/plane/bgtasks/export_task.py
fix: aws region changed for exporter
> fix: aws region changed for exporter

- apiserver/plane/bgtasks/export_task.py
fix: aws region changed for exporter (#1933)
> fix: aws region changed for exporter (#1933)

- docker-compose-hub.yml
- docker-compose.yml
- nginx/nginx.conf.template
dev: deploy docker containers (#1939)
> dev: deploy docker containers (#1939)

- apiserver/plane/api/serializers/cycle.py
- apiserver/plane/api/serializers/module.py
fix: added date validation in cycle and module
> fix: cycle and module date validation

- apps/app/styles/globals.css
- apps/app/tailwind.config.js
chore:
- custom css shadow variables added for sidebar and body only for the predefined themes.
> chore: custom CSS shadow variables added

- apps/app/components/project/delete-project-modal.tsx
- apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/index.tsx
https://github.com/makeplane/plane/assets/65252264/5ea791fa-8cb3-4f88-b38a-3e8dfc0e9c66
> fix: redirection after deleting a project

- apps/app/components/core/activity.tsx
chore:
- redirect to cycle and module from t=the issue activity log.
> chore: issue activity redirection to cycle and module

- apiserver/plane/api/views/project.py
fix: 
- update the create response object to return member status and member role.
> fix: add member role and member status in project create response

- apiserver/plane/api/serializers/project.py
fix
- Project Members list n+1
> fix: project members n+1

- apps/app/components/profile/sidebar.tsx
> chore: don't show completion percentage if user doesn't have any assigned issues

- apiserver/plane/api/urls.py
- apiserver/plane/api/views/user.py
chore: update user activity endpoint to return only workspace activities
> chore: update user activity endpoint to return only workspace activities

- apiserver/Procfile
> dev: remove gunicorn config

- apps/app/constants/timezones.ts
- apps/app/pages/[workspaceSlug]/me/profile/index.tsx
- apps/app/types/users.d.ts
> feat: user timezone select option in profile settings

- apiserver/plane/api/views/workspace.py
> fix: user created by stats

- apiserver/plane/api/views/asset.py
fix: added asset key validation to verify the existence of the key
> fix: asset key validation

- apps/app/components/project/publish-project/modal.tsx
- apps/app/components/project/publish-project/popover.tsx
- apps/app/components/project/single-sidebar-project.tsx
- apps/app/store/project-publish.tsx
This PR makes the following changes on the project publish modal-
1. Added options to toggle comments, reactions and votes.
1. Utilize `react-hook-form` in a better way by using `Controller` component and remove `watch` from wherever possible.
2. Add an `Update` button to update the publish settings instead of auto-saving on change.
3. Refactor code for better readability.
4. Define types for places without any type.
1. Improved consistency and optimized the dropdown.
> dev: revamp publish project modal

- apiserver/plane/api/serializers/issue.py
chore: return issue votes in public issue list endpoint
> chore: return issue votes in public issue list endpoint

- apps/app/components/tiptap/index.tsx
- apps/app/components/tiptap/table-menu/index.tsx
- apps/app/styles/editor.css
- apps/app/styles/globals.css
1. Fixed the table menu position.
2. Polished the table menu design.
3. Polished table borders and other designs.
> style: tiptap table

- apiserver/plane/api/views/issue.py
fix: subscribed issues are filtering
> fix: subscribed issues are filtering

- apiserver/plane/api/views/cycle.py
chore: cycle endpoint to return display name as well in the assignee distribution
> chore: cycle endpoint to return display name as well in the assignee distribution

- apiserver/plane/db/migrations/0042_alter_analyticview_created_by_and_more.py
fix: imported the uuid in the migration file
> fix: migration error 

- apps/app/components/project/send-project-invitation-modal.tsx
chore:
- updates project invite placeholder.
> chore: updates project invite placeholder

- apiserver/plane/api/serializers/issue.py
> chore: vote actor details

- apps/app/hooks/use-user-notifications.tsx
This PR includes mutation fix that addresses notifications count not updating correctly when the "Mark All as Read" action is performed.
> fix: notification count mutation fix

- apps/space/components/issues/navbar/index.tsx
- apps/space/components/issues/peek-overview/issue-activity.tsx
- apps/space/pages/index.tsx
- apps/space/store/user.ts
chore:
1. Sign in button added to the navbar and the comment section.
2. Fixed redirection to `next_path` after sign in.
> chore: sign in options added

- apiserver/plane/db/migrations/0042_alter_analyticview_created_by_and_more.py
- apiserver/plane/db/models/issue.py
> fix: issue vote constraints

- apps/app/components/issues/sidebar-select/blocked.tsx
- apps/app/components/issues/sidebar-select/blocker.tsx
- apps/app/components/issues/sidebar-select/cycle.tsx
- apps/app/components/issues/sidebar-select/module.tsx
fix:
- issue details sidebar cycle and module select.
> fix: sidebar cycle and module select

- apps/app/components/issues/peek-overview/layout.tsx
- apps/space/components/issues/peek-overview/layout.tsx
fix:
- Peek overview size not changing when switching from full screen to modal peek.
> fix: peek overview layout switch

- web/components/cycles/gantt-chart/cycle-issues-layout.tsx
- web/components/cycles/gantt-chart/cycles-list-layout.tsx
- web/components/issues/gantt-chart/layout.tsx
- web/components/modules/gantt-chart/module-issues-layout.tsx
- web/components/modules/gantt-chart/modules-list-layout.tsx
- web/components/views/gantt-chart.tsx
This PR focuses on adding authorization to the Gantt chart.
> chore: add authorization to the gantt chart

- apiserver/plane/api/views/cycle.py
chore:
- Update only `sort_order` when the cycle has already been completed
> chore: cycle update errors

- apiserver/plane/api/views/issue.py
fix: state ordering for project public boards
> fix: state ordering for project public boards

- space/pages/_app.tsx
- space/public/site.webmanifest.json
fix:
- favicon route updated.
chore:
- site webmanifest file added.
> fix: favicon path on Plane space

- web/components/project/send-project-invitation-modal.tsx
fix:
- project invite modal members filter function.
chore:
- add full name along with the display name in the project invite modal"
> fix: project invite modal members filter function

- web/components/core/views/all-views.tsx
- web/components/core/views/board-view/all-boards.tsx
- web/components/core/views/board-view/single-board.tsx
- web/components/core/views/list-view/all-lists.tsx
- web/components/core/views/list-view/single-list.tsx
- web/components/issues/my-issues/my-issues-view.tsx
- web/components/profile/profile-issues-view.tsx
chore: 
- add issue option removed from subscribed issue page
> chore: add issue option removed from subscribed issue page

- apiserver/plane/bgtasks/issue_automation_task.py
fix: added  a validation in automation task
> fix: validation in automation task

- apiserver/plane/api/views/workspace.py
- apiserver/plane/bgtasks/issue_automation_task.py
- apiserver/plane/utils/analytics_plot.py
fix: issue object for filtering
> fix: issue object for filtering

- apiserver/plane/api/views/issue.py
fix: public issue list endpoint n+1
> fix: public issue list endpoint n+1

- web/components/core/modals/existing-issues-list-modal.tsx
- web/components/issues/parent-issues-list-modal.tsx
- web/pages/[workspaceSlug]/projects/[projectId]/settings/index.tsx
- web/pages/[workspaceSlug]/settings/index.tsx
- workspace level typo fix
- setting page opacity fix
> fix: ui improvement and bug fixes

- apiserver/plane/api/views/issue.py
fix: issue comment ordering for public boards
> fix: issue comment ordering for public boards

- space/components/accounts/onboarding-form.tsx
fix:
- onboarding role select dropdown text color.
> fix: onboarding role select dropdown text color

- web/components/web-view/activity-message.tsx
- web/components/web-view/index.ts
- web/components/web-view/issue-activity.tsx
- web/components/web-view/issue-web-view-form.tsx
- web/components/web-view/web-view-modal.tsx
- web/layouts/web-view-layout/index.tsx
fix: 
- options list overflowing 
- links in the issue activity component
> fix: issue activity

- web/layouts/web-view-layout/index.tsx
- web/pages/m/[workspaceSlug]/editor.tsx
fix: 
- authorized editor for web-view
> fix: authorized editor for web-view

- .github/workflows/Update_Docker_Images.yml
- docker-compose-hub.yml
- docker-compose.yml
- package.json
> chore: added pre-release tag for workflow publications

- web/components/core/views/calendar-view/calendar.tsx
fix: 
- calendar issues display filters loop fix.
> fix: calendar issues display filters loop fix

- apiserver/plane/api/views/issue.py
- apiserver/plane/utils/grouper.py
feat: changed issues payload for swimlanes
> feat: changed payload for swimlanes

- apiserver/plane/db/models/project.py
- apiserver/plane/db/models/workspace.py
chore: changed default props for workspace and project members
> chore: changed default props for workspace and project members

- apiserver/plane/api/views/cycle.py
- apiserver/plane/api/views/issue.py
- apiserver/plane/api/views/module.py
fix: added sub groups in cycle module and my issues for swimlanes
> fix: sub groups in cycle module and my issues

- apiserver/plane/api/views/cycle.py
- apiserver/plane/api/views/issue.py
- apiserver/plane/api/views/module.py
- apiserver/plane/utils/grouper.py
fix: changed payload for issue subgroups and added subgroups in cycle module and my issues
> fix: changed payload for issue subgroups

- apiserver/plane/bgtasks/issue_activites_task.py
fix: tracking logs for issue activity
> fix: tracking logs for issue activity

- apiserver/plane/api/views/issue.py
fix: changed time to timestamp
> fix: changed time to timestamp

- web/components/ui/product-updates-modal.tsx
refactor:
1. Product updates modal structure.
style:
1. Made the modal title sticky.
2. Increased the width of the modal.
3. Changed the spinner loader with the skeleton loader.
> refactor: product updates modal layout

- web/components/analytics/custom-analytics/graph/index.tsx
- web/helpers/array.helper.ts
fix:
- `findStringWithMostCharacters` function error handling when an empty array is passed.
> fix: helper function to handle array with no elements

- web/components/issues/main-content.tsx
- web/components/issues/sub-issues/issue.tsx
- web/components/issues/sub-issues/issues-list.tsx
- web/components/issues/sub-issues/progressbar.tsx
- web/components/issues/sub-issues/properties.tsx
- web/components/issues/sub-issues/root.tsx
Fixes in this pull request include:
1. Implementation of new issue creation and addition to existing issue mutation.
2. Mutation for assigning issues.
3. Display of issue delete loaders.
> fix: issues resolved in sub issues

- apiserver/plane/api/views/workspace.py
chore: added state and priority order in workspace user profile
> chore: added state and priority order in workspace user profile

- web/components/analytics/scope-and-demand/scope.tsx
- web/components/project/single-project-card.tsx
- web/pages/[workspaceSlug]/index.tsx
Resolved the following issues in this pull request:
Addressed the pending issue graph in analytics.
Implemented user wishes in the dashboard.
Fixed a typo in the projects list.
> fix: fixed issues in workspace level

- apiserver/plane/db/models/project.py
- apiserver/plane/db/models/workspace.py
chore: changed priority props in workspace and project
> chore: changed priority props in workspace and project

- web/components/issues/sub-issues/properties.tsx
fix: 
- sub issue state and member select build error
> fix: sub issue state and member select build error

- web/components/core/views/inline-issue-create-wrapper.tsx
- web/components/issues/delete-draft-issue-modal.tsx
- web/components/issues/draft-issue-form.tsx
- web/components/issues/draft-issue-modal.tsx
fix: 
- draft issue delete not working
- project can't be changed from the draft issue modal
refactor:
- removed mutation for view(or layout) where we don't show draft issues 
feat:
- 'quick add' works for draft issues as well
> fix: draft issue delete not working

- apiserver/plane/api/serializers/cycle.py
- apiserver/plane/api/views/project.py
fix: n+1 queries for cycle list and project member endpoints
> fix: n+1 queries for cycle list and project member endpoints

- apiserver/plane/utils/issue_filters.py
chore: make target dates inclusive when filtering
> chore: make target dates inclusive when filtering

- apiserver/plane/db/models/view.py
chore: removed project filter in global views
> chore: removed project filter in global views

- apiserver/plane/api/views/inbox.py
> fix: inbox issue deletes

- apiserver/plane/bgtasks/issue_activites_task.py
fix: notifications for created by me and assigned to me
> fix: notifications for created by me and assigned to me

- apiserver/plane/api/views/issue.py
chore: handle error when creating label with the same name
> chore: handle error when creating label with the same name

- .github/workflows/Update_Docker_Images.yml
fix: update build workflow for the deploy app
> fix: update build workflow for the deploy app

- web/components/issues/modal.tsx
fix: 
- workspace view add issue mutation fix.
> fix: workspace view add issue mutation fix

- .github/workflows/create-sync-pr.yml
dev: create action to sync PR changes to the repo
> dev: create action to sync PR changes to the repo

- .github/workflows/create-sync-pr.yml
fix: sync script for token variable
> fix: sync script for token variable

- .github/workflows/create-sync-pr.yml
dev: add permissions to the action
> dev: add permissions to the action

- .github/workflows/create-sync-pr.yml
dev: rename token variable in github action
> dev: rename token variable in github action

- README.md
> fix: updated readme fixes

- web/components/core/views/board-view/single-board.tsx
- web/components/core/views/list-view/single-list.tsx
- web/components/emoji-icon-picker/index.tsx
- web/components/gantt-chart/chart/index.tsx
- web/components/issues/draft-issue-form.tsx
- web/components/issues/draft-issue-modal.tsx
- web/components/issues/form.tsx
- web/components/issues/sidebar-select/blocked.tsx
- web/components/issues/sidebar-select/blocker.tsx
- web/components/issues/sidebar-select/duplicate.tsx
- web/components/issues/sidebar-select/relates-to.tsx
- web/components/issues/sidebar.tsx
- web/pages/[workspaceSlug]/me/profile/index.tsx
fix:
- issue description not being saved in draft issue modal
- except title and description fields are not getting updated in the draft issue modal
- UX around the "New Issue" button on the draft issues page
- issue relation mutation
- issue activity not getting updated when issue relation is removed
- draft issue endpoint making patch request
- profile page type
- select the emoji going below
- 'New Issue' coming in cycle and module page
> fix: issue relation mutation and draft issue

- web/pages/[workspaceSlug]/me/profile/index.tsx
Small fix to correct the label on the update button.
Fixes #2342
> fix: Typo changes in profile page. 

- apiserver/plane/api/views/workspace.py
chore: removed the issue draft log from my profile
> chore: removed the issue draft log from my profile

- space/components/issues/navbar/index.tsx
In this pull request, we have addressed the issue of board layout shift functionality in Plane Deploy.
> chore: layout access validation and switch in plane deploy issues route

- space/store/user.ts
In this pull request, we've fixed the issue where the deploy login page got stuck on the loading screen. We've resolved this problem by addressing the loader and error states through modifications in the makeObservable function within the MobX user store.
> fix: added user store variables in Mobx store observable

- .github/workflows/create-sync-pr.yml
modified github action - [create-sync-pr.yml](https://github.com/makeplane/plane/blob/master/.github/workflows/create-sync-pr.yml)
> dev: sync CE master changes

- docker-compose-hub.yml
- web/components/pages/pages-list/recent-pages-list.tsx
* docker-compose-hub modified for envs
* bug:fix recent page hiding last item on scroll #1468 (#2411)
* fixed the AMD build on ARM
> stage: hub compose file update (#2376)

- docker-compose-hub.yml
- web/components/pages/pages-list/recent-pages-list.tsx
* docker-compose-hub modified for envs
* bug:fix recent page hiding last item on scroll #1468 (#2411)
* fixed the AMD build on ARM
> release: docker compose hub changes

- web/components/headers/projects.tsx
- web/components/project/card.tsx
- web/types/projects.d.ts
This PR includes ui revamp for project list page.
before: 
after:
> style: project card revamp

- packages/ui/package.json
- packages/ui/src/form-fields/input-color-picker.tsx
- yarn.lock
chore: 
- color picker input popper js integration.
> chore: color picker popperjs integration

- web/components/issues/form.tsx
- web/components/issues/modal.tsx
style: 
- create/update issue modal ui improvement.
---
> style: create/update issue modal ui improvement

- web/components/command-palette/command-modal.tsx
- web/components/project/create-project-modal.tsx
- web/components/ui/avatar.tsx
- web/components/workspace/member-select.tsx
- member select dropdown ui improvement.
- command k modal alignment fix.
> style: member select dropdown ui and command k modal alignment fix

- web/components/core/modals/bulk-delete-issues-modal.tsx
> fix: modal alignment fix

- web/components/project/card.tsx
chore: 
- project page link error fix.
> chore: project page link error

- web/components/workspace/create-workspace-form.tsx
- web/pages/create-workspace/index.tsx
- back redirection and workspace dashboard redirection added in create workspace page.
- fix the border issue for the workspace URL input.
> chore: create workspace ui improvement

- web/components/account/email-code-form.tsx
- web/components/account/email-forgot-password-form.tsx
- web/components/account/email-password-form.tsx
- web/components/account/email-signup-form.tsx
- web/pages/accounts/sign-up.tsx
- sign up redirection fix.
- ui improvement for the input fields and buttons on the sign-in page.
> chore: sign in page ui improvement and redirection fix

- web/components/page-views/signin.tsx
- web/components/workspace/create-workspace-form.tsx
- implemented validation for sign-in as follows: When a new user signs in, they will be directed to the onboarding page. If the user's profile is complete, they will be redirected to the Create Workspace page. If they have received any workspace invitations, they will be directed to the invitation page.
- resolved the issue with the workspace name and slug inputs in the "Create Workspace" form.
> chore: redirection validation and create workspace form fix

- web/styles/command-pallette.css
This PR addresses the problem with the styling of the command modal.
> style: command modal style

- web/components/cycles/sidebar.tsx
- web/components/issues/sidebar-select/duplicate.tsx
- web/components/issues/sidebar-select/relates-to.tsx
- fix cycle sidebar overlapping issue.
- fix  duplicate and related-to icons in the issue sidebar.
> chore: sidebar fix and ui improvement

- apiserver/plane/api/views/module.py
chore: make module create and list endpoint response structure similar
> chore: make module create and list endpoint response structure similar

- apiserver/plane/settings/production.py
chore:
- use database url if provided else take from the db configuration
> chore: database configuration 

- web/components/notifications/notification-card.tsx
- web/helpers/string.helper.ts
fix: 
- HTML sanitization function
> fix: html sanitization function

- apiserver/plane/api/views/cycle.py
- apiserver/plane/api/views/issue.py
- apiserver/plane/api/views/module.py
- apiserver/plane/api/views/view.py
- apiserver/plane/api/views/workspace.py
revert:
- issues endpoint - total issues count
- response structure
> revert: issues endpoint

- web/components/headers/global-issues.tsx
- web/components/issues/issue-layouts/kanban/block.tsx
- web/components/issues/issue-layouts/kanban/blocks-list.tsx
- web/components/issues/issue-layouts/kanban/default.tsx
- web/components/issues/issue-layouts/kanban/properties.tsx
- web/components/issues/issue-layouts/kanban/roots/cycle-root.tsx
- web/components/issues/issue-layouts/kanban/roots/module-root.tsx
- web/components/issues/issue-layouts/kanban/roots/profile-issues-root.tsx
- web/components/issues/issue-layouts/kanban/roots/project-root.tsx
- web/components/issues/issue-layouts/kanban/swimlanes.tsx
- web/components/issues/issue-layouts/roots/global-view-layout-root.tsx
- web/components/issues/issue-layouts/roots/project-layout-root.tsx
- web/components/issues/issue-layouts/spreadsheet/columns/created-on-column.tsx
- web/components/issues/issue-layouts/spreadsheet/columns/updated-on-column.tsx
- web/components/workspace/views/form.tsx
- web/store/global-view/global_view_issues.store.ts
1. Members list not loading in the filters dropdown.
2. Issues not being updated.
3. Spreadsheet layout- `Created on` and `Updated on` columns' UI.
1. Added proper types to the Kanban components.
> fix: global views filters, issue update function

- web/components/project/card.tsx
- web/components/project/index.ts
- web/components/project/settings/delete-project-section.tsx
- web/components/project/settings/index.ts
- web/pages/404.tsx
This PR fixes the following bugs-
1. Edit project button should redirect to the general project settings.
2. 404 page `Go to Home` button alignment.
> fix: edit project button redirection

- packages/ui/src/form-fields/input-color-picker.tsx
- web/components/core/theme/custom-theme-selector.tsx
1. Added proper validations to the color inputs-
- Each hex code should be of 6 characters.
- Hex code should contain valid characters of the following pattern- `^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$`
2. Input color picker component refactoring.
> fix: custom theme form validations

- packages/ui/src/dropdowns/helper.tsx
- web/components/headers/cycle-issues.tsx
- web/components/headers/global-issues.tsx
- web/components/headers/module-issues.tsx
- web/components/headers/project-issues.tsx
- web/components/headers/project-view-issues.tsx
- web/components/issues/issue-layouts/filters/header/helpers/dropdown.tsx
- web/components/issues/issue-layouts/list/block.tsx
- web/components/issues/issue-layouts/list/blocks-list.tsx
- web/components/issues/issue-layouts/list/default.tsx
- web/components/issues/issue-layouts/list/inline-create-issue-form.tsx
- web/components/issues/issue-layouts/quick-action-dropdowns/cycle-issue.tsx
- web/components/issues/issue-layouts/quick-action-dropdowns/module-issue.tsx
- web/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx
- web/components/profile/profile-issues-filter.tsx
1. List layout UI.
2. Dropdown placements.
> style: list layout

- apiserver/plane/api/serializers/module.py
- apiserver/plane/api/serializers/page.py
- apiserver/plane/bgtasks/issue_activites_task.py
chore:
- In the pages payload the labels_list is changed to labels
- In the module payload the members_list is changed to members
> chore: fix: changed assignees and labels list in pages and modules

- apiserver/plane/api/serializers/user.py
chore: 
- handle workspace does not exist error in user settings endpoint
> chore: user settings endpoint

- apiserver/plane/api/views/authentication.py
chore
- removed numbers from magic code sent in email
> chore: removed numbers from magic code

- apiserver/plane/api/views/importer.py
chore: 
- added permission for importer (only the workspace admin and members can use importers)
> chore: importer permission

- apiserver/plane/utils/issue_filters.py
chore
- The issue with creating a view and applying date filters has been resolved, allowing the view to be successfully created.
> chore:  view creation and date filter fix

- web/components/issues/issue-layouts/properties/assignee.tsx
- web/components/issues/issue-layouts/properties/labels.tsx
- web/components/issues/issue-layouts/properties/state.tsx
- web/components/issues/issue-layouts/spreadsheet/columns/assignee-column.tsx
- web/components/issues/issue-layouts/spreadsheet/columns/created-on-column.tsx
- web/components/issues/issue-layouts/spreadsheet/columns/due-date-column.tsx
- web/components/issues/issue-layouts/spreadsheet/columns/estimate-column.tsx
- web/components/issues/issue-layouts/spreadsheet/columns/label-column.tsx
- web/components/issues/issue-layouts/spreadsheet/columns/priority-column.tsx
- web/components/issues/issue-layouts/spreadsheet/columns/start-date-column.tsx
- web/components/issues/issue-layouts/spreadsheet/columns/state-column.tsx
- web/components/issues/issue-layouts/spreadsheet/columns/updated-on-column.tsx
- web/components/issues/view-select/due-date.tsx
- web/components/issues/view-select/start-date.tsx
fix: 
- spreadsheet view properties fix.
> fix: spreadsheet view properties fix

- web/components/cycles/gantt-chart/cycles-list-layout.tsx
- web/components/gantt-chart/blocks/blocks-display.tsx
- web/components/gantt-chart/chart/index.tsx
- web/components/gantt-chart/helpers/draggable.tsx
- web/components/gantt-chart/root.tsx
- web/components/gantt-chart/sidebar.tsx
- web/components/issues/issue-layouts/calendar/calendar.tsx
- web/components/issues/issue-layouts/calendar/day-tile.tsx
- web/components/issues/issue-layouts/calendar/issue-blocks.tsx
- web/components/issues/issue-layouts/calendar/roots/cycle-root.tsx
- web/components/issues/issue-layouts/calendar/roots/module-root.tsx
- web/components/issues/issue-layouts/calendar/roots/project-root.tsx
- web/components/issues/issue-layouts/calendar/roots/project-view-root.tsx
- web/components/issues/issue-layouts/calendar/week-days.tsx
- web/components/issues/issue-layouts/gantt/blocks.tsx
- web/components/issues/issue-layouts/gantt/cycle-root.tsx
- web/components/issues/issue-layouts/gantt/module-root.tsx
- web/components/issues/issue-layouts/gantt/project-view-root.tsx
- web/components/issues/issue-layouts/gantt/root.tsx
- web/components/issues/issue-layouts/kanban/block.tsx
- web/components/issues/issue-layouts/list/block.tsx
- web/components/issues/issue-layouts/spreadsheet/columns/issue/issue-column.tsx
- web/components/issues/issue-layouts/spreadsheet/columns/issue/spreadsheet-issue-column.tsx
- web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
- web/components/issues/issue-peek-overview/root.tsx
- web/components/issues/sub-issues/issue.tsx
- web/components/issues/sub-issues/issues-list.tsx
- web/components/issues/sub-issues/root.tsx
- web/components/modules/gantt-chart/modules-list-layout.tsx
- web/store/issue/issue.store.ts
- address problem with peek-overview in kanban, calendar , spreadsheet and gantt layout.
- fix  peek-overview mutation.
- integrate the new peek-overview into sub-issues.
> fix: peekoverview

- web/components/project/member-list.tsx
- web/store/project/project_label_store.ts
- web/store/project/project_state.store.ts
- web/store/user.store.ts
fix: 
- exception error
- removed any type & unnecessary SWR query
> fix: exception error

- packages/editor/core/src/ui/components/editor-container.tsx
- packages/editor/core/src/ui/index.tsx
- packages/editor/lite-text-editor/src/ui/index.tsx
- packages/editor/lite-text-editor/src/ui/menus/fixed-menu/index.tsx
- web/components/issues/issue-peek-overview/activity/comment-card.tsx
- web/components/issues/issue-peek-overview/activity/comment-editor.tsx
1. New UI for the toolbar of the lite text editor.
> style: lite text editor editor toolbar

- CODE_OF_CONDUCT.md
Updated the contact email to `squawk@plane.so`.
> chore: updated the contact email

- web/components/issues/issue-layouts/properties/labels.tsx
This PR includes fix for select label dropdown in list view. [FED-634](https://app.plane.so/plane/projects/6cd3f18f-93a9-4e8b-97c8-d501c8d5543c/issues/34a2ddad-dfc0-41ca-a850-b913e38175f3)
> [FED-634] fix: select label dropdown fix for list view

- web/components/views/view-list-item.tsx
This PR include fix for project view edit option. [[FED-636]](https://app.plane.so/plane/projects/6cd3f18f-93a9-4e8b-97c8-d501c8d5543c/issues/cfde4e05-f11f-4eaa-8d3c-43f5d217daec)
> [FED-636] fix: project view edit option 

- web/components/issues/issue-layouts/filters/applied-filters/filters-list.tsx
- web/components/issues/issue-layouts/kanban/block.tsx
- web/components/issues/issue-layouts/kanban/blocks-list.tsx
- web/components/issues/issue-layouts/kanban/default.tsx
- web/components/issues/issue-layouts/kanban/headers/assignee.tsx
- web/components/issues/issue-layouts/kanban/headers/created_by.tsx
- web/components/issues/issue-layouts/kanban/properties.tsx
- web/components/issues/issue-layouts/kanban/roots/cycle-root.tsx
- web/components/issues/issue-layouts/kanban/roots/module-root.tsx
- web/components/issues/issue-layouts/kanban/roots/profile-issues-root.tsx
- web/components/issues/issue-layouts/kanban/roots/project-root.tsx
- web/components/issues/issue-layouts/kanban/swimlanes.tsx
- web/components/issues/issue-layouts/list/block.tsx
- web/components/issues/issue-layouts/list/blocks-list.tsx
- web/components/issues/issue-layouts/list/default.tsx
- web/components/issues/issue-layouts/list/properties.tsx
- web/components/issues/issue-layouts/list/roots/project-root.tsx
- web/components/issues/issue-peek-overview/activity/card.tsx
In this pull request, we've enhanced the handling of scenarios where labels and assignees have no properties to display. This improvement applies to both the issue layouts in the list and kanban views.
> chore: Improved Handling of Empty Properties for Labels and Assignees

- web/components/modules/sidebar.tsx
This PR includes fix for module sidebar status select. [[FED-641]](https://app.plane.so/plane/projects/6cd3f18f-93a9-4e8b-97c8-d501c8d5543c/issues/1090c75a-2d54-4b63-8978-01891595bc16)
> [FED-641 ] fix: module sidebar status select

- web/components/onboarding/user-details.tsx
- web/components/onboarding/workspace.tsx
- web/components/page-views/signin.tsx
- web/components/workspace/create-workspace-form.tsx
- web/layouts/auth-layout/user-wrapper.tsx
- web/layouts/auth-layout/workspace-wrapper.tsx
- web/pages/onboarding/index.tsx
- web/store/user.store.ts
- web/store/workspace/workspace.store.ts
This PR implements MobX in the onboarding screens
> chore: implemented MobX in the onboarding screens

- web/components/cycles/active-cycle-details.tsx
- web/components/cycles/active-cycle-stats.tsx
This PR includes fix for  active cycle bug that occurs when no active cycle is present.
> fix: active cycle fix

- web/components/page-views/signin.tsx
- web/components/workspace/sidebar-dropdown.tsx
- web/hooks/use-user-auth.tsx
Added authentication for the sign in page, considered the following cases-
1. Check if the user has onboarded or not.
2. Check for the `next_url` in the URL.
3. Check for the last active or fallback workspaceSlug.
4. Check for pending invites.
> fix: user authentication on the index page

- web/components/issues/issue-layouts/kanban/default.tsx
- web/components/issues/issue-layouts/kanban/swimlanes.tsx
- web/pages/[workspaceSlug]/profile/[userId]/assigned.tsx
- web/pages/[workspaceSlug]/profile/[userId]/created.tsx
- web/pages/[workspaceSlug]/profile/[userId]/subscribed.tsx
In this pull request, we've resolved a bug related to project rendering in the kanban layout of profile issues. Additionally, we've fixed multiple layout rendering issues within subscribed profile issues.
> fix: Project Rendering Error in Kanban Layout and Layout Rendering Fixes in Subscribed Profile Issues

- web/components/automation/auto-archive-automation.tsx
- web/components/automation/auto-close-automation.tsx
- web/components/project/member-list-item.tsx
This PR includes improvements and refactoring of the project member settings page.
> chore: refactor and improve project member settings

- web/components/analytics/custom-analytics/select-bar.tsx
- web/components/analytics/custom-analytics/select/x-axis.tsx
- web/helpers/string.helper.ts
Added undefined argument condition to the `addSpaceIfCamelCase` helper function.
> fix: string helper function

- web/components/analytics/custom-analytics/graph/index.tsx
fix: Bar graph avatar image rendering & tooltip
Before:
After:
> style: custom analytics bar graph label overlapping

- apiserver/plane/bgtasks/analytic_plot_export.py
- apiserver/plane/utils/analytics_plot.py
fix: 
- custom analytics graph display issue
- Export csv not working for analytics
> fix: custom analytics graph display issue

- web/components/issues/issue-layouts/properties/assignee.tsx
- web/components/issues/issue-layouts/roots/global-view-layout-root.tsx
fix:
- No values are changeable from all issues spreadsheet view
- Assignees images are not showing on "All Issues" section
> fix: all issues values not changeable and assignee image not rendering

- apiserver/plane/api/views/config.py
chore
- configuration add tracker variables to configuration api
> chore: configuration add tracker variables

- apiserver/plane/api/views/cycle.py
- apiserver/plane/api/views/module.py
chore: 
- favourite cycle and module displayed at top
> chore: favourite cycle and module displayed at top

- web/components/issues/issue-layouts/filters/applied-filters/date.tsx
- web/components/issues/issue-layouts/filters/applied-filters/filters-list.tsx
- web/components/issues/issue-layouts/filters/applied-filters/label.tsx
- web/components/issues/issue-layouts/filters/applied-filters/members.tsx
- web/components/issues/issue-layouts/filters/applied-filters/priority.tsx
- web/components/issues/issue-layouts/filters/applied-filters/project.tsx
- web/components/issues/issue-layouts/filters/applied-filters/roots/project-view-root.tsx
- web/components/issues/issue-layouts/filters/applied-filters/state-group.tsx
- web/components/issues/issue-layouts/filters/applied-filters/state.tsx
This PR addresses the overflow issue in the filter list component when selecting multiple filters.
> fix: filter list overflow fix

- packages/ui/src/icons/priority-icon.tsx
- web/components/analytics/custom-analytics/table.tsx
- web/components/inbox/issue-card.tsx
- web/components/issues/issue-layouts/filters/applied-filters/priority.tsx
- web/components/project/priority-select.tsx
Fix: 
- Show Priority Icon in the custom analytics table when dimension selected as Priority
- Show icon color based on the priority 
Priority Icon Component (Package):
- Handle Priority Icon color in this component itself based on priority 
- No need to pass priority text color from parent component
Refactored the code to avoid passing icon color
> Fix: Show Priority icon in custom analytics table.

- web/components/headers/cycle-issues.tsx
- web/components/headers/cycles.tsx
- web/components/headers/global-issues.tsx
- web/components/headers/module-issues.tsx
- web/components/headers/modules-list.tsx
- web/components/headers/page-details.tsx
- web/components/headers/pages.tsx
- web/components/headers/profile-preferences.tsx
- web/components/headers/project-archived-issue-details.tsx
- web/components/headers/project-archived-issues.tsx
- web/components/headers/project-draft-issues.tsx
- web/components/headers/project-inbox.tsx
- web/components/headers/project-issue-details.tsx
- web/components/headers/project-issues.tsx
- web/components/headers/project-settings.tsx
- web/components/headers/project-view-issues.tsx
- web/components/headers/project-views.tsx
- web/components/headers/projects.tsx
- web/components/headers/user-profile.tsx
- web/components/headers/workspace-analytics.tsx
- web/components/headers/workspace-dashboard.tsx
- web/components/headers/workspace-settings.tsx
This PR includes improvement to the header, ensuring consistent height and button.
> fix: header consistency

- web/components/cycles/cycles-board-card.tsx
fix:
- cycle card title responsiveness added.
> fix: cycle card title responsiveness added

- web/components/issues/comment/comment-card.tsx
- web/components/issues/issue-peek-overview/activity/view.tsx
chore: 
- peek overview comment ordering  and comment icon alignment fix
> chore: peek overview comment ordering  and comment icon alignment fix

- web/components/project/integration-card.tsx
- web/components/project/leave-project-modal.tsx
- web/components/project/sidebar-list.tsx
- web/components/views/delete-view-modal.tsx
- web/components/views/view-list-item.tsx
- web/pages/[workspaceSlug]/projects/[projectId]/settings/integrations.tsx
This PR focuses on the following UI improvements and fixes:
* [style: add transition to favorite projects dropdown.](https://github.com/makeplane/plane/commit/7b9c6d9210b298b751ef6bb5a12d67cb18cb87da)
* [style: update project integration settings borders.](https://github.com/makeplane/plane/commit/a7a0014d3ffb1ce49473c657b4b932927684f5fa)
* [style: fix text overflow issue in project views.](https://github.com/makeplane/plane/commit/5e86c65df6020d1a4d162c6d7ec15dbd0f413131)
* [fix: issue with non-functional cancel button in leave project modal.](https://github.com/makeplane/plane/commit/ad5c8505879bcfe9c7aba9a3d0bf328262076664)
> style: ui improvements and bug fixes

- web/components/issues/issue-layouts/filters/header/filters/assignee.tsx
- web/components/issues/issue-layouts/filters/header/filters/created-by.tsx
- web/components/issues/issue-layouts/filters/header/filters/mentions.tsx
- web/components/pages/single-page-detailed-item.tsx
- web/components/pages/single-page-list-item.tsx
- web/components/views/view-list-item.tsx
style:
- page, view title width is fixed and not responsive
- page detailed list view  padding issue
- In create view model, if we select filters, then the assignee avatar images, mention avatar images and created by avatar images have inconsistent size
- page detailed item block text need truncate
> style: ui fixes for pages and views

- web/components/headers/project-issues.tsx
This PR addresses project icon issue. Previously, the icon wasn't rendering correctly.
> chore: breadcrumb project icon fix

- web/components/issues/form.tsx
This PR includes improvement for create/update issue modal. [[FED-810]](https://app.plane.so/plane/projects/6cd3f18f-93a9-4e8b-97c8-d501c8d5543c/issues/8f1b3980-b714-4312-a02a-11b816d2d34c)
> chore: create update issue modal improvement

- web/components/issues/issue-layouts/spreadsheet/columns/issue/issue-column.tsx
- web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
This PR includes improvement for spreadsheet layout column.
> chore: spreadsheet layout column improvement

- web/components/modules/select/lead.tsx
- web/components/workspace/member-select.tsx
This PR includes modifications to the lead select dropdown.
> chore: lead select dropdown fix

- web/components/cycles/active-cycle-details.tsx
- web/components/issues/select/label.tsx
- web/components/issues/select/state.tsx
- web/components/project/sidebar-list-item.tsx
- web/components/views/form.tsx
- web/pages/[workspaceSlug]/projects/[projectId]/settings/automations.tsx
- web/pages/[workspaceSlug]/projects/[projectId]/settings/estimates.tsx
fix: 
- project settings automation mutation not working
before:
https://github.com/makeplane/plane/assets/65905942/09ae0971-edd0-4d1a-b3da-8991977acebe
after:
https://github.com/makeplane/plane/assets/65905942/eb371cc4-102d-4928-b3e2-c040efa5db87
- active cycle stuck on loader
before:
after(opens after API call):
- removed 'delete project' option from the sidebar
- project discloser not opening when navigating using cmd+k or navigating using the project list page.
before: 
https://github.com/makeplane/plane/assets/65905942/137f1039-9165-413e-89ae-77dba828f0d2
after:
https://github.com/makeplane/plane/assets/65905942/bead6fa4-c18f-4710-b53f-d284f1d9b27b
- filter category stays even when filters are de-selected & x-mark is not working
before: …
> fix: bugs 

- web/components/core/activity.tsx
- web/components/issues/issue-layouts/properties/assignee.tsx
- web/components/issues/select/cycle.tsx
- web/components/issues/select/module.tsx
- web/components/modules/delete-module-modal.tsx
- web/components/project/join-project-modal.tsx
* [style: fix text overflow in:](https://github.com/makeplane/plane/commit/bbea2a3aa480b7e3fffa9083d1d56babcf93fea1) 
* Issue activity
* Cycle and Module Select in Create Issue form
* Delete Module modal
* Join Project modal
* [style: update assignee select border as per design.](https://github.com/makeplane/plane/commit/428bdab2f945810780056fb45aa5563bf6b424fa)
> style: text overflow fix and border color update

- apiserver/bin/bucket_script.py
- deploy/selfhost/docker-compose.yml
- docker-compose-local.yml
- docker-compose.yml
dev: 
- update bucket script to make the bucket public
> dev: update bucket script to make the bucket public

- web/components/headers/cycle-issues.tsx
- web/components/headers/module-issues.tsx
- web/components/issues/issue-layouts/filters/applied-filters/roots/cycle-root.tsx
- web/components/issues/issue-layouts/filters/applied-filters/roots/module-root.tsx
- web/components/issues/issue-layouts/gantt/project-root.tsx
- web/components/issues/issue-layouts/roots/cycle-layout-root.tsx
- web/components/issues/issue-layouts/roots/module-layout-root.tsx
- web/components/issues/issue-layouts/roots/project-layout-root.tsx
- web/components/issues/issue-layouts/spreadsheet/roots/project-root.tsx
- web/services/issue/issue.service.ts
- web/store/cycle-issues/index.ts
- web/store/cycle-issues/issue_filters.store.ts
- web/store/module-issues/index.ts
- web/store/module-issues/issue_filters.store.ts
- web/store/project-issues/issue.store.ts
- web/store/project-issues/issue_filters.store.ts
- web/store/root.ts
1. Initialized the new MobX stores for cycle and module issue filters.
2. Updated the cycle and module filter components to use the new stores and removed the instances of the old store.
3. Used the new project issues store to display issues in the project spreadsheet layout.
> dev: initialized cycle and module issue filters store

- apiserver/plane/api/serializers/issue.py
- apiserver/plane/api/urls/cycle.py
- apiserver/plane/api/urls/module.py
- apiserver/plane/api/views/__init__.py
- apiserver/plane/api/views/base.py
- apiserver/plane/api/views/cycle.py
- apiserver/plane/api/views/module.py
feat: v3 endpoint for module and cycle
> feat: v3 endpoint for module and cycle

- apiserver/plane/app/views/config.py
dev:
- added `has_openai_configured` to configs api
> dev: openai configured

- apiserver/plane/bgtasks/export_task.py
- apiserver/plane/bgtasks/exporter_expired_task.py
- apiserver/plane/db/management/commands/create_bucket.py
- apiserver/plane/settings/common.py
chore: 
- aws bucket url name changed (`AWS_S3_BUCKET_NAME`)
- Added `AWS_REGION`
> chore: aws bucket url name changed

- apiserver/plane/license/management/commands/register_instance.py
dev: change url for the license engine instance registration
> dev: instance url

- web/components/project/join-project-modal.tsx
- web/services/project/project.service.ts
This PR updates the join project endpoint.
> chore: update join project endpoint

- web/components/project/sidebar-list-item.tsx
**Before:**
https://github.com/makeplane/plane/assets/94619783/798ac30c-8b18-4595-8748-f69e96161b1f
**After:**
https://github.com/makeplane/plane/assets/94619783/82c0306b-9637-4801-9ee1-1e1dddfc713a
> fix: sidebar project section hover

- web/components/workspace/issues-stats.tsx
This PR includes fix for dashboard stats card redirection.
> [FED-891] chore: dashboard redirection fix

- web/components/modules/sidebar.tsx
This PR resolve module sidebar link section disclosure bug.
> [FED-937] fix: module sidebar link section

- web/components/project/card.tsx
This PR includes ui improvement for project card.
> [FED-882] style: project card improvement

- web/components/analytics/custom-analytics/select/project.tsx
This PR includes fix for custom analytics project dropdown.
> [FED-883] fix: custom analytics project dropdown fix

- web/components/cycles/sidebar.tsx
- web/components/modules/sidebar.tsx
This PR includes fix for module and cycle loading state bug.
> [FED-906] fix/module_and_cycle_sidebar_loading_state

- web/components/cycles/modal.tsx
- web/components/modules/modal.tsx
This PR addresses issues occurring when selecting a different project from the dropdown menu in cycle and module modal.
> [FED-903] fix/cycle_and_module_create_modal

- web/pages/[workspaceSlug]/me/profile/index.tsx
This PR include profile setting overflow fix.
> [FED-894] fix: profile setting overflow

- web/components/project/form.tsx
This PR include ui improvement and consistency for project setting.
> [FED-884] style: project setting ui improvement

- web/components/issues/parent-issues-list-modal.tsx
This PR include improvement for parent issue select modal.
> [FED-888] fix: parent issue select modal improvement

- apiserver/plane/app/serializers/user.py
- apiserver/plane/app/views/auth_extended.py
The code allows authenticated users to change password of the existing account by providing the `old_password`, `new_password` and `confirm_password`.
> chore: change password endpoint

- web/components/core/filters/date-filter-modal.tsx
This PR addresses the issue with the date filter selection within the view modal. Previously, when selecting a custom date, the form was being submitted prematurely. The fix rectifies this behaviour.
> [FED-826] fix: view date filter select behaviour

- apiserver/plane/app/serializers/issue.py
- apiserver/plane/app/urls/user.py
- apiserver/plane/app/views/user.py
- changed user activity of the user, independent of workspace
> chore: user activity in profile page

- .github/workflows/build-branch.yml
- web/components/issues/form.tsx
> fix: adding slack notification when build is failed to upload to docker

- web/components/onboarding/invite-members.tsx
> chore: added error toast for invitations

- web/components/cycles/sidebar.tsx
- web/components/modules/sidebar.tsx
This PR addresses the module sidebar issue, resolving the problem where the date selection wasn't functioning as expected.
> [FED-873] fix: module sidebar date select fix and code refactor

- packages/ui/src/badge/badge.tsx
- packages/ui/src/badge/helper.tsx
- packages/ui/src/badge/index.ts
- packages/ui/src/index.ts
In this pull request, I've incorporated badge component into the Plane UI package.
> [FED-1041] dev: badges component

- apiserver/plane/app/urls/asset.py
- apiserver/plane/app/views/__init__.py
- apiserver/plane/app/views/asset.py
- separated the routes for deleting and restoration of file asset
> chore: file asset deletion

- web/components/cycles/cycles-board-card.tsx
- web/components/cycles/delete-modal.tsx
- web/components/cycles/sidebar.tsx
- web/components/modules/delete-module-modal.tsx
- web/components/modules/module-card-item.tsx
- web/layouts/settings-layout/workspace/sidebar.tsx
- web/store/module/modules.store.ts
**Fixes:**
1. only the admin should be able to see API tokens.
2. On creating a new module total issues are undefined.
3. In the cycle card layout, more popover -> `delete module` should be `delete cycle`.
4. The peek view should be closed on deleting the cycle or module.
5. The copy link toast message should be consistent in the cycle peek view.
> fix: bug fixes & UI improvements

- web/components/instance/email-form.tsx
- web/components/instance/general-form.tsx
- web/components/instance/google-config-form.tsx
- web/components/instance/image-config-form.tsx
- web/components/instance/sidebar-dropdown.tsx
- web/components/instance/sidebar-menu.tsx
- web/layouts/admin-layout/header.tsx
- web/layouts/admin-layout/layout.tsx
- web/pages/god-mode/ai.tsx
- web/pages/god-mode/authorization.tsx
- web/pages/god-mode/email.tsx
- web/pages/god-mode/image.tsx
- web/pages/god-mode/index.tsx
- web/pages/god-mode/mail.tsx
- web/services/instance.service.ts
- web/store/instance/instance.store.ts
- web/types/instance.d.ts
- instance admin endpoint added.
- sidebar, header and form improvement.
- content and icon updated.
> chore: instance admins endpoint added and ui/ux improvement

- web/components/auth-screens/project/join-project.tsx
- web/components/project/join-project-modal.tsx
This PR include fix for join project mutation bug.
> [FED-1054] fix: join project mutation

- web/components/workspace/sidebar-dropdown.tsx
This PR include improvement for workspace dropdown when workspace name is longer.
> [FED-1018] chore: workspace dropdown improvement

- web/components/page-views/signin.tsx
> chore: signup removed

- web/components/workspace/sidebar-dropdown.tsx
This PR include fix for workspace dropdown scroll issue.
> [FED-1019] fix: workspace dropdown

- web/components/api-token/empty-state.tsx
- web/components/project/publish-project/modal.tsx
- web/components/web-hooks/empty-state.tsx
- web/layouts/settings-layout/profile/sidebar.tsx
- web/pages/[workspaceSlug]/settings/api-tokens.tsx
- web/pages/invitations/index.tsx
The PR focuses on following bug fixes and UI / UX improvements:
* [Fix: issue with project publish modal data not updating immediately/ when the modal is opened.](https://github.com/makeplane/plane/commit/157903a9b9347292fc59e98980fff24d43ecbc61)
* [Fixed issue in Profile settings sidebar where the workspace list was not scrollable.](https://github.com/makeplane/plane/commit/2e4b13abc05346de80c51875fce41d2cb8c9beee)
* [Fixed issue with the workspace slug redirect buttons where it was redirecting user to `/` instead of previously used workspace.](https://github.com/makeplane/plane/commit/4cc86ca3288f3598f4f08f8e8ba43997cd1e8b7c)
* [Updated API tokens and Webhooks empty state design for consistency.](https://github.com/makeplane/plane/commit/02a5598ac7744425f3f96751900e5b4b5210b44c)
> Fix: bug fixes and UI / UX improvements

- deploy/selfhost/migration-0.13-0.14.sh
```
curl -fsSL -o migrate.sh https://raw.githubusercontent.com/makeplane/plane/master/deploy/selfhost/migration-0.13-0.14.sh
chmod +x migrate.sh
./migrate.sh
```
> dev: Self Hosting Migration from 0.13.2 => 0.14.0

- web/components/onboarding/invite-members.tsx
**chore:**
1. tweaked member email validation.
**style:**
1. added invalid email indication.
2. added active member role indication.
> style: member role visibility

- web/components/issues/issue-layouts/filters/applied-filters/roots/profile-issues-root.tsx
- web/components/profile/profile-issues.tsx
- web/store/issues/global/filter.store.ts
- web/store/issues/profile/filter.store.ts
- web/store/issues/profile/issue.store.ts
- web/store/issues/project-issues/archived/issue.store.ts
This PR fixes all the bugs with profile, archived and draft issues... This includes changes to filter stores, issue stores and views of the above mentioned views.
> fix: all functionalities for profile, archived and draft issues

- web/components/workspace/sidebar-dropdown.tsx
This PR includes improvement for workspace sidebar dropdown menu.
> [FED-1019] style: workspace sidebar improvement

- web/components/web-hooks/form/form.tsx
- web/components/web-hooks/form/individual-event-options.tsx
1. Updated the description of individual events.
> chore: update the content of webhooks form

- apiserver/plane/app/urls/views.py
- apiserver/plane/app/views/__init__.py
- apiserver/plane/app/views/view.py
> chore: v3 global issues

- web/components/account/deactivate-account-modal.tsx
- Added new design for deactivate account modal.
> style: deactivate acount modal

- web/components/common/empty-state.tsx
This PR includes improvement for empty state
> [FED-1107] style: empty state improvement

- apiserver/plane/bgtasks/forgot_password_task.py
- apiserver/plane/bgtasks/workspace_invitation_task.py
- apiserver/templates/emails/auth/forgot_password.html
- apiserver/templates/emails/auth/magic_signin.html
- apiserver/templates/emails/invitations/workspace_invitation.html
> chore: transactional emails

- ENV_SETUP.md
- deploy/coolify/coolify-docker-compose.yml
- deploy/selfhost/docker-compose.yml
- deploy/selfhost/variables.env
Removed the `DJANGO_SETTINGS_MODULE` variable
> chore: removed django settings module

- web/components/command-palette/command-pallette.tsx
- web/components/headers/project-views.tsx
- web/store/command-palette.store.ts
This PR include fix for view modal overlapping issue.
> [FED-868] fix: create view modal overlapping

- web/components/issues/select/cycle.tsx
- web/components/issues/select/module.tsx
This PR includes improvement for create issue modal. Previously, there was no option available to deselect a selected module or cycle.
> [FED-862] fix: create issue modal improvement

- web/constants/issue.ts
This PR include improvement for profile issue display filters.
> [FED-924] chore: profile issue display filters content updated

- web/components/account/sign-in-forms/unique-code.tsx
- web/components/onboarding/join-workspaces.tsx
- web/components/onboarding/workspace.tsx
- Added validation fix in create workspace form in onboarding.
> fix: create workspace form validation

- web/components/issues/form.tsx
- web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
- web/components/issues/issue-layouts/kanban/swimlanes.tsx
- web/components/views/modal.tsx
- web/store/command-palette.store.ts
- web/store/issues/project-issues/base-issue.store.ts
This PR fixes the following urgent category bug fixes,
- [FED-1101](https://app.plane.so/plane/projects/6cd3f18f-93a9-4e8b-97c8-d501c8d5543c/issues?peekIssue=199ba625-7e1c-48ad-95ac-3fbecca3b769)
- [FED-1100](https://app.plane.so/plane/projects/6cd3f18f-93a9-4e8b-97c8-d501c8d5543c/issues?peekIssue=33c8bb2f-1deb-4e11-85ee-0e53045fde7f)
- [FED-1096](https://app.plane.so/plane/projects/6cd3f18f-93a9-4e8b-97c8-d501c8d5543c/issues?peekIssue=166b0663-ac11-4a9c-9f61-a5209c091a63)
- [FED-1093](https://app.plane.so/plane/projects/6cd3f18f-93a9-4e8b-97c8-d501c8d5543c/issues?peekIssue=4e62bb05-99c0-42d9-9bdd-4b10721a9640)
- Exception fix for the subgroup by swimlanes
> fix: V3 release blocker bugs

- web/components/issues/issue-layouts/roots/all-issue-layout-root.tsx
In this pull request, we've fixed an issue related to the updating of global issues properties.
> fix: global issues properties updation issue resolved

- web/services/auth.service.ts
Updated the instance admin sign in service to not send headers while making the request.
> chore: update instance admin sign in service

- apiserver/plane/api/serializers/cycle.py
- apiserver/plane/api/serializers/issue.py
- apiserver/plane/api/serializers/project.py
- apiserver/plane/api/serializers/state.py
- apiserver/plane/api/views/state.py
- apiserver/plane/app/views/state.py
- apiserver/plane/bgtasks/webhook_task.py
- apiserver/plane/utils/issue_filters.py
- apiserver/requirements/base.txt
This PR enhances data integrity by implementing stricter validation for `description_html` and `comment_html` fields from external APIs. It also introduces restrictions preventing updates to specified fields via these APIs.
> chore: html validation

- web/components/cycles/sidebar.tsx
- web/components/modules/sidebar.tsx
This PR include fix for module and cycle sidebar date mutation fix.
> [FED-790] chore: module and cycle sidebar date mutation fix

- apiserver/plane/settings/common.py
fix: 
- sentry DSN invalid error
> fix: sentry error

- web/components/project/member-list-item.tsx
- web/components/project/sidebar-list-item.tsx
- web/components/workspace/settings/members-list-item.tsx
1. After leaving a project, it should get removed from the sidebar.
2. The projects listing should be updated.
> fix: leave project mutation

- web/components/inbox/main-content.tsx
- web/components/issues/description-form.tsx
- web/components/issues/index.ts
- web/components/issues/issue-peek-overview/issue-detail.tsx
- web/components/issues/issue-peek-overview/view.tsx
- web/components/issues/issue-update-status.tsx
- web/components/issues/main-content.tsx
- web/components/issues/sidebar.tsx
**peek view:**
https://github.com/makeplane/plane/assets/94619783/deb0f330-fb39-41ee-b055-391540d2088b
**detail-page:**
https://github.com/makeplane/plane/assets/94619783/2c452dda-e405-435c-9694-729a693d5a3b
> chore: issue update status in peekview & detail

- Dockerfile
- apiserver/Dockerfile.api
- apiserver/gunicorn.config.py
- apiserver/plane/settings/common.py
- apiserver/requirements/base.txt
- apiserver/requirements/production.txt
dev: 
- remove unused packages
> dev: remove unused packages

- apiserver/plane/db/management/commands/reset_password.py
**Required**
- email
```
python manage.py reset_password captain@plane.so
```
> dev: management command to reset user password

- web/components/headers/project-views.tsx
- web/components/issues/select/label.tsx
- web/components/issues/sidebar-select/label.tsx
- Project view modal auto close fix.
- Issue peek overview permission validation for label select.
> fix: bug fixes 

- web/components/issues/issue-layouts/empty-states/project.tsx
- web/components/issues/issue-layouts/spreadsheet/spreadsheet-column.tsx
- web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
- web/components/issues/view-select/due-date.tsx
- web/components/issues/view-select/start-date.tsx
**Fixes:**
1. Start / Due Date Picker modal is hidden for fewer rows sheet.
2. The spreadsheet's rightmost column border is not visible.
> fix: spreadsheet layout bugs

- packages/editor/core/package.json
- packages/editor/document-editor/package.json
- packages/editor/extensions/package.json
- packages/editor/lite-text-editor/package.json
- packages/editor/rich-text-editor/package.json
- packages/editor/types/package.json
- packages/ui/package.json
This PR just adds a "--minify" modifier to the existing build command of all the packages to minify them.
> Chore: Minify build for plane packages

- .github/workflows/build-branch.yml
- deploy/selfhost/docker-compose.yml
> chore: public images

- packages/editor/document-editor/src/ui/extensions/index.tsx
- packages/editor/extensions/package.json
- packages/editor/extensions/src/extensions/slash-commands.tsx
- packages/editor/types/src/types/slash-commands-suggestion.ts
- yarn.lock
The UI of the slash command menu was not in accordance to the new Figma design.
Updated the UI of the slash command menu.
1. Updated type of slash command menu item.
2. Replaced the use of array index with a unique key for the key of menu item while mapping through the list.
3. Updated the `lucide-react` version to `0.293.0` in the `editor/extensions` package.
4. Fixed some typos.
> style: update the ui of the slash command menu

- web/components/core/modals/gpt-assistant-modal.tsx
This PR focuses on fixing the issue with GPT assistant response not being updated for new requests. 
Before the fix: 
https://github.com/makeplane/plane/assets/33979846/5f2fb98d-6eb3-4795-85bc-61f70f559a1b
After the fix: 
https://github.com/makeplane/plane/assets/33979846/99aec091-1fbe-4081-be91-b07e0d1fb8d9
> fix: issue with GPT assistant response not updating on new requests.

- web/components/cycles/cycles-board-card.tsx
- web/components/cycles/cycles-list-item.tsx
- web/components/issues/issue-layouts/properties/state.tsx
- web/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx
- web/components/modules/module-card-item.tsx
- web/components/modules/module-list-item.tsx
- web/components/pages/pages-list/list-item.tsx
**Problems:**
Guests and viewers were able to execute actions they shouldn't have been able to.
I implemented validation measures to prevent users with guest and viewer roles from carrying out any unauthorized actions.
> chore: user permission related fix

- web/components/cycles/modal.tsx
- web/components/headers/cycle-issues.tsx
- web/components/headers/cycles.tsx
- web/components/headers/module-issues.tsx
- web/components/headers/modules-list.tsx
- web/components/headers/project-issues.tsx
- web/components/headers/project-view-issues.tsx
- web/components/issues/modal.tsx
- web/components/modules/modal.tsx
- web/components/pages/create-update-page-modal.tsx
1. Create operation for the cycle, module, pages, and issues are hidden for **VIEWER/GUEST.**
2. Proper toast message on update operation failure due to permissions.
> chore: access restriction for lower roles

- web/components/views/form.tsx
Before fix: 
https://github.com/makeplane/plane/assets/33979846/46a6e281-92ab-493a-b711-e4ae133b89b5
After fix:
https://github.com/makeplane/plane/assets/33979846/546907ce-08da-494f-a935-9453313f8785
> fix: issue with clear filter option not working for filter groups in create view modal.

- web/components/issues/issue-layouts/spreadsheet/columns/assignee-column.tsx
- web/components/issues/issue-layouts/spreadsheet/columns/attachment-column.tsx
- web/components/issues/issue-layouts/spreadsheet/columns/created-on-column.tsx
- web/components/issues/issue-layouts/spreadsheet/columns/due-date-column.tsx
- web/components/issues/issue-layouts/spreadsheet/columns/estimate-column.tsx
- web/components/issues/issue-layouts/spreadsheet/columns/label-column.tsx
- web/components/issues/issue-layouts/spreadsheet/columns/link-column.tsx
- web/components/issues/issue-layouts/spreadsheet/columns/priority-column.tsx
- web/components/issues/issue-layouts/spreadsheet/columns/start-date-column.tsx
- web/components/issues/issue-layouts/spreadsheet/columns/state-column.tsx
- web/components/issues/issue-layouts/spreadsheet/columns/sub-issue-column.tsx
- web/components/issues/issue-layouts/spreadsheet/columns/updated-on-column.tsx
- web/components/issues/issue-layouts/spreadsheet/spreadsheet-column.tsx
> fix: spreadsheet layout alignment

- web/components/issues/delete-issue-modal.tsx
- web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
- web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
- web/pages/profile/activity.tsx
- web/store/issues/project-issues/cycle/issue.store.ts
- web/store/issues/project-issues/module/issue.store.ts
- web/store/issues/project-issues/project/issue.store.ts
**Fixes**:
1. On delete issue, the toast should be there in all the layouts.
2. on deleting the last issue, the empty state is not there.
3. on deleting that last issue in the spreadsheet layout, loading was not taking full height.
4. profile activity issue link update.
> fix: delete issue mutation & toast

- web/components/core/modals/link-modal.tsx
- web/components/issues/peek-overview/properties.tsx
- web/components/issues/peek-overview/root.tsx
- web/components/issues/peek-overview/view.tsx
- web/components/issues/sidebar.tsx
- web/services/issue/issue.service.ts
- web/services/module.service.ts
- web/store/issue/issue_detail.store.ts
- web/store/module/modules.store.ts
**Problem:**
There was a mutation problem in the issue link action within the issue sidebar and peek overview.
I've addressed this by adding the issue link action to the issue detail store.
> chore: issue link mobx integration

- web/components/cycles/sidebar.tsx
- web/components/issues/attachment/attachment-upload.tsx
- web/components/modules/sidebar.tsx
This PR includes theme fixes for the module, cycle sidebar, and peek overview.
> style: cycle and module sidebar improvement

- apiserver/plane/app/views/project.py
- web/components/project/member-list-item.tsx
**Backend:**
- now viewer and guest can leave a project.
<br/>
**Frontend:**
**Problem:**
1. Member role not able to leave the project.
**Solution:**
1. Updated the leave project condition.
> chore: guest and viewer can leave project

- web/components/inbox/main-content.tsx
- web/components/issues/description-form.tsx
- web/components/issues/issue-layouts/properties/assignee.tsx
- web/components/issues/main-content.tsx
- web/components/issues/sidebar-select/parent.tsx
- web/components/issues/sub-issues/properties.tsx
This PR include following changes: 
- Issue detail page improvement.
- Improvements to parent select in the issue sidebar and peek overview. (Remove option added)
- Validation of permissions for sub-issue properties on the issue detail page.
---
---
> chore: issue details related bug fixes and improvement

- web/components/issues/issue-layouts/calendar/day-tile.tsx
- web/components/issues/issue-layouts/calendar/issue-blocks.tsx
- web/components/issues/issue-layouts/calendar/quick-add-issue-form.tsx
This PR include following changes: 
- "See More" button has been added on the calendar day tile for dates with more than four issues.
- Header & sidebar permission validation added. 
Before: 
After:
> chore: calendar layout improvement

- web/components/headers/project-view-issues.tsx
- web/components/headers/project-views.tsx
- web/components/issues/sidebar-select/assignee.tsx
- web/components/issues/sidebar.tsx
- web/components/views/view-list-item.tsx
**Problem:**
- Guests and viewers have access to specific actions within the Project view:
- Adding views from the header on the project view list page.
- Adding issues from the header on the project view detail page.
- Editing or deleting views from the project view list page.
- Implemented validation to prevent user with guest and viewer role from accessing above mentioned action.
**Other Changes**
- Issue sidebar improvement.
- Copy view link option added in project view list item.
> chore: issue sidebar and project view improvement and validation

- web/components/cycles/sidebar.tsx
- web/components/modules/sidebar.tsx
**Problem:**
- Guest and viewer can access the following action in the cycle sidebar:
- Deleting a cycle.
- Changing start and end dates.
- Guest and viewer can access the following action in the module sidebar:
- Deleting a module.
- Changing start and end dates.
- Module status.
- Implemented validation to prevent user with guest and viewer role from accessing above mentioned action.
> chore: cycle and module sidebar validation

- web/components/issues/issue-layouts/empty-states/project.tsx
- web/components/modules/modules-list-view.tsx
- web/components/page-views/workspace-dashboard.tsx
- web/components/pages/pages-list/list-view.tsx
- web/components/pages/pages-list/recent-pages-list.tsx
- web/components/project/card-list.tsx
- web/components/views/views-list.tsx
- web/pages/[workspaceSlug]/analytics.tsx
- web/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx
**Problem:**
- Users with guest and viewer roles can access an empty state action button.
- Implemented validation to prevent user with guest and viewer role from accessing the empty state action button.
> chore: empty state action button validation

- web/components/headers/global-issues.tsx
- web/components/headers/project-view-issues.tsx
- web/components/headers/projects.tsx
- web/components/project/sidebar-list.tsx
- web/layouts/user-profile-layout/layout.tsx
**Problem:**
Guest users are unable to access profile page.
I've addressed this problem by implementing validation within the ProfileAuthWrapper to grant access to the profile dashboard page for guest users.
> chore: guest user profile access-related problem

- web/components/headers/project-view-issues.tsx
This PR include build error fix.
> fix: build error

- apiserver/plane/bgtasks/analytic_plot_export.py
- apiserver/plane/bgtasks/forgot_password_task.py
- apiserver/plane/bgtasks/magic_link_code_task.py
- apiserver/plane/bgtasks/project_invitation_task.py
- apiserver/plane/bgtasks/workspace_invitation_task.py
Problem:
- #3108
Resolution:
- Resolved the issue by comparison method instead of converting the string to a boolean value.
> chore: resolved the email-use-tls error

- apiserver/plane/app/views/project.py
- Added the members list inside a project in the response of the project creation.
> chore: project member list

- web/components/issues/issue-layouts/properties/assignee.tsx
In Workspace Issues, issue assignee selection isn't functioning as intended; it fails to retrieve project members details upon selection.
I've modified the members fetching logic to rectify this issue. Now, it fetching and working as expected.
> fix: project members fetch fix

- deploy/selfhost/install.sh
> fix: typo in install.sh

- .github/workflows/build-branch.yml
branch build fix for space, backend, proxy build
> fix: branch build fix

- web/components/instance/email-form.tsx
This PR focuses on UI & UX update in instance admin email settings.
The following things have been updated: 
* `From address` ux copy
* Padding between the form fields.
> style: instance admin email settings ui & ux update.

- space/components/accounts/sign-in-forms/create-password.tsx
- space/components/accounts/sign-in-forms/email-form.tsx
- space/components/accounts/sign-in-forms/optional-set-password.tsx
- space/components/accounts/sign-in-forms/password.tsx
- space/components/accounts/sign-in-forms/self-hosted-sign-in.tsx
- space/components/accounts/sign-in-forms/set-password-link.tsx
- space/components/accounts/sign-in-forms/unique-code.tsx
- space/pages/accounts/password.tsx
- web/components/account/sign-in-forms/create-password.tsx
- web/components/account/sign-in-forms/email-form.tsx
- web/components/account/sign-in-forms/optional-set-password.tsx
- web/components/account/sign-in-forms/password.tsx
- web/components/account/sign-in-forms/self-hosted-sign-in.tsx
- web/components/account/sign-in-forms/set-password-link.tsx
- web/components/account/sign-in-forms/unique-code.tsx
- web/components/instance/setup-form/sign-in-form.tsx
- web/components/onboarding/invite-members.tsx
- web/pages/accounts/password.tsx
This PR includes an email placeholder text update, across the platform.
> style: email placeholder changed across the platform

- web/lib/wrappers/posthog-wrapper.tsx
* fix: posthog events trigger in staging
* refactor: cleared comment lines for warnings, added dependancy values
* refactor: removed unnecessary dependency
> fix: posthog events trigger in staging (#3220)

- web/components/labels/project-setting-label-list.tsx
This change resolves #3209 by fixing a minor typo.
> Fix spelling error in setting-label-list.tsx

- packages/editor/extensions/src/extensions/slash-commands.tsx
Fixed types for slash commands by inspecting generics
> fix: Fixed types for slash commands by inspecting generics

- .env.example
- docker-compose.yml
Adding docker file changes for segway
> feat: segway dockerize

- web/components/core/activity.tsx
- web/components/profile/overview/activity.tsx
> fix: adding issue title to the activity

- apiserver/plane/app/serializers/cycle.py
- apiserver/plane/app/views/cycle.py
- web/components/cycles/active-cycle-details.tsx
- web/components/cycles/cycles-board-card.tsx
- web/components/cycles/cycles-list-item.tsx
- web/components/cycles/gantt-chart/blocks.tsx
- web/components/cycles/sidebar.tsx
- web/components/cycles/transfer-issues-modal.tsx
- web/components/issues/issue-layouts/roots/cycle-layout-root.tsx
- web/helpers/date-time.helper.ts
- web/store/cycle/cycles.store.ts
- web/types/cycles.d.ts
In this PR
- Now the current status of the cycle will be sent in the response of the cycle.
- the status of the cycle can be `CURRENT`, `UPCOMING`, `COMPLETED` and `DRAFT`
> chore: cycle current status

- web/components/workspace/settings/members-list-item.tsx
- web/pages/workspace-invitations/index.tsx
- web/store/workspace/workspace-member.store.ts
Implemented new status like account not created and rejected values.
> fix: workspace invitation status fixes

- web/components/core/theme/theme-switch.tsx
- web/components/issues/issue-layouts/roots/project-layout-root.tsx
* style: fix `background-color` inconsistency in issue layout when custom theme is applied.
* fix: theme dropdown overlapping with input color picker icons (z-index issue).
> Style: custom theme UI fixes (#3284)

- web/pages/profile/index.tsx
- Updated profile setting form validation.
- Consistent error indicator added.
> chore: profile setting improvement

- packages/types/src/workspace.d.ts
- web/components/onboarding/invitations.tsx
- web/pages/invitations/index.tsx
- web/pages/workspace-invitations/index.tsx
Problem:
There were problems with workspace invitations not functioning correctly.
Resolution:
I resolved the issue occurring from changes in the workspace invitation responses. I ensured that names and other details are displayed accurately and functioning properly by updating the responses where necessary.
> fix: workspace invitations response updated

- apiserver/plane/app/urls/config.py
- apiserver/plane/app/views/__init__.py
- apiserver/plane/app/views/config.py
> chore: mobile configs

- apiserver/plane/api/views/base.py
- apiserver/plane/app/views/base.py
- apiserver/plane/space/views/base.py
- apiserver/plane/utils/issue_search.py
- apiserver/plane/utils/paginator.py
fix: security warnings related to information exposure and regex validations
> fix: security warnings related to information exposure and regex validations

- .github/workflows/codeql.yml
- apiserver/plane/app/views/importer.py
- apiserver/plane/utils/importers/jira.py
- web/components/integration/single-integration-card.tsx
- web/services/project/project.service.ts
fix: 
- jira importer validations
> fix: jira importer validations

- apiserver/plane/utils/importers/jira.py
fix: 
- jira summary endpoints to manually create urls with validations
> fix: update jira summary endpoints

- web/Dockerfile.web
Public assets copied to frontend image
> fix: web container public assets

- apiserver/plane/license/urls.py
- apiserver/plane/urls.py
- web/services/auth.service.ts
- web/services/instance.service.ts
> chore: instance api urls

- apiserver/plane/app/views/config.py
> fix: smtp configuration

- web/components/issues/issue-layouts/roots/project-layout-root.tsx
- web/constants/swr-config.ts
This PR updates the swr config to stop fetching on every focus, to avoid performance overheads because of it
> chore: update swr config

- web/components/cycles/active-cycle-details.tsx
- web/components/inbox/modals/select-duplicate.tsx
- web/components/issues/issue-layouts/calendar/issue-blocks.tsx
- web/components/issues/issue-layouts/gantt/blocks.tsx
- web/components/issues/select/label.tsx
- web/store/cycle.store.ts
- web/store/label/project-label.store.ts
- web/store/member/project-member.store.ts
- web/store/module.store.ts
- web/store/project-view.store.ts
- web/store/state.store.ts
This PR adds loaders to the store so that the value can be fetched from outside the project wrapper
> fix: project loaders for mobx store

- web/components/issues/issue-layouts/spreadsheet/base-spreadsheet-root.tsx
- web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
- web/components/issues/issue-layouts/spreadsheet/spreadsheet-table.tsx
- web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
This PR contains changes to enable peekoverview for spreadsheet layout and also minor refactor to enable faster opening between peekoverview
> fix: enable spreadsheet peek overview

- web/components/issues/issue-layouts/filters/header/helpers/dropdown.tsx
This PR include improvement for filter and display properties popover.
> chore: filter and display properties popover improvement

- web/components/issues/issue-detail/subscription.tsx
- web/components/issues/issue-layouts/filters/applied-filters/roots/project-view-root.tsx
- web/components/issues/issue-layouts/properties/labels.tsx
- web/components/issues/issue-layouts/save-filter-view.tsx
- web/components/issues/peek-overview/view.tsx
- web/components/issues/sub-issues/issue-list-item.tsx
- web/components/issues/sub-issues/issues-list.tsx
- web/components/issues/sub-issues/root.tsx
- web/components/views/form.tsx
- web/components/views/view-list-item.tsx
- web/store/issue/issue-details/relation.store.ts
- web/store/issue/issue-details/root.store.ts
- web/store/issue/issue-details/sub_issues.store.ts
- web/store/issue/project-views/filter.store.ts
- web/store/issue/project-views/issue.store.ts
This PR contains fixes for the following bugs,
- sub issues inside issue detail
- close peek over view after opening issue detail
- fix error while opening peek overview
- fix saving project views
> fix: refactor related bugs

- web/components/issues/issue-layouts/roots/cycle-layout-root.tsx
- web/store/issues/project-issues/cycle/issue.store.ts
This PR fixes the bug where in an error toast was being shown on successful creation of an issue.
> fix: error message on successful creation of cycle issues

- .github/ISSUE_TEMPLATE/--bug-report.yaml
- .github/ISSUE_TEMPLATE/--feature-request.yaml
chore: 
- update issue template to auto assign and update labels
> chore: update issue template to auto assign and update labels

- apiserver/plane/app/views/authentication.py
fix: key validation in email check endpoint
> fix: key validation in email check endpoint

- web/components/issues/issue-layouts/roots/all-issue-layout-root.tsx
- web/components/issues/peek-overview/root.tsx
- web/components/profile/profile-issues.tsx
- web/constants/common.ts
- web/store/issue/helpers/issue-filter-helper.store.ts
- web/store/issue/profile/filter.store.ts
- web/store/issue/profile/issue.store.ts
- web/store/issue/root.store.ts
This PR fixes,
- The global issues page filters and loading issue
- Enables Profile issues
- Add peek overview to global and profile issues
> fix: update global issues filter and enable profile issues

- apiserver/.env.example
dev: 
- update apiserver .env.example for Postgres
> dev: update apiserver .env.example

- .github/workflows/build-branch.yml
This PR reduces the time takes to generate the docker images. Also provides the workflow dispatch event to trigger builds manually.
> fix: docker branch builds

- apiserver/plane/db/models/issue.py
- apiserver/plane/utils/analytics_plot.py
- packages/types/src/cycles.d.ts
- packages/ui/src/progress/linear-progress-indicator.tsx
- web/components/core/sidebar/single-progress-stats.tsx
- web/components/cycles/active-cycle-details.tsx
- web/components/cycles/active-cycle-stats.tsx
- web/components/cycles/form.tsx
- web/components/issues/label.tsx
- web/components/modules/form.tsx
- web/constants/cycle.ts
- Project active cycles bug fixes & improvement. [[PLE-258](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/2c3e09c2-0222-4223-a92c-607e92761a0d)]
- Linear progress indicator component improvement.
- Start date validation added in cycle and module form modal.
> chore: project cycle bug fixes and improvement

- web/components/cycles/active-cycle-details.tsx
- web/constants/cycle.ts
- web/store/issue/cycle/issue.store.ts
- web/store/issue/module/issue.store.ts
- The add existing issues mutation is not functioning correctly in the module. [[PLE-280](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/e1215c3f-e635-4f84-81a7-7519a61dcab6)]
- The add existing issues mutation is not working properly in the cycles. [[PLE-279](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/41e8598d-0cc3-439b-a6ac-74568a5f735b)]
- Resolve the module mutation issue by updating the logic of the addIssueToModule function.
- Resolve the cycle mutation issue by updating the logic of the addIssueToCycle function.
- In addition, worked on enhancing the project active cycle.
> chore: module and cycle bug fixes

- web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
- web/components/issues/issue-layouts/kanban/blocks-list.tsx
- web/components/issues/issue-layouts/kanban/default.tsx
- web/components/issues/issue-layouts/roots/all-issue-layout-root.tsx
- web/helpers/state.helper.ts
- web/store/issue/helpers/issue-helper.store.ts
- web/store/issue/issue_kanban_view.store.ts
- web/store/state.store.ts
This PR takes care of the following issues in Kanban,
- sort states accordingly
- Disable drag n drop for un supported groups
- Enable horizontal scroll bar
- sorting order while dnd
And also one issue in Spread sheet quick action that was overlapping in all issues
> fix: Kanban related issues

- web/components/issues/sub-issues/issue-list-item.tsx
- web/components/issues/sub-issues/issues-list.tsx
- web/components/issues/sub-issues/properties.tsx
- web/components/issues/sub-issues/root.tsx
- web/lib/app-provider.tsx
- web/store/issue/issue-details/issue.store.ts
- web/store/issue/issue-details/root.store.ts
- web/store/issue/issue-details/sub_issues.store.ts
- web/store/issue/root.store.ts
- web/store/state.store.ts
1. While changing the state in the sub-issues the progress bar is not updating.
2. While changing the parent_issue_id in the sub-issues the issues are not moving between the parent issues.
1. Updated the actions in the sub-issues store to handle all the updates for state and parent_issue_id
> chore: sub issue mutation for state and project change

- package.json
- packages/ui/src/dropdowns/custom-search-select.tsx
- packages/ui/src/dropdowns/helper.tsx
- web/components/core/activity.tsx
- web/components/dashboard/widgets/recent-activity.tsx
- web/components/exporter/export-modal.tsx
- web/components/issues/issue-layouts/filters/header/filters/state.tsx
- web/components/issues/issue-modal/form.tsx
- web/components/profile/overview/activity.tsx
- web/components/workspace/sidebar-quick-action.tsx
- web/pages/profile/activity.tsx
This PR includes the changes for the following issues,
- Add concurrency to dev command to avoid erroring out
- Add context of the issue to issue activity
- Minor quality of life improvement for Exporter modal
- Show the option to save draft issue only when there is content in name or description
- Maintain commonality while referencing the user in activity
- minor change is state component for filter 
- change use last draft issue button to state control over previous on hover as that was inconsistent
> fix: minor bug fixes and quality of life improvements

- web/components/core/activity.tsx
- web/components/issues/issue-detail/issue-activity/activity/actions/estimate.tsx
- web/components/issues/issue-detail/main-content.tsx
- web/components/issues/issue-detail/root.tsx
- web/components/issues/issue-layouts/list/roots/archived-issue-root.tsx
- web/components/issues/issue-layouts/roots/all-issue-layout-root.tsx
- web/components/issues/issue-layouts/roots/archived-issue-layout-root.tsx
- web/components/issues/peek-overview/issue-detail.tsx
- web/components/issues/peek-overview/root.tsx
- web/components/issues/peek-overview/view.tsx
- web/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx
- web/store/estimate.store.ts
- web/store/issue/archived/filter.store.ts
- web/store/issue/archived/issue.store.ts
- web/store/issue/cycle/filter.store.ts
- web/store/issue/draft/filter.store.ts
- web/store/issue/helpers/issue-filter-helper.store.ts
- web/store/issue/issue_kanban_view.store.ts
- web/store/issue/module/filter.store.ts
- web/store/issue/profile/filter.store.ts
- web/store/issue/project-views/filter.store.ts
- web/store/issue/project/filter.store.ts
- web/store/issue/workspace/filter.store.ts
This PR fixes the following issues,
- Define computedFn methods without optional arguments as it is a bad practice
- Fix archived issues and peek overview
- Fix activity to have proper context regarding the issue
- Fix to change display filters that require server side filtering
> fix: archived issues and minor bug fixes

- web/components/core/activity.tsx
- web/components/issues/issue-layouts/kanban/default.tsx
- web/components/issues/issue-layouts/kanban/kanban-group.tsx
- web/components/issues/peek-overview/activity/card.tsx
- web/pages/profile/activity.tsx
This PR contains changes for,
- Changing Kanban back to enable full board scrolling to fix horizontal scrolling while dragging
- Adding context for issue in activity
> Chore: change kanban layout and issue activity fixes

- apiserver/plane/app/views/page.py
- Fixed the archive functionality to ensure pages are correctly marked and stored in the archive.
- Corrected the unarchive process, ensuring that previously archived pages are restored accurately.
> fix: page archive and unarchive

- web/components/empty-state/empty-state.tsx
- web/components/page-views/workspace-dashboard.tsx
- web/components/workspace/help-section.tsx
- Improved empty state images.
- Added tooltip in the app sidebar's help section.
- Refined dashboard empty state for better user experience.
> chore: bug fixes and ui improvements

- web/components/core/modals/bulk-delete-issues-modal.tsx
- web/store/issue/project/issue.store.ts
- web/store/issue/workspace/filter.store.ts
This PR includes 
1. Removed log from the global issue filter store
2. While deleting the bulk issues from the bulk issue delete modal we are also removing the issues from the global issue store
> fix: updating the global issue store while removing the issue from bulk delete.

- web/pages/[workspaceSlug]/projects/[projectId]/archived-issues/[archivedIssueId].tsx
- web/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx
- web/store/issue/archived/issue.store.ts
- web/store/issue/issue-details/issue.store.ts
- web/store/issue/issue-details/root.store.ts
This PR fixes the issue detail page of archived issues
> chore: archived issues restructure.

- web/components/project/member-list.tsx
This PR adds more guards against member list from throwing an exception
> chore: add more guards against exception in member-list

- web/components/issues/attachment/attachment-detail.tsx
- web/components/issues/attachment/attachment-upload.tsx
- web/components/profile/sidebar.tsx
- web/helpers/attachment.helper.ts
- web/store/issue/issue-details/attachment.store.ts
This PR handles 
1. Attachment upload filename length issue and optimizes the mutation of the attachment store
2. UI improvement on profile detail page
> fix: handled attachment upload filename size error in the issue detail

- web/components/cycles/sidebar.tsx
- web/components/modules/sidebar.tsx
- web/components/profile/index.ts
- web/components/profile/sidebar.tsx
- web/components/profile/time.tsx
- web/components/user/user-greetings.tsx
- web/hooks/use-current-time.tsx
Dashboard and profile sidebar time not updating in real-time.
1. Created a new custom hook, `useCurrentTime`, to get current time and update it in real-time.
2. Replaced the old time logic with the new hook in the dashboard greeting and profile sidebar.
1. Close cycle and module sidebar date-picker after selecting a date.
> chore: update time in real-time in dashboard and profile sidebar

- web/components/issues/issue-layouts/kanban/roots/profile-issues-root.tsx
- web/components/issues/issue-layouts/list/roots/profile-issues-root.tsx
- web/components/issues/issue-layouts/properties/labels.tsx
- web/components/project/sidebar-list.tsx
This PR resolves the application error that arises when navigating to a user profile issues, and it rectify the malfunctioning profile issue update, which was not functioning as intended previously.
> fix: profile issue application error

- web/components/dashboard/home-dashboard-widgets.tsx
- web/components/dashboard/widgets/created-issues.tsx
- web/components/dashboard/widgets/recent-projects.tsx
1. Added `key` to items while mapping through an array in all the missing places.
> fix: unique key errors

- web/components/cycles/active-cycle-details.tsx
- web/components/cycles/cycles-board.tsx
- web/components/cycles/cycles-list.tsx
- web/components/issues/issue-layouts/empty-states/archived-issues.tsx
- web/components/issues/issue-layouts/empty-states/draft-issues.tsx
- web/components/issues/issue-layouts/empty-states/project-issues.tsx
- web/components/issues/issue-layouts/roots/all-issue-layout-root.tsx
- web/components/modules/modules-list-view.tsx
- web/components/page-views/workspace-dashboard.tsx
- web/components/pages/pages-list/list-view.tsx
- web/components/pages/pages-list/recent-pages-list.tsx
- web/components/profile/profile-issues.tsx
- web/components/project/card-list.tsx
- web/components/views/views-list.tsx
- web/pages/[workspaceSlug]/analytics.tsx
- web/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx
- web/pages/[workspaceSlug]/projects/[projectId]/pages/index.tsx
This PR includes enhancements for the empty state, taking into account system preferences. Previously, it did not function as intended in alignment with system preferences theme.
> chore: empty state theme improvement

- web/components/headers/global-issues.tsx
- web/components/issues/description-form.tsx
- web/components/issues/issue-detail/parent/siblings.tsx
- web/components/issues/issue-layouts/calendar/quick-add-issue-form.tsx
- web/components/issues/issue-layouts/empty-states/archived-issues.tsx
- web/components/issues/issue-layouts/empty-states/draft-issues.tsx
- web/components/issues/issue-layouts/empty-states/project-issues.tsx
- web/components/issues/issue-layouts/gantt/blocks.tsx
- web/components/issues/issue-layouts/kanban/quick-add-issue-form.tsx
- web/components/issues/issue-layouts/roots/all-issue-layout-root.tsx
- web/components/issues/issue-layouts/spreadsheet/base-spreadsheet-root.tsx
- web/components/issues/select/label.tsx
- web/components/pages/create-update-page-modal.tsx
- web/pages/profile/activity.tsx
In this PR, I have eliminated unused variables, enhancing code clarity and maintainability.
> chore: unused var removed

- packages/ui/src/progress/linear-progress-indicator.tsx
- web/components/cycles/active-cycle-details.tsx
- linear progress indicator component improvement.
- project active cycle improvement.
> chore: project active cycle and linear progress indicator improvement

- web/store/issue/cycle/issue.store.ts
This PR fixes error with quick add in cycle issues
> fix: Quick add fix for cycles

- web/components/account/sign-in-forms/optional-set-password.tsx
- web/components/account/sign-in-forms/password.tsx
- web/components/account/sign-up-forms/optional-set-password.tsx
- web/components/account/sign-up-forms/password.tsx
- web/components/instance/setup-form/sign-in-form.tsx
- web/pages/accounts/reset-password.tsx
Our password fields didn't had the functionality to hide/ unhide password.
Implemented the same.
> improvement: add hide/ unhide icon for all password field in the platform.

- web/components/issues/issue-detail/inbox/main-content.tsx
- web/components/issues/issue-detail/issue-activity/comments/comment-create.tsx
- web/components/issues/issue-detail/issue-activity/root.tsx
- web/components/issues/issue-detail/main-content.tsx
- web/components/issues/peek-overview/view.tsx
Disabled comments for guests/viewers after recent refactor.
Removed unnecessary code that disabled comments for these user roles.
> chore: enable comments for guest/ viewers.

- web/components/cycles/sidebar.tsx
- web/components/issues/issue-layouts/calendar/base-calendar-root.tsx
- web/store/issue/cycle/issue.store.ts
- web/store/issue/module/issue.store.ts
- web/store/issue/root.store.ts
1. Changes made to the layout are not reflected in the module and sidebar when updating any issue.
2. The drag-and-drop functionality in the calendar does not behave as expected in the cycle and module issues.
1. The problem has been addressed by implementing the required mutation and fetch logic.
2. The problem has been addressed by implementing the required fixes to enhance the drag-and-drop functionality in the calendar for cycle and module issues.
> fix: cycle and module sidebar mutation fix

- packages/editor/core/src/ui/mentions/custom.tsx
- packages/editor/core/src/ui/mentions/suggestion.ts
- packages/editor/lite-text-editor/src/ui/extensions/enter-key-extension.tsx
- packages/editor/lite-text-editor/src/ui/extensions/index.tsx
- web/components/issues/issue-detail/issue-activity/comments/comment-create.tsx
> chore: removing unnecessary code

- apiserver/plane/bgtasks/email_notification_task.py
- apiserver/templates/emails/notifications/issue-updates.html
This PR fixes, the email-template heading.
> fix: email-template heading overview

- apiserver/plane/app/serializers/cycle.py
- packages/types/src/cycles.d.ts
- web/components/analytics/custom-analytics/sidebar/sidebar-header.tsx
- web/components/cycles/active-cycle-details.tsx
- web/components/cycles/sidebar.tsx
- Encountered an error with the update cycle.
- Resolved the update cycle error, ensuring proper response, and implemented the necessary changes.
> fix: update cycle error

- web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
- web/components/issues/issue-layouts/roots/all-issue-layout-root.tsx
This PR contains changes to fix,
- The sorting in spreadsheet for all issues
- Dnd for Kanban for long lists
> fix: all issues spreadsheet sorting and kanban dnd for long lists

- web/components/core/sidebar/sidebar-progress-stats.tsx
This PR include improvement for cycle and module sidebar improvement.
> chore: cycle and module sidebar improvement

- web/components/modules/form.tsx
- web/components/modules/sidebar.tsx
This PR addresses the issue related to module date validation, resolving the issue where users were unable to modify the date of an existing module.
> chore: module date validation

- apiserver/plane/app/views/module.py
This fixes the count of the module issue's
> chore: module issue count

- web/components/headers/workspace-dashboard.tsx
This PR refactors the workspace dashboard component.
> chore: workspace dashboard refactor

- web/pages/_document.tsx
This PR include the removal of unnecessary PostHog code.
> chore: posthog code refactor

- apiserver/templates/emails/notifications/issue-updates.html
chore:
- email template logo changed
> chore: email template logo changed

- apiserver/plane/app/views/issue.py
- web/components/command-palette/command-palette.tsx
- web/components/headers/project-draft-issues.tsx
- web/components/issues/issue-layouts/kanban/block.tsx
- web/components/issues/issue-layouts/kanban/headers/group-by-card.tsx
- web/components/issues/issue-layouts/list/block.tsx
- web/components/issues/issue-layouts/list/headers/group-by-card.tsx
- web/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx
- web/components/issues/issue-modal/draft-issue-layout.tsx
- web/components/issues/issue-modal/form.tsx
- web/components/issues/issue-modal/modal.tsx
- web/store/issue/draft/issue.store.ts
- Enhanced functionality in the create/update issue modal to properly handle draft issues. The feature to move draft issues to project issues was not functioning as intended and has been corrected.
> fix: handled the draft issue from issue create modal and optimised the draft issue store

- web/components/headers/project-issues.tsx
This PR fixes the missing Inbox on the mobile view
> fix: Add Inbox back on mobile

- web/components/headers/project-issues.tsx
- web/components/modules/module-mobile-header.tsx
This PR contains the fix for the module issues header persisting on bigger screens.
> fix: module header hide on bigger screens

- web/components/core/sidebar/sidebar-menu-hamburger-toggle.tsx
- web/components/headers/user-profile.tsx
- web/components/profile/navbar.tsx
- web/components/profile/sidebar.tsx
- web/layouts/settings-layout/profile/preferences/layout.tsx
- web/layouts/settings-layout/profile/preferences/sidebar.tsx
- web/layouts/settings-layout/profile/sidebar.tsx
- web/layouts/user-profile-layout/layout.tsx
- web/pages/[workspaceSlug]/profile/[userId]/assigned.tsx
- web/pages/[workspaceSlug]/profile/[userId]/created.tsx
- web/pages/[workspaceSlug]/profile/[userId]/index.tsx
- web/pages/[workspaceSlug]/profile/[userId]/subscribed.tsx
- web/pages/profile/activity.tsx
- web/pages/profile/change-password.tsx
- web/pages/profile/index.tsx
- web/pages/profile/preferences/theme.tsx
- web/store/application/theme.store.ts
This PR contains the following updates
1. Responsive profile screen.
2. Responsive profile settings screen.
https://github.com/makeplane/plane/assets/31303617/5c25065b-dcab-410e-84cb-2da37b76df45
> style: responsive profile

- packages/ui/src/breadcrumbs/breadcrumbs.tsx
- packages/ui/src/dropdowns/custom-menu.tsx
- The breadcrumb component lacks responsiveness on smaller screens.
- Custom menu dropdowns fail to close upon selecting an option.
- Implemented essential modifications to ensure responsiveness of the breadcrumb component.
- Addressed the issue by implementing necessary validation.
> chore: custom menu dropdown improvement

- packages/ui/src/dropdowns/custom-menu.tsx
- web/components/notifications/notification-card.tsx
This PR includes a fix for an event propagation issue related to the notification card's snooze button. It ensures that the snooze button behaves as expected without any propagation problems.
> fix: notification card snooze

- web/components/notifications/notification-card.tsx
- web/components/notifications/notification-header.tsx
- web/components/notifications/notification-popover.tsx
- web/components/notifications/select-snooze-till-modal.tsx
https://github.com/makeplane/plane/assets/94619783/d182ac98-6a96-4b19-a1bf-0f9ba2ed1087
https://github.com/makeplane/plane/assets/94619783/248b44d4-d368-46ff-9c5b-eda856410aba
**Fixes:**
1. The popover was also closing on the close notification snooze modal.
2. The custom menu was not closing on clicking any menu item.
> fix: notification popover responsiveness

- packages/ui/src/form-fields/checkbox.tsx
- packages/ui/src/form-fields/index.ts
- web/components/profile/preferences/email-notification-form.tsx
- web/pages/profile/preferences/email.tsx
This PR adds custom checkbox component to our UI packages and includes improvements in email notification settings page by adding new checkbox component along with a loader.
Created a new customized checkbox component as per our designs:
> feat: checkbox component

- web/components/headers/project-issue-details.tsx
- web/components/issues/issue-detail/issue-activity/activity/actions/helpers/activity-block.tsx
- web/components/issues/issue-detail/root.tsx
- web/components/issues/issue-detail/sidebar.tsx
- web/components/issues/issue-detail/subscription.tsx
- web/components/issues/issue-layouts/spreadsheet/columns/header-column.tsx
- web/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx
- web/store/application/theme.store.ts
This PR contains the update for the issue detail screen responsiveness.
https://github.com/makeplane/plane/assets/31303617/814c5dea-e6a2-4b6e-b6f7-54ed1b760934
> style: issue detail responsiveness

- packages/editor/document-editor/src/ui/components/editor-header.tsx
- packages/editor/document-editor/src/ui/components/page-renderer.tsx
- packages/editor/document-editor/src/ui/components/summary-popover.tsx
- packages/editor/document-editor/src/ui/index.tsx
- packages/editor/document-editor/src/ui/menu/fixed-menu.tsx
- web/components/core/sidebar/sidebar-menu-hamburger-toggle.tsx
- web/components/empty-state/empty-state.tsx
- web/components/headers/page-details.tsx
- web/components/pages/create-update-page-modal.tsx
- web/components/pages/page-form.tsx
- web/components/pages/pages-list/list-item.tsx
- web/components/pages/pages-list/recent-pages-list.tsx
- web/pages/[workspaceSlug]/projects/[projectId]/pages/index.tsx
https://github.com/makeplane/plane/assets/94619783/3a942d3d-c486-4409-a2eb-8672ecabc091
https://github.com/makeplane/plane/assets/94619783/aac8e8e4-2dbf-4d27-975c-4a9cf49484e8
> fix: project-pages responsiveness

- web/components/gantt-chart/blocks/blocks-list.tsx
- web/components/gantt-chart/chart/main-content.tsx
- web/components/gantt-chart/chart/root.tsx
- web/components/gantt-chart/chart/views/month.tsx
- web/components/gantt-chart/root.tsx
- web/components/gantt-chart/sidebar/root.tsx
- web/components/issues/issue-layouts/gantt/base-gantt-root.tsx
- web/components/modules/gantt-chart/modules-list-layout.tsx
1. Gantt chart sidebar not occupying full width.
2. Add block button authorization not working.
> fix: sidebar height, authorization

- web/components/core/render-if-visible-HOC.tsx
- web/components/cycles/sidebar.tsx
- web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
Minor change to add border color of placeholder for spreadsheet
> chore: change border of placeholder for spreadsheet

- web/components/core/sidebar/sidebar-menu-hamburger-toggle.tsx
- web/layouts/app-layout/sidebar.tsx
- web/store/application/theme.store.ts
This PR resolves an issue with the app sidebar reseting upon reloading. It includes the required fixes to rectify this problem.
> chore: app sidebar state

- web/components/issues/issue-layouts/kanban/utils.ts
This PR contains changes to fix Kanban dnd by stopping the modification of the original array by spreading to change the array reference
> fix: Kanban DND within the array

- web/components/issues/issue-layouts/filters/applied-filters/roots/cycle-root.tsx
- web/components/issues/issue-layouts/filters/applied-filters/roots/module-root.tsx
- web/components/issues/issue-layouts/roots/all-issue-layout-root.tsx
- web/components/issues/issue-layouts/roots/archived-issue-layout-root.tsx
- web/components/issues/issue-layouts/roots/cycle-layout-root.tsx
- web/components/issues/issue-layouts/roots/draft-issue-layout-root.tsx
- web/components/issues/issue-layouts/roots/module-layout-root.tsx
- web/components/issues/issue-layouts/roots/project-layout-root.tsx
- web/components/issues/issue-layouts/roots/project-view-layout-root.tsx
- web/store/issue/archived/issue.store.ts
- web/store/issue/draft/issue.store.ts
- yarn.lock
This PR includes empty state loaders and filter cancel state updates for modules and cycles
> fix: empty state loaders and filter cancel state updates for modules and cycles

- web/components/issues/issue-layouts/roots/cycle-layout-root.tsx
- web/components/issues/issue-layouts/roots/draft-issue-layout-root.tsx
- web/components/issues/issue-layouts/roots/module-layout-root.tsx
- web/components/issues/issue-layouts/roots/project-view-layout-root.tsx
This PR contains enhancements for the loading state loader. Previously, there was a brief occurrence of the spinner loader appearing before the layout loader. I have addressed and resolved this issue.
> chore: loading state improvement

- web/components/issues/description-form.tsx
This PR includes resolving the infinity loader in the issue description in the issue peek overview and issue detail page
> fix: infinity loader in the issue description in the issue peek overview and issue detail page

- web/components/issues/issue-layouts/kanban/default.tsx
<hr>
https://github.com/makeplane/plane/assets/94619783/ba8a6df7-84ac-4c4a-8985-7a17921ba6e5
> fix: kanban-layout responsiveness

- web/components/cycles/cycles-board-card.tsx
- web/components/cycles/cycles-list-item.tsx
- web/components/issues/issue-detail/sidebar.tsx
- fix for the cycle favorite mutation bug.
- Issue detail sidebar overflow fix.
> fix: cycle favorite mutation

- web/components/core/sidebar/sidebar-menu-hamburger-toggle.tsx
- web/components/project/sidebar-list-item.tsx
- web/components/workspace/help-section.tsx
- web/components/workspace/sidebar-dropdown.tsx
- web/components/workspace/sidebar-menu.tsx
- web/layouts/settings-layout/profile/preferences/layout.tsx
- web/layouts/settings-layout/profile/sidebar.tsx
- web/pages/profile/activity.tsx
- web/pages/profile/change-password.tsx
- web/pages/profile/index.tsx
This PR contains the fix for the sidebar close on item tap in mobile responsiveness.
https://github.com/makeplane/plane/assets/31303617/76b8498b-5d61-4252-8123-1855e6b78886
> fix: mobile responsive sidebar close on item tap

- web/components/issues/issue-detail/parent/root.tsx
This PR includes fix for parent issue redirection in issue details page.
> fix: issue details page parent issue redirection

- web/components/gantt-chart/chart/main-content.tsx
- web/components/gantt-chart/chart/root.tsx
- web/components/gantt-chart/root.tsx
- web/components/gantt-chart/sidebar/issues.tsx
- web/components/gantt-chart/sidebar/root.tsx
- web/components/issues/issue-layouts/gantt/base-gantt-root.tsx
- web/components/issues/issue-layouts/gantt/quick-add-issue-form.tsx
This PR has changes for fixing horizontal scroll in gantt chart while dragging the blocks in the sidebar
> fix: horizontal scroll in gantt chart while dragging

- apiserver/plane/app/views/search.py
chore: An Issue added as a parent to an issue can also be added as a parent to another issue.
> chore: parent can be added to issue

- web/components/issues/description-form.tsx
* fix: peek overview issue description infinite loading for certain data sets
> release: peek overview issue description initial load bug (#3670)

- apiserver/plane/app/views/inbox.py
- web/components/inbox/inbox-issue-status.tsx
- web/components/issues/description-form.tsx
1. The description in the inbox is not loading.
2. Mutation for changing the inbox status is not occurring without a refresh to view the changes.
1. To resolve this issue, the backend has been updated to include description_html in the inbox response. Additionally, necessary adjustments have been made to the frontend.
2. The missing MobX observer method in the component has been added, fixing the mutation issue.
> fix: inbox description and mutation

- web/components/headers/project-issues.tsx
- web/components/inbox/sidebar/root.tsx
- web/components/project/sidebar-list-item.tsx
- web/components/ui/loader/layouts/index.ts
- web/components/ui/loader/layouts/project-inbox/inbox-layout-loader.tsx
- web/components/ui/loader/layouts/project-inbox/inbox-sidebar-loader.tsx
- web/components/ui/loader/layouts/project-inbox/index.ts
- web/pages/[workspaceSlug]/projects/[projectId]/inbox/index.tsx
- Integration of project inbox into the app sidebar among project items.
- Introduction of an indicator for inbox issues.
- Implementation of a loader within the inbox layout to enhance user experience.
This PR is linked to [[WEB-386]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/2093aa31-a014-4ad7-b90c-eeabc7199b06).
> chore : project inbox improvement

- web/components/issues/sub-issues/root.tsx
This PR addresses the requirement to have the sub-issues accordion on the issue detail page open by default.
[scrnli_2_20_2024_7-59-51 PM.webm](https://github.com/makeplane/plane/assets/33979846/1bd2ccc0-d08e-4d6d-92b7-a5dc51212b78)
This PR is linked to [WEB-463](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/f1d60033-90cc-4ac7-ad5a-9a1a8b51afbb)
> [WEB-463] improvement: open sub-issues accordion by default in issue details page.

- web/components/dropdowns/module.tsx
- web/components/issues/issue-detail/sidebar.tsx
- web/components/issues/issue-detail/subscription.tsx
- web/components/issues/peek-overview/properties.tsx
1. The issue sidebar overflows when a module with a longer name is selected.
2. The properties section of multi-select options is misaligned and inconsistent.
3. An exception error occurs occasionally when opening a peek overview of an issue without any assignee.
4. When initially opening the peek overview, the subscription button flickers for a second, and during the update, the loading state appears misaligned.
1. Address the overflow issue by truncating the text.
2. Adjust the layout to ensure alignment and consistency.
3. Resolve the error by implementing a check for the absence of an assignee.
4. Address this issue by implementing a loader and ensuring proper alignment for the loading state.
| ![image …
> [WEB-482] chore: issue sidebar improvement

- web/styles/globals.css
This PR resolves the issue of empty space for scrollbar in areas where scrolling is not available. I have addressed this and made the necessary changes.
Issue link: [[WEB-327]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/b9076fe4-f6bb-4e12-b84e-69f721c0916a)
> [WEB-327] chore: scrollbar improvement

- apiserver/plane/api/views/issue.py
- apiserver/plane/api/views/state.py
[WEB - 485](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/089b9f42-48e5-4161-998d-1879ecdce91e)
chore:
- add name validation for already existing states
- add external_id and external_source validation for already existing issue comments
> [WEB - 485] chore: external apis validation

- apiserver/plane/app/views/dashboard.py
- web/components/dashboard/widgets/issue-panels/issue-list-item.tsx
- web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
[[WEB-490]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/1ae011b6-9ad7-40a9-b985-6b69bffa1a3f)
- Fixed dashboard issue serializer
> [WEB - 490] chore: issue serializer changes

- web/components/ui/loader/layouts/project-inbox/inbox-layout-loader.tsx
This PR includes enhancements to the inbox layout loader. Previously, there were two distinct loaders; I've unified them to ensure consistency.
Issue link: [[WEB-487]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/aececa19-17da-4352-a95e-40cb676cf05d)
> [WEB-487] chore: inbox loader improvement

- web/constants/issue.ts
- web/store/issue/archived/filter.store.ts
- web/store/issue/cycle/filter.store.ts
- web/store/issue/draft/filter.store.ts
- web/store/issue/module/filter.store.ts
- web/store/issue/profile/filter.store.ts
- web/store/issue/project-views/filter.store.ts
- web/store/issue/project/filter.store.ts
This PR enables sub issue toggle to solve [WEB-547](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/bedcf4ca-bfb6-4998-b508-2e41d54f37aa) in spreadsheet layouts
> [WEB-547] fix: Re enable sub issues toggle in spreadsheet layout

- web/components/views/view-list-item.tsx
- web/components/workspace/views/default-view-list-item.tsx
- web/components/workspace/views/view-list-item.tsx
This PR addresses the flickering issue observed when hovering over the project and workspace views list.
> [WEB-543] chore: project and workspace views list improvement

- apiserver/plane/app/serializers/issue.py
- apiserver/plane/app/views/inbox.py
- apiserver/plane/app/views/issue.py
- apiserver/plane/bgtasks/email_notification_task.py
[[WEB-532](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/aaea8126-446e-483d-a6e7-c62dad87c435)]
fix:
- Email notification getting triggered for the issue assignees
> [WEB-532] fix: email notification assignees

- web/components/onboarding/user-details.tsx
- web/pages/profile/index.tsx
This PR includes maximum length validation for the user's first name, last name, and display name.
> [WEB-476] chore: max length validation added in user name inputs

- web/pages/[workspaceSlug]/projects/[projectId]/archived-issues/index.tsx
- web/pages/[workspaceSlug]/projects/[projectId]/draft-issues/index.tsx
This pull request includes a fix for the header draft issue. Previously, it was not functioning properly and did not appear as intended.
| ![image (49)](https://github.com/makeplane/plane/assets/121005188/30d53a78-082d-4d96-b719-daa1c22e7991) | ![image (50)](https://github.com/makeplane/plane/assets/121005188/bb587223-bf50-4514-bfc7-af7b088bcf93) |
> [WEB-542] fix: project draft issue button

- apiserver/plane/settings/common.py
chore: 
- fix sentry profiling rate
> chore: fix sentry profiling rate

- web/components/issues/issue-detail/subscription.tsx
- web/pages/[workspaceSlug]/projects/[projectId]/inbox/[inboxId].tsx
This PR includes enhancements for the inbox issue layout loader and the subscription button loader in the issue peek overview.
> [WEB-565] chore: inbox layout loader and peek overview subscription improvement

- .github/workflows/build-branch.yml
- packages/ui/src/avatar/avatar-group.tsx
Github action `branch-build` modified to do builds if any of the 1 condition is met
- files are changed or
- release tag is set or
- branch is master
> [INFRA-7] feat: selective build

- apiserver/plane/app/views/config.py
[WEB-533](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/650ba1a3-b68b-4000-aa5c-606526641aa0)
- Added null key validation for the posthog events
> [WEB-533] chore: posthog key validation

- apiserver/plane/utils/issue_search.py
[WEB-572](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/a251f06b-2ae3-4619-bb8b-24b6fe041826)
Chore: Issues can be searched by sequence id in issue detail page
> [WEB-572] chore: sequence id search in the issue search

- web/components/onboarding/user-details.tsx
This PR includes improvement for onboarding screen user name validation error indicator.
> [WEB-560] chore: onboarding improvement

- web/components/issues/issue-detail/inbox/root.tsx
This PR includes enhancements for the inbox issue detail activity and comment initial loading. Previously, it wasn't loading on the initial load; instead, it was reflecting on issue update. I've made the necessary adjustments to ensure it loads during the initial load phase.
> [WEB-587] chore: inbox issue detail activity and comment initial load improvement

- web/components/dropdowns/cycle/index.tsx
- web/components/dropdowns/member/index.tsx
This PR includes improvements for keyboard accessibility in spreadsheet layout:
- Enabled toggling focus using the Enter key for dropdowns.
> [WEB-586] chore: spreadsheet layout dropdowns focus on toggle functionality added

- web/components/emoji-icon-picker/index.tsx
- web/helpers/emoji.helper.tsx
This PR addresses the consistency of project emoji-icons. Previously, there was a disparity in size between emojis and icons, with icons being slightly larger than emojis. I have made the necessary adjustments to ensure consistency in their dimensions.
> [WEB-602] chore: project emoji icon improvement

- web/components/dropdowns/priority.tsx
This PR introduces enhancements for the hover state of the "none" value in the priority dropdown. Previously, there was no hover state available. I have added the hover state to ensure consistency.
> [WEB-603] chore: priority icon none state hover state added

- web/components/issues/issue-detail/cycle-select.tsx
This PR includes enhancements to the cycle select styling in both the issue sidebar and peek overview. Previously, it lacked consistency with the rest of the dropdowns. I've now ensured uniformity.
> [WEB-589] chore: issue sidebar and peek overview cycle select improvement

- web/components/issues/issue-modal/modal.tsx
- web/components/workspace/sidebar-quick-action.tsx
This PR addresses an issue where the description of an issue did not appear in the draft issue edit modal. Users encountered difficulties in accessing and modifying the description of draft issues, impacting the accuracy and completeness of issue details.
> [WEB-606] fix: issue description on last draft issue

- web/components/analytics/custom-analytics/main-content.tsx
- web/components/analytics/custom-analytics/sidebar/projects-list.tsx
- web/components/analytics/custom-analytics/sidebar/sidebar.tsx
- web/components/core/image-picker-popover.tsx
- web/components/core/modals/existing-issues-list-modal.tsx
- web/components/emoji-icon-picker/index.tsx
- web/components/issues/issue-layouts/filters/header/display-filters/display-filters-selection.tsx
- web/components/issues/issue-layouts/filters/header/filters/filters-selection.tsx
- web/components/issues/parent-issues-list-modal.tsx
- web/components/profile/sidebar.tsx
- web/layouts/settings-layout/profile/layout.tsx
- web/layouts/settings-layout/profile/preferences/layout.tsx
- web/layouts/settings-layout/profile/sidebar.tsx
- web/layouts/settings-layout/project/layout.tsx
- web/layouts/settings-layout/workspace/layout.tsx
- web/pages/[workspaceSlug]/profile/[userId]/index.tsx
- web/pages/[workspaceSlug]/projects/[projectId]/settings/estimates.tsx
- web/pages/[workspaceSlug]/projects/[projectId]/settings/integrations.tsx
- web/pages/[workspaceSlug]/projects/[projectId]/settings/labels.tsx
- web/pages/[workspaceSlug]/settings/api-tokens.tsx
- web/pages/[workspaceSlug]/settings/webhooks/index.tsx
- web/pages/profile/activity.tsx
- web/pages/profile/index.tsx
- web/pages/profile/preferences/email.tsx
This PR includes the implementation of scrollbars in following places:
- Workspace settings.
- Project settings.
- Profile settings.
- Filter & dropdowns.
- Modals.
> [WEB-579] style: scrollbar implementation

- packages/editor/core/src/ui/extensions/custom-link/helpers/clickHandler.ts
- packages/editor/core/src/ui/extensions/custom-link/helpers/pasteHandler.ts
- packages/editor/core/src/ui/extensions/custom-link/index.ts
Fixed the issue with links not working when applying formatting (like bold, itatic, etc) on the link node
https://github.com/makeplane/plane/assets/73993394/2066f34b-8809-42b2-b787-100ff51ebae8
> [WEB-617] fix: link behaviour fixed on formatting

- web/pages/[workspaceSlug]/projects/[projectId]/settings/states.tsx
This PR includes updates to the project states setting header content.
> [WEB-581] chore: project states setting page improvement

- web/components/modules/module-card-item.tsx
- web/components/modules/module-list-item.tsx
This PR addresses the overflow issue in the module quick action dropdown.
> [WEB-623] fix: module quick action dropdown overflow fix

- .github/workflows/feature-deployment.yml
The new process makes the build and uploads tar.gz to S3 bucket. Helm then pull the tar.gz and do the deployment
Required Secrets and Variables mentioned below
- FEATURE_PREVIEW_KUBE_CONFIG
- FEATURE_PREVIEW_AWS_SECRET_ACCESS_KEY
- TAILSCALE_OAUTH_CLIENT_ID
- TAILSCALE_OAUTH_SECRET
- FEATURE_PREVIEW_AWS_BUCKET
- FEATURE_PREVIEW_AWS_ACCESS_KEY_ID
- FEATURE_PREVIEW_NEXT_PUBLIC_API_BASE_URL
- FEATURE_PREVIEW_PRIMARY_DOMAIN
- FEATURE_PREVIEW_DOCKER_BASE
- FEATURE_PREVIEW_DEPLOY_SCRIPT_URL
- FEATURE_PREVIEW_HELM_CHART_URL
- FEATURE_PREVIEW_HELM_CHART_NAME
- FEATURE_PREVIEW_NAMESPACE
- FEATURE_PREVIEW_KUBE_VERSION
> chore: feature build process optimization

- web/components/workspace/sidebar-dropdown.tsx
| ![image](https://github.com/makeplane/plane/assets/33979846/2218ac11-d59b-4602-9d0d-e8c654fde005) | ![image](https://github.com/makeplane/plane/assets/33979846/95dbd49e-2302-4b6f-87ae-1d2320c6b961) | 
| ![image](https://github.com/makeplane/plane/assets/33979846/24e78f09-73ba-42f3-acdf-fd77ef5e86d1) | ![image](https://github.com/makeplane/plane/assets/33979846/a62cbd95-a39d-4f5b-adb6-514838b9c2f0) | 
This PR is linked to [WEB-666](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/cedf9b62-c063-494d-97ef-ffc07e0f16f9)
> [WEB-666] chore: rename `View profile` to `My activity`.

- web/components/project/create-project-form.tsx
- web/components/project/create-project-modal.tsx
- web/components/project/index.ts
- web/components/project/project-feature-update.tsx
- web/components/project/settings/features-list.tsx
- web/pages/[workspaceSlug]/projects/[projectId]/settings/features.tsx
1. When creating a new project, there's no option to let the project creator select the features of the project they want to enable.
2. Users don't understand what project identifier stands for and how it will be used by them or why they should edit it. 
1. Added the functionality to update projects features after the creation of project.
2. Renamed to project identifier to Project Id and added a tooltip to explain it. 
[scrnli_3_8_2024_2-22-32 PM.webm](https://github.com/makeplane/plane/assets/33979846/708c8bbb-e8f6-40a4-8c92-3c876ae69cf1)
> [WEB-440] feat: create project feature selection modal.

- web/components/issues/issue-layouts/filters/applied-filters/filters-list.tsx
- web/components/issues/issue-layouts/filters/applied-filters/roots/archived-issue.tsx
- web/components/issues/issue-layouts/filters/applied-filters/roots/cycle-root.tsx
- web/components/issues/issue-layouts/filters/applied-filters/roots/draft-issue.tsx
- web/components/issues/issue-layouts/filters/applied-filters/roots/module-root.tsx
- web/components/issues/issue-layouts/filters/applied-filters/roots/project-root.tsx
This PR includes improvement for applied filter ui. 
| ![before](https://github.com/makeplane/plane/assets/121005188/0bfd4bd8-69e2-40f7-82cc-76b1c55bf7ba) | ![after](https://github.com/makeplane/plane/assets/121005188/909783d0-76c0-49f8-93fb-ca3c473fd08c) |
> [WEB-688] chore: applied filters improvement

- web/components/pages/pages-list/list-view.tsx
This PR includes a fix for the empty state of the project page.
> [WEB-725] fix: page empty state

- deploy/1-click/README.md
Changed title, first paragraph, and bullets.
> chore: updated one-click deploy's readme for readability and presentation

- web/components/core/modals/gpt-assistant-popover.tsx
In this PR, I've included a disclaimer message in the AI modal.
> [WEB-752] chore: ai modal disclaimer added

- apiserver/plane/app/views/project.py
chore: 
- Added a project filter to remove projects that the user has already left.
Issue Link: [WEB-753](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/2d05f88e-30e5-461b-b3fa-54a45147ced7)
> [WEB-753] chore: project active filter

- web/pages/[workspaceSlug]/profile/[userId]/activity.tsx
This PR includes implementation of scrollbar for the profile activity page.
https://github.com/makeplane/plane/assets/121005188/66a07571-41c4-46e3-a004-99ce9e665030
> [WEB-698] chore: profile activity page scrollbar added

- web/components/project/card-list.tsx
This fix addresses an issue where an infinite loader was encountered when accessing workspace projects for the first time. Previously, users experienced continuous loading without successfully displaying the projects within the workspace. With this fix, the infinite loader issue has been resolved, ensuring efficient retrieval and display of workspace projects upon initial access, thus enhancing the user experience and workflow efficiency.
> fix: resolved infinite loader issue in workspace projects retrieval

- apiserver/plane/api/views/module.py
- apiserver/plane/app/views/cycle/base.py
- apiserver/plane/app/views/module/base.py
- apiserver/plane/app/views/workspace/module.py
dev: 
- This pull request addresses the issue where the count of issues was being displayed incorrectly due to multiple members.
Issue Link: [WEB-792](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/1605d7cc-136c-4da1-a0ae-f1c76111dee8)
> [WEB-792] dev: removed double issue count

- apiserver/plane/app/views/cycle/base.py
- apiserver/plane/app/views/cycle/issue.py
- apiserver/plane/app/views/dashboard/base.py
- apiserver/plane/app/views/inbox/base.py
- apiserver/plane/app/views/issue/archive.py
- apiserver/plane/app/views/issue/base.py
- apiserver/plane/app/views/issue/draft.py
- apiserver/plane/app/views/issue/sub_issue.py
- apiserver/plane/app/views/module/issue.py
- apiserver/plane/app/views/view/base.py
- apiserver/plane/app/views/workspace/user.py
fix:
- This pull request addresses the issue by implementing a fix that ensures the assignees' names are removed from issues once they have left the project.
Issue Link: [WEB-774](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/5f795082-a479-4834-ac49-8e5470d6536e)
> [WEB-774] fix: issue assignee display persistence for departed users

- web/components/modules/modules-list-view.tsx
- web/helpers/module.helper.ts
- On the Module list page, the search and filter functionality is not functioning as expected, resulting in an empty state. Additionally, ordering by progress in descending order displays incorrect data.
- Identified and implemented necessary adjustments to ensure proper functionality as intended.
> [WEB-814] fix: module list filter and order by

- web/components/cycles/list/root.tsx
- This PR includes consistent padding throughout the layout of the cycle list page.
> [WEB-813] chore: cycle list page alignment

- web/components/headers/cycle-issues.tsx
- web/components/headers/global-issues.tsx
- web/components/headers/module-issues.tsx
- web/components/headers/project-draft-issues.tsx
- web/components/headers/project-issues.tsx
- web/components/headers/project-view-issues.tsx
- web/components/issues/issue-layouts/filters/header/filters/start-date.tsx
- web/components/issues/issue-layouts/filters/header/filters/target-date.tsx
- web/components/issues/issues-mobile-header.tsx
- web/components/modules/module-mobile-header.tsx
- web/components/profile/profile-issues-filter.tsx
- web/lib/app-provider.tsx
- This PR includes enhancements for the custom date selection functionality in the filter dropdown.
> [WEB-811] chore: filter dropdown custom date select improvement

- apiserver/plane/app/views/cycle/base.py
- apiserver/plane/app/views/module/base.py
Fix:
- This pull request corrects the total count of issues' states within the respective module and cycle.
Issue Link: [WEB-820](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/0df4f62d-f4d4-4dc0-8e3f-fe6b84376a70)
> [WEB-820] fix: state count in cycle and module

- web/components/issues/issue-layouts/properties/all-properties.tsx
This PR include fix for kanban layout quick add error.
> [WEB-827] fix: kanban layout quick add

- apiserver/back_migration.py
- apiserver/plane/app/views/issue/label.py
- Add missing color in random label color generator
> fixed bug with missed color #FFFFFF

- apiserver/plane/app/serializers/issue.py
This PR includes fixes for error occurring with issue reactions.
> [WEB-828] fix: issue reaction

- apiserver/plane/app/views/workspace/estimate.py
chore: 
- removed project from workspace estimate.
Issue Link: [WEB-832](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/99278186-bb5a-45b5-aff2-ecd9ba1f1f24)
> [WEB-832] chore: removed project from workspace estimate

- apiserver/plane/app/views/cycle/base.py
fix: 
- optimise cycles endpoint for sql
- remove subquery annotation
> fix: optimise cycles endpoint for sql

- web/components/command-palette/command-palette.tsx
- web/components/cycles/modal.tsx
- web/components/issues/issue-layouts/calendar/base-calendar-root.tsx
- web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
- web/components/modules/modal.tsx
- web/components/project/create-project-form.tsx
- web/components/project/form.tsx
- web/components/project/project-logo.tsx
- web/components/views/modal.tsx
This PR include includes following changes:
- Resolve sentry issue PLANE-WEB-1AF.
- Resolve sentry issue PLANE-WEB-1AG.
- Remove unnecessary console log.
> [WEB-831] fix: sentry issue and code refactor

- apiserver/plane/app/views/cycle/base.py
fix: 
- cycle issue subquery filter when adding multiple assignees
> fix: cycle issue subquery filter when adding multiple assignees

- apiserver/plane/app/views/workspace/estimate.py
chore: 
- workspace estimate project filter
> chore: workspace estimate project filter

- apiserver/plane/app/views/module/base.py
- apiserver/plane/app/views/workspace/estimate.py
fix:
- module endpoint validations.
- check for `.first()` before fetching the attributes.
> fix: module endpoint validations

- apiserver/plane/api/serializers/issue.py
dev: 
- remove error from the response when invalid html is passed.
> dev: fix api security error

- web/components/headers/workspace-dashboard.tsx
- web/components/onboarding/onboarding-sidebar.tsx
- web/pages/[workspaceSlug]/index.tsx
- web/pages/invitations/index.tsx
- web/pages/workspace-invitations/index.tsx
This PR focuses on updating all the instance of word `Dashboard` with `Home` as we are now calling it as home. 
This PR is linked to [WEB-851](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/1842132e-4d5c-48fa-a2f4-416458095148)
> [WEB-851] chore: update all instances of `Dashboard` with `Home`.

- web/components/analytics/scope-and-demand/demand.tsx
This PR is linked to [WEB-852](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/b6e6ada0-673d-44dd-ba08-32b9398c9399)
> [WEB-852] chore: remove `Estimate Demand` data from the anaylytics.

- web/components/project/form.tsx
This PR address the issue with incorrect project id validation in project settings page.
This PR is linked to [WEB-839](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/b8636810-b7cb-4089-b6e3-4d630e4b53f6)
> [WEB-839] chore: limit project identifier to 5 letters in project settings page.

- web/components/core/activity.tsx
* Before fix
* After fix
This PR is linked to [WEB-652](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/d6c3acf7-3a48-4fd9-9e69-50f112b15e88)
> [WEB-652] fix: issue activities alignment in dashboard.

- web/components/cycles/archived-cycles/modal.tsx
- web/components/cycles/quick-actions.tsx
- web/components/cycles/sidebar.tsx
- web/components/issues/archive-issue-modal.tsx
- web/components/issues/issue-detail/root.tsx
- web/components/issues/issue-layouts/quick-action-dropdowns/archived-issue.tsx
- web/components/issues/peek-overview/root.tsx
- web/components/modules/archived-modules/modal.tsx
- web/components/modules/quick-actions.tsx
- web/components/modules/sidebar.tsx
- web/pages/[workspaceSlug]/projects/[projectId]/archives/issues/[archivedIssueId].tsx
This PR includes following enhancements in archive issues/ cycles/ modules:
* Removed redirection to archives page on archiving cycles and modules.
* Removed redirection to details page on restoring cycles and modules.
* Implement toasts for archived issues archival/ restore.
This PR is linked to [WEB-874](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/404e0c57-f7a6-4212-8a88-7b04b3fc4d8b)
> [WEB-874] chore: archival of modules, cycles and issues enhancement.

- apiserver/plane/app/views/cycle/base.py
- apiserver/plane/bgtasks/email_notification_task.py
fix: 
- decode error in email notification
- remove exception when issue does not exists in email notification log
- return when base api does not exists
- add validation for subject when sending email notification
- Check for data when retrieving cycles
[[WEB - 883]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/19fff1a3-203c-4cc6-b85f-147a512524ab)
> [WEB - 883] fix: api and worker errors

- Dockerfile
- apiserver/Dockerfile.api
- apiserver/Dockerfile.dev
- apiserver/plane/settings/production.py
- space/Dockerfile.space
- web/Dockerfile.web
chore: 
- remove user dependency in dockerfile
[[WEB - 908]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/bd3e345b-93bb-412c-afc4-82a391719ea0)
> [WEB - 908] chore: remove user dependency in dockerfile

- web/components/issues/issue-layouts/calendar/issue-block.tsx
- web/components/issues/issue-layouts/gantt/blocks.tsx
- web/components/issues/issue-layouts/kanban/block.tsx
- web/components/issues/issue-layouts/list/block.tsx
- web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
- web/components/issues/peek-overview/view.tsx
- web/components/issues/sub-issues/issue-list-item.tsx
- web/hooks/use-peek-overview-outside-click.tsx
- The entire Kanban card is now clickable for improved functionality.
- Enhanced the Issue Peek overview for better usability.
- Resolved the flickering problem in the Peek overview.
> [WEB-905] chore: issue peek overview and kanban layout improvement

- packages/editor/core/src/ui/extensions/table/table/table-view.tsx
- space/components/issues/filters/applied-filters/filters-list.tsx
- web/components/issues/issue-layouts/filters/header/display-filters/display-filters-selection.tsx
- web/components/issues/issue-layouts/filters/header/display-filters/group-by.tsx
- web/components/project/applied-filters/root.tsx
- web/components/project/create-project-form.tsx
- web/components/project/form.tsx
- web/constants/fetch-keys.ts
- web/helpers/string.helper.ts
- web/hooks/use-reload-confirmation.tsx
- web/pages/installations/[provider]/index.tsx
[WEB-881](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/870e16b4-375e-44df-b973-c29b265f2f83)
This PR contains changes to fix the following sentry issues,
- [Fix for Sentry Fix for "Non-Error promise rejection captured with value: Route change to url was aborted"](https://plane-hq.sentry.io/issues/5157387733/?project=4505589698002944&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=0)
- [Sentry fix for "undefined is not an object (evaluating 'n.response')"](https://plane-hq.sentry.io/issues/5109093652/?project=4505589698002944&query=is%3Aunresolved+n.response&referrer=issue-stream&statsPeriod=14d&stream_index=0)
- [Possible Sentry Fix for "TypeError Function.entries(<anonymous>)"](https://plane-hq.sentry.io/issues/4907802268/?projec …
> [WEB-881] fix: Sentry errors from previous build

- apiserver/plane/app/views/workspace/invite.py
- apiserver/plane/app/views/workspace/member.py
- apiserver/plane/utils/cache.py
fix:
- invalidate cache on workspace **leave** for current and workspace users
- invalidate cache on workspace **delete** for current and multiple users
- invalidate cache on workspace **update** for current and multiple users
[[WEB - 922]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/0b7dd37a-bf48-4859-89d5-5d4a47e435c9)
> [WEB - 922]dev: fix workspace member caching

- web/components/modules/select/status.tsx
* Before
* After
This PR is linked to [WEB-918](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/6295be4f-2b5c-43f1-815e-558b0d5ccd1a)
> [WEB-918] style: update size of `state` dropdown button for consistency.

- web/layouts/auth-layout/workspace-wrapper.tsx
- web/pages/invitations/index.tsx
This PR includes improvement for workspace invite loader.
> [WEB-920] chore: workspace invite loader improvement

- apiserver/plane/app/serializers/inbox.py
- apiserver/plane/app/views/inbox/base.py
- apiserver/plane/utils/issue_filters.py
- packages/types/src/inbox.d.ts
- web/components/inbox/content/inbox-issue-header.tsx
- web/components/inbox/content/issue-properties.tsx
- web/components/inbox/content/issue-root.tsx
- web/components/inbox/content/root.tsx
- web/components/inbox/inbox-filter/applied-filters/date.tsx
- web/components/inbox/inbox-filter/applied-filters/label.tsx
- web/components/inbox/inbox-filter/applied-filters/root.tsx
- web/components/inbox/inbox-filter/applied-filters/status.tsx
- web/components/inbox/inbox-filter/filters/date.tsx
- web/components/inbox/inbox-filter/filters/filter-selection.tsx
- web/components/inbox/inbox-filter/filters/labels.tsx
- web/components/inbox/inbox-filter/filters/status.tsx
- web/components/inbox/inbox-issue-status.tsx
- web/components/inbox/root.tsx
- web/components/inbox/sidebar/root.tsx
- web/components/issues/issue-detail/label/create-label.tsx
- web/helpers/inbox.helper.ts
- web/store/inbox/inbox-issue.store.ts
- web/store/inbox/project-inbox.store.ts
This PR includes following changes for inbox issue:
- Making the appearance of status icons consistent.
- Checking that the closed tab filter works correctly.
- Handling accepted and disabled inbox issues properly.
- Updating filters and fixing duplicate issues.
- Improving loader and cleaning up code.
> [WEB-406] chore: project inbox improvement 

- web/components/issues/issue-detail/issue-activity/comments/comment-create.tsx
- Previously, users were unable to comment only use mention. I have made the necessary adjustments to make it work as intended.
> [WEB-929] chore: issue comment mention user improvement

- packages/types/src/inbox.d.ts
- web/components/inbox/content/inbox-issue-header.tsx
- web/components/inbox/modals/create-issue-modal.tsx
- web/components/inbox/root.tsx
- web/components/inbox/sidebar/inbox-list-item.tsx
- web/components/inbox/sidebar/inbox-list.tsx
- web/components/inbox/sidebar/root.tsx
- web/constants/inbox.tsx
- web/helpers/inbox.helper.ts
- web/pages/[workspaceSlug]/projects/[projectId]/inbox/index.tsx
- web/store/inbox/inbox-issue.store.ts
- web/store/inbox/project-inbox.store.ts
- Handled loaders in inbox issues
- Updated the enums for inbox issue status and inbox current rab for better understanding
- Handled update inbox issue status modal confirmation
> [WEB-934] chore: optimised issue loaders and added enum for issue status and current tab

- web/pages/[workspaceSlug]/projects/[projectId]/inbox/index.tsx
- web/store/inbox/project-inbox.store.ts
- [PLANE-WEB-1ER] sentry Issue fix.
- Remove unnecessary console log.
> [WEB-937] fix: inbox issue hook render issue and code refactor

- web/store/inbox/project-inbox.store.ts
This pull request incorporates local sorting functionality for inbox issues within the project inbox store.
> [WEB-934] fix: Handled inbox issue sorting locally in inbox store

- web/components/inbox/content/inbox-issue-header.tsx
- Copy issue link and open issue action added to cancelled inbox issues in the header.
> [WEB-943] chore: inbox cancelled issue header action improvement

- apiserver/plane/api/views/state.py
- apiserver/plane/app/views/inbox/base.py
- apiserver/plane/app/views/state/base.py
- apiserver/plane/bgtasks/dummy_data_task.py
- apiserver/plane/db/management/commands/create_dummy_data.py
- apiserver/plane/settings/common.py
Chore
- This script generates dummy data within the workspace.
Issue Link - [WEB-983](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/c8d2be96-0c0a-494c-bc06-2e8a099e2924)
> [WEB-983] chore: dummy data script

- web/helpers/analytics.helper.ts
This pull request addresses the color exception handling issue for the state_group on the x-axis and the group dropdown in the custom analytics tab in analytics.
> [WEB-1000] fix: handled edge case for color on custom analytics state_group

- apiserver/plane/bgtasks/dummy_data_task.py
- apiserver/plane/db/management/commands/create_dummy_data.py
chore: 
- pages and Inbox issues in dummy data script
Issue Link: [WEB-990](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/8e42e7b5-ecfa-45f5-afb0-a486754caebc)
> [WEB-990] fix: pages and Inbox issues in dummy data script

- apiserver/plane/app/views/inbox/base.py
- web/components/inbox/content/inbox-issue-header.tsx
- web/components/inbox/modals/create-edit-modal/create-root.tsx
- web/components/inbox/modals/create-edit-modal/issue-title.tsx
- web/components/issues/description-input.tsx
- web/pages/[workspaceSlug]/projects/[projectId]/inbox/index.tsx
- web/store/inbox/inbox-issue.store.ts
- web/store/inbox/project-inbox.store.ts
- Duplicate inbox issue header improvement. (Include copy issue link and open issue option)
- Snooze inbox issue decline and duplicate action added.
- Disable description height consistency.
- Project inbox exception error.
- Create Inbox issue modal onEnter and title validation added.
- Inbox issue sidebar mutation fix.
>  [WEB-999] chore: inbox issue bug fixes and improvement

- web/components/inbox/content/issue-root.tsx
- web/store/inbox/project-inbox.store.ts
- Inbox issue attachment added.
> [WEB-939] chore: inbox issue attachment

- web/components/cycles/list/root.tsx
- This PR includes ui improvement for cycle list page.
> chore: cycle list page improvement

- web/components/project/send-project-invitation-modal.tsx
- web/components/workspace/send-workspace-invitation-modal.tsx
- This PR includes enhancements to the member invite modal UI.
| ![before-1](https://github.com/makeplane/plane/assets/121005188/3516e40f-a63b-4035-be58-a1d818bf18d5) |  ![after-2](https://github.com/makeplane/plane/assets/121005188/73a095e7-f936-4bd7-b8ff-1533e259c620) | 
| ![before-2](https://github.com/makeplane/plane/assets/121005188/3efb5a86-d0c5-42f0-91be-0cc5a63c508c) | ![after-1](https://github.com/makeplane/plane/assets/121005188/439a70a7-398a-493d-b26d-ee73776a8f88) |
> [WEB-837] chore: member invite modal improvement

- packages/editor/core/src/styles/editor.css
- packages/editor/core/src/ui/extensions/horizontal-rule/horizontal-rule.ts
- packages/editor/document-editor/src/ui/menu/block-menu.tsx
- packages/editor/extensions/src/extensions/drag-drop.tsx
1. Fixes bugs with horizontal rule not being able to be selected as expected using the new drag handle menu, wrong positioning and some additional checks to ensure safe operations happen while duplicating using the block menu....
2. Fixes the position of drag handles on tables
3. Fixes the selection, deletion, duplication and positioning with blockquotes
4. Fixes the position of drag handles on code blocks
> [WEB - 480] fix: horizontal rule drag and drop

- web/components/issues/issue-layouts/properties/labels.tsx
[WEB-1013](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/a75ae048-3e8e-46ac-aec8-ed97343998a4)
This PR fixes Regressed Keyboard navigation for labels dropdown in spreadsheet
> [WEB-1013] fix spreadsheet labels dropdown keyboard navigation

- web/components/issues/issue-layouts/kanban/block.tsx
- Issue kanban card on hover cursor improvement.
> [WEB-999] chore: issue kanban block improvement

- packages/editor/core/src/hooks/use-editor.tsx
Fixed unnecessary focus onto the editor post swr sync calls
> fix: unnecessary focus in editor on swr sync

- web/components/profile/overview/priority-distribution.tsx
- web/components/profile/overview/state-distribution.tsx
This PR addresses the color exception handling issue for the state_group on the x-axis and the group dropdown in the custom analytics tab in analytics.
> [WEB-1000] fix: profile activity application error

- web/components/issues/issue-modal/form.tsx
- This PR include fix for the parent selection modal in draft issues.
Issue Link: [[WEB-1020]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/db5f18c5-1dde-4d68-897f-5b43e414a74b)
> [WEB-1020] fix: draft issue parent select query params

- apiserver/plane/app/views/page/base.py
- apiserver/plane/bgtasks/page_transaction_task.py
chore: 
- added validation for empty strings to handle cases where no mentions are present while creating a page.
Issue Link: [WEB-1023](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/e30c4dda-e4ee-45d1-a2d2-7de5b85ae5cb)
> [WEB-1023] chore: page mention transactions

- apiserver/plane/api/views/inbox.py
- apiserver/plane/app/views/inbox/base.py
- apiserver/plane/bgtasks/dummy_data_task.py
- apiserver/plane/bgtasks/issue_activites_task.py
- web/components/issues/issue-detail/issue-activity/activity/actions/inbox.tsx
- web/components/issues/issue-detail/issue-activity/activity/actions/index.ts
- web/components/issues/issue-detail/issue-activity/activity/activity-list.tsx
- Now, every action – accept, decline, snooze, or duplicate – is meticulously logged in the activity feed, ensuring seamless tracking and accountability.
| Media |
|--------|
| ![987-1](https://github.com/makeplane/plane/assets/121005188/7176fb40-98d4-4acd-b803-70f68ece82fb) |
| ![987-2](https://github.com/makeplane/plane/assets/121005188/85b34588-c796-4866-ab90-397d09935801) |
| ![987-3](https://github.com/makeplane/plane/assets/121005188/eea0bf51-04bb-4f95-89dd-b4cf525e5e3a) |
| ![987-4](https://github.com/makeplane/plane/assets/121005188/6120c25c-7566-46e3-a2b9-8fe0c88cfbef) |
> [WEB-987] fix: inbox issue activity

- web/components/account/index.ts
- web/components/account/sign-in-forms/root.tsx
- web/components/account/sign-up-forms/root.tsx
- web/components/account/terms-and-conditions.tsx
This PR include improvement for sign in page.
> chore: sign in page improvement

- web/components/inbox/modals/create-edit-modal/edit-root.tsx
- web/components/inbox/modals/create-edit-modal/issue-properties.tsx
- Resolved parent ID sentry error in the inbox issue.
- Rectified search endpoint issue in the inbox accept modal.
> [WEB-999] fix: inbox sentry error and accept modal fix

- apiserver/plane/app/views/workspace/base.py
- apiserver/plane/app/views/workspace/invite.py
- apiserver/plane/app/views/workspace/member.py
fix: 
- caching login when member joins a workspace from the email.
[[WEB - 1029]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/ae030eed-3ebc-4521-be3f-41a56b45c359)
> [WEB - 1029]fix: caching login when member joins a workspace from the email

- web/components/issues/issue-layouts/list/blocks-list.tsx
- In list layout issue block is having double border.
- Identified and resolved the issue by making necessary adjustment.
| ![before](https://github.com/makeplane/plane/assets/121005188/40ca1aac-0ad1-480b-942d-4cafefbc42ac) | ![after](https://github.com/makeplane/plane/assets/121005188/f0b5b7c9-d1fa-4d05-9e6d-372de02abfcf) |
> [WEB-853] chore: list layout improvement

- web/components/cycles/archived-cycles/header.tsx
- web/components/cycles/cycles-view-header.tsx
- web/components/cycles/dropdowns/filters/end-date.tsx
- web/components/cycles/dropdowns/filters/start-date.tsx
- web/components/headers/modules-list.tsx
- web/components/modules/archived-modules/header.tsx
- web/components/modules/dropdowns/filters/start-date.tsx
- web/components/modules/dropdowns/filters/target-date.tsx
- web/components/pages/list/filters/created-at.tsx
- web/components/pages/list/filters/root.tsx
- web/components/project/dropdowns/filters/created-at.tsx
- web/helpers/date-time.helper.ts
- Custom checkbox toggle is not working in following filters:
- Cycle list page filter.
- Module list page filter.
- Page list page filter.
- Resolve this issue by updating custom date select logic, additionally refactor the code.
> [WEB-1022] fix: filters custom date selection improvement

- web/hooks/use-sign-in-redirection.ts
- Workspace not found empty state is flicker on sign in.
- Resolve this issue by fetching workspaces just after redirection.
| ![5ab86c6f-c3f9-4ddd-a7f1-51ac5f3a57d5](https://github.com/makeplane/plane/assets/121005188/3fe79f9e-d03a-4739-ba77-a95910c5109e)| ![a3c3fe1c-5eb5-406c-934f-fc468d77e416](https://github.com/makeplane/plane/assets/121005188/d820608c-c033-448b-b02d-3dbfff5c7ba2) |
> [WEB-1031] fix: workspace not found flicker

- web/components/issues/issue-layouts/calendar/dropdowns/options-dropdown.tsx
- The action button in the calendar layout header is not aligned centrally.
- Correct this issue by making the necessary adjustments.
| ![before](https://github.com/makeplane/plane/assets/121005188/8a57e1d9-798b-440c-8da7-7278a3f3ce4d) | ![after](https://github.com/makeplane/plane/assets/121005188/bc9a47fc-8a71-4c1a-9594-bbfc63ac1289) |
> [WEB-1032] fix: calendar header action alignment

- web/components/core/activity.tsx
- web/store/label.store.ts
- Inbox activity was not rendering properly in the dashboard and user activity sections.
- Identified and resolved isue by implementing necessary changes.
| ![before](https://github.com/makeplane/plane/assets/121005188/bb2e9c74-1e48-48b4-bc81-a558761d93a6) | ![after](https://github.com/makeplane/plane/assets/121005188/f8bcad90-92e5-40d3-903d-7f07aa0ac327) | 
| ![before](https://github.com/makeplane/plane/assets/121005188/ed2838f0-a618-4189-8deb-f7c30ebdfdb7) | ![after](https://github.com/makeplane/plane/assets/121005188/00abf269-c379-4adc-bc3d-80c7b4d75972) |
> [WEB-1034] fix: inbox issue user activity

- apiserver/plane/app/views/user/base.py
fix: 
- workspace redirection when logging in.
[[WEB - 1039]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues)
> [WEB - 1039] fix: workspace redirection when logging in

- apiserver/plane/app/views/dashboard/base.py
- apiserver/plane/db/management/commands/test_email.py
fix: 
- Resolves 'dashboard collaborators active issue count' issue - updated code for accurate issue count display.
Issue Link: [WEB-1042](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/c1640714-7ec8-4dfe-8875-976bd3d65842)
> [WEB-1042] fix: dashboard collaborators active issue count

- web/components/pages/modals/page-form.tsx
This PR include improvement for create project modal.
| ![before](https://github.com/makeplane/plane/assets/121005188/b35cc56c-6cb3-4278-975f-d98ce3d57198) | ![after](https://github.com/makeplane/plane/assets/121005188/e9c03942-806c-4e02-b906-7c3f693f42d8) | 
| ![before](https://github.com/makeplane/plane/assets/121005188/bc0c29e2-0f62-41a8-850a-f593a42cf3ba) | ![after](https://github.com/makeplane/plane/assets/121005188/c40daccc-d130-4797-a995-4eb4f212a44f) |
> [WEB-1047] chore: create page modal improvement

- web/components/inbox/inbox-filter/filters/members.tsx
- web/components/issues/issue-layouts/filters/header/filters/assignee.tsx
- web/components/issues/issue-layouts/filters/header/filters/created-by.tsx
- web/components/issues/issue-layouts/filters/header/filters/mentions.tsx
This PR includes enhancements for sorting order of member filter options.
| ![579ec01c-4a23-45d4-b516-3aa18e83d22d](https://github.com/makeplane/plane/assets/121005188/e25b0b5d-3b73-407f-800b-68f7f7590684) | ![9c31617d-5210-4ee0-9d90-52933c4c3d6e](https://github.com/makeplane/plane/assets/121005188/508450d6-907b-4ef2-9c5f-e4270125934e) |
> [WEB-988] chore: issue filter member options improvement

- web/components/issues/issue-layouts/filters/applied-filters/filters-list.tsx
This PR include improvement for applied issue filter responsiveness. 
| ![before](https://github.com/makeplane/plane/assets/121005188/ffba6779-9833-49bc-8ec6-21316fad184e) | ![after](https://github.com/makeplane/plane/assets/121005188/d0d8a26a-29d7-4583-b954-edfc3ffb3048) |
> [WEB-1049] chore: applied filter responsiveness

- web/components/modules/module-list-item.tsx
- Clicking outside the module delete modal triggers the peek module.
- Resolve this problem by implementing the necessary adjustments.
> [WEB-1048]  fix: module delete modal outside click event propagation

- packages/ui/src/form-fields/input.tsx
- web/components/cycles/form.tsx
- web/components/inbox/modals/create-edit-modal/create-root.tsx
- web/components/inbox/modals/create-edit-modal/edit-root.tsx
- web/components/inbox/modals/create-edit-modal/issue-title.tsx
- web/components/issues/issue-modal/form.tsx
- web/components/modules/form.tsx
- web/components/project/form.tsx
- web/components/views/form.tsx
- web/components/workspace/create-workspace-form.tsx
This PR includes modifications for input error state and also updated error messages.
| ![before](https://github.com/makeplane/plane/assets/121005188/4cdad1c4-0cc9-4255-a8cf-54d050fe7d20) | ![after](https://github.com/makeplane/plane/assets/121005188/e5930fdb-97c1-449f-887f-f73abc620f3c) | 
| ![before](https://github.com/makeplane/plane/assets/121005188/acd9bab5-9f4e-4fac-bf80-e3dd705622ef) | ![after](https://github.com/makeplane/plane/assets/121005188/687c5d87-fcdd-4c03-be44-debd7c16f1d5) | 
| ![before](https://github.com/makeplane/plane/assets/121005188/7edfb3fc-e387-4af5-a5f2-79934ad165d5) | ![after](https://github.com/makeplane/plane/assets/121005188/912f519e-ef15-47d8-a482-bed4b9d2e000) | 
| …
> [WEB-1030] chore: input error message improvement

- apiserver/plane/app/views/workspace/base.py
- apiserver/plane/app/views/workspace/state.py
chore: 
- added a state filter at the workspace level to filter out the triage state.
Issue Link: [WEB-1050](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/82c0ddf4-98b5-4876-a5cf-a4db59cf8c62)
> [WEB-1050] chore: triage state filter in workspace level

- web/components/issues/issue-layouts/list/blocks-list.tsx
1. Updated the bottom border color of issue blocks in the list layout.
> [WEB-1052] fix: list layout issue block border color

- apiserver/plane/api/urls/issue.py
- apiserver/plane/api/views/__init__.py
- apiserver/plane/api/views/issue.py
- apiserver/plane/app/permissions/project.py
This PR adds an API endpoint to find an issue by its sequenceId (XYZ-1234).
This is required to connect plane to any other services, where the tickets are only referenced by their sequenceId.
> feat: api /workspaces/<str:slug>/issues/<str:project__identifier>-<str:issue__identifier>/

- web/components/core/modals/existing-issues-list-modal.tsx
- web/components/issues/parent-issues-list-modal.tsx
- When opening, the existing and parent issue modal displays an empty state flicker.
- Resolve this issue by implementing the necessary changes.
| ![before](https://github.com/makeplane/plane/assets/121005188/86c2be22-65e7-4153-8877-b28ce2b0e301) | ![after](https://github.com/makeplane/plane/assets/121005188/508708be-cb5d-46e9-a5fd-a9d9f7b0f0da) |
> [WEB-1054] fix: existing and parent issue modal empty state flicker

- web/components/cycles/board/cycles-board-card.tsx
- web/components/cycles/list/cycles-list-item.tsx
- web/components/modules/module-card-item.tsx
- web/components/modules/module-list-item.tsx
- This PR include fix for cycle and module quick action z-index issue.
> [WEB-1048] fix: cycle and module quick action z-index

- packages/ui/src/form-fields/textarea.tsx
- packages/ui/src/hooks/use-auto-resize-textarea.ts
- web/components/pages/editor/summary/heading-components.tsx
- web/components/pages/editor/title.tsx
- web/components/pages/list/block.tsx
1. Updated the font weight of the page title in the pages list.
2. Fixed the alignment of the headings in the Outline(Table of contents) section.
3. Fixed the margin of the headings in the Outline section.
4. Textarea auto-resize logic.
> [WEB-1072] fix: pages UI improvements

- web/components/headers/global-issues.tsx
1. Removed extra slash from the global issues layout switch routes.
> [WEB-1075] fix: double slashes in the global issues layout routes

- web/components/pages/editor/editor-body.tsx
- web/components/pages/editor/header/index.ts
- web/components/pages/editor/header/mobile-root.tsx
- web/components/pages/editor/header/options-dropdown.tsx
- web/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx
https://github.com/makeplane/plane/assets/94619783/bc218d89-a19b-43c8-bac0-10ba67ed571b
This PR is attached to the issue [WEB-705](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/3b71dba5-6562-4004-8732-a659a7e4173e)
> [WEB-705] fix: pages responsiveness

- web/components/headers/projects.tsx
- web/components/project/dropdowns/order-by.tsx
- web/components/project/projects-mobile-header.tsx
- web/pages/[workspaceSlug]/projects/index.tsx
https://github.com/makeplane/plane/assets/31303617/359340fe-e936-42d3-9075-c719737aab80
> [WEB-708] style: projects list responsiveness

- web/components/inbox/content/inbox-issue-header.tsx
- web/components/inbox/content/inbox-issue-mobile-header.tsx
- web/components/inbox/content/root.tsx
- web/components/inbox/root.tsx
- web/components/inbox/sidebar/inbox-list-item.tsx
- web/components/inbox/sidebar/inbox-list.tsx
- web/components/inbox/sidebar/root.tsx
This PR ensures the inbox list is visible by default on mobile devices.
> [WEB-1094] chore: inbox sidebar mobile responsiveness

- web/components/headers/global-issues.tsx
- web/components/issues/issue-layouts/filters/applied-filters/roots/global-view-root.tsx
- web/components/issues/issue-layouts/filters/applied-filters/roots/project-view-root.tsx
- web/pages/[workspaceSlug]/workspace-views/[globalViewId].tsx
- web/pages/[workspaceSlug]/workspace-views/index.tsx
- Eliminates the list layout from the workspace view.
- Fixes the issue with the empty applied filter UI.
| ![before](https://github.com/makeplane/plane/assets/121005188/2a273360-a7e9-4bb1-9777-af234ccba695) | ![after](https://github.com/makeplane/plane/assets/121005188/7ca2f7e7-eec5-4395-b3c7-a1c263542776) |
> [WEB-1065] chore: workspace view and empty filter improvement

- web/components/inbox/content/issue-root.tsx
- web/components/inbox/content/root.tsx
- web/components/issues/issue-modal/modal.tsx
- web/components/labels/label-block/label-item-block.tsx
- web/components/pages/editor/summary/content-browser.tsx
- web/pages/[workspaceSlug]/projects/[projectId]/pages/index.tsx
This PR include following changes: 
- Inbox issue description is resetting on the first type.
- Issue description resets when updating from modal and switching tabs or leaving idle.
- Removed outline heading in Page Detail page.
- Fixed Label Setting quick action UI.
- Added head title to the project page.
> [WEB-1100] fix: bug fixes and enhancement

- web/components/views/views-list.tsx
This PR addresses an application error that occurs on the project view list page due to conditionally rendered hooks.
> [WEB-1121] fix: project view application error

- web/store/pages/project-page.store.ts
1. Updated the default sorting order of pages list to last updated at time in descending order.
> [WEB-1124] chore: default pages sorting order

- web/components/core/modals/existing-issues-list-modal.tsx
This PR addresses a bug with the existing issue list modal where there is a loading flicker occurring.
| ![before](https://github.com/makeplane/plane/assets/121005188/c95b5400-50a8-4cc9-89f5-b0463d0ad59c) | ![after](https://github.com/makeplane/plane/assets/121005188/bbab6209-0d86-4032-9632-cd64bb7aeb0b) |
> [WEB-1101] fix: existing issue list modal loading flicker

- apiserver/plane/api/views/issue.py
- apiserver/requirements/base.txt
- apiserver/requirements/local.txt
- apiserver/requirements/production.txt
- apiserver/requirements/test.txt
dev:
- update dependencies to latest version (except Django)
- remove unwanted dependencies
- add ruff as local dependency for formatting
[[WEB - 1149]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/547e79c4-2a8c-4559-8fec-ef72aa2cd09e)
> [WEB -1149] dev: update dependencies

- apiserver/plane/app/views/workspace/cycle.py
- apiserver/plane/app/views/workspace/module.py
chore: 
- This pull request addresses an issue with the workspace module list endpoint, ensuring it accurately displays all modules within the workspace. 
Issue Link: [WEB-1158](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/4db63863-4f04-47ea-a0fa-0bdf99a8fbe3)
> [WEB-1158] chore: workspace module list endpoint

- web/components/inbox/content/inbox-issue-header.tsx
- Inbox issue header quick action user role permission validation added.
> [WEB-1150] fix: inbox issue header quick action validation

- apiserver/plane/license/management/commands/register_instance.py
chore: 
- update the default name that is added to instance
> chore: update the default name that is added to instance

- web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
- web/components/issues/issue-layouts/kanban/block.tsx
- web/components/issues/issue-layouts/kanban/default.tsx
- web/components/issues/issue-layouts/kanban/kanban-group.tsx
- web/components/issues/issue-layouts/kanban/swimlanes.tsx
- web/components/issues/issue-layouts/kanban/utils.ts
- web/package.json
- web/styles/globals.css
- yarn.lock
[WEB-1136](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/95c62d1d-79b5-4efe-b742-ee23a777f9ad)
This PR improves the Kanban DnD with the following changes,
- Once dropped, scroll to the issue and highlight the issue
- If not sorted by manual, Then display a column overlay for the user to drop on
- When drag is disabled, display a message to show the drag is disabled
https://github.com/makeplane/plane/assets/71900764/38847679-466c-407b-93a0-354c32dc43a0
> [WEB-1136] chore: Kanban drag and drop improvements

- web/components/issues/issue-detail/parent-select.tsx
- web/components/issues/issue-detail/relation-select.tsx
- web/components/issues/peek-overview/header.tsx
- web/components/issues/peek-overview/view.tsx
- web/components/issues/sub-issues/root.tsx
- web/store/issue/issue-details/root.store.ts
This PR includes a fix for the modal context. Previously, we were only storing modal state in a boolean, which wasn't specific to each issueId. I've made necessary changes to rectify this issue.
> [WEB-1175] fix: modal context

- apiserver/plane/db/migrations/0065_auto_20240415_0937.py
- apiserver/plane/db/models/project.py
dev: 
- add `start_date` and `end_date` to projects
[[WEB - 1180]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/44707ab2-84a9-4ab5-8295-e52932f96016)
> [WEB - 1180]dev: add start date and end date to projects

- web/components/issues/issue-layouts/filters/applied-filters/roots/global-view-root.tsx
- web/components/workspace/views/modal.tsx
- web/store/global-view.store.ts
This PR resolves a bug occurring when editing global view filters from a modal.
> [WEB-1183] fix: updated global issues filter while updating global view

- web/components/pages/editor/editor-body.tsx
- web/components/pages/loaders/index.ts
- web/components/pages/loaders/page-content-loader.tsx
1. Added a skeleton loader to the page description.
https://github.com/makeplane/plane/assets/65252264/a4d2f409-cb5b-4264-aa8f-17fc16df1c2f
> [WEB-1181] chore: added a loader for page description

- web/components/core/activity.tsx
This PR updated inbox issue activity message for recent activity section.
| ![before](https://github.com/makeplane/plane/assets/121005188/9b08f2aa-882f-4ea0-9193-9bab18382964) | ![after](https://github.com/makeplane/plane/assets/121005188/42303a71-a4d6-4eaf-91f1-4401ec9662e7) |
> [WEB-1114] chore: recent activity message updated

- web/components/issues/issue-detail/cycle-select.tsx
- web/components/issues/issue-detail/root.tsx
- web/components/issues/peek-overview/root.tsx
- web/hooks/use-issues-actions.tsx
- web/services/issue/issue.service.ts
- web/services/module.service.ts
- web/store/issue/cycle/issue.store.ts
- web/store/issue/issue-details/issue.store.ts
- web/store/issue/issue-details/root.store.ts
- web/store/issue/issue.store.ts
- web/store/issue/module/issue.store.ts
- web/store/issue/root.store.ts
1. Optimistically add issue to cycle/modules.
2. Update the store actions to optimistically update the store data and revert the update on error.
> [WEB-1142] chore: optimistically add issue to cycle/modules

- apiserver/plane/app/views/issue/base.py
- apiserver/plane/utils/user_timezone_converter.py
fix: 
- This pull request fixes the bug for not rendering the issue's when the created by filter is applied.
Issue Link: [WEB-1237](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/ba3995a1-331a-4aad-9d20-c27a5dbe26d0)
> [WEB-1237] fix: displaying issues when applied created by filter

- apiserver/plane/app/views/issue/archive.py
- apiserver/plane/app/views/issue/draft.py
fix:
- This pull request resolves the issues with the listing of draft and archive issues.
Issue Link:  [WEB-1242](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/01fe5735-abf7-4814-99e5-186617ce5259)
> [WEB-1242] fix: draft archive issues listing

- web/components/inbox/inbox-filter/applied-filters/state.tsx
Inbox State filter title shows `Status`.
Updated the title to `State`.
* Before
* After
**Plane Link: [WEB-1182](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/7bae97ea-3c53-4fa9-9113-093de7cb5062)**
> [WEB-1182] style: fix inbox state filter title.

- web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
- Improved the indentation for sub-issues in the spreadsheet.
- Enabled clickability for the entire issue name block.
| Media |
|--------|
| ![img](https://github.com/makeplane/plane/assets/121005188/abca838a-828e-4589-b319-5cf0cdaaedcc) |
> [WEB-1040] chore: spreadsheet indentation improvement

- web/components/issues/issue-layouts/list/block-root.tsx
- web/components/issues/issue-layouts/list/block.tsx
- web/components/issues/issue-layouts/list/blocks-list.tsx
- web/components/issues/issue-layouts/list/index.ts
- web/components/issues/issue-layouts/properties/index.ts
- Implement indentation for sub-issues in the list layout.
| Media |
|--------|
| ![img](https://github.com/makeplane/plane/assets/121005188/8a467486-bac0-4917-8c74-c4280b0af430) |
> [WEB-1040] chore: list layout sub issue nesting implementation

- .gitignore
- deploy/selfhost/README.md
- deploy/selfhost/install.sh
- Modified self host setup.sh for "Backup Data" option
- Updated self-host Readme
- Modified self host setup.sh for "Backup Data" option
- Updated self-host Readme
> feat: Self Host Data Backup

- web/components/issues/issue-layouts/list/block.tsx
This PR includes a fix for the list layout sub-issue toggle button, which was rendering for all issues.
> [WEB-1040] fix: list layout indentation fix

- web/components/notifications/notification-card.tsx
- Resolved issue where notification action items were overlapping with notification message.
- Restricted notification message to 2 lines.
> [WEB-1273] chore: notification action item enhancement

- web/components/issues/issue-layouts/list/block.tsx
This PR includes a fix for an application error occurring in the list issue layout.
> [WEB-1285] fix: issue layout application error

- packages/ui/src/dropdowns/custom-menu.tsx
- Stop the default behavior on the custom menu button to prevent it from opening the link.
- Refactor menu click handler function
Issue link: [[WEB-1275]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/37708924-5ad3-4646-b55b-9ce2a5ae077e)
> [WEB-1275] fix: calendar and spreadsheet layout quick action toggle

- apiserver/plane/api/serializers/issue.py
- apiserver/plane/app/serializers/issue.py
fix: 
- this pull request addresses the problem with updating the title of the issue link.
Issue Link: [WEB-1305](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/1837046c-19a7-4876-ae46-b53d79ca5e95)
> [WEB-1305] fix: issue link title updation

- web/components/analytics/scope-and-demand/demand.tsx
- web/components/analytics/scope-and-demand/scope-and-demand.tsx
- web/components/analytics/scope-and-demand/scope.tsx
This PR includes enhancement for project analytics scope and demand UI.
| ![before](https://github.com/makeplane/plane/assets/121005188/466bf7b4-0cfb-418b-9948-b7e9b0d08e6a) | ![after](https://github.com/makeplane/plane/assets/121005188/02d58c57-c84b-4abb-9f07-3d12708a8629) |
| ![before](https://github.com/makeplane/plane/assets/121005188/1bc1921c-34b4-4dad-b0f4-6243e2bad609) | ![after](https://github.com/makeplane/plane/assets/121005188/ea8c5089-ce58-487d-826d-5cf20fc9569b) |
> [WEB-1308] chore: project analytics ui improvement

- web/components/onboarding/switch-delete-account-modal.tsx
1. Sign out the user after deleting/deactivating account while onboarding.
> [WEB-1319] chore: sign out after deactivating account

- web/components/core/theme/custom-theme-selector.tsx
- Updated custom theme input placeholder content.
- Updated placeholder text color.
| ![before](https://github.com/makeplane/plane/assets/121005188/e420f75b-12cb-4d07-982d-3df13241bd89) | ![after](https://github.com/makeplane/plane/assets/121005188/15af0839-db23-4b36-9f55-f8d85d743efc) |
> [WEB-1306] chore: custom theme input placeholder improvement

- admin/app/globals.css
- space/app/layout.tsx
- space/components/instance/not-ready-view.tsx
- space/helpers/common.helper.ts
- space/styles/globals.css
- web/components/instance/not-ready-view.tsx
- web/components/workspace/sidebar-dropdown.tsx
- web/helpers/common.helper.ts
1. Updated the light and dark mode theme color values for the `admin` and `space` apps.
2. Created `GOD_MODE_URL` constant in the `web` and `space` apps to fix redirections to the `admin` app.
> [WEB-1326] style: update space and admin app colors

- space/components/issues/navbar/controls.tsx
- space/components/views/project-details.tsx
- space/store/project.store.ts
- space/store/root.store.ts
- space/store/user.store.ts
- space/styles/globals.css
- space/types/project.d.ts
- web/styles/globals.css
This pull request includes updates to the Space application with a focus on the authentication page and project settings store.
> [WEB-1319] chore: enhanced UI and preloading for authentication page

- web/components/profile/preferences/email-notification-form.tsx
- This PR fixes a bug occurring in the email preferences form where the latest data was not being displayed when changing tabs.
> [WEB-1313] fix: email preferences form reset

- web/components/common/logo-spinner.tsx
- web/pages/accounts/forgot-password.tsx
- web/pages/index.tsx
- web/pages/sign-in.tsx
- Auth screens header action button responsiveness.
- Reduce logo loader size for smaller screen.
> [WEB-1345] chore: auth and loader responsiveness

- web/components/page-views/workspace-dashboard.tsx
This PR removes the unnecessary loader from the dashboard page to eliminate flicker issues.
> [WEB-1341] chore: unwanted loader

- web/components/issues/issue-layouts/list/block.tsx
- web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
- web/store/issue/issue-details/root.store.ts
This PR ensures only the clicked nested issue is highlighted, preventing multiple instances of the same issue from being highlighted simultaneously.
> [WEB-1264] chore: nested issue highlighting improvement

- apiserver/plane/authentication/provider/credentials/magic_code.py
- apiserver/plane/authentication/views/space/email.py
- apiserver/plane/authentication/views/space/github.py
- apiserver/plane/authentication/views/space/google.py
- apiserver/plane/authentication/views/space/magic.py
- apiserver/plane/authentication/views/space/password_management.py
- space/app/page.tsx
- space/components/account/auth-forms/auth-root.tsx
- space/components/account/auth-forms/password.tsx
- space/components/account/auth-forms/unique-code.tsx
- space/components/account/oauth/oauth-options.tsx
- space/components/issues/peek-overview/comment/comment-reactions.tsx
- space/components/issues/peek-overview/issue-emoji-reactions.tsx
- space/components/issues/peek-overview/issue-vote-reactions.tsx
This pull request addresses the handling of redirection for users who are not logged in within the Space application.
> [WEB-1319] chore: handled redirection when user is not logged in

- apiserver/plane/app/serializers/__init__.py
- apiserver/plane/app/serializers/cycle.py
- apiserver/plane/app/serializers/module.py
- apiserver/plane/app/serializers/page.py
- apiserver/plane/app/serializers/project.py
- apiserver/plane/app/serializers/view.py
- apiserver/plane/app/views/cycle/archive.py
- apiserver/plane/app/views/cycle/base.py
- apiserver/plane/app/views/module/archive.py
- apiserver/plane/app/views/module/base.py
- apiserver/plane/app/views/page/base.py
- apiserver/plane/app/views/project/base.py
- apiserver/plane/app/views/view/base.py
- apiserver/plane/authentication/views/common.py
- apiserver/plane/db/migrations/0065_auto_20240415_0937.py
- apiserver/plane/db/models/__init__.py
- apiserver/plane/db/models/estimate.py
- apiserver/plane/db/models/favorite.py
- apiserver/plane/db/models/issue.py
- apiserver/plane/db/models/page.py
- apiserver/plane/db/models/workspace.py
- Pages
- name blank true
- description_binary
- EstimatePoints
- type
- key validations
- Issues
- estimate_point
- UserFavorite - new model
Back migrated the data from the cyclefavorite, issueviewfavorite, projectfavorite, pagefavorite, and modulefavorite table.
> dev: migrations

- space/components/account/user-logged-in.tsx
- space/components/issues/navbar/controls.tsx
- space/components/issues/navbar/user-avatar.tsx
- space/components/issues/peek-overview/comment/comment-reactions.tsx
- space/store/user.store.ts
This pull request includes fixes and enhancements for the Space application, focusing on the comment reaction section and user authentication features.
> [WEB-1319] chore: resolved build errors on the comment reaction section and implemented sign out button

- apiserver/plane/authentication/views/common.py
fix: 
- cache invalidation on set password
[[WEB - 1362]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/f0c7ef84-013e-42ea-916c-dadced0c1dbb)
> [WEB - 1362] fix: cache invalidation on set password

- space/components/issues/peek-overview/issue-reaction.tsx
- space/components/issues/peek-overview/issue-vote-reactions.tsx
This pull request includes a critical fix for the issue voting component within the Space application.
> [WEB-1319] fix: handled workspaceSlug and projectId in issue voting component props

- apiserver/plane/authentication/views/space/signout.py
- space/components/issues/navbar/user-avatar.tsx
This pull request updates the sign out process within the Space application to enhance user experience.
> [WEB-1319] chore: after signout instead of redirecting to login page we are navigating to the same page where he logged out

- apiserver/plane/authentication/adapter/credential.py
- apiserver/plane/authentication/adapter/oauth.py
- apiserver/plane/authentication/provider/credentials/email.py
- apiserver/plane/authentication/provider/credentials/magic_code.py
- apiserver/plane/settings/common.py
dev: 
- remove session save 
- add callback for providers
[[WEB - 1370]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/ee0d7b84-0345-4970-a30a-a3ba631486d6)
> [WEB - 1370] dev: remove session save and add callback for providers

- packages/tailwind-config-custom/tailwind.config.js
- web/components/issues/issue-layouts/kanban/kanban-group.tsx
[WEB-1249](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/84db6b08-7c33-47c1-9e8d-fe5a5e6be8bd)
This PR changes the design for Kanban Column while dragging
https://github.com/makeplane/plane/assets/71900764/05a65b1c-d460-42ac-88b7-db66b91b2741
> [WEB-1249] chore: New Kanban column design changes

- web/components/onboarding/invite-members.tsx
- web/pages/profile/change-password.tsx
- Added validation to ensure the old password is not the same as the new password on the change password page.
- Fixed the issue of the button overflowing in the Onboarding invite member section.
| ![1319-4](https://github.com/makeplane/plane/assets/121005188/113047bd-728f-40e0-974a-83a62c4bb8c8) | ![1319-3](https://github.com/makeplane/plane/assets/121005188/cb119b6e-348a-4a30-8742-bd4b2c73714d) |
| ![1319-2](https://github.com/makeplane/plane/assets/121005188/da866e77-d667-41fd-ad86-368ed7c8e09b) | ![1319-1](https://github.com/makeplane/plane/assets/121005188/3b7ec0fc-3a9e-4d5c-abe6-eae08a9faf8c) |
> [WEB-1319] chore: auth fixes and enhancement

- web/lib/wrappers/authentication-wrapper.tsx
- web/lib/wrappers/instance-wrapper.tsx
This pull request addresses the auto-reload issue affecting the auth-wrapper and instance-wrapper components.
> [WEB-1319] chore: handled the auto reload issue in auth-wrapper and instance wrapper

- apiserver/plane/app/views/user/base.py
chore:
- delete workspace invitation on user deactivation
[[WEB - 1375]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/07c33128-6679-442a-b8a4-ecc8258e5f82)
> [WEB - 1375] chore: delete workspace invitation on user deactivation

- apiserver/plane/authentication/provider/credentials/magic_code.py
fix: 
- magic code 500 error on wrong code or expired code
[[WEB - 1381]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/ff5fa33f-eee7-42fc-83a9-8ab64ee11636)
> [WEB - 1381] fix: magic code 500 error on wrong code or expired code

- web/helpers/authentication.helper.tsx
- web/pages/accounts/reset-password.tsx
This PR include error handling for reset password.
> [WEB-1319] chore: reset password error handling

- space/components/account/oauth/github-button.tsx
- space/components/account/oauth/google-button.tsx
- web/components/account/oauth/github-button.tsx
- web/components/account/oauth/google-button.tsx
This pull request includes an important fix for the OAuth authentication flow that enables the next_auth in the OAuth authentication.
> [WEB-1319] fix: enabled next_path for OAuth Authentication

- web/lib/wrappers/authentication-wrapper.tsx
This pull request addresses onboarded steps validation in web app auth wrapper
> [WEB-1319] fix: onboarded steps validation in web app

- web/components/headers/cycle-issues.tsx
- web/components/headers/module-issues.tsx
- web/components/headers/project-issues.tsx
- web/helpers/issue.helper.ts
- web/store/issue/cycle/issue.store.ts
- web/store/issue/module/issue.store.ts
- web/store/issue/project/issue.store.ts
This pull request resolved the auto updates of the issues count within projects, modules, and cycles when the filter was applied to the issues.
> [WEB-1301] chore: handled issues count in project, module, and cycle issues

- apiserver/plane/authentication/views/common.py
- apiserver/plane/settings/common.py
- apiserver/templates/csrf_failure.html
dev:
- created a custom template and view for csrf failure
[[WEB - 1387]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/4e28fcee-260d-4b78-88ec-06912f227b96)
> [WEB - 1387]dev: custom csrf failure view

- packages/ui/src/drag-handle.tsx
- packages/ui/src/index.ts
- web/components/issues/issue-layouts/group-drag-overlay.tsx
- web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
- web/components/issues/issue-layouts/kanban/block.tsx
- web/components/issues/issue-layouts/kanban/kanban-group.tsx
- web/components/issues/issue-layouts/list/base-list-root.tsx
- web/components/issues/issue-layouts/list/block-root.tsx
- web/components/issues/issue-layouts/list/block.tsx
- web/components/issues/issue-layouts/list/blocks-list.tsx
- web/components/issues/issue-layouts/list/default.tsx
- web/components/issues/issue-layouts/list/list-group.tsx
- web/components/issues/issue-layouts/list/quick-add-issue-form.tsx
- web/components/issues/issue-layouts/utils.tsx
- web/components/labels/label-block/label-item-block.tsx
- web/constants/issue.ts
- web/hooks/use-group-dragndrop.ts
- web/store/issue/archived/issue.store.ts
- web/store/issue/issue_kanban_view.store.ts
[WEB-1138](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/644287bd-d9a6-46fb-94fa-0c8e50be9d4d)
This PR enables list issue layout Drag and drop.
https://github.com/makeplane/plane/assets/71900764/859b4fa0-1527-42db-aefa-2796e5d3d742
> [WEB-1138] feat: List lssue Layout Drag and Drop

- space/components/issues/filters/applied-filters/filters-list.tsx
- space/components/issues/peek-overview/header.tsx
- space/components/issues/peek-overview/issue-reaction.tsx
- space/components/issues/peek-overview/issue-vote-reactions.tsx
- web/components/account/oauth/github-button.tsx
- web/components/account/oauth/google-button.tsx
- web/components/issues/title-input.tsx
- web/components/project/send-project-invitation-modal.tsx
- web/components/workspace/send-workspace-invitation-modal.tsx
- web/pages/create-workspace.tsx
- web/pages/invitations/index.tsx
- Updated OAuth button styling.
- Fixed Space app issue filter background overflow.
- Ensured peek overview icon consistency in Space app.
- Rectified issue title input validation.
- Resolved logo theming issue on workspace pages.
- Corrected alignment in workspace and project invite modal.
| ![before](https://github.com/makeplane/plane/assets/121005188/33fa567a-f437-42f0-bda4-b2f7ed46e35a) | ![after](https://github.com/makeplane/plane/assets/121005188/6ea4421f-ea6e-4289-b649-0e54cbd2b56e) |
| ![before](https://github.com/makeplane/plane/assets/121005188/3214742c-bcb9-4075-b530-1624abdc956e) | ![after](https://github.com/makeplane/plane/assets/121005188/bc96ba7c-6982-4372-adbf-80dc4c1bfaf9) |
| …
> [WEB-1385] style: oauth button enhancement

- packages/ui/src/drag-handle.tsx
- web/components/issues/issue-layouts/list/block-root.tsx
- web/components/issues/issue-layouts/list/block.tsx
- web/components/issues/issue-layouts/list/headers/group-by-card.tsx
- web/components/issues/issue-layouts/list/quick-add-issue-form.tsx
[WEB-1138](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/1e826089-cdb5-4903-b2f7-7782204d1179)
This PR is to fix alignment for issues in list layout
> [WEB-1138] chore: fix list view visual alignments

- web/components/analytics/scope-and-demand/scope-and-demand.tsx
- web/components/analytics/scope-and-demand/scope.tsx
[WEB-1394](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/d7237ad4-33ff-4960-a1b5-528a1f02e9d6)
This PR fixes the Unassigned count in Burndown chart for analytics
> [WEB-1394] fix: unassigned issues count in analytics page

- space/components/issues/navbar/controls.tsx
- space/components/issues/peek-overview/comment/comment-detail-card.tsx
- space/components/issues/peek-overview/comment/comment-reactions.tsx
- space/components/issues/peek-overview/header.tsx
- space/components/issues/peek-overview/issue-activity.tsx
- space/components/issues/peek-overview/issue-reaction.tsx
- space/components/issues/peek-overview/issue-vote-reactions.tsx
- space/hooks/use-clipboard-write-permission.tsx
- space/hooks/use-is-in-iframe.tsx
https://github.com/makeplane/plane/assets/33979846/dcc9e453-5a4c-4360-bd55-0f6f9d6d65d9
This PR is linked to [WEB-1396](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/debeea68-63f0-4657-8944-54c88f554c72)
> [WEB-1396] chore: remove/ disable all actionable items from deploy url in case url is embedded using Iframe.

- web/components/issues/sub-issues/issue-list-item.tsx
- web/components/issues/sub-issues/issues-list.tsx
- web/components/issues/sub-issues/root.tsx
[WEB-1382](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/455f3321-360d-4b98-87ad-e0f451ae3c79)
This PR makes sure to remove loading sub issues if it is also the root issue
https://github.com/makeplane/plane/assets/71900764/2fa58b72-89bd-45c2-9c6c-b7490e1efe4a
> [WEB-1382] fix: infinite loop for sub issues

- space/components/instance/not-ready-view.tsx
- space/components/views/auth.tsx
- space/lib/instance-provider.tsx
This PR include space app logo redirection changes.
> [WEB-1404] chore: space app logo redirection updated

- web/components/issues/issue-layouts/empty-states/module.tsx
* Before
* After
Issue link [WEB-1216](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/62d154b3-bc31-4b43-81f1-a38c54d8697e)
> [WEB-1216] chore: update module empty state size for consistency.

- admin/components/common/copy-field.tsx
Updated the text color of Service provider label and description for better visibility on dark mode. 
Issue link [WEB-1404](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/bd9d0367-520a-43aa-9548-342e2f96b88a)
> [WEB-1404] chore: minor improvement in admin service provider field.

- web/components/labels/create-label-modal.tsx
- web/components/labels/create-update-label-inline.tsx
* Before
* After
Issue link [WEB-1413](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/bc42b79e-5bf7-48f1-a5be-93f7860d8336)
> [WEB-1413] chore: update label creation toast error message.

- web/components/headers/project-inbox.tsx
- web/components/headers/project-settings.tsx
- web/components/headers/workspace-settings.tsx
- web/pages/[workspaceSlug]/projects/[projectId]/settings/automations.tsx
- web/pages/[workspaceSlug]/projects/[projectId]/settings/estimates.tsx
- web/pages/[workspaceSlug]/projects/[projectId]/settings/features.tsx
- web/pages/[workspaceSlug]/projects/[projectId]/settings/index.tsx
- web/pages/[workspaceSlug]/projects/[projectId]/settings/labels.tsx
- web/pages/[workspaceSlug]/projects/[projectId]/settings/members.tsx
- web/pages/[workspaceSlug]/projects/[projectId]/settings/states.tsx
- web/pages/[workspaceSlug]/settings/api-tokens.tsx
- web/pages/[workspaceSlug]/settings/billing.tsx
- web/pages/[workspaceSlug]/settings/exports.tsx
- web/pages/[workspaceSlug]/settings/imports.tsx
- web/pages/[workspaceSlug]/settings/index.tsx
- web/pages/[workspaceSlug]/settings/integrations.tsx
- web/pages/[workspaceSlug]/settings/members.tsx
- web/pages/[workspaceSlug]/settings/webhooks/[webhookId].tsx
- web/pages/[workspaceSlug]/settings/webhooks/index.tsx
Issue link [WEB-656](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/21c4f351-f62f-40c4-9f70-471439d075df)
> [WEB-656] chore: fix breadcrumbs inconsistency.

- admin/app/authentication/github/page.tsx
- admin/app/authentication/google/page.tsx
- admin/app/globals.css
- admin/components/admin-sidebar/help-section.tsx
- admin/components/admin-sidebar/sidebar-menu.tsx
- admin/components/instance/setup-form.tsx
- admin/components/new-user-popup.tsx
- apiserver/plane/license/api/views/instance.py
* fix: redirection to web app and issue with telemetry checkbox in setup form.
* chore: add scrollbar in admin app.
* chore: fix `workspaces_exist` logic in instance api.
> [WEB-1404] chore: admin app improvements

- web/next.config.js
Issue link [WEB-1404](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/bd9d0367-520a-43aa-9548-342e2f96b88a)
> [WEB-1404] fix: redirection to `/god-mode`.

- web/store/issue/issue-details/issue.store.ts
This PR addresses a sub-issue retrieval problem on the issue detail page. Previously, adding a parent issue from a different project resulted in an error. The changes in this PR resolve this issue, ensuring that the functionality now works as expected without errors.
> [WEB-1432] fix: issue store sub issue retrieve problem

- admin/app/ai/page.tsx
- admin/app/authentication/page.tsx
- admin/app/email/page.tsx
- admin/app/email/test-email-modal.tsx
- admin/app/general/page.tsx
- admin/app/image/page.tsx
Issue link [WEB-1404](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/bd9d0367-520a-43aa-9548-342e2f96b88a)
> [WEB-1404] chore: send test email error message update and scrollbar improvement.

- web/components/issues/issue-detail/parent/root.tsx
- web/components/issues/issue-detail/parent/sibling-item.tsx
- web/components/issues/issue-detail/parent/siblings.tsx
- Sibling issue redirection and issue fetch fix.
| ![1441(2)](https://github.com/makeplane/plane/assets/121005188/ad0e5a9e-c77d-45d3-98c5-4ffea61193cc) | ![1441(1)](https://github.com/makeplane/plane/assets/121005188/370411cb-3b74-49c0-a12c-ed83febddf8f) |
> [WEB-1441] fix: sibling issue redirection and fetching issue resolved

- web/components/core/list/list-item.tsx
- web/components/cycles/active-cycle/productivity.tsx
- web/components/cycles/active-cycle/progress.tsx
- web/components/cycles/active-cycle/root.tsx
- web/components/cycles/list/cycles-list-item.tsx
- Added className prop to List Item component for customization.
- Enhanced Project Active Cycle UI.
| ![before](https://github.com/makeplane/plane/assets/121005188/ad6bc786-062d-48fc-a798-4a67346f4ed4) | ![after](https://github.com/makeplane/plane/assets/121005188/0c6ea38c-6c9c-4f33-84f7-37a0324c9c16) |
> [WEB-1395] chore: project active cycle ui enhancements

- web/components/project/card-list.tsx
- web/store/project/project.store.ts
- Fix for flicker on project list page empty state during reload.
| ![1451(2)](https://github.com/makeplane/plane/assets/121005188/69f113eb-d890-465d-9b6c-b27bb757b225) | ![1451(1)](https://github.com/makeplane/plane/assets/121005188/a8c81387-ada2-4434-98af-e94c4a9aeec0) |
> [WEB-1451] fix: project list page empty state flicker

- web/components/issues/issue-layouts/empty-states/cycle.tsx
- web/components/issues/issue-layouts/empty-states/draft-issues.tsx
- web/components/issues/issue-layouts/empty-states/project-issues.tsx
- web/components/issues/issue-layouts/roots/all-issue-layout-root.tsx
In this PR, I have updated the empty states to use same size across the platform for consistency. 
Issue link [WEB-1216](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/62d154b3-bc31-4b43-81f1-a38c54d8697e)
> [WEB-1216] style: fix all empty states size of inconsistency.

- web/components/core/activity.tsx
In this PR, I've updated the user activity from "set the name" to "set the title".
| ![before](https://github.com/makeplane/plane/assets/121005188/7a505e6b-e198-4393-b101-f3190c3da995) | ![after](https://github.com/makeplane/plane/assets/121005188/d1a0ad05-3597-4981-8032-96313099dee0) |
> [WEB-1267] chore: user activity title update message updated

- web/components/analytics/project-modal/main-content.tsx
- web/pages/[workspaceSlug]/analytics.tsx
- Workspace and Project analytics UI enhancement.
| ![1335(B)](https://github.com/makeplane/plane/assets/121005188/2d01e92f-f674-45d8-8513-de5edb64ade6) | ![1335(A)](https://github.com/makeplane/plane/assets/121005188/8d78f76d-b0ce-486c-b6fd-a6801265412d) |
> [WEB-1335] chore: analytics tab enhancement

- apiserver/plane/db/management/commands/activate_user.py
Management command to activate user if the user account is deactivated
`python manage.py activate_user <user_email>`
**Ticket** -  [WEB - 1471](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/cf34a29a-bed8-42a7-8ebb-77ff6e2f4d1f)
> [WEB - 1471] dev: activate user management command

- apiserver/plane/api/views/issue.py
fix: 
- remove issue duplicated when adding multiple modules due to annotation.
Fixes: #4629
> fix: remove issue duplicated when adding multiple modules

- web/components/issues/issue-modal/modal.tsx
[WEB-1374](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/236a76e8-7b35-4437-877d-3a1c8c1a2381)
> [WEB-1374] fix: clear changes made on modal close

- web/lib/wrappers/store-wrapper.tsx
* Before
https://github.com/makeplane/plane/assets/33979846/4284adaf-7818-4165-a8c4-375914b60aea
* After
https://github.com/makeplane/plane/assets/33979846/69185bef-7270-4adb-8a5e-f7048d5536e9
Issue link [WEB-1465](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/c7eb26e1-359c-4a88-a05a-0d31136ab2c4)
> [WEB-1465] fix: theme fluctuation on initial load.

- web/components/inbox/modals/create-edit-modal/create-root.tsx
- web/components/issues/issue-modal/form.tsx
Negate wrong check while trying to discard editor in forms while image is uploading.
regression due to #4508
> fix: negate check while trying to discard editor in forms while image is uploading

- web/components/issues/issue-layouts/empty-states/module.tsx
* Before
* After
Issue link [WEB-1216](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/62d154b3-bc31-4b43-81f1-a38c54d8697e)
> [WEB-1216] chore: increase module empty state for consistency.

- packages/ui/src/drag-handle.tsx
- web/components/issues/issue-layouts/list/block.tsx
- web/components/labels/label-block/label-item-block.tsx
Drag handle component now accepts `className`. This removes the group logic from inside the component to the specific components where it's being used.
> refactor: drag handle component

- packages/ui/src/form-fields/checkbox.tsx
- web/components/profile/preferences/email-notification-form.tsx
1. Renamed the `intermediate` prop to `indeterminate`.
2. Added new props- `containerClassName`, `iconClassName` and `className`.
> refactor: checkbox ui component

- web/components/dropdowns/priority.tsx
Priority dropdown now accepts `undefined` as the value, in which case, placeholder icon and text are shown.
> chore: priority dropdown now accepts undefined as the value

- web/components/core/index.ts
- web/components/core/multiple-select/entity-select-action.tsx
- web/components/core/multiple-select/group-select-action.tsx
- web/components/core/multiple-select/index.ts
- web/components/core/multiple-select/select-group.tsx
- web/hooks/store/index.ts
- web/hooks/store/use-multiple-select-store.ts
- web/hooks/use-multiple-select.ts
- web/store/multiple_select.store.ts
- web/store/root.store.ts
This PR introduces the multiple select components which can be used to perform selection logic anywhere.
Multiple select provides various ways to perform selection-
1. By clicking on the entity action checkbox.
2. By using arrow keys to navigate between entities and using `Shift + ArrowDown/ArrowUp` to select an entity.
3. By using `Shift + left mouse click` to select all the entities between the last selected entity and the clicked entity.
Created a HOC `<MultipleSelectGroup />` which accepts the following prop-
1. `entities`- Object of the following structure-
```typescript
{
[groupId: string]: string[] // entity ids
}
``` 
This HOC makes use of the `MultipleSelectStore` to manage selected entities state. This HOC can be reused to implement multiple select functionality anywhere.
This …
> [WEB-1501] dev: multiple select core components

- web/components/issues/issue-detail/sidebar.tsx
- web/components/issues/issue-layouts/quick-action-dropdowns/all-issue.tsx
- web/components/issues/issue-layouts/quick-action-dropdowns/cycle-issue.tsx
- web/components/issues/issue-layouts/quick-action-dropdowns/module-issue.tsx
- web/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx
- web/components/issues/peek-overview/header.tsx
- web/constants/state.ts
Created a new constant `ARCHIVABLE_STATE_GROUPS` which is an array of the state groups. An issue can be archived if it belongs to any of these state groups.
> [WEB-1501] chore: created a new constant for archivable state groups

- packages/ui/src/form-fields/checkbox.tsx
- Corrected check icon positioning in checkbox UI component.
| ![before](https://github.com/makeplane/plane/assets/121005188/750a3850-1662-4687-aed1-e704ee147ad9) | ![after](https://github.com/makeplane/plane/assets/121005188/ba7129ed-b5e1-460f-b2e0-0a29c3e517aa) |
> fix: checkbox ui component

- apiserver/plane/license/migrations/0002_rename_version_instance_current_version_and_more.py
- apiserver/plane/license/models/instance.py
chore:
- alter instance id field to increase the max_length to 255 characters to support uuid.
**Ticket** - [[WEB - 1505]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/4d51271b-1d8d-40d1-9be9-b2e4d5eb71c4)
> [WEB - 1505] chore: alter instance id field

- web/components/states/create-update-state-inline.tsx
In this PR, I have added `autofocus` property to `name` field in create/ update state form.
Issue link [WEB-1503](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/81d94ab2-5294-4e17-9cc2-bb8e4392380d)
> [WEB-1503] chore: add `autofocus` to name field in inline create/ update state component.

- admin/app/authentication/page.tsx
- admin/components/admin-sidebar/help-section.tsx
Issue link [WEB-1521](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/f9251cab-1bbb-48bf-82db-8e7548681730)
> [WEB-1521] chore: add configuration to enable/disable sign-ups.

- web/components/project/sidebar-list.tsx
When a user collapses "Your projects" - save that setting. Today, on refresh it expands all Your projects.
The window might contain issues or module or cycles from a specific project but user has made a conscious choice of
collapsing the Projects should be honored
For this, I update both the lists to handle their collapsed state based on values from local storage.
* Before
https://github.com/makeplane/plane/assets/33979846/1be8c516-0011-4246-aaf7-ce5d0f550422
* After
https://github.com/makeplane/plane/assets/33979846/284fa16b-043a-4dd7-99c0-d0f29074c405
Issue link [WEB-1459](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/7e771cca-f860-4f31-95e0-09c7df5916e8)
> [WEB-1459] chore: save users all / favorite project list collapse state into local storage.

- web/components/issues/issue-layouts/list/block.tsx
- web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
- web/store/project/project.store.ts
- yarn.lock
In the case of undefined project identifier, app breaks.
1. Added proper types to the getProjectIdentifier helper.
2. Handled undefined identifier case.
> [WEB-1540] chore: handle undefined identifier error

- web/components/workspace/sidebar-dropdown.tsx
* Removed `My activity`
* Updated `Settings` to `Workspace settings`
* Before
* After
Issue link [WEB-1529](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/e355c030-dcfb-46e0-814a-c7bbefb1a561)
> [WEB-1529] chore: workspace sidebar updates.

- packages/editor/extensions/src/extensions/slash-commands.tsx
Currently lines with / aren't exitable in anyway. This PR solves that.
> fix: temporary fix exiting lines with slashes

- web/components/workspace/settings/members-list-item.tsx
This PR include fix for member list item custom menu option placement.
| ![WEB-1507-BEFORE](https://github.com/makeplane/plane/assets/121005188/ad24bcf6-22cf-4592-a58b-a87c54bc95eb) | ![WEB-1507-AFTER](https://github.com/makeplane/plane/assets/121005188/785c1df7-7556-4b62-a01e-57383f8f35f1) |
> [WEB-1507] fix: member list item custom menu placement

- web/components/project/form.tsx
This PR includes improvements for the emoji picker project. Previously, if a broken emoji was selected, the picker modal would stop functioning.
> [WEB-1535] chore: project logo picker improvement

- web/components/project/project-feature-update.tsx
> style: fix ux copy style on project feature preview page.

- web/components/cycles/cycle-mobile-header.tsx
- web/components/headers/cycle-issues.tsx
- web/components/headers/global-issues.tsx
- web/components/headers/module-issues.tsx
- web/components/headers/project-draft-issues.tsx
- web/components/headers/project-issues.tsx
- web/components/headers/project-view-issues.tsx
- web/components/issues/archived-issues-header.tsx
- web/components/issues/issue-layouts/filters/header/display-filters/display-filters-selection.tsx
- web/components/issues/issue-layouts/filters/header/filters/filters-selection.tsx
- web/components/issues/issues-mobile-header.tsx
- web/components/modules/module-mobile-header.tsx
- web/components/profile/profile-issues-filter.tsx
- web/components/profile/profile-issues-mobile-header.tsx
- Move issue types from display properties to filters dropdown.
> [WEB-1538] chore: issue and properties filter dropdown improvement

- README.md
found via:
- https://github.com/makeplane/docs/issues/48
- https://github.com/makeplane/plane/pull/3109
> docs: update self-host guide link in README

- web/core/components/project/publish-project/modal.tsx
- Project publish url updated.
| ![before](https://github.com/makeplane/plane/assets/121005188/890425e0-604d-4729-9a7f-416e01305ab9) | ![after](https://github.com/makeplane/plane/assets/121005188/0ba0c926-617f-4e15-af7b-f61bff081195) |
> [WEB-1561] chore: project publish url

- apiserver/plane/utils/paginator.py
This PR include fix for inbox issues fetch issue.
> [WEB-1572] fix: inbox issues

- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/cycles/(detail)/[cycleId]/page.tsx
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/modules/(detail)/[moduleId]/page.tsx
This PR includes improvements for the module and cycle peek sidebar.
| ![before](https://github.com/makeplane/plane/assets/121005188/238329bb-b364-4972-accb-b77d27a94033) | ![after](https://github.com/makeplane/plane/assets/121005188/787ec4d9-42ce-4bb0-a0b8-7d85182351cd) |
> [WEB-1508] chore: module and cycle peek view improvement

- web/core/hooks/use-page-title.tsx
This PR include page head custom hook.
> [WEB-1574] dev: page head hook

- web/core/components/cycles/gantt-chart/blocks.tsx
- web/core/components/gantt-chart/sidebar/cycles/block.tsx
- web/core/components/gantt-chart/sidebar/cycles/sidebar.tsx
- web/core/components/gantt-chart/sidebar/gantt-dnd-HOC.tsx
- web/core/components/gantt-chart/sidebar/issues/block.tsx
- web/core/components/gantt-chart/sidebar/issues/sidebar.tsx
- web/core/components/gantt-chart/sidebar/modules/block.tsx
- web/core/components/gantt-chart/sidebar/modules/sidebar.tsx
- web/core/components/labels/label-block/label-item-block.tsx
- web/core/components/labels/label-block/label-name.tsx
- web/core/components/labels/project-setting-label-group.tsx
- web/core/components/labels/project-setting-label-item.tsx
- web/core/components/modules/gantt-chart/blocks.tsx
- web/core/components/project/sidebar-list-item.tsx
- web/core/components/project/sidebar-list.tsx
This PR aims to remove all the drag handles from Gantt Drag n drop, Project sidebar and Labels list
https://github.com/makeplane/plane/assets/71900764/645ac33b-185b-4725-aa14-c79f66b6b69a
https://github.com/makeplane/plane/assets/71900764/8f78891b-87bf-4932-a981-67a0f09696e2
> [WEB-1548] chore: Remove Drag Handles

- apiserver/plane/app/urls/external.py
- apiserver/plane/app/views/__init__.py
- apiserver/plane/app/views/external/base.py
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/[pageId]/page.tsx
- web/core/components/core/modals/gpt-assistant-popover.tsx
- web/core/components/issues/issue-modal/form.tsx
- web/core/components/pages/editor/header/extra-options.tsx
- web/core/components/pages/editor/header/mobile-root.tsx
- web/core/components/pages/editor/header/root.tsx
- web/core/services/ai.service.ts
Removed `projectId` from the AI assistant endpoint to enable its usage in the workspace level.
> [WEB-1559] chore: make AI assistant endpoint workspace level

- web/core/components/issues/title-input.tsx
- Issue title flicker fix.
| ![WEB-1409-Before](https://github.com/makeplane/plane/assets/121005188/10fe3f7c-f297-494d-9ca5-512b97333bb5) | ![WEB-1409-After](https://github.com/makeplane/plane/assets/121005188/b2b39346-4bc7-4ba1-b315-39e08f77cd66) |
> [WEB-1409] fix: issue title input flicker

- apiserver/plane/app/views/dashboard/base.py
chore:
- This pull request resolves the issue of duplicate project member collaborators appearing in the collaborator's section of the dashboard.
Issue Link: [WEB-1562](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/78840a8c-91aa-497d-a47d-f9052afc32ce)
> [WEB-1562] chore: duplicated project collaborators

- web/core/components/ui/loader/layouts/spreadsheet-layout-loader.tsx
This PR include fix for spreadsheet layout loader unwanted styling.
| ![Screen Recording 2024-06-12 at 6 (1)](https://github.com/makeplane/plane/assets/121005188/3579b152-967d-4851-bd11-0a1447ff94be) | ![Screen Recording 2024-06-12 at 6](https://github.com/makeplane/plane/assets/121005188/3e084f40-4365-4463-8498-b27b834da70f) |
> [WEB-1598] style: spreadsheet layout loader

- web/core/services/api.service.ts
- web/core/services/user.service.ts
> [WEB-1564] chore: add interceptor to handle 401 errors and redirect users to login page.

- packages/ui/package.json
- yarn.lock
- Updated the Headless UI version in the ui package.
> [WEB-1571] [WEB-1566] fix: headless ui version

- admin/components/admin-sidebar/root.tsx
- Reduced admin sidebar width.
> [WEB-1580] chore: admin sidebar improvement

- web/core/store/issue/helpers/base-issues-utils.ts
- web/core/store/issue/helpers/base-issues.store.ts
This PR aims to fixing the issue mutation and issue count inconsistensies in Pagination logic
This PR Fixes the following,
[WEB-1584](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/30a692ee-8bff-4032-b57a-6a2c7ab7b4e6)
[WEB-1591](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/1b509529-01bd-4c3f-a32e-234a9a81a094)
[WEB-1590](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/3a54fcc1-83ce-41d7-b614-644a4f736278)
[WEB-1587](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/0dca3f8e-8692-484e-b60e-fe4cc8972ea0)
[WEB-1588](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/0ef9d34c-b904-4ba8-8051-33f331855109)
> [WEB-1584] fix: issue mutation inconsistencies with pagination

- web/core/components/pages/header/root.tsx
- web/core/components/pages/list/search-input.tsx
Accept `searchQuery` and `updateSearchQuery` as props to make the search input component generic.
> [WEB-1559] chore: update page search input props

- apiserver/plane/app/views/project/base.py
- web/core/layouts/auth-layout/project-wrapper.tsx
> [WEB-1608] fix: deleted project errors

- web/core/components/dropdowns/state.tsx
When opened create issue modal default state should be populate.
Fixed the default state selection logic inside the state dropdown...
> [WEB-1607] fix: state dropwdown default state.

- web/next.config.js
Issue link : [WEB-1614](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/3c348219-7307-49f9-8956-b9dc15bb8c71)
> [WEB-1614] fix: god mode redirection without trailing slash.

- web/core/store/issue/helpers/base-issues.store.ts
> [WEB-1601] fix: archive issues mutation.

- apiserver/plane/utils/paginator.py
- pagination on many to many fields when grouping and sub grouping
- rectify the variable on subgrouping
**Ticket** - [[WEB - 1604]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/0bdf126a-3af2-48a4-87f2-1122d9933497)
> [WEB - 1604]fix: pagination on many to many fields when grouping and sub grouping

- apiserver/plane/authentication/provider/oauth/gitlab.py
fix: 
- move GITLAB_HOST check to init function rather than class.
**Ticket** - [[WEB - 1629]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/2a326dac-5627-4414-a631-4adcdd00dffb)
> [WEB - 1629] fix: backend crash on app startup

- web/core/components/cycles/active-cycle/productivity.tsx
Issue link : [WEB-522](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/6d658a72-0898-49c8-8989-7841ae9c3498)
> [WEB-522] fix: Remove duplicate import.

- web/core/components/issues/issue-detail/issue-detail-quick-actions.tsx
- web/core/components/issues/issue-detail/sidebar.tsx
- web/core/components/issues/peek-overview/properties.tsx
- Added "Created by" field to the issue peek overview and issue detail sidebar to enhance user experience.
- Properties section of the issue peek overview.
- Properties section of the issue detail sidebar.
- Issue detail page sidebar:
Path: `web/core/components/issues/issue-detail/sidebar.tsx`
- Issue peek overview:
Path: `web/core/components/issues/peek-overview/properties.tsx`
| ![before](https://github.com/makeplane/plane/assets/121005188/36ee80db-5eb5-4a73-b1a0-9ac92aea01cd) | ![after](https://github.com/makeplane/plane/assets/121005188/311c6480-0047-432f-90f7-f0fca9dbe577) |
| ![before](https://github.com/makeplane/plane/assets/121005188/39e7c5c7-8a5e-48b7-968e-117c59ff020e) | …
> [WEB-1617] chore: created by implementation

- web/core/hooks/use-multiple-select.ts
[WEB-1592](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/92f88bfb-c3e5-4d25-8586-dbf705f49d48)
This PR fixes the exception while switching groups in list view by adding multiple checks
> [WEB-1592] fix: exception while switching groups in list view

- web/app/profile/activity/page.tsx
- web/app/profile/appearance/page.tsx
- web/app/profile/notifications/page.tsx
- web/app/profile/page.tsx
- web/app/profile/security/page.tsx
- web/core/components/profile/index.ts
- web/core/components/profile/notification/email-notification-form.tsx
- web/core/components/profile/profile-setting-content-header.tsx
- web/core/components/profile/profile-setting-content-wrapper.tsx
- Fixed alignment issues in the profile settings layout.
- Resolved overlapping issues in the cover modal and  scrolling issue in layout.
- Created common components for the profile setting wrapper and profile setting content header to eliminate repetitive code.
| ![before](https://github.com/makeplane/plane/assets/121005188/78686e26-0d5f-4c3d-970f-a584bab73f6f) | ![after](https://github.com/makeplane/plane/assets/121005188/2d6a96e5-b2e5-4ce2-a419-3fafdb9c33b2) |
| ![before](https://github.com/makeplane/plane/assets/121005188/efccdd56-86eb-4521-9cbf-498441f639f6) | ![after](https://github.com/makeplane/plane/assets/121005188/86cb4512-1533-4474-96aa-16bd444229b7) |
> [WEB-1622] chore: profile setting layout improvement

- web/core/lib/wrappers/store-wrapper.tsx
* Before
https://github.com/makeplane/plane/assets/33979846/79f983b5-4e63-4983-9496-ceb2b961b0e5
* After
https://github.com/makeplane/plane/assets/33979846/059a3af8-1e53-419e-96f5-3e84be714286
> [WEB-1551] fix: theme mutation when custom theme is applied.

- web/core/layouts/auth-layout/project-wrapper.tsx
* Before
https://github.com/makeplane/plane/assets/33979846/d5a65f7d-bab0-4256-b372-57bec685b14f
* After
https://github.com/makeplane/plane/assets/33979846/965f5710-66a1-4364-8f96-d9cab9183dc2
> [WEB-1630] chore: fix project doesn't exist empty state fluctuation on refresh.

- web/core/components/core/multiple-select/entity-select-action.tsx
- web/core/components/issues/issue-layouts/list/default.tsx
- web/core/components/issues/issue-layouts/utils.tsx
[WEB-1594](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/53042437-ba27-45da-b784-9a4e57b7004e)
This PR fixes the bulk issues selection checkboxes when grouped in list view
> [WEB-1594] fix: bulk issues selection checkbox

- packages/ui/src/emoji/helpers.ts
- packages/ui/src/emoji/index.ts
- packages/ui/src/emoji/logo.tsx
Created a new component to render emoji/icon in the `@plane/ui` package.
> [WEB-1397] dev: create a global component for emoji/icon logo

- packages/ui/src/emoji/logo.tsx
- space/core/store/root.store.ts
- web/core/store/pages/page.ts
1. Removed `"use client";` from the logo component.
2. Converted `reset` function of the space app root store from an arrow function to a regular function.
3. Added the missing `anchor` observable to the page instance.
> [WEB-1397] fix: UI package logo component

- web/core/components/issues/issue-layouts/spreadsheet/columns/state-column.tsx
> [WEB-1611] style: fixed state column width for consistency.

- web/core/components/analytics/custom-analytics/graph/index.tsx
- web/core/components/analytics/custom-analytics/table.tsx
- web/helpers/analytics.helper.ts
This PR updates the styling of the global analytics graphs UI and table UI 
1. Analytics Table
2. Analytics graph
3. Analytics helpers
> [WEB-1616] chore: improving the graphs ui and label in analytics

- space/app/error.tsx
- space/app/not-found.tsx
- space/core/components/account/auth-forms/auth-header.tsx
- space/core/components/account/user-logged-in.tsx
- web/app/error.tsx
Updated the content of the following pages in the space app-
1. Error page.
2. 404 page.
3. Sign in page.
> [WEB-1397] chore: updated error state, sign in page and 404 page content

- web/core/components/cycles/gantt-chart/blocks.tsx
- web/core/components/issues/issue-layouts/calendar/issue-block.tsx
- web/core/components/issues/issue-layouts/kanban/roots/profile-issues-root.tsx
- web/core/components/issues/issue-layouts/list/roots/profile-issues-root.tsx
- web/core/components/issues/issue-layouts/spreadsheet/columns/sub-issue-column.tsx
- web/core/components/issues/issue-modal/form.tsx
- web/core/components/issues/issue-modal/modal.tsx
- web/core/components/modules/module-list-item.tsx
> [WEB-1652] fix: add optional chaining to fix app crash if router params are not available.

- web/core/components/account/auth-forms/password.tsx
- Implemented a password strength banner on the signup page to enhance user experience when the password is not strong.
| ![before](https://github.com/makeplane/plane/assets/121005188/754b6e81-ca9f-4265-9be1-11411b843048) | ![after](https://github.com/makeplane/plane/assets/121005188/2fcc37c8-3d82-428c-a420-47eec15dc853) |
> [WEB-1615] chore: sign up password strength improvement

- web/core/components/issues/issue-modal/modal.tsx
- web/core/store/issue/module/issue.store.ts
[WEB-1654](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/b9e5e609-f914-419b-b5e3-2b68e5d53911)
This PR fixes the issue creation logic by making sure to use the appropriate store while creating based on the issue Payload's cycle id or module id
> [WEB-1654] fix: issue creation logic for modules and cycles

- packages/editor/core/src/ui/mentions/mention-node-view.tsx
- web/core/hooks/use-reload-confirmation.tsx
> [WEB-1610] chore: re-implement reload confirmation hook.

- apiserver/plane/app/views/workspace/cycle.py
chore:
- Optimised the workspace cycles endpoint to return a specific response to load the data.
Issue Link: [WEB-1676](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/21f690f6-ca1d-4473-8fd4-e5d09a7426bd)
> [WEB-1676] chore: workspace cycles list endpoint 

- packages/ui/src/breadcrumbs/breadcrumbs.tsx
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/archives/header.tsx
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/archives/issues/(detail)/header.tsx
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/cycles/(detail)/header.tsx
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/cycles/(list)/header.tsx
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/draft-issues/header.tsx
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/inbox/header.tsx
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/issues/(detail)/header.tsx
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/issues/(list)/header.tsx
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/modules/(detail)/header.tsx
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/modules/(list)/header.tsx
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/header.tsx
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(list)/header.tsx
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/settings/header.tsx
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/views/(detail)/[viewId]/header.tsx
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/views/(list)/header.tsx
- web/app/[workspaceSlug]/(projects)/settings/header.tsx
- Implementation of the breadcrumb item loader.
| ![before](https://github.com/makeplane/plane/assets/121005188/19996958-bee5-438a-b76a-beb8621292f4) | ![after](https://github.com/makeplane/plane/assets/121005188/0f892605-6b4c-4660-961d-7569c4c4cc70) |
> [WEB-1647] chore: breadcrumb items loader

- web/.gitignore
- web/app/error.tsx
- web/app/global-error.tsx
- web/package.json
- yarn.lock
> [WEB-1669] chore: enable sign out and sentry on exception error page.

- admin/components/common/password-strength-meter.tsx
- admin/components/instance/setup-form.tsx
- admin/helpers/password.helper.ts
- space/core/components/account/auth-forms/password.tsx
- space/core/components/account/helpers/password-strength-meter.tsx
- space/helpers/password.helper.ts
This PR enhances password strength validation and improves the criteria for acceptable characters, ensuring stronger and more secure passwords.
1. Admin password screen
2. Space Password screen
> [WEB-1681] chore: handled password strength validation and improved the acceptable char

- web/core/components/labels/create-update-label-inline.tsx
- web/core/components/labels/label-block/label-item-block.tsx
- web/core/components/labels/label-block/label-name.tsx
- Added a character limit exceeded error message to label create inline block.
- Improved UI alignment and fixed the quick action overflow issue.
| ![before](https://github.com/makeplane/plane/assets/121005188/fe348a8d-dddd-40cb-bbe1-536d19c19485) | ![after](https://github.com/makeplane/plane/assets/121005188/fae8539a-c5c4-41a9-9427-f6721c6965db) |
> [WEB-1673] fix: project label error message and improvement

- web/app/[workspaceSlug]/(projects)/profile/[userId]/navbar.tsx
> [WEB-1670] style: fix tab highlights on user activity page.

- web/core/components/onboarding/profile-setup.tsx
- yarn.lock
This PR fixes the password validation during the onboarding process to ensure weak passwords are correctly identified and rejected.
1. Web onboarding screen
> [WEB-1681] fix: onboarding password validation on weak password

- web/core/components/estimates/points/create.tsx
- web/core/components/estimates/points/update.tsx
This PR updates the input validation on the create and update estimate point forms and ensures that estimate points are truncated appropriately in issues.
1. Estimate point create and update form
> [WEB-1672] chore: updated input validation on create and update estimate point form and truncated in issues

- web/core/components/workspace/settings/members-list.tsx
This PR updates the request for fetching workspace members in the workspace settings, improving the efficiency and accuracy of data retrieval.
1. Members in workspace settings
> [WEB-1662] chore: updated workspace members request in workspace settings members

- web/app/[workspaceSlug]/(projects)/projects/(list)/header.tsx
- web/core/components/cycles/cycles-view-header.tsx
- web/core/components/modules/module-view-header.tsx
- web/core/components/pages/list/search-input.tsx
- web/core/components/views/view-list-header.tsx
- yarn.lock
In the filters search input field, if the user types a search query, the search filed should not hide.
1. Projects search.
2. Cycles search.
3. Modules search.
4. Views search.
5. Pages search.
| <video src="https://github.com/makeplane/plane/assets/65252264/8fb42895-1e7c-41c4-bd56-bf63fa034e20"></video> | <video src="https://github.com/makeplane/plane/assets/65252264/17cb0f13-e29e-4bce-aed7-76eacf5d43fb"></video> |
> [WEB-1690] fix: always show the search input if search query is present

- packages/editor/src/ce/extensions/document-extensions.tsx
- packages/editor/src/ce/extensions/index.ts
- packages/editor/src/core/hooks/use-document-editor.ts
- packages/editor/src/ee/extensions/index.ts
Created a new file for additional extensions of the document editor for differences in community and enterprise editions.
> [WEB-1682] chore: additional document editor extensions

- admin/core/components/admin-sidebar/root.tsx
- web/core/components/pages/list/block.tsx
- web/core/components/views/view-list-item.tsx
- web/core/components/workspace/help-section.tsx
- Removed the logo picker from both the page and the view list page..
> [WEB-1685] chore: page and view list page improvement

- apiserver/plane/utils/grouper.py
fix: 
- pagination when group is not present in results.
**Ticket** - [[WEB - 1703]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/ef94d22c-3c5a-4bec-b237-e7127779c223)
> [WEB - 1703] fix: pagination when group is not present in result

- packages/editor/src/core/extensions/mentions/extension.tsx
- web/core/components/issues/issue-modal/form.tsx
Mentions dropdown not rendering in any of the editors.
> [WEB-1682] fix: mentions not working in any editor

- web/app/[workspaceSlug]/(projects)/profile/[userId]/activity/page.tsx
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/archives/cycles/layout.tsx
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/archives/header.tsx
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/archives/issues/(list)/layout.tsx
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/archives/modules/layout.tsx
- web/app/profile/appearance/page.tsx
- web/app/profile/notifications/page.tsx
- web/app/profile/page.tsx
- web/app/profile/security/page.tsx
> [WEB-1702] chore: fix project archives breadcrumbs and minor ui fixes in profile page.

- web/app/onboarding/page.tsx
- web/core/components/onboarding/create-workspace.tsx
This PR handles the multiple redirections to reach the workspace on onboarding is resolved.
1. Onboarding page
2. Onboarding Create workspace component
> [WEB-1499] fix: fixed onboarding multiple redirections

- web/core/components/issues/issue-layouts/quick-action-dropdowns/draft-issue.tsx
- Added validation for viewer and guest roles in the draft issue quick action menu.
| ![before](https://github.com/makeplane/plane/assets/121005188/bf98c821-cb75-4f8b-aeb2-6dadef637c4c) | ![after](https://github.com/makeplane/plane/assets/121005188/dfc998ef-55ae-4489-a9a2-c2558dd9250c) |
> [WEB-1695] chore: draft issue quick action menu validation

- packages/ui/src/toast/index.tsx
- web/core/components/issues/create-issue-toast-action-items.tsx
- web/core/components/issues/index.ts
- web/core/components/issues/issue-layouts/calendar/quick-add-issue-form.tsx
- web/core/components/issues/issue-layouts/gantt/quick-add-issue-form.tsx
- web/core/components/issues/issue-layouts/kanban/quick-add-issue-form.tsx
- web/core/components/issues/issue-layouts/list/quick-add-issue-form.tsx
- web/core/components/issues/issue-layouts/spreadsheet/quick-add-issue-form.tsx
- web/core/components/issues/issue-modal/modal.tsx
- Reduced toast alert icon size.
- Fixed flickering issue when hovering over toast alerts.
- Improved padding and spacing in toast alerts.
- Added the "actionItems" prop to the toast alert component for better UX by allowing action items to be passed.
- Created a common component for the "create issue" toast alert action item.
| ![WEB-1008 Before](https://github.com/makeplane/plane/assets/121005188/1758ea36-66ec-4782-87bb-7031c73cc378) | ![WEB-1008 After](https://github.com/makeplane/plane/assets/121005188/25cdbc93-7b23-46fd-a228-92c9c6525098) |
> [WEB-1008] chore: issue toast alert improvement

- web/core/components/cycles/analytics-sidebar/issue-progress.tsx
- web/core/components/modules/analytics-sidebar/issue-progress.tsx
In PR #4763 , the sidebar was refactored, which caused the sidebar filter to malfunction. I have made the necessary changes to restore its intended functionality.
> [WEB-1714] fix: module and cycle sidebar issue progress

- packages/ui/src/control-link/control-link.tsx
- web/core/components/core/list/list-item.tsx
- web/core/components/inbox/content/inbox-issue-header.tsx
- web/core/components/inbox/content/issue-properties.tsx
- web/core/components/issues/issue-layouts/calendar/issue-block.tsx
- web/core/components/issues/issue-layouts/gantt/blocks.tsx
- web/core/components/issues/issue-layouts/kanban/block.tsx
- web/core/components/issues/issue-layouts/list/block.tsx
- web/core/components/issues/issue-layouts/spreadsheet/issue-row.tsx
- web/core/components/issues/sub-issues/issue-list-item.tsx
> [WEB-1691] fix: update `ControlLink` default target to `_blank` to avoid unwanted N-progress trigger.

- web/app/profile/appearance/page.tsx
- web/core/components/core/theme/custom-theme-selector.tsx
- web/core/lib/wrappers/store-wrapper.tsx
This PR handles the theme updation workflow in store-wrapper and workspace preferences
1. Store Wrapper
2. Workspace profile appearance
> [WEB-1723] fix: resolved theme updation workflow in store-wrapper and workspace preferences

- web/app/[workspaceSlug]/(projects)/sidebar.tsx
- web/core/components/workspace/sidebar/projects-list-item.tsx
- web/core/components/workspace/sidebar/projects-list.tsx
- web/core/components/workspace/sidebar/user-menu.tsx
- web/core/components/workspace/sidebar/workspace-menu.tsx
- web/core/constants/dashboard.ts
1. Spacing between `Favorites` and `My projects` sections.
2. Section separator color.
3. Project button size on the collapsed state increased to match the other options.
4. Show project section tooltip only in the collapsed state.
5. Spacing between project items increased to match other sections.
> [WEB-1716] fix: sidebar UI inconsistencies

- packages/editor/.eslintrc.js
- packages/editor/src/core/components/editors/editor-content.tsx
- packages/editor/src/core/components/menus/block-menu.tsx
- packages/editor/src/core/extensions/code/code-block-node-view.tsx
- packages/editor/src/core/extensions/code/index.tsx
- packages/editor/src/core/extensions/core-without-props.tsx
- packages/editor/src/core/extensions/custom-list-keymap/list-helpers.ts
- packages/editor/src/core/extensions/custom-list-keymap/list-keymap.ts
- packages/editor/src/core/extensions/extensions.tsx
- packages/editor/src/core/extensions/image/extension.tsx
- packages/editor/src/core/extensions/image/image-extension-without-props.tsx
- packages/editor/src/core/extensions/image/image-resize.tsx
- packages/editor/src/core/extensions/image/utilities/insert-line-above-image.ts
- packages/editor/src/core/extensions/image/utilities/insert-line-below-image.ts
- packages/editor/src/core/extensions/keymap.tsx
- packages/editor/src/core/extensions/mentions/extension.tsx
- packages/editor/src/core/extensions/mentions/mention-node-view.tsx
- packages/editor/src/core/extensions/mentions/mentions-without-props.tsx
- packages/editor/src/core/extensions/read-only-extensions.tsx
- packages/editor/src/core/extensions/slash-commands.tsx
- packages/editor/src/core/extensions/table/table/table-controls.ts
- packages/editor/src/core/extensions/table/table/table.ts
- packages/editor/src/core/extensions/table/table/utilities/create-table.ts
- packages/editor/src/core/extensions/table/table/utilities/delete-table-when-all-cells-selected.ts
- packages/editor/src/core/extensions/typography/index.ts
- packages/editor/src/core/helpers/editor-commands.ts
- packages/editor/src/core/helpers/insert-content-at-cursor-position.ts
- packages/editor/src/core/hooks/use-editor.ts
- packages/editor/src/core/plugins/image/utils/placeholder.ts
- packages/editor/src/core/types/editor.ts
1. Added import order rules to the editor package.
2. Updated the files with incorrect import order.
> fix: added import order rules to the editor package

- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/[pageId]/page.tsx
- web/core/components/pages/pages-list-view.tsx
Added `workspaceSlug` and `projectId` check to the SWR call.
> chore: add extra check to fetch pages list and page details

- web/core/components/workspace/sidebar/projects-list-item.tsx
- web/core/components/workspace/sidebar/projects-list.tsx
- web/core/components/workspace/sidebar/quick-actions.tsx
- web/core/components/workspace/sidebar/workspace-menu.tsx
1. Updated the `Add project` button UI.
2. Show `Favorites` and `My projects` accordion chevron to guest and viewers as well.
3. Show the `New issue` button to guests and viewers as well.
4. Store the open status of workspace menu in local storage.
> [WEB-1716] chore: sidebar improvements for guests/viewers

- packages/types/src/views.d.ts
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/views/(list)/header.tsx
- web/core/components/views/applied-filters/access.tsx
- web/core/components/views/applied-filters/index.tsx
- web/core/components/views/applied-filters/root.tsx
- web/core/store/global-view.store.ts
- web/core/store/project-view.store.ts
- web/helpers/project-views.helpers.ts
This PR contains necessary changes for advanced views
> [WEB-1255] chore: necessary changes for advanced views

- apiserver/plane/bgtasks/dummy_data_task.py
fix: 
- dummy data script to create Pages without project.
**Ticket** - [[WEB - 1750]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/550faa81-d847-4bf4-b905-69bf023c0239)
> [WEB - 1750] fix: dummy data script to create Pages without project

- apiserver/plane/app/views/user/base.py
- apiserver/plane/authentication/adapter/base.py
- apiserver/plane/authentication/views/app/check.py
- apiserver/plane/authentication/views/app/email.py
- apiserver/plane/authentication/views/app/magic.py
- apiserver/plane/authentication/views/space/check.py
- apiserver/plane/authentication/views/space/email.py
- apiserver/plane/authentication/views/space/magic.py
- apiserver/plane/bgtasks/user_activation_email_task.py
- apiserver/plane/bgtasks/user_deactivation_email_task.py
- apiserver/plane/utils/host.py
- apiserver/templates/emails/user/user_activation.html
- apiserver/templates/emails/user/user_deactivation.html
- send email to the user when the account has been deactivated.
- re-activate the account when the user signs in again.
- send email to the user when the account has been deactivated.
**Ticket** - [[WEB - 1742]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/935658c9-1854-407a-a74b-ea6325731fa0)
> [WEB - 1742] chore: user activation and deactivation workflow

- web/app/onboarding/page.tsx
> [WEB-1748] fix: onboarding infinite loading issue.

- web/ce/components/views/access-controller.tsx
- web/ce/components/views/filters/access-filter.tsx
- web/core/components/common/access-field.tsx
- web/core/components/issues/issue-layouts/filters/applied-filters/roots/global-view-root.tsx
- web/core/components/issues/issue-layouts/filters/applied-filters/roots/project-view-root.tsx
- web/core/components/pages/modals/page-form.tsx
- web/core/components/views/filters/filter-selection.tsx
- web/core/components/views/form.tsx
- web/core/components/workspace/views/form.tsx
- web/ee/components/views/access-controller.tsx
- web/ee/components/views/filters/access-filter.tsx
This PR contains core changes required to enable Advanced views
> [WEB-1255] chore: make core changes for Advanced views

- web/core/store/project-view.store.ts
This Minor PR changes the default filter properties of project views.
> [WEB-1255] chore: modify default filter options for views

- packages/editor/src/core/extensions/enter-key-extension.tsx
- packages/editor/src/core/types/editor.ts
- space/core/components/editor/lite-text-editor.tsx
- space/core/components/editor/toolbar.tsx
- space/core/components/issues/peek-overview/comment/add-comment.tsx
- space/core/components/issues/peek-overview/comment/comment-detail-card.tsx
- web/core/components/editor/lite-text-editor/lite-text-editor.tsx
- web/core/components/issues/issue-detail/issue-activity/comments/comment-card.tsx
- web/core/components/issues/issue-detail/issue-activity/comments/comment-create.tsx
- web/core/components/workspace/sidebar/projects-list-item.tsx
- web/core/components/workspace/sidebar/projects-list.tsx
- web/core/components/workspace/sidebar/workspace-menu.tsx
Pressing `Cmd/Ctrl + Enter` in a comment box now enters a new line instead of submitting the form.
> [WEB-1689] fix: command enter submits the form

- web/app/profile/security/page.tsx
> [WEB-1802] chore: remove redirection logic from security settings page if the user password is not setup.

- web/core/components/issues/peek-overview/view.tsx
> [WEB-1810] style: fix issue with screen height on all layouts when peek overview is opened.

- web/core/store/issue/issue-details/link.store.ts
This PR includes a fix for issue link count mutation issue.
> [WEB-1822] fix: issue link count mutation

- packages/ui/src/dropdowns/custom-menu.tsx
- packages/ui/src/dropdowns/helper.tsx
- Added open-on-hover functionality to the custom menu.
> [WEB-1821] dev: open dropdown on hover

- apiserver/plane/app/serializers/notification.py
- apiserver/plane/app/views/notification/base.py
- packages/types/src/workspace-notifications.d.ts
- web/app/[workspaceSlug]/(projects)/notifications/page.tsx
- web/core/components/inbox/content/inbox-issue-header.tsx
- web/core/components/inbox/content/root.tsx
- web/core/components/issues/peek-overview/loader.tsx
- web/core/components/workspace-notifications/notification-app-sidebar-option.tsx
- web/core/components/workspace-notifications/sidebar/header/root.tsx
- web/core/components/workspace-notifications/sidebar/loader.tsx
- web/core/components/workspace-notifications/sidebar/notification-card/item.tsx
- web/core/components/workspace-notifications/sidebar/notification-card/options/archive.tsx
- web/core/components/workspace-notifications/sidebar/root.tsx
- web/core/store/notifications/notification.ts
- web/core/store/notifications/workspace-notifications.store.ts
- web/core/store/user/user-membership.store.ts
This PR integrates inbox issues into the notification peek view and handles the increment and decrement of unread notifications, providing a comprehensive and interactive notification experience.
> [WEB-1792] chore: integrated inbox issue in notification peek view and handled increment/decrement of unread notifications

- web/app/[workspaceSlug]/(projects)/workspace-views/[globalViewId]/page.tsx
- web/core/components/issues/issue-layouts/roots/all-issue-layout-root.tsx
This Fix adds an empty state when view is not available.
https://github.com/makeplane/plane/assets/71900764/e21317e6-1681-4b15-ae2d-0cdcd59567e1
> [WEB-1798] fix : Add empty state when view is not available

- web/core/components/inbox/content/inbox-issue-header.tsx
This PR fixes the redirection issue that occurs when changing the status of an inbox issue in notifications, ensuring proper navigation and user experience.
1. inbox issue header
> [WEB-1792] fix: handled redirection issue when we change the status of the inbox issue in the notification

- packages/editor/src/core/components/links/link-edit-view.tsx
Link preview properly updates the links now on editing an existing link!
> [WEB-1823] fix: update link view now updates the link

- web/core/components/command-palette/command-palette.tsx
> [WEB-1801] fix: avoid opening shortcut guide on editors / input elements.

- apiserver/plane/app/serializers/workspace.py
- apiserver/plane/app/views/workspace/base.py
- apiserver/plane/db/models/workspace.py
fix: 
- update validation on serializer
- add validation on model level
- add validation in workspace slug check endpoint
**Ticket** - [[WEB - 1838]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/c783705e-493c-4841-be82-81b2d436eed2)
> [WEB - 1838]fix: workspace slug validation

- web/app/[workspaceSlug]/(projects)/profile/[userId]/mobile-header.tsx
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/cycles/(detail)/header.tsx
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/cycles/(detail)/mobile-header.tsx
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/draft-issues/header.tsx
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/issues/(list)/header.tsx
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/issues/(list)/mobile-header.tsx
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/modules/(detail)/header.tsx
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/modules/(detail)/mobile-header.tsx
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/views/(detail)/[viewId]/header.tsx
- web/app/[workspaceSlug]/(projects)/workspace-views/header.tsx
- web/core/components/issues/archived-issues-header.tsx
- web/core/components/profile/profile-issues-filter.tsx
- web/helpers/filter.helper.ts
This PR includes the following updates:
- Addition of the isIssueFilterActive helper function.
- Implementation of the isIssueFilterActive function wherever necessary.
| ![WEB-1715 (2)](https://github.com/makeplane/plane/assets/121005188/6cfe1a2e-3d42-4b1c-ae91-35dd4dd1314f) | ![WEB-1715 (1)](https://github.com/makeplane/plane/assets/121005188/092ba57a-eab8-422a-aebb-f0a19b9a2d09) |
> [WEB-1715] chore: issue filters indicator enhancement

- apiserver/plane/db/models/issue.py
fix: 
- issue pagination listing when the list contains inbox issues causing a KeyError
**Ticket** - [[WEB - 1841]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/59775e7b-1fbe-4d62-9e17-3d0b53d603a4)
> [WEB - 1841] fix: issue pagination listing

- web/core/components/issues/issue-detail/module-select.tsx
- web/core/components/issues/issue-detail/root.tsx
- web/core/components/issues/peek-overview/root.tsx
- web/core/store/issue/archived/issue.store.ts
- web/core/store/issue/cycle/issue.store.ts
- web/core/store/issue/draft/issue.store.ts
- web/core/store/issue/helpers/base-issues.store.ts
- web/core/store/issue/issue-details/issue.store.ts
- web/core/store/issue/issue-details/root.store.ts
- web/core/store/issue/module/issue.store.ts
- web/core/store/issue/profile/issue.store.ts
- web/core/store/issue/project-views/issue.store.ts
- web/core/store/issue/project/issue.store.ts
- web/core/store/issue/workspace/issue.store.ts
This PR fixes the mutation issue of issues in layouts when issues are updated in issue peek overview
https://github.com/makeplane/plane/assets/71900764/d822e265-afc3-44ad-843f-aeee3355fcff
> [WEB-1818] fix: issue changes done in Peek overview to reflect in the issue list boards

- web/core/components/editor/lite-text-editor/lite-text-editor.tsx
Updated the placeholder of the comment box to `Add comment...`
| <img width="740" alt="image" src="https://github.com/makeplane/plane/assets/65252264/eda94465-b9de-4a2b-bf6c-c5d5a629cc1c"> | <img width="740" alt="image" src="https://github.com/makeplane/plane/assets/65252264/7d7265c8-ba97-4a5b-a63a-3e022f4a2521"> |
> [WEB-1857] chore: update comment box placeholder

- web/core/components/issues/issue-detail/links/links.tsx
This PR include fix for issue peek view link list ui.
> [WEB-1858] fix: issue peek view link list ui

- web/core/components/workspace-notifications/notification-app-sidebar-option.tsx
- web/core/components/workspace-notifications/sidebar/header/root.tsx
- web/core/store/issue/helpers/base-issues.store.ts
- web/core/store/notifications/workspace-notifications.store.ts
This PR updates the UI notification tooltip on the header and app sidebar, enhancing the visual presentation and usability of notifications.
1. App sidebar
2. Notification Header
> [WEB-1792] chore: updated UI notification tooltip on header and app sidebar

- web/core/store/issue/helpers/base-issues.store.ts
fix Build errors due to conflicting PRs
> [WEB-1953] fix: Build errors due to conflicting PRs

- apiserver/plane/utils/analytics_plot.py
chore: 
- This pull request fixes the issue of rendering custom analytics charts at the project level. Now, the user can select the estimate on the x-axis.
Issue Link: [WEB-1868](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/94013101-a8b2-4602-979e-cec2f8dd4382/)
> [WEB-1868] chore: custom analytics chart

- web/core/components/modules/analytics-sidebar/root.tsx
This PR includes a fix for the module sidebar scroll issue.
| ![Before (1)](https://github.com/makeplane/plane/assets/121005188/cd984285-ce04-4707-b0e7-1f50d7792515) | ![After (1)](https://github.com/makeplane/plane/assets/121005188/54baaa13-4025-4436-969d-4424f5720dbf) |
> [WEB-1875] fix: module sidebar scroll

- packages/ui/src/avatar/avatar.stories.tsx
- packages/ui/src/index.ts
- packages/ui/src/popovers/index.ts
- packages/ui/src/popovers/popover-menu.stories.tsx
- packages/ui/src/popovers/popover-menu.tsx
- packages/ui/src/popovers/popover.stories.tsx
- packages/ui/src/popovers/popover.tsx
- packages/ui/src/popovers/types.ts
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/settings/layout.tsx
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/settings/states/page.tsx
- web/core/components/project-states/create-update/form.tsx
This PR implements a new popover component in the UI package, providing a reusable and customizable UI element for displaying additional information or actions.
1. popover component in the packages
> [WEB-1878] ui: implementing popover component in a UI package

- web/core/components/issues/peek-overview/properties.tsx
- web/core/components/issues/peek-overview/view.tsx
- Added issue detail widgets to the issue peek overview.
| Media |
|--------|
| ![media](https://github.com/makeplane/plane/assets/121005188/2cf1e33c-7641-4cac-ac38-6186fdd66c92) |
> [WEB-1679] dev: issue details widgets added to issue peek overview

- web/core/components/issues/issue-detail/sidebar.tsx
- web/core/components/issues/peek-overview/properties.tsx
- Removed the "created by" tooltip from the issue peek overview and issue detail properties.
| ![1720 (1)](https://github.com/makeplane/plane/assets/121005188/9ea7de4f-58af-4162-8c68-d56e2f53ef1a)| ![1720 (2)](https://github.com/makeplane/plane/assets/121005188/7871ba3f-7a1f-4daf-8a76-6c9e8f6bab8f) |
> [WEB-1720] fix: created by tooltip removed

- web/core/components/command-palette/command-palette.tsx
- web/core/components/issues/issue-layouts/quick-action-dropdowns/all-issue.tsx
- web/core/components/issues/issue-layouts/quick-action-dropdowns/draft-issue.tsx
- web/core/components/issues/issue-modal/modal.tsx
- web/core/components/workspace/sidebar/quick-actions.tsx
- web/core/hooks/use-issue-layout-store.ts
This PR fixes the issue for issue creation by using the appropriate issue stores to create issues.
https://github.com/makeplane/plane/assets/71900764/20ccc4df-1a4b-4ebd-bca4-9a7e2e59ccc8
> [WEB-1890] fix: issue creation by using appropriate stores

- packages/types/src/workspace-notifications.d.ts
- web/app/[workspaceSlug]/(projects)/notifications/layout.tsx
- web/app/[workspaceSlug]/(projects)/notifications/page.tsx
- web/core/components/inbox/content/inbox-issue-header.tsx
- web/core/components/inbox/content/root.tsx
- web/core/components/issues/peek-overview/root.tsx
- web/core/components/issues/peek-overview/view.tsx
- web/core/components/workspace-notifications/sidebar/notification-card/item.tsx
- web/core/components/workspace-notifications/sidebar/root.tsx
- web/core/store/notifications/workspace-notifications.store.ts
This PR fixes the issue with tapping on notifications in the mobile view for the inbox issue and peek overview components, ensuring proper navigation and interaction.
1. Notification issue peek overview
2. Notification inbox issue peek overview
> [WEB-1889] fix: handled tapping on a notification in Notifications from mobile in inbox issue and issue peek overview component

- apiserver/plane/api/serializers/cycle.py
- apiserver/plane/api/views/cycle.py
- apiserver/plane/app/views/cycle/base.py
dev: 
- log issue activity when transferring issues from one cycle to another.
**Ticket** - [[WEB - 1888]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/2ee31e7f-dfdc-464b-b270-2b162f101e38)
> [WEB - 1888] dev: log issue activity when transferring issues from one cycle to another

- apiserver/plane/app/serializers/notification.py
- apiserver/plane/app/views/notification/base.py
- packages/types/src/workspace-notifications.d.ts
- web/app/[workspaceSlug]/(projects)/notifications/page.tsx
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/issues/(list)/header.tsx
- web/core/components/common/count-chip.tsx
- web/core/components/common/index.ts
- web/core/components/inbox/content/inbox-issue-header.tsx
- web/core/components/inbox/content/inbox-issue-mobile-header.tsx
- web/core/components/workspace-notifications/notification-app-sidebar-option.tsx
- web/core/components/workspace-notifications/sidebar/notification-card/item.tsx
- web/core/components/workspace-notifications/sidebar/root.tsx
- web/core/store/notifications/notification.ts
- web/core/store/notifications/workspace-notifications.store.ts
This PR addresses multiple enhancements and fixes, including mentions mutation, a UI fix for the notification badge on the app sidebar, and the integration of a back button for the inbox issue notification embed.
1. Workspace notification store
2. Notification store
3. inbox issue mobile header component
4.  Notification sidebar badge
> [WEB-1900] chore: mentions mutation, ui fix on app sidebar notification badge, and back button inbox issue notification embed

- ENV_SETUP.md
chore:
- updated environment variables for root and apiserver.
Issue Link: [WEB-1904](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/f5dd8551-8dd9-4044-adc4-5d8931e0f414/)
> [WEB-1904] chore: updated setup env

- apiserver/plane/db/migrations/0070_issuetype_issue_type.py
dev: 
- remove page version back migrations
> dev: remove page version back migrations

- space/core/components/views/auth.tsx
- web/app/accounts/forgot-password/page.tsx
- web/app/accounts/reset-password/page.tsx
- web/app/accounts/set-password/page.tsx
- web/app/page.tsx
- web/app/sign-up/page.tsx
This PR includes fix for the padding on the authentication screen.
| ![before](https://github.com/makeplane/plane/assets/121005188/6235a8b0-7e39-4026-9f0c-4c19143809e6) | ![after](https://github.com/makeplane/plane/assets/121005188/ba977994-12ea-43eb-9526-75d33df8e859) |
> [WEB-1513] chore: auth screen layout padding

- web/core/components/views/views-list.tsx
[[WEB-1891]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/0d306a90-2e1c-42a6-aee6-1b20363f4d21)
> [WEB-1891] fix: empty state for view page fixed

- packages/types/src/issues/issue.d.ts
- packages/ui/src/collapsible/collapsible-button.tsx
- web/core/components/issues/issue-detail-widgets/attachments/quick-action-button.tsx
- web/core/components/issues/issue-detail-widgets/attachments/root.tsx
- web/core/components/issues/issue-detail-widgets/links/quick-action-button.tsx
- web/core/components/issues/issue-detail-widgets/links/root.tsx
- web/core/components/issues/issue-detail-widgets/relations/quick-action-button.tsx
- web/core/components/issues/issue-detail-widgets/relations/root.tsx
- web/core/components/issues/issue-detail-widgets/sub-issues/quick-action-button.tsx
- web/core/components/issues/issue-detail-widgets/sub-issues/root.tsx
- web/core/components/issues/issue-detail/links/create-update-link-modal.tsx
- web/core/components/issues/issue-detail/links/link-detail.tsx
- web/core/components/issues/issue-detail/links/link-item.tsx
- web/core/components/issues/issue-detail/links/root.tsx
- web/core/store/issue/issue-details/root.store.ts
- Updated the border color of the collapsible button.
- Modified the onClose function for the issue link modal.
- Added interaction for the issue detail widget.
> [WEB-1925] dev: issue detail widget enhancement

- apiserver/plane/app/views/issue/base.py
chore: 
- This pull request fixes the issue with duplication of assignees and labels activity when adding or removing an assignee or labels.
Issue Link: [WEB-1909](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/1afd4b49-4c57-4b91-af58-d0de40e27631/)
> [WEB-1909] chore: removed duplication of assignee and label activity

- apiserver/plane/settings/common.py
- web/core/components/issues/issue-detail-widgets/action-buttons.tsx
- web/core/components/issues/issue-detail-widgets/attachments/root.tsx
- web/core/components/issues/issue-detail-widgets/index.ts
- web/core/components/issues/issue-detail-widgets/issue-detail-widget-modals.tsx
- web/core/components/issues/issue-detail-widgets/links/quick-action-button.tsx
- web/core/components/issues/issue-detail-widgets/links/root.tsx
- web/core/components/issues/issue-detail-widgets/links/title.tsx
- web/core/components/issues/issue-detail-widgets/relations/quick-action-button.tsx
- web/core/components/issues/issue-detail-widgets/relations/root.tsx
- web/core/components/issues/issue-detail-widgets/relations/title.tsx
- web/core/components/issues/issue-detail-widgets/root.tsx
- web/core/components/issues/issue-detail-widgets/sub-issues/quick-action-button.tsx
- web/core/components/issues/issue-detail-widgets/sub-issues/root.tsx
- web/core/components/issues/issue-detail-widgets/sub-issues/title.tsx
- web/core/store/issue/issue-details/root.store.ts
- Fixed the issue with the detail widget modal where the spacebar key was not working when the modal was opened from a collapsible title.
- Moved the modal to the widget component root and performed code refactoring.
- Default open widget updated.
> [WEB-1921] fix: issue widgets modal and code refactor

- web/app/onboarding/page.tsx
- web/core/lib/wrappers/authentication-wrapper.tsx
> [WEB-1929] chore: improve finishOnboarding logic to handle case where user profile setup is done and user already has a workspace.

- web/core/components/issues/issue-modal/form.tsx
- Added handleFormChange to the start and due date properties in the issue form.
- Fixed a bug where changing properties of the last draft issue did not work as expected.
| Scenario One |
|--------|
| ![Condition ONE](https://github.com/user-attachments/assets/e5724b48-ef78-4411-95fb-56fac79de1b9) |
| Scenario Two |
|--------|
| ![Condition TWO](https://github.com/user-attachments/assets/52f0e5c9-84c3-4874-b6dc-e52f2b8c4057) |
| Scenario Three |
|--------|
| ![Condition THREE](https://github.com/user-attachments/assets/5afa4712-b779-4beb-95c3-cb6a35035b12) |
> [WEB-1902] fix: last draft issue properties

- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/cycles/(detail)/[cycleId]/page.tsx
- web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/modules/(detail)/[moduleId]/page.tsx
- web/core/components/cycles/analytics-sidebar/root.tsx
- web/core/components/modules/analytics-sidebar/root.tsx
This PR includes the following updates:
- Fixed the scrolling issue in the module and cycle sidebar.
| ![WEB-1875 (2)](https://github.com/user-attachments/assets/741e3efb-226d-4742-9ffc-817d29b496b5) | ![WEB-1875 (1)](https://github.com/user-attachments/assets/f34cd32e-d3e8-4e8e-992e-73f6426cd623) |
> [WEB-1875] fix: module and cycle sidebar scroll

- web/core/components/exporter/guide.tsx
- Added validation for export issues in workspace settings. Previously, the export option was enabled even when no projects were available.
| ![Before (2)](https://github.com/user-attachments/assets/f0f8f988-6300-4a7b-b4dc-220696d8cb76) | ![After (2)](https://github.com/user-attachments/assets/6ce4f9d9-dfe8-40e4-89a1-8d04843a7c92) |
> [WEB-1834] fix: export issues validation

- space/core/components/issues/peek-overview/comment/add-comment.tsx
- Updated the issue comment placeholder in the Space app.
| ![before](https://github.com/user-attachments/assets/ff3e4872-bc99-46ae-a9b9-d31d655d4b1a) | ![after](https://github.com/user-attachments/assets/9b9ebf6a-f8f7-43cf-92fa-dce88b86c5bd) |
> [WEB-1869] chore: space app issue comment placeholder updated

- apiserver/plane/db/models/issue.py
fix: 
- added atomicity and removed the signal-based approach for saving the sequence ID in the database, ensuring that all database operations are completed successfully before any changes are committed, thus providing consistency and reliability.
Issue Link: [WEB-1945](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/14685cef-36fb-40f7-83af-6f13987b4975/)
> [WEB-1945] fix: added atomic transactions for sequence id in issue

- packages/ui/src/index.ts
- packages/ui/src/tables/index.ts
- packages/ui/src/tables/table.stories.tsx
- packages/ui/src/tables/table.tsx
- packages/ui/src/tables/types.ts
- Implemented dynamic table component on plane UI library
> [WEB-1954] chore: implemented table component in ui library

- web/core/components/issues/issue-detail-widgets/attachments/root.tsx
- web/core/components/issues/issue-detail-widgets/links/root.tsx
- web/core/components/issues/issue-detail-widgets/relations/root.tsx
- web/core/components/issues/issue-detail-widgets/sub-issues/root.tsx
- Resolved the width issue with the issue detail widget collapsible title.
> [WEB-1921] fix: isssue widgets collapsible ui

- web/core/components/issues/issue-detail/label/create-label.tsx
- web/core/components/issues/issue-detail/label/root.tsx
> [WEB-1957] fix: exception error on label creation for unauthorized users.

- space/core/components/account/auth-forms/password.tsx
- web/core/components/account/auth-forms/password.tsx
- This PR resolves the issue that the user is not able to log in via one password
1. Web app auth password form
2. Space app auth password form
> [WEB-1958] fix: handled the auto form submit for all authenticators

- web/core/components/exporter/export-modal.tsx
- Fixed project select dropdown option overflow and width issue.
| ![before](https://github.com/user-attachments/assets/1de42bb6-e4b0-45f3-8e14-2f090709cd54) | ![after](https://github.com/user-attachments/assets/01512116-fe36-4952-a1a8-4eb2cf9dea25) |
> [WEB-1952] fix: issues export project select dropdown

- web/core/components/core/activity.tsx
- web/core/components/inbox/modals/create-edit-modal/create-root.tsx
- web/core/components/inbox/modals/delete-issue-modal.tsx
- web/core/components/issues/issue-detail/issue-activity/activity/actions/inbox.tsx
- web/core/store/inbox/project-inbox.store.ts
- Updated intake activity and toast alert messages.
> [WEB-1730] chore: project intake toast and activity message

- packages/ui/src/modals/constants.ts
- packages/ui/src/modals/modal-core.tsx
- turbo.json
- web/ce/components/workspace/edition-badge.tsx
- web/ce/components/workspace/upgrade/index.tsx
- web/ce/components/workspace/upgrade/one-plan-upgrade.tsx
- web/ce/components/workspace/upgrade/paid-plans-upgrade-modal.tsx
- web/ce/components/workspace/upgrade/pro-plan-upgrade.tsx
- web/core/hooks/use-app-router.tsx
> [WEB-1960]: chore: upgrade to plane paid plans modal.

- web/app/[workspaceSlug]/(projects)/sidebar.tsx
- web/ce/components/projects/settings/useProjectColumns.tsx
- web/ce/components/workspace/settings/useMemberColumns.tsx
- web/core/components/project/member-list-item.tsx
- web/core/components/workspace/settings/members-list-item.tsx
**Changes**
- Made sidebar collapsible for smaller screens by default
[[WEB-1918]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/e325c403-c981-4eef-9d9e-83d46e65369d)
| ![before](https://planefs.s3.amazonaws.com/cd4ab5a2-1a5f-4516-a6c6-8da1a9fa5be4/67208bba37984df58e55b9bfd3f20a64-Screenshot_2024-07_Ac5EZ3g.png) | ![after](
> [WEB-1918]: Fix/sidebar collapse issue

- web/core/components/inbox/sidebar/root.tsx
**Changes**
Fixed the relaod issue on switching tabs or adding a new issue
[[WEB-647] ](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/a3391ce0-c811-45c0-9d50-91908eb7187e)
> [WEB-647] fix: inbox dependency array fix

- web/ce/constants/issues.ts
- This PR resolves the issue activity components rendered on the issue peek overview and issue detail page
1. Issue activity constants
> [WEB-1990] fix: issue activity render enum keys update

- apiserver/plane/app/urls/page.py
- apiserver/plane/app/views/page/base.py
- web/core/services/page/project-page.service.ts
- web/core/store/pages/page.ts
chore:
- users can change the access of the page even though the page is locked.
Issue Link: [WEB-1985](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/a7a08323-cc7d-4d0b-931b-5cdc4114a788/)
> [WEB-1985] chore: page access control

- live/package.json
- live/src/core/config/redis-config.ts
- live/src/server.ts
- yarn.lock
Initialize a Redis client that accepts REDIS_URL and then pass it down to the Hocuspocus's Redis extension as it doesn't accept an URL!
> fix: initialize redis client and pass it to hocuspocus

- web/core/components/issues/filters.tsx
- web/core/components/project/filters.tsx
This PR adds missing Mobx observers to filter components to fix any issues that it causes.
> chore: Add missing Mobx observers to components

- apiserver/plane/app/views/project/base.py
fix: 
- only the admins can delete a project
> fix: only admins can delete a project

- web/core/components/inbox/modals/create-edit-modal/create-root.tsx
> fix: intake issue

- packages/types/src/de-dupe.d.ts
- packages/types/src/index.d.ts
- web/ce/components/de-dupe/duplicate-modal/index.ts
- web/ce/components/de-dupe/duplicate-modal/root.tsx
- web/ce/components/de-dupe/duplicate-popover/index.ts
- web/ce/components/de-dupe/duplicate-popover/root.tsx
- web/ce/components/de-dupe/index.ts
- web/ce/components/de-dupe/issue-block/button-label.tsx
- web/ce/components/de-dupe/issue-block/index.ts
- web/ce/hooks/use-debounced-duplicate-issues.tsx
- web/core/components/inbox/content/issue-root.tsx
- web/core/components/inbox/modals/create-modal/create-root.tsx
- web/core/components/inbox/modals/create-modal/modal.tsx
- web/core/components/issues/archive-issue-modal.tsx
- web/core/components/issues/delete-issue-modal.tsx
- web/core/components/issues/issue-detail/main-content.tsx
- web/core/components/issues/issue-modal/base.tsx
- web/core/components/issues/issue-modal/draft-issue-layout.tsx
- web/core/components/issues/issue-modal/form.tsx
- web/core/components/issues/peek-overview/issue-detail.tsx
- web/helpers/editor.helper.ts
This PR includes de-dupe code splitting changes.
> chore: code refactoring

- web/core/local-db/storage.sqlite.ts
This PR fixes the issue of fetching with change in filters by passing down the abort config.
> [WEB-2734] fix: Issues fetching with change in filters

- apiserver/plane/app/views/project/base.py
chore: 
- this pull request resolves the issue for enabling intake from project settings
> chore: enable intake from project settings

- web/ce/constants/index.ts
- web/ce/constants/page.ts
- web/core/components/pages/dropdowns/actions.tsx
- web/core/components/pages/editor/header/options-dropdown.tsx
- web/core/services/page/project-page.service.ts
- web/core/store/pages/project-page.store.ts
- web/ee/constants/page.ts
This PR adds the missing page actions and permission checks.
> [PE-97] refactor: page actions

- web/core/hooks/use-page-operations.ts
This PR fixes the `Open in new tab` action for pages.
> fix: page open in new tab action

- packages/i18n/src/locales/en/translations.json
- web/app/accounts/forgot-password/page.tsx
- web/app/accounts/reset-password/page.tsx
- web/app/accounts/set-password/page.tsx
- web/app/page.tsx
- web/app/profile/security/page.tsx
- web/app/profile/sidebar.tsx
- web/app/sign-up/page.tsx
- web/core/components/account/auth-forms/auth-header.tsx
- web/core/components/account/auth-forms/auth-root.tsx
- web/core/components/account/auth-forms/email.tsx
- web/core/components/account/auth-forms/forgot-password-popover.tsx
- web/core/components/account/auth-forms/password.tsx
- web/core/components/account/auth-forms/unique-code.tsx
- web/core/components/account/password-strength-meter.tsx
- web/core/components/onboarding/profile-setup.tsx
- web/core/components/profile/form.tsx
- web/core/components/workspace/sidebar/dropdown.tsx
Authentication related translations
> refactor: authentications related translations

- web/core/components/modules/form.tsx
- web/core/components/project/search-projects.tsx
> fix: language support

- web/core/components/global/product-updates/modal.tsx
- Increased the width of the “What’s New” modal.
[[WEB-3390]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/a47fadd2-f98f-47c5-813d-37794697db64/)
> [WEB-3390] chore: whats new modal improvement

- packages/editor/src/core/extensions/custom-image/components/image-block.tsx
This PR adds the missing node id check to the image upload status component.
> regression: add node id check for image upload status

- README.md
This PR updates the dub.sh links in the README file to ensure they point to the correct URLs.
#6828
> docs: updated links in README.md file

- apiserver/plane/api/views/intake.py
- apiserver/plane/app/views/intake/base.py
- apiserver/plane/db/models/intake.py
This PR will set source value as IN_APP as default for intake issues.
> [WEB-3930] chore: set IN_APP as default source value for intake issue

- web/core/components/empty-state/detailed-empty-state-root.tsx
fix: broken detailed empty state layout
before 
after
> [WEB-4092] fix:broken detailed empty state layout

- .github/workflows/build-branch.yml
- admin/package.json
- apiserver/requirements/base.txt
- deploy/selfhost/README.md
- deploy/selfhost/install.sh
- deploy/selfhost/restore-airgapped.sh
- deploy/selfhost/restore.sh
- space/package.json
- web/package.json
- yarn.lock
- Updated API service startup check to use HTTP requests instead of logs.
- Enhanced backup and restore scripts for containerized data.
- Upgraded Next.js version.
- Upgraded Django version.
> release: v0.26.1

- packages/types/src/project/projects.d.ts
- web/core/store/member/base-project-member.store.ts
> fix: build errors related to project member list

- packages/logger/.eslintrc.js
- packages/logger/package.json
- packages/logger/tsup.config.ts
Adding tsup config to logger package. Enable build processing.
> feat: adding build process to logger package using tsup

- web/ce/components/projects/settings/intake/header.tsx
This update removes the unwanted border for header in Intake
> [WEB-4416]fix: Unnecessary border on Intake header

- README.md
> Updated README images

- packages/ui/src/tabs/tab-list.tsx
- packages/ui/src/tabs/tabs.tsx
- yarn.lock
> Feat base UI tabs
