makeplane/plane

web/components/project/sidebar-list-item.tsx
web/store/inbox/inbox_issue.store.ts

1. There is an issue where updating any inbox issue does not reflect the changes in the sidebar, and the count of pending issues in the inbox is not accurately rendered.
1. I have made the necessary adjustments to ensure that it functions as expected.

[WEB-462] fix: inbox mutation

---

web/pages/[workspaceSlug]/workspace-views/[globalViewId].tsx

**Problem:**
The tab title is coming as  `<Workspace Name> - Views` for the global view detail page.
**Improvement:**
A specific active view name should be there: `<Workspace Name> - <View Name>`
**Before:**
**After:**
https://github.com/makeplane/plane/assets/94619783/5f30eddc-8bf3-4adc-b54f-b2712b5bc5d0
This PR is attached to [WEB-472](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/e27fa535-b873-4441-bb26-b683236ee5ab)

[WEB-472] fix: Page title for global view

---

web/components/issues/issue-layouts/calendar/calendar.tsx
web/components/issues/issue-layouts/calendar/dropdowns/options-dropdown.tsx
web/components/issues/issue-layouts/calendar/week-days.tsx
web/components/issues/issue-layouts/calendar/week-header.tsx
web/store/issue/issue_calendar_view.store.ts

1. Layout change is not working in the calendar layout inside cycles and modules.
2. When clicking on the `Today` button in the week layout, a week ahead of the current week is being displayed.
1. Fixed update layout handler, the function required `cycleId`/`moduleId` as a param which was missing.
2. Fixed the logic to display all days of the current week, which was always rendering a week ahead of the desired week.
https://github.com/makeplane/plane/assets/65252264/a9de4468-3803-4fe6-b798-5967c3f6cd26

[WEB-474]: Layout change not working in cycles and modules

---

web/components/issues/title-input.tsx

This PR addresses and resolves the overflow issue encountered in the titles of issues displayed in the issue peek overview and the issue detail page. The fix ensures that long-issue titles are properly handled, preventing text overflow and ensuring that titles are displayed cleanly and consistently across the platform.

[WEB-479]: rendering issue title without overflow problem in issue peekoverview

---

web/components/views/view-list-item.tsx
web/components/workspace/views/default-view-list-item.tsx
web/components/workspace/views/view-list-item.tsx

This PR simplifies the UI by removing icons from the views at both the workspace and project levels. 
The primary goal is to increase the number of list items visible on the screen, thereby improving user experience by enabling users to view more of their projects or workspaces at a glance. This change is aimed at streamlining navigation and making the interface more efficient for users.
Screenshots:
| Old screenshot | New Screenshot |
| <img width="2282" alt="Screenshot 2024-02-21 at 1 15 27 PM" src="https://github.com/makeplane/plane/assets/28592219/569f5d49-bfc4-44a5-af81-bfc7769ecab1"> | <img width="2282" alt="Screenshot 2024-02-21 at 1 15 38 PM" src="https://github.com/makeplane/plane/assets/28592219/c1584de4-029c-49e1-a463-89b6a1bf138a"> |

[WEB-396] fix: removed view icons from workspace and project views list

---

web/components/issues/sub-issues/root.tsx

This PR addresses the requirement to remove `Add sub-issues` button from the bottom part when sub-issues are available as we already have the same buttons on top.
This PR is linked to [WEB-464](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/7ed71e98-02c0-4c4d-8e7f-5df7d2dfbf22)

[WEB-464] improvement: remove `add sub-issues` button from the bottom if sub-issues are available.

---

web/constants/issue.ts
web/store/issue/workspace/filter.store.ts

- Users are unable to view sub-issues in the global view of issues.
- To resolve this issue, I have implemented a toggle option to display sub-issues in the filter menu.
---
This PR is linked to [[WEB-456]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/5a443a21-5f92-4aa9-8194-70ae511f0320).
---

[WEB-456] chore: display sub issues option added in global view issues

---

web/components/cycles/transfer-issues.tsx

In this PR, I've implemented validation for the transfer issue button when the cycle is completed. If an issue from a completed cycle has already been transferred with a captured snapshot, the user is now prevented from transferring it again.
This PR is linked to [[WEB-461]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/81392d2d-59ef-4b56-8e3d-c5088d695cbe).

[WEB-461] chore: issue transfer validation added for completed cycle

---

apiserver/plane/bgtasks/email_notification_task.py

[WEB-457](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/9917a4ad-e531-46fb-ad25-99da7cd18711)
fix:
- duplicate sends for email notification by placing a lock on redis. For reference see [here](https://docs.celeryq.dev/en/stable/tutorials/task-cookbook.html).

[WEB-457] fix: email notification duplicates

---

packages/editor/document-editor/src/ui/extensions/widgets/issue-embed-suggestion-list/issue-suggestion-renderer.tsx

- When the length of the issue is too long, the issue title gets cut off in the issue suggestion dropdown within the issue embed on Page.
- I have addressed this issue and made necessary adjustments to improve its appearance.
| ![isssue-suggestion-before](https://github.com/makeplane/plane/assets/121005188/28e34a9f-2984-4ebb-8d6f-5230a850adf0) |  ![isssue-suggestion-after](https://github.com/makeplane/plane/assets/121005188/f6b33f6e-7e63-4066-9dc9-92d68aea32e3) |

[WEB-483] chore: issue embed suggestion dropdown improvement

---

web/components/issues/issue-layouts/properties/all-properties.tsx
web/components/issues/issue-layouts/spreadsheet/columns/sub-issue-column.tsx
web/components/issues/sub-issues/root.tsx

This PR addresses the requirement for redirection to the issue detail page upon clicking the sub-issue count property in list, kanban, and spreadsheet layouts.
[scrnli_2_21_2024_6-10-16 PM.webm](https://github.com/makeplane/plane/assets/33979846/395b5882-6f73-41f8-ac05-4f7bca44fea5)
The PR is linked to [WEB-465](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/8b825d23-144a-4597-973a-71a2b0d0bfbf)

[WEB-465] improvement: redirect to issue detail on click on the sub-issue count property.

---

.github/workflows/build-test-pull-request.yml

- The Pull Request removes redundant node cache responsible for taking significant time in `post-node-setup`, the cache will be handled by means of Artifacts in next Pull Request.

Removed redundant cache from `build-test-pull-request` action for more efficient builds

---

packages/ui/src/dropdowns/custom-select.tsx
web/components/core/filters/date-filter-select.tsx
web/components/modules/sidebar-select/select-status.tsx
web/components/project/create-project-modal.tsx
web/components/project/form.tsx
web/constants/project.ts

1. Project network title isn't descriptive enough, making it hard for the new users to differentiate between `Public` and `Private` projects.
1. Added a description alongside the network title.
1. Create project modal
****
2. Project general settings

[WEB-394]: Added a description to project network options

---

web/components/issues/issue-detail/module-select.tsx
web/store/issue/module/issue.store.ts

1. Upon removing the last module from the module select dropdown, an initial success alert is displayed. However, upon refreshing the page, the previous state is restored.
1. Identified a logic issue in update handling. Adjusted the logic to ensure proper functionality and addressed the issue accordingly.

[WEB-470] fix: module select fix

---

apiserver/plane/app/serializers/issue.py
apiserver/plane/app/urls/issue.py
apiserver/plane/app/views/cycle.py
apiserver/plane/app/views/inbox.py
apiserver/plane/app/views/issue.py
apiserver/plane/app/views/module.py
apiserver/plane/app/views/view.py
apiserver/plane/app/views/workspace.py
web/components/issues/description-input.tsx

[WEB - 467](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/497ca957-3d60-4879-98d0-372e06e4c02a)
perf:
- improve query performance for issue listing endpoints.
- use values instead of serializers wherever required.

[WEB - 467] perf: issues listing endpoints

---

apiserver/plane/app/views/workspace.py

- In the user profile page, a few projects are displayed that the user has already exited from.
- Resolved the bug by filtering the project member active filter

[WEB-491] chore: project filter updated

---

apiserver/plane/app/views/cycle.py

[[WEB - 492]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/e46866a9-7985-4370-bb8e-4cf8b0479645)
fix: 
- the endpoint was breaking due to removal of estimates from the serializer and queryset

[WEB - 492] fix: transfer cycle issues

---

web/components/issues/issue-detail/issue-activity/comments/comment-create.tsx

This PR addresses the requirement to disable submit button when there is no text in comment box.
[scrnli_2_22_2024_6-36-35 PM.webm](https://github.com/makeplane/plane/assets/33979846/9cb65df8-0fc4-4fb5-9a57-354244f15b01)
This PR is linked to [WEB-496](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/4346614a-d52f-418b-8a40-b929d10079c5)

[WEB-496] improvement: disable submit button when there is no text in comment box.

---

web/components/issues/select/label.tsx

Selected label indicator are not showing up on the issue create modal.
The indicator was already there but there was an overflow issues in the labels select component. Fixed it by changing the CSS.
This PR is linked to [WEB-494](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/50b7de51-33a2-4e33-ba94-42bd0143ce4e)

[WEB-494] fix: selected label indicator are not showing up on the issue create modal.

---

web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
web/components/issues/issue-layouts/kanban/headers/group-by-card.tsx

1. Kanban collapse/expand toggle button not working as expected.
1. Added the missing param to the kanban filter update handler.
1. Before-
https://github.com/makeplane/plane/assets/65252264/5e89466f-ee9a-4ff4-9fec-09eb5152315b
****
2. After-
https://github.com/makeplane/plane/assets/65252264/f18f2e9b-33a7-48ef-a9dd-8dce4f137a15

[WEB-521] fix: kanban column collapse toggle not working

---

web/components/headers/cycle-issues.tsx
web/components/headers/global-issues.tsx
web/components/headers/module-issues.tsx
web/components/headers/project-issues.tsx
web/components/headers/project-view-issues.tsx
web/components/issues/issue-layouts/spreadsheet/columns/header-column.tsx
web/components/issues/issue-layouts/spreadsheet/spreadsheet-header.tsx

1. Properties dropdown in all layouts overflow the header.
2. Spreadsheet column sort by dropdown overlaps with the app header.
4. Spreadsheet title column header does not stick to the top.
1. Resolved a z-indexing problem causing the overflow and conducted testing to ensure resolution wherever applicable.
2. Implemented necessary modifications to the spreadsheet layout to resolve the dropdown overlap with the app header.
3. Implemented necessary changes to the spreadsheet header component to address the issue of the title column header not sticking to the top.

[WEB-515] fix: spreadsheet layout overflow

---

packages/ui/src/control-link/control-link.tsx
web/components/issues/issue-layouts/calendar/issue-blocks.tsx
web/components/issues/issue-layouts/gantt/blocks.tsx
web/components/issues/issue-layouts/kanban/block.tsx
web/components/issues/issue-layouts/list/block.tsx
web/components/issues/issue-layouts/spreadsheet/issue-row.tsx

[WEB-501](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/b8b4cff6-c076-400b-b24a-ea6334366caa)
This PR disables peek overview actions for issues that are created quick add until the issue is confirmed from the server

[WEB-501] fix: disable peek overview for temporary issues until it is confirmed

---

web/helpers/issue.helper.ts

This PR contains a fix for the default priority state when we are creating an issue via quick-add in all layouts.

[WEB-531] fix: added default priority state in quick-add in issues layouts

---

web/constants/dashboard.ts

The Analytics tab highlight was not being shown when we switch between scope_and_demand` and `custom` tabs inside the page. This was due to the changes in the URL while switching between tabs as the highlight logic was checking for an exact match in the URL.
Updated the highlight logic to check if the URL includes `analytics` in it. 
This PR is linked to [WEB-536](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/1ed3978e-e5e4-4a6a-978b-7204b6dc747a)

[WEB-536] fix: analytics highlight while switching between `scope_and_demand` and `custom` tab.

---

packages/types/src/cycles.d.ts
web/components/analytics/custom-analytics/sidebar/sidebar-header.tsx
web/components/cycles/active-cycle-details.tsx
web/components/cycles/sidebar.tsx
web/components/project/sidebar-list.tsx

1. Cycle lead details are not visible.
1. Updated the `owned_by` key to `owned_by_id`.

[WEB-507] fix: cycle lead details not visible

---

web/components/issues/issue-layouts/properties/all-properties.tsx
web/components/issues/issue-layouts/spreadsheet/columns/sub-issue-column.tsx

`sub_issue`, `link`, `attachment` properties were visible in list and kanban layout even if their count is 0.  
Added the condition to hide these properties if there are not available. 
When clicked on sub-issue count, only redirect to issue detail page if sub issues are available.
This PR is linked to [WEB-540](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/544e0fd8-68cc-4bf1-aa27-112178d71352)

[WEB-540] fix: hide `sub_issue`, `link`, `attachment` property from list/ kanban view if their count is 0.

---

web/components/workspace/sidebar-dropdown.tsx

This PR is linked to [WEB-539](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/95ec7b16-c796-4f7b-824e-c6ae37768820)

[WEB-539] style: add background to user email in dashboard dropdown for better UX on workspace list scroll.

---

web/components/issues/issue-layouts/calendar/calendar.tsx
web/components/issues/issue-layouts/calendar/day-tile.tsx
web/components/issues/issue-layouts/calendar/week-header.tsx

[WEB-541](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/258a1776-6ac0-4b7b-92eb-83dd2bb78672)
fix:
- make the entire calendar scrollable along with header and make the header sticky to the top
- reduce min height of the day tile to not have scrollbar in the first place because without any issues
before with issues: 
after with issues:
before without issues: 
after without issues:

[WEB-541] fix: calendar misalignment because of scrollbar

---

web/components/project/sidebar-list.tsx

1. There's no right side padding for the sidebar projects.
1. Added right padding to the sidebar projects list.

[WEB-506] style: add right padding to sidebar projects list

---

web/components/workspace/views/header.tsx

1. An odd overflow animation occurs for the last views when choosing a view from the views navbar.
2. Upon reloading, the view header fails to reload to the current view.
1. Implemented specific conditions to prevent this undesired behavior.
2. Adjusted the dependencies array within the useEffect hook to ensure proper functionality upon reloading.

[WEB-517] bug: workspace view navbar scroll to view improvement

---

web/components/gantt-chart/chart/main-content.tsx

1. Gantt chart timeline is not occupying the complete available height.
1. Added `h-max` class to the scroll container.

[WEB-552] fix: Gantt chart scroll container height

---

web/components/dropdowns/cycle.tsx
web/components/issues/issue-layouts/properties/all-properties.tsx

1. In the issue layout, selecting a module with a longer title causes the UI to break and overflow.
1. This issue has been resolved by implementing a maximum width and truncte.
| ![2d596ef6-ac07-48c8-aa61-5367edbce9ff](https://github.com/makeplane/plane/assets/121005188/859cdc33-0199-46cf-8b58-e1acb0b06e61) | ![6aab0c4b-6ce8-41f2-914d-29c322cfa29d](https://github.com/makeplane/plane/assets/121005188/3d325b22-c46c-46e9-bbb9-ef54174710bb) |

[WEB-553] fix: cycle select dropdown issue layout overflow

---

web/components/issues/issue-detail/label/label-list-item.tsx

1. Longer label names overflow in the sidebar.
1. Resolve this problem by truncating longer label name.

[WEB-509] fix: issue sidebar label overflow

---

web/layouts/user-profile-layout/layout.tsx

1. The profile sidebar is not fully visible on smaller devices.
1. Addressed this issue by implementing necessary adjustments.
| ![856d8e614e644d1bae3035980307d22a-image](https://github.com/makeplane/plane/assets/121005188/c96d3c23-9b9f-45ff-9bc4-edba70a64767) | ![profile-sidebar-after](https://github.com/makeplane/plane/assets/121005188/5a3afc9c-3870-4acd-86bb-54754adeb7d2) |

[WEB-555] fix: profile sidebar layout

---

web/store/cycle.store.ts

1. Active cycles with today's end date were not displaying some actionable items in the issue layout.
1. After investigating, I found a problem with the cycle store regarding the filtering of completed cycles from the cycle map. Cycles that end today were not being taken into account. I've made the required adjustments to ensure it now operates as expected.

[WEB-556] fix: cycle store get completed cycle function updated

---

web/components/dashboard/widgets/assigned-issues.tsx
web/components/dashboard/widgets/created-issues.tsx
web/components/dashboard/widgets/issue-panels/issues-list.tsx

1. In the `Assigned issues` and `Created issues` dashboard widgets, on changing the filter from `None` to some other and then switching back to `None` resulted in a blank screen with no issues.
1. Updated the logic to save new tabs on filter change and handling selected tab logic manually.
Before fix-
https://github.com/makeplane/plane/assets/65252264/3e384c03-af0f-46b2-98d5-e18e2184e780
After fix-
https://github.com/makeplane/plane/assets/65252264/cff151d5-8752-4b54-b70c-a07691dfc992

[WEB-544] fix: dashboard issues widget tab rendering bug

---

web/components/issues/issue-detail/issue-activity/comments/comment-create.tsx
web/helpers/string.helper.ts
web/package.json
yarn.lock

1. Users are able to submit empty strings or paragraphs as comments.
1. Validation has been included to prevent this behavior.

[WEB-496] fix: issue comment 

---

web/components/gantt-chart/chart/views/month.tsx
yarn.lock

1. Even if there are a very few number of blocks in the Gantt chart, it was scrollable.
1. Updated the height of the background timeline.
Before fix-
https://github.com/makeplane/plane/assets/65252264/a1a32e03-25e2-4f5f-9ca4-9b4fa19b1ba8
After fix-
https://github.com/makeplane/plane/assets/65252264/884bfcd4-2d4f-441a-9eea-eba240307b6f

[WEB-552] fix: Gantt chart unnecessary overflow

---

web/components/dropdowns/cycle.tsx
web/components/dropdowns/estimate.tsx
web/components/dropdowns/member/project-member.tsx
web/components/dropdowns/module.tsx
web/components/dropdowns/priority.tsx
web/components/dropdowns/state.tsx
web/components/issues/issue-detail/label/select/label-select.tsx

1. Within the peek overview, when opening any search select dropdown and typing into the search input, pressing the escape key closes the peek overview instead of clearing the typed input.
1. Address this by implementing an input keydown handler that clears the typed input in the dropdown search, ensuring expected behavior.

[WEB-493] chore: custom search select input key down improvement

---

web/components/command-palette/command-modal.tsx

When the command / search box is visible, clicking outside should close it. But there are some places where its not closing even if its not part of the command / search box
This was due to some styling applied to the modal which was interrupting the close handlers. I have fixed those issues by implementing the required changes. 
Before
[4e10dbbff30f43628f586513bd0bd69c-20231220-0816-24.0513795.webm](https://github.com/makeplane/plane/assets/33979846/73885d41-f789-4196-8b0f-706b42bdcb19)
After
[scrnli_2_27_2024_5-39-38 PM.webm](https://github.com/makeplane/plane/assets/33979846/62231220-13c3-4f86-a147-77233e65aa5a)
This PR is linked to issue [WEB-127](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/38aa57a6-b6de-485e-9103-85b5d7699d86)

[WEB-127] fix: issue with command palette outside click detection.

---

web/components/issues/issue-detail/issue-activity/comments/comment-card.tsx

This PR addresses the validation of edited issue comments. Previously, users could edit existing comments and submit blank spaces, which was unintended behavior. I've implemented validation to prevent this issue.

[WEB-582] chore: issue comment edit validation

---

web/components/issues/peek-overview/view.tsx

This PR implements an enhancement for the issue peek overview. Previously, when the peek overview was open and a user attempted to close a toast alert, it inadvertently closed the peek overview, which was not the intended behavior. I have addressed this issue and made the necessary adjustments to ensure that it now functions as expected.

[WEB-580] chore: issue peek overview improvement

---

apiserver/plane/api/views/gpt.py
apiserver/requirements/base.txt

This PR adds support for the above mentioned LLMs using LiteLLM https://github.com/BerriAI/litellm/ 
LiteLLM is a lightweight package to simplify LLM API calls - use any llm as a drop in replacement for gpt-3.5-turbo. 
Example
```python
from litellm import completion
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["COHERE_API_KEY"] = "cohere key"
messages = [{ "content": "Hello, how are you?","role": "user"}]
response = completion(model="gpt-3.5-turbo", messages=messages)
response = completion(model="command-nightly", messages)
response = completion(model="claude-instant-1", messages=messages)
```

Add support for Claude-2, Cohere Llama2, CodeLlama, Azure OpenAI, Replicate LLMs (100+LLMs)

---

web/components/issues/issue-detail/sidebar.tsx
web/components/issues/issue-layouts/properties/all-properties.tsx
web/components/issues/issue-layouts/spreadsheet/columns/due-date-column.tsx
web/components/issues/issue-layouts/spreadsheet/columns/start-date-column.tsx
web/components/issues/peek-overview/properties.tsx
web/constants/spreadsheet.ts

1. Issue start date and due date have the same icon causing confusion.
1. Added new icons for start and due dates.

[WEB-592] chore: update issue start and due date icons across the platform

---

web/hooks/store/use-page.ts

1. When navigating to a page from the `Cmd K` modal in the dashboard, the application crashes.
1. When the `projectId` is not present in the route, the `usePage` hook throws an error, but now it simply returns undefined which is handled in the component level.

[WEB-591] fix: navigating to a page through Cmd K throws error

---

web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
web/components/issues/issue-layouts/spreadsheet/spreadsheet-header.tsx

This PR includes enhancements for the dropdown z-index in spreadsheet layout, resolving the issue of overlap during scrolling that occurred previously.

[WEB-562] chore: spreadsheet layout dropdown z index improvement

---

web/components/core/sidebar/sidebar-menu-hamburger-toggle.tsx
web/components/project/sidebar-list-item.tsx
web/components/workspace/help-section.tsx
web/components/workspace/sidebar-dropdown.tsx
web/components/workspace/sidebar-menu.tsx
web/layouts/app-layout/sidebar.tsx
web/layouts/settings-layout/profile/sidebar.tsx
web/store/application/theme.store.ts

This PR addresses an enhancement to the app sidebar toggle functionality for mobile screens. Previously, it was not functioning as intended. I have implemented the necessary adjustments to ensure it now operates as expected.

[WEB-594] fix: app sidebar toggle

---

packages/types/src/issues.d.ts
packages/types/src/view-props.d.ts
web/components/cycles/cycle-mobile-header.tsx
web/components/headers/cycle-issues.tsx
web/components/headers/module-issues.tsx
web/components/issues/issue-layouts/filters/header/display-filters/display-filters-selection.tsx
web/components/issues/issue-layouts/filters/header/display-filters/group-by.tsx
web/components/issues/issue-layouts/filters/header/display-filters/sub-group-by.tsx
web/components/issues/issue-layouts/kanban/default.tsx
web/components/issues/issue-layouts/kanban/kanban-group.tsx
web/components/issues/issue-layouts/kanban/swimlanes.tsx
web/components/issues/issue-layouts/list/default.tsx
web/components/issues/issue-layouts/utils.tsx
web/components/issues/issues-mobile-header.tsx
web/components/modules/module-mobile-header.tsx
web/constants/issue.ts
web/store/issue/helpers/issue-helper.store.ts
web/store/issue/issue_kanban_view.store.ts

This PR introduces a significant feature enhancement aimed at improving the display filters in project issues lists and Kanban layouts. With this new capability, users can now effectively group and organize issues based on cycles and modules, enhancing visibility and workflow management.

[WEB-601] feat: enhanced display filters grouping by cycles and modules in project issues

---

web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
web/components/issues/issue-layouts/kanban/block.tsx
web/components/issues/issue-layouts/kanban/default.tsx
web/components/issues/issue-layouts/kanban/kanban-group.tsx
web/components/issues/issue-layouts/kanban/swimlanes.tsx

This repository addresses an issue related to UI inconsistency observed in the Kanban layout following the introduction of grouped and sub-grouped display filters. With the recent addition of these filters, users have reported inconsistencies in the visual representation of tasks within the Kanban view.
Media:
| <img width="915" alt="image" src="https://github.com/makeplane/plane/assets/28592219/41367e9a-8a94-4c7b-a6b6-cfa837ae3548"> | <img width="915" alt="image" src="https://github.com/makeplane/plane/assets/28592219/90386a5b-3931-4313-ae5f-062fa5f261aa"> |

[web-599] ui: kanban layout UI consistency enhancement for grouped display filters

---

web/store/project/project.store.ts

This PR resolves an issue with the project sidebar favorite list. Previously, when a user favorited project XYZ and then left it, the project would still appear under the favorite section, which was not the intended behavior. I have addressed this issue and made the necessary changes to ensure it functions as intended.

[WEB-605] fix: project sidebar favorite list logic updated

---

web/components/issues/issue-layouts/kanban/swimlanes.tsx

This PR contains a fix aimed at resolving an issue with the display of sub-group-by issue counts in the header of the Kanban layout within project issues.
Media:
| <img width="352" alt="Screenshot 2024-02-29 at 5 00 34 PM" src="https://github.com/makeplane/plane/assets/28592219/ea74f15a-2359-42a8-9581-f48bb85f47e5"> | <img width="354" alt="Screenshot 2024-02-29 at 5 00 44 PM" src="https://github.com/makeplane/plane/assets/28592219/ee725210-73a2-4ce4-81fc-e9167ea3be0c"> |

[WEB-600] fix: fixed sub-group-by issue count display in kanban layout header

---

web/components/modules/sidebar.tsx

This PR addresses a bug in the module sidebar where the description was rendered twice, which was not the intended behavior. I have resolved this issue and made the necessary changes to ensure it appears as intended.

[WEB-607] fix: module sidebar description duplicacy

---

web/components/issues/issue-layouts/kanban/default.tsx
web/components/issues/issue-layouts/kanban/headers/group-by-card.tsx

This PR addresses a problem with text overflow in the header of the Kanban layout, which resulted in truncated or poorly displayed header text.
Media:
| ![image](https://github.com/makeplane/plane/assets/28592219/77e7c267-1cca-4bbb-88c1-c58efe90415e) | <img width="722" alt="Screenshot 2024-02-29 at 8 19 02 PM" src="https://github.com/makeplane/plane/assets/28592219/181445b7-2dce-4a74-8ddf-5e78aaa4bfaa"> |

[WEB-609] fix: header text overflow issue in kanban layout

---

web/components/issues/issue-detail/issue-activity/comments/comment-create.tsx

1. When pressing the enter key multiple times in an issue comment, the same comment is being submitted repeatedly.
1. To address this problem, I've implemented validation that disables the enter key press action when submitting a comment, thus preventing multiple comments from being posted simultaneously.

[WEB-615] fix: multiple issue comment

---

packages/ui/src/dropdowns/custom-menu.tsx
packages/ui/src/dropdowns/helper.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/all-issue.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/archived-issue.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/cycle-issue.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/module-issue.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx

1. The quick action menu was not appearing in the spreadsheet layout of the issue.
1. Upon inspection, it was discovered that the spreadsheet issue column had a higher z-index due to recent refactoring, causing the menu to not display. This issue has been addressed by adding the menuItemsClassName prop to the custom menu component, allowing for the passing of a custom class name to the menu container.

[WEB-619] fix: workspace all issue quick action

---

web/components/inbox/inbox-issue-actions.tsx

1. In the project inbox, when the focus is on any input or description, pressing the down or up arrow key triggers navigation issues within the inbox.
1. I have identified the problem and implemented necessary changes to ensure it functions as intended.
| ![90de96b0-6a27-405e-a999-3965ee1b3df6](https://github.com/makeplane/plane/assets/121005188/41360d84-4377-4f23-87fc-9f0f0a2165d7) | ![1c9098ca-ba11-4b18-a885-782d8a2bbee1](https://github.com/makeplane/plane/assets/121005188/1dcc3fb2-0a3d-4515-aba0-e1a5e01076d7) |

[WEB-616] fix: inbox issue navigation issue title and description event propagation

---

packages/editor/document-editor/src/ui/components/links/link-edit-view.tsx

Fixed the bug that causes the editor to crash due to the internal implementation of `textBetween` implementation that uses nodeSize but on further debugging, crashes due to the [unhandled checks in Prosemirror's core library](https://discuss.prosemirror.net/t/feature-request-better-error-message-for-nodesbetween/4417) that threw this cryptic error `TypeError: Cannot read properties of undefined (reading 'nodeSize')` while editing text of links on the last node of the editor

fix: crash while updating link text on the last node

---

.github/workflows/check-version.yml

The Pull Request adds a new workflow, that runs when a pull request is raised to `master` branch, which withstands the below two cases, 
- If the package.json version of the `master` branch and `head` branch is same, this means that the version has not been changed and the job will fail.
- If the package.json version of `master` and `head` are different, this implies that the version has been successfully changed, resulting in the job to pass.

[CHANG-6] Added Workflow for comparing version between Master & Head before Release

---

.github/workflows/feature-deployment.yml

Purpose: Deploy Feature Preview build in Kubernetes environment as per `kube_config` file provided. Since this environment is part of in-house infrastructure, it uses Tailscale action to connect and then do the deployment. 
> Note: This PR is set to RUN manually only. 
Please add the below secrets before proceeding to merge (Contact @mguptahub  for details)
- KUBE_CONFIG
- TS_OAUTH_CLIENT_ID
- TS_OAUTH_SECRET
- FEATURE_HELM_CHART_URL
- FEATURE_HELM_CHART_NAME
- FEATURE_NAMESPACE
- KUBE_VERSION=v1.26.11

feat: feature preview deploys for web and space nextjs applications

---

web/components/workspace/send-workspace-invitation-modal.tsx

1. Remove button gets misaligned when error message is displayed in the workspace invite modal.
1. Grouped role select and remove button for proper alignment.
Before-
https://github.com/makeplane/plane/assets/65252264/80e774e9-525c-42a2-afb0-78324b9863c5
After-
https://github.com/makeplane/plane/assets/65252264/27b61b9e-6cdb-46ab-9ad2-15674250c0bf

[WEB-618] fix: remove member button alignment in the workspace invite modal

---

web/components/issues/issue-layouts/properties/all-properties.tsx

This PR addresses the issue of state name overflow in the kanban layout when the state name is longer.
|  ![before](https://github.com/makeplane/plane/assets/121005188/ce44bbfd-fc78-4059-8bf6-61fb7b13724f) |  ![after](https://github.com/makeplane/plane/assets/121005188/42251767-2959-4288-b445-3e16397d2a4e)  |

[WEB-627] fix: kanban card state name overflow

---

packages/editor/core/src/styles/table.css
packages/editor/core/src/ui/extensions/table/table/table-view.tsx

1. Added text to empty color picker boxes for both light and dark modes
| Light mode | Dark mode |
| <img width="911" alt="image" src="https://github.com/makeplane/plane/assets/73993394/0179499a-00ac-43c2-b3e1-a65654c95bef"> | <img width="911" alt="image" src="https://github.com/makeplane/plane/assets/73993394/5f5a6cf0-a0e5-47d0-bb37-5d6f546c26dd"> | 
2. This PR fixes the issue in which row/col action pickers in tables are shown over the modals if there's an editor behind it.
| <img width="911" alt="image" src="https://github.com/makeplane/plane/assets/73993394/056a1875-2cad-4f7d-b772-317814a96aa1"> | <img width="911" alt="image" src="https://github.com/makeplane/plane/assets/73993394/92c46ccc-ad34-4adc-aa33-0888f91f1c68"> | 
3. …

[WEB-566] feat: Added text to empty color picker boxes and other fixes

---

web/components/project/member-select.tsx
web/components/project/project-settings-member-defaults.tsx

**Problem:**
1. When either the project lead or default assignee is changed, the other property automatically changes to None for a blink.
2. Default assignee & project lead container have slight differences in height when one of the property have value as None.
**Solution:**
1. While updating project details, one of the property value was going as undefined, so fixed it by checking for its value in currentProjectDetails.
2. Gave fixed height to both property container's.
_**Before:**_
https://github.com/makeplane/plane/assets/94619783/51b11d07-f15a-4af6-9d5b-21ca1f7ff4e9
_**After:**_
https://github.com/makeplane/plane/assets/94619783/632701e0-fa98-40fd-8ab1-9951b4f63a78
This PR is attached to [WEB-663](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/949f4a5 …

[WEB-663] fix: project members settings flickering

---

web/store/issue/helpers/issue-helper.store.ts

This PR resolves a rendering issue encountered in the Kanban swimlanes view when a cycle or module is not assigned to an issue. Previously, such unassigned items were causing visual inconsistencies in the Kanban board. With this fix, the Kanban view now accurately handles unassigned cycles or modules.

[WEB-612] fix: rendering Issue in kanban swimlanes view for unassigned cycle or Modules

---

web/components/project/create-project-modal.tsx

**Problem:**
Unable to deselect the project lead in create project modal, if once selected.
**Solution:**
If the selected lead is getting clicked again, then deselect the selected lead.
https://github.com/makeplane/plane/assets/94619783/5451a623-5768-4f20-a535-2774787f6ea6
This PR is attached to the issue [WEB-667](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/d410d5d7-8189-4150-bc30-027072e9ec8e)

[WEB-667] fix: unable to deselect project lead in create project modal

---

web/components/project/sidebar-list.tsx

The padding of the menu items in project dropdown was inconsistent.
Removed the empty space between the project menu item and scroll bar by adding necessary styles.
* Before Fix
[scrnli_3_8_2024_11-40-49 AM.webm](https://github.com/makeplane/plane/assets/33979846/d8f03586-a9bf-4065-a360-d1d42f6f6d70)
* After Fix
[scrnli_3_8_2024_11-38-10 AM.webm](https://github.com/makeplane/plane/assets/33979846/9e1fb932-8a15-4a49-828b-0157b8898afa)
This PR is linked to [WEB-665](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/73624fa4-e646-4ad4-ae59-162f76c02fca)

[WEB-665] fix Padding in the project dropdown.

---

web/components/empty-state/empty-state.tsx
web/constants/empty-state.ts

1. Project page is encountering an error on the favorite tab.
1. Issue has been resolved by updating the tab key and the empty state key, which were previously different, causing the error. Additionally, error handling for the empty state has been implemented to prevent such errors in the future.

[WEB-687] fix: project page empty state and empty state error handling 

---

web/components/core/filters/date-filter-modal.tsx

1. Users can de-select date in the date range picker modal causing unexpected behavior.
1. Disabled date de-selection.

[WEB-670] fix: date filter modal selection

---

web/components/workspace/sidebar-menu.tsx
web/constants/dashboard.ts

This PR includes updates to the app sidebar dashboard label, changing it to "Home", and also updating the associated icon.
| Before | After | 
| ![before](https://github.com/makeplane/plane/assets/121005188/9b8d3b8d-e657-48c5-be45-903338b99147) | ![after](https://github.com/makeplane/plane/assets/121005188/d6a08619-2a17-4908-8cc6-d44d683ba041)  |

[WEB-686] chore: app sidebar label update

---

web/components/issues/issue-layouts/empty-states/module.tsx

1. "Create Issue" action on the empty state page of Module issues is not functioning.
1.  Issue has been resolved, and necessary changes have been made to ensure it works as expected.

[WEB-685] fix: module empty state issue creation 

---

web/components/issues/issue-layouts/quick-action-dropdowns/all-issue.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/archived-issue.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/cycle-issue.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/module-issue.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx

1. The max height of the issue quick action is insufficient for the content.
1. This issue has been resolved by updating the max height to achieve the desired appearance.
| ![before](https://github.com/makeplane/plane/assets/121005188/f6610d21-2513-422f-872f-d6d45d6ae75a) | ![after](https://github.com/makeplane/plane/assets/121005188/9bcca9b1-07b5-429b-817e-f4ecea9a92ea) |

[WEB-689] chore: issue quick action dropdown improvement

---

web/components/core/sidebar/sidebar-progress-stats.tsx
web/components/cycles/sidebar.tsx
web/components/modules/sidebar.tsx
web/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
web/pages/[workspaceSlug]/projects/[projectId]/modules/[moduleId].tsx

**Problem:**
The cycle & model sidebar progress statistics panels were not taking full height.
**Solution:**
Removed static `h-44` given to panels.
**Improvement:**
Made the sidebar header fixed while scrolling.
**Before:**
https://github.com/makeplane/plane/assets/94619783/d8b7bd8a-8074-47ef-9fef-8df5e226f923
**After:**
https://github.com/makeplane/plane/assets/94619783/2f5cb6f7-8315-4b44-9e4f-353d56dc8e2d
This PR is attached to the issue [WEB-697](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/924628f6-3fc6-4f1e-bf91-084004d1f189)

[WEB-697] fix: cycle & module sidebar progress-stats scroll

---

apiserver/bin/takeoff
apiserver/bin/takeoff.local
apiserver/plane/db/management/commands/clear_cache.py
apiserver/plane/utils/cache.py

fix: 
- Clear cache when the server is started to remove old stale values in case of schema and response changes.
- Remove caching of APIs in `DEBUG` mode for quick iterations.

[WEB - 691]: Remove caching on DEBUG and server restart

---

packages/editor/core/src/ui/extensions/index.tsx
packages/editor/core/src/ui/read-only/extensions.tsx
packages/editor/document-editor/src/ui/readonly/index.tsx

This PR fixes the issue of code blocks getting converted to inline code blocks, typography changes, and other bugs while changing from Editable instance of the editor to the read only instance of the editor by updating all the extensions for the read only instances.

[WEB-641] fix: update extensions in read only instance of the editor

---

web/components/dashboard/widgets/recent-collaborators/default-list.tsx
web/components/dashboard/widgets/recent-collaborators/root.tsx
web/components/dashboard/widgets/recent-collaborators/search-list.tsx
web/components/project/send-project-invitation-modal.tsx

1. Added a `View less` button to the Collaborators widget which reduces the number of collaborators back to the first 8.
2. Updated the title and description of the Collaborators widget.
https://github.com/makeplane/plane/assets/65252264/60f0baac-92bc-4a2a-a8ec-6d3b9c58aef4

[WEB-673] chore: added view less button to the collaborators widget

---

web/components/dashboard/widgets/assigned-issues.tsx
web/components/dashboard/widgets/created-issues.tsx
web/components/dashboard/widgets/error-states/index.ts
web/components/dashboard/widgets/error-states/issues.tsx
web/components/dashboard/widgets/index.ts
web/store/dashboard.store.ts

1. On error, the widget keeps on loading, disabling any sort of user actions.
1. Added an error state for the issues widgets with a `Retry` button which resets the widget filters.
https://github.com/makeplane/plane/assets/65252264/7a23344a-6d41-46f8-806b-f8642f15f4dc

[WEB-690] chore: error state for the issues widgets

---

web/components/issues/issue-layouts/list/default.tsx
web/styles/globals.css

This PR contains improvements for the scrollbar in the list layout. Previously, the scrollbar was overlapping with the group header. I've made the necessary changes to ensure it appears as intended.

[WEB-585] chore: list layout scrollbar improvement

---

apiserver/plane/app/views/cycle/base.py

- Total count in the active cycles were breaking due to the serializer change.
Issue Link: [WEB-719](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/2127f3f2-4d24-47f4-a8b6-4105c5bc3361)

[WEB-719] chore: active issue total count

---

web/components/cycles/gantt-chart/blocks.tsx
web/components/gantt-chart/chart/views/month.tsx
web/components/modules/gantt-chart/blocks.tsx

1. Gantt chart sidebar and main content headers' height don't match.
2. Cycles and modules sidebar blocks don't have a pointer cursor.
1. Updated the main content height.
2. Added cursor pointer to the sidebar blocks.

[WEB-723] fix: gantt sidebar blocks cursor

---

packages/ui/src/emoji/emoji-icon-picker.tsx

1. Emoji picker has an unnecessary scroll.
1. Removed the fixed height from the dropdown.

[WEB-724] fix: emoji picker unnecessary scroll

---

web/components/issues/issue-detail/label/label-list.tsx

**Problem:**
Label mutation was not happening in the peek-overview & issue-detail on the label add & remove action.
**Solution:**
Selected label data was getting used from `store`, but the observer was not there to observe changes.
**Before:**
https://github.com/makeplane/plane/assets/94619783/a1b67af9-fbd7-4a74-a680-c5c6e30f9e15
**After:**
https://github.com/makeplane/plane/assets/94619783/aa993646-1982-4b8e-9b6d-33ff1115c312
This PR is attached to issue [WEB-722](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/6929621e-9a74-477a-8a66-23bee1f2f868)

[WEB-722] fix: label mutation in peek-overview & issue detail

---

web/components/issues/issue-detail/root.tsx
web/components/issues/peek-overview/view.tsx

1. When the close button within the delete modal popup is clicked, the peek overview gets automatically closed.
2. When clicking on 'Delete' or 'Archive Issue' to open the modal in the issue details sidebar, the entire sidebar shifts downward.
1. Removed the `removeRoutePeekId` from the close action of the modal.
* Before
[scrnli_3_12_2024_3-13-26 PM.webm](https://github.com/makeplane/plane/assets/33979846/65503184-cdc2-4cbc-9b1a-f50097accae7)
* After
[scrnli_3_12_2024_3-06-22 PM.webm](https://github.com/makeplane/plane/assets/33979846/900430d3-0cb9-41e1-8950-6c3ca575db66)
2. Removed the style that was causing the issue. 
* Before
[scrnli_3_12_2024_1-52-40 PM.webm](https://github.com/makeplane/plane/assets/33979846/4359f122-e1ae-4648-82d1-104896bb3505)   
* After
[scrnli_3_12_2024_3-01-09 …

[WEB-717] fix: delete issue modal UI fixes.

---

web/components/issues/issue-detail/reactions/issue-comment.tsx
web/components/issues/issue-detail/reactions/issue.tsx
web/helpers/issue.helper.ts

This PR includes enhancements for issue reactions. Previously, tooltips were absent. I have now added tooltips to the reactions so that users can see who reacted.
| ![b4d360e1-cd16-47f0-9f48-318f1b98bc58](https://github.com/makeplane/plane/assets/121005188/46263dc4-89d4-4062-99fb-ab0ba188ff96) | ![2b9e7d16-d60b-44b0-8c5d-b531c49fa214](https://github.com/makeplane/plane/assets/121005188/d3b9d34e-9324-4c5d-b41f-2edcbe547f55) |

[WEB-720] chore: reaction tooltip added

---

web/components/dropdowns/module/index.tsx
web/components/issues/issue-detail/module-select.tsx

**Improvement:**
There were multiple tooltips, on the module property in peek-overview & issue-detail, so removed them for a clear view.
**Before:**
**After:**
No Tooltip.

[WEB-721] chore: removed module tooltip from peek-overview & issue detail

---

web/components/issues/issue-layouts/kanban/default.tsx
web/components/issues/issue-layouts/kanban/kanban-group.tsx
web/components/issues/issue-layouts/kanban/swimlanes.tsx

This PR addresses an issue where, despite proper rendering of issues when filtered by group and sub-group, the "showEmptyGroup" filter was not behaving as expected. Even though empty states were visible, setting "showEmptyGroup" to null did not function correctly. With this fix, the behavior of the "showEmptyGroup" filter has been corrected, ensuring consistent rendering of empty states alongside filtered issues in group and sub-group views.
| <img width="2283" alt="Screenshot 2024-03-13 at 1 54 45 PM" src="https://github.com/makeplane/plane/assets/28592219/300d1c71-476e-41d6-9e45-9104250ac160"> | <img width="2279" alt="Screenshot 2024-03-13 at 1 54 51 PM" src="https://github.com/makeplane/plane/assets/28592219/8348208a-da2d-4eef-b108-e2e67baea198"> …

[WEB-749] fix: rendering empty states with "showEmptyGroup" filter in issue grouping

---

web/store/issue/helpers/issue-helper.store.ts

This PR resolves a rendering issue encountered in the Kanban swimlanes view when a cycle or module is not assigned to an issue. Previously, such unassigned items were causing visual inconsistencies in the Kanban board. With this fix, the Kanban view now accurately handles unassigned cycles or modules.

[WEB-751] fix: rendering Issue in kanban swimlanes view for unassigned cycle or Modules

---

web/components/cycles/list/cycles-list-item.tsx

1. The current order of the properties seems inconsistent.
1. Swapped the dates and cycle status properties.

[WEB-741] chore: swapped dates and status properties in the cycle list item

---

web/components/cycles/modal.tsx

1. Wrong `projectId` being sent in the cycle date check endpoint.
1. Updated the function to use `projectId` from the form data.

[WEB-754] fix: cycle date check endpoint

---

packages/ui/src/dropdowns/custom-menu.tsx

https://github.com/makeplane/plane/assets/31303617/2f73e6eb-0c0c-406a-af4e-c9cd9f4f6c37

[WEB-715] chore: closing custom dropdown on button click

---

packages/types/src/issues/issue_reaction.d.ts
web/components/issues/issue-detail/reactions/issue.tsx
web/store/issue/issue-details/reaction.store.ts

This PR addresses the issue of initial non-display of reactions tooltip. There was a change in the response where we were receiving 'actor_id' which has now been replaced with 'actor'. I have resolved this issue and updated the store accordingly to ensure it functions as intended.
Issue link: [[WEB-747]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/953f392a-9cf4-48e6-8e84-6f911f965fca)

[WEB-747] chore: issue reaction response

---

web/components/cycles/cycle-peek-overview.tsx
web/components/modules/module-peek-overview.tsx

**Problem:**
The cycle & module peek-view header was not stuck to the top.
**Solution:**
There was extra padding at the top, so removed it.
**Before:**
https://github.com/makeplane/plane/assets/94619783/03e6e6b6-ca12-438a-8b0e-6925c8913e96
**After:**
https://github.com/makeplane/plane/assets/94619783/4640da05-101d-4a33-b215-6fb6f99f9ab0
This PR is attached to issue [WEB-697](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/924628f6-3fc6-4f1e-bf91-084004d1f189)

[WEB-697] fix: cycle & module peekview scroll

---

web/components/issues/attachment/attachments-list.tsx
web/components/issues/attachment/delete-attachment-confirmation-modal.tsx
web/components/issues/peek-overview/header.tsx
web/components/issues/peek-overview/index.ts
web/components/issues/peek-overview/issue-attachments.tsx
web/components/issues/peek-overview/issue-detail.tsx
web/components/issues/peek-overview/properties.tsx
web/components/issues/peek-overview/view.tsx
web/components/issues/sub-issues/issue-list-item.tsx
web/components/issues/sub-issues/root.tsx
web/store/issue/issue-details/root.store.ts

1. Sub-issues and attachments can now be viewed and updated from the peek overview as well, improving the UX.
1. Changed the linear sub-issues progress bar to a circular progress bar.
https://github.com/makeplane/plane/assets/65252264/8a05808d-e5e3-4007-8c39-2c20c17525b4

[WEB-699] chore: implement sub-issues and attachments in the peek overview

---

web/components/issues/issue-layouts/empty-states/cycle.tsx

This PR includes enhancements for validating the empty state of completed cycles.

[WEB-545] chore: completed cycle empty state validation

---

web/components/cycles/board/root.tsx
web/components/cycles/cycles-view-header.tsx
web/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx

1. Cycles `All` tab not rendering.
1. Cycles layout was not getting initialized, so set a default value for the layout to `list`.
1. Cycles board layout has unnecessary padding when only completed cycles are present.

[WEB-748] fix: cycle layout not getting initialized

---

web/components/workspace/sidebar-menu.tsx

This PR contains alignment fix for the collapsed state of the app sidebar.
| ![Screenshot 2024-03-15 at 1 13 26 PM](https://github.com/makeplane/plane/assets/121005188/bdd1d1bc-3404-460c-99d2-0903d148fb07) | ![Screenshot 2024-03-15 at 1 13 20 PM](https://github.com/makeplane/plane/assets/121005188/b10b8046-907d-413e-b789-f4c5819a21ec) |

[WEB-757] chore: app sidebar improvement

---

web/components/issues/issue-layouts/calendar/calendar.tsx
web/components/issues/issue-layouts/calendar/day-tile.tsx
web/components/issues/issue-layouts/calendar/dropdowns/options-dropdown.tsx
web/components/issues/issue-layouts/calendar/header.tsx
web/components/issues/issue-layouts/calendar/index.ts
web/components/issues/issue-layouts/calendar/issue-block-root.tsx
web/components/issues/issue-layouts/calendar/issue-block.tsx
web/components/issues/issue-layouts/calendar/issue-blocks.tsx
web/components/issues/issue-layouts/calendar/quick-add-issue-form.tsx
web/components/issues/issue-layouts/calendar/week-days.tsx
web/components/issues/issue-layouts/calendar/week-header.tsx

https://github.com/makeplane/plane/assets/94619783/e1219152-8408-4edc-be5b-25415ffd53a3
| Month Layout | Week Layout |
| ![image](https://github.com/makeplane/plane/assets/94619783/c4aef02e-cf81-41de-a7b2-1ab95e21cbe2) | ![image](https://github.com/makeplane/plane/assets/94619783/9676c182-67c9-43d2-8f35-285e3252045c) | 
This PR is attached to the issue [WEB-759](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/d9a23f6d-d238-4a00-9c83-8abd2936117a)

[WEB-759] style: added calendar layout responsiveness

---

packages/editor/core/src/lib/editor-commands.ts
packages/editor/extensions/src/extensions/slash-commands.tsx
packages/editor/rich-text-editor/src/ui/menus/bubble-menu/index.tsx
packages/editor/rich-text-editor/src/ui/menus/bubble-menu/link-selector.tsx
packages/editor/rich-text-editor/src/ui/menus/bubble-menu/node-selector.tsx

Clearing current node (i.e. resetting before converting to other type of node into the default node which is paragraph) and only then applying the change to other type of nodes.
Say if you had an existing node which is a Heading 1, and if you try to change it to a block quote, it doesn't clear the existing nodes and the Heading 1 tag is still present along with the blockquote. This PR fixes that.
Changed the menu items' command for slash commands and bubble menu items to first do the `clearNodes()` operation before chaining other commands. For more reference on what this does, please refer [the tiptap docs](https://tiptap.dev/docs/editor/api/commands/clear-nodes)
In the bubble menu, if the selected node is a inline code block, then Link and other marks like Bold, Italic and Underline …

[WEB-755] fix: Clearing nodes to default node i.e. paragraph before converting it to other type

---

web/components/issues/issues-mobile-header.tsx

**Problem:**
The mobile header was always there even in full screen.
**Solution:**
Added media query to hide it on screens greater than 768px.
This PR is attached to issue [WEB-766](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/866e5514-f202-4f5a-87a3-9c393b2a50e4)

[WEB-766] fix: Project issues mobile header visibility

---

apiserver/plane/app/views/workspace/base.py
apiserver/plane/app/views/workspace/member.py

fix:
- user caching when the user leaves / deletes the workspace
- invalidate the cache `/users/me/settings/` cache
[[WEB - 779]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/8eda8a9e-5de2-4644-ae05-2d1638de1b3b)

[WEB - 779] fix: user caching when the user leaves/deletes the workspace

---

web/components/analytics/project-modal/modal.tsx

**Problem:**
When the analytics section is open, clicking outside of the dialog does not closing the dialog.
**Solution:**
Wrapped the Dialog with div & its class.
https://github.com/makeplane/plane/assets/94619783/46d95dc8-bd64-4541-8441-3b0ae92cc0b0
This PR is attached to issue [WEB-675](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/b70bcaf6-1df8-4aa0-b1fd-e801b3894e1c)

[WEB-675] fix: analytics dialog close on outside click

---

apiserver/plane/db/management/commands/test_email.py

This was missed in pull request #3732 and/or the command didn't exist yet then ...

fix: test email command to use new SSL settings

---

web/store/cycle_filter.store.ts
web/store/module_filter.store.ts
web/store/project/project_filter.store.ts

**Problem:**
When switching between projects for the very first time even for active cycles also, search & filter options were rendered.
**Solution:**
1. On debugging found that the filter store's **_autorun_** function was experiencing an infinite loop, so fixed it by replacing it with _**reaction**_.
2. and, also fixed the filter data loss on the project/workspace switch.
This PR is attached to the issue [WEB-768](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/159d1a2c-887b-4960-bbdb-b786c7b55e5e)

[WEB-768] fix: project, module, cycle filter store infinite loop.

---

web/components/issues/issue-detail/label/create-label.tsx
web/components/issues/issue-detail/label/select/label-select.tsx

**Problem:**
Labels dropdown, and colour picker while creating a new label overflowing in issue peek and detail view.
**Solution:**
https://github.com/makeplane/plane/assets/94619783/7dac56b8-4ed5-4289-9817-d1b6fb7e4b79
This PR is attached to the issue [WEB-767](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/e786caac-5d65-4a2f-8246-8c135058d179)

[WEB-767] fix: Labels overflow in peek, detail view

---

web/components/issues/sub-issues/properties.tsx
web/store/issue/issue-details/sub_issues.store.ts

This PR addresses an issue where the state and members from different projects were not rendered correctly in sub-issues. Prior to the fix, sub-issues were not properly displaying the state and members associated with their respective projects. Additionally, this update includes exception handling for creating issues from different projects, ensuring smooth issue creation across project boundaries without encountering errors.

[WEB-383] fix: rendering state and members from different projects in sub-issues

---

web/components/issues/issue-modal/draft-issue-layout.tsx
web/components/issues/issue-modal/form.tsx
web/components/issues/issue-modal/modal.tsx

This fix implements autofocus functionality on the title element within the issue create modal when creating bulk issues. Previously, users had to manually select the title field before inputting data, leading to inefficiencies in the bulk issue creation process. With this enhancement, the title field is automatically focused upon opening the modal, streamlining the workflow and improving user experience during bulk issue creation.

[WEB-736] fix: autofocus added to title element in bulk issue creation modal

---

web/components/workspace/create-workspace-form.tsx

**Problem:**
Create workspace fields were not marked as required (w.r.t UI).
**Solution:**
This PR is attached to issue [WEB-784](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/ebeb4cf1-0bef-43fc-a85e-fea8caba44a5)

[WEB-784] chore: create workspace fields as required indication

---

web/components/labels/project-setting-label-list.tsx
web/pages/[workspaceSlug]/projects/[projectId]/settings/labels.tsx

**Problem:**
Labels create colour select dropdown is overflowing the container and looking like it is cut.
**Solution:**
This PR is attached to the issue [WEB-786](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/b12c02a8-4479-4bd8-872f-426831144f0b)

[WEB-786] fix: create label inline overflow

---

web/components/issues/sub-issues/issue-list-item.tsx
web/components/issues/sub-issues/root.tsx

- When users attempt to open the update sub-issue modal or delete modal from the peek overview, the peek overview closes unexpectedly.
- Implement the necessary adjustments to ensure the expected functionality.

[WEB-781] fix: peek overview sub issue edit

---

web/components/core/image-picker-popover.tsx
web/pages/profile/index.tsx

- The profile cover upload feature is malfunctioning and remains stuck in the uploading state.
- The problem stemmed from the use of the workspace asset endpoint, which require the workspace slug, which is missing in the current flow. To address this, I've made adjustments by updating the upload endpoint to the user asset, resolving the issue.

[WEB-787] fix: profile cover upload

---

web/components/core/image-picker-popover.tsx

- Within the create project modal, the project dropdown is overlapping with the cover upload modal.
- Address this by adjusting the z-index.
| ![before](https://github.com/makeplane/plane/assets/121005188/ce63fb39-4d93-4b88-9da6-df48270eba2a) | ![after](https://github.com/makeplane/plane/assets/121005188/b342ba17-d9e2-4d9a-94cc-be1f248f99db) |

[WEB-692] fix: project modal cover image popover z-index fix

---

web/components/dropdowns/state.tsx
web/store/state.store.ts

This fix addresses an issue where the default state of a project was not properly rendered in the issue create/update modal when switching between projects. With this fix, the issue create/update modal now accurately renders the default state corresponding to the selected project.

[WEB-750] fix: default state rendering fix in issue create/update modal project switching

---

packages/ui/src/dropdowns/custom-menu.tsx

When closing custom menu button in modules/ cycles card, the users were redirected to module/ cycle details page. 
Added `event.preventDefault()` to the `onClick` event listener of the menu button to prevent it from calling Module/ Cycle card's redirect event. 
* Before Fix
[scrnli_3_21_2024_5-03-08 PM.webm](https://github.com/makeplane/plane/assets/33979846/a917e805-d3be-45a0-addb-d822073d9158)
* After Fix
[scrnli_3_21_2024_5-01-07 PM.webm](https://github.com/makeplane/plane/assets/33979846/949c1ba7-8981-4bc3-9510-879710cccf4b)
This PR is linked to [WEB-795](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/b4297059-1b98-4e9e-a3ae-699c3f5c0f0f)

[WEB-795] fix: prevent custom menu button from opening cycle/ module details page when closed.

---

web/components/dropdowns/module/index.tsx
web/components/issues/issue-layouts/properties/all-properties.tsx

- The project list layout state and cycle select dropdown do not adjust their positions based on available space.
- Identified and resolved the dropdown positioning bug.
| ![c9622010-308d-44c3-9017-fa713b33408f](https://github.com/makeplane/plane/assets/121005188/d748a24c-a920-4e62-bea1-83d7ccc6267a) | ![fe485fc8-f769-4ad7-b614-e2e78dff7c8f](https://github.com/makeplane/plane/assets/121005188/52b9b72f-4c2e-43cd-b0a3-93b21259aea9) |

[WEB-797] fix: project list dropdown placement

---

web/components/dropdowns/member/index.tsx
web/components/dropdowns/member/types.d.ts
web/components/issues/issue-layouts/properties/all-properties.tsx

**Problem:**
Issue card empty assignee dropdown doesn't have a tooltip.
**Solution:**
Introduced a new variable to customize tooltip content.
This PR is attached to issue [WEB-794](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/51f3f7d3-8c2f-46b4-92db-663340e7a8ce)

[WEB-794] fix: issue card assignee empty state tooltip

---

web/components/issues/issue-modal/draft-issue-layout.tsx
web/components/issues/issue-modal/form.tsx

This fix encompasses several improvements: addressing empty issue properties, enabling creation of more properties in the edit modal, and enhancing draft management during issue movement. Previously, encountering empty issue properties caused inconsistencies, restricting the ability to create additional properties in the edit modal. Additionally, managing drafts during issue movement posed challenges. With this fix, empty issue properties are handled effectively, users can create more properties in the edit modal, and drafts are seamlessly managed during issue movement, enhancing overall usability and functionality.

[WEB-802] fix: handling empty issue properties, enabling creation in edit modal, and draft management enhancement

---

web/components/cycles/list/cycles-list-item.tsx
web/components/modules/module-list-item.tsx

- In cycle and module list page quick action do not adjust their positions based on available space.
- Identified and resolved the dropdown positioning bug.

[WEB-804] fix: module and cycle list page quick action

---

web/components/project/dropdowns/order-by.tsx

- On the project list page, when the "Order By" dropdown is set to descending and the user attempts to switch to manual sorting, the page fails to render any results.
- Resolved the issue by implementing necessary modifications.
| ![before](https://github.com/makeplane/plane/assets/121005188/8e7ffbd1-a64d-47d0-b420-85309b1bb4df) | ![after](https://github.com/makeplane/plane/assets/121005188/2e238fcb-be20-497a-b4ba-c7fe1a4a300e) |

[WEB-815] fix: project order by dropdown

---

web/components/issues/issue-modal/draft-issue-layout.tsx

This fix addresses an issue where the initial empty state remained open upon opening the issue create/edit modal. Previously, when accessing the modal, the empty state would persist, causing inconvenience to users. With this fix, the modal now automatically closes the initial empty state upon opening, ensuring a smoother user experience and improved usability during issue creation or editing.

[WEB-806] fix: initial empty state closure in issue Create/Edit modal

---

web/components/issues/issue-detail/label/create-label.tsx

**Problem:**
The label colour selector in the issue peek-view & detail page is not auto-repositioning itself according to space availability.
**Solution:**
Implemented auto-placement using react-popper.
https://github.com/makeplane/plane/assets/94619783/e07854b0-b24a-425b-a2fb-12ff10f62c92
This PR is attached to the issue [WEB-800](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/7aba55df-fe81-4645-8ab4-26f07b2f37b1)

[WEB-800] fix: issue peekview, and detail page create label colour selector autoplacement

---

web/components/issues/issue-layouts/kanban/roots/draft-issue-root.tsx
web/components/issues/issue-layouts/list/roots/draft-issue-root.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/draft-issue.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/index.ts

This fix addresses an issue where quick actions were not properly handled for project draft issues. Previously, attempting to perform quick actions on draft issues within a project encountered errors or inconsistencies. With this fix, quick actions are appropriately managed for project draft issues, ensuring seamless interaction and efficient workflow management within the project environment.

[WEB-805] fix: quick actions handling for project draft issues

---

web/components/issues/issue-modal/modal.tsx

This fix addresses an issue where changes made in the issue create-edit modal were not reset when the "Create More" toggle was turned on. Previously, activating the "Create More" option did not revert any modifications made to the issue properties, leading to potential data inconsistencies. With this fix, changes made in the modal are properly reset upon toggling the "Create More" option, ensuring a clean slate for each new issue creation and maintaining data integrity.

[WED-731] fix: resetting changes made on "create more" toggle activation in issue create-edit modal

---

web/components/issues/attachment/attachment-detail.tsx
web/components/issues/peek-overview/header.tsx
web/components/issues/peek-overview/view.tsx
web/components/issues/sub-issues/issue-list-item.tsx
web/components/issues/sub-issues/root.tsx
web/store/issue/issue-details/root.store.ts

1. On trying to delete a sub-issue from the peek overview, delete confirmation for the parent issue also pops up making it impossible to delete the sub-issue and user mistakenly deletes the parent issue.
2. On clicking on the delete attachment confirmation modal, the attachment doesn't get deleted and the peek overview closes.
1. Open the delete confirmation modal only for the sub-issue and not for the parent issue.
2. Prevent the peek overview from closing on trying to delete an attachment.
1. Sub-issue deletion-
https://github.com/makeplane/plane/assets/65252264/4141c06c-b1c3-4513-818e-39850252bbf2
2. Attachment deletion-
https://github.com/makeplane/plane/assets/65252264/9d589eab-1079-4a4a-b355-284d25d109c7

[WEB-818] fix: sub-issue and attachment delete not working in the peek overview

---

web/components/dropdowns/cycle/index.tsx
web/components/dropdowns/module/index.tsx
web/components/issues/issue-modal/form.tsx

When no cycle or module was selected in the issue card. A placeholder was visible for the Cycle and Modules leading to inconsistent UI. 
Made necessary changes to fix the issue.
* Before Fix
* After Fix
This PR is linked to [WEB-793](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/87f8da62-3813-454f-811c-16543b630a10)

[WEB-793] style: hide cycle and module dropdown placeholder from list and kanban view.

---

web/store/issue/project/issue.store.ts

Project total issue count on the header was not mutating when we add/ remove any issue from the project. The project `total_issue_count` data is a part of project details object. So while adding/ removing any issue from the project we were not updating this data. 
Added a fetch request to project details endpoint in order to get the up to date value of `total_issue_count` for all CRUD related issue operations.
* Before Fix
[scrnli_3_22_2024_5-38-01 PM.webm](https://github.com/makeplane/plane/assets/33979846/4713f86f-4793-4b90-bb1b-2ed3ad7f1002)
* After Fix
[scrnli_3_22_2024_5-36-34 PM.webm](https://github.com/makeplane/plane/assets/33979846/62bd0322-d7a6-48b0-b813-46a5ef061a52)
This PR is linked to [WEB-816](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/c9 …

[WEB-816] fix: project total issue count mutation.

---

web/components/issues/issue-modal/draft-issue-layout.tsx

This fix involves disabling the validation check for issue properties within the issue edit modal. Previously, the modal enforced validation on issue properties, potentially causing issues with certain inputs. With this fix, validation has been disabled, allowing users to freely input or edit issue properties without encountering unnecessary restrictions, thereby enhancing the usability and flexibility of the issue edit modal.

[WEB-789] fix: disabling issue property validation in issue edit modal

---

web/components/issues/issue-modal/draft-issue-layout.tsx

This PR Includes fixing the issue when we save the issue in the draft mode without giving the title, we are keeping the title as "Untitled" by default.

[WEB-802] fix: handling undefined condition for issue title while saving the issue as draft

---

web/pages/profile/activity.tsx

1. Profile activity page's `Load more` button isn't visible.
1. Updated the scroll container styling to make the button visible.

[WEB-821] fix: profile activity load more button visibility

---

web/components/issues/issue-layouts/calendar/base-calendar-root.tsx
web/components/issues/issue-layouts/calendar/calendar.tsx
web/components/issues/issue-layouts/calendar/day-tile.tsx
web/components/issues/issue-layouts/calendar/issue-block-root.tsx
web/components/issues/issue-layouts/calendar/issue-block.tsx
web/components/issues/issue-layouts/calendar/issue-blocks.tsx
web/components/issues/issue-layouts/calendar/quick-add-issue-form.tsx
web/components/issues/issue-layouts/calendar/week-days.tsx
web/components/issues/issue-layouts/list/list-view-types.d.ts
web/components/issues/issue-layouts/quick-action-dropdowns/cycle-issue.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/module-issue.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx

- Resolves the flickering issue in the quick add feature when users hover over any calendar date.
- Fixes the placement of the quick action dropdown in the calendar layout.
| ![before](https://github.com/makeplane/plane/assets/121005188/118a9dfc-4ba7-4b30-a758-f9cf851240cd) | ![after](https://github.com/makeplane/plane/assets/121005188/121a0d50-35d3-4a5b-8aec-5e0135a06949) |

[WEB-823] fix: quick add flicker and dropdown placement in calendar layout

---

web/components/issues/peek-overview/view.tsx

This PR include fix for the delete modal in the peek overview.

[WEB-828] fix: peek overview delete modal

---

web/components/issues/issue-update-status.tsx
web/layouts/settings-layout/workspace/sidebar.tsx

1. After reloading the issue detail page, the project identifier is missing from the top header.
2. When reloading workspace settings, the settings sidebar only shows limited options, even though I have an admin user role.
1. Upon inspection, it was discovered that the observer was missing. Therefore, it was added to rectify the issue.
2. After looking into it, I've found that the observer was missing. So, we added it to fix the issue.

[WEB-849] fix: issue detail identifier and workspace settings

---

web/components/command-palette/command-modal.tsx

This PR address the issue in command k modal where the `create a new issue` option was available even if no projects is being created leading to poor user experience. 
This PR is linked to [WEB-833](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/0cb5fb41-34bb-45fc-adf4-fd978bafd2ce)

[WEB-833] chore: remove `create a new issue` option from command k modal if no projects are there.

---

web/components/issues/issue-layouts/quick-action-dropdowns/draft-issue.tsx

This PR remove `make a copy` option from draft issue quick actions menu. 
This PR is linked to [WEB-840](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/927105da-5611-4bc5-be1d-d9295a865c96)

[WEB-840] chore: remove `make a copy` option from draft issue quick action menu.

---

web/components/command-palette/actions/help-actions.tsx

This PR address the issue with `chat with us` option not working in command k modal. 
This PR is linked to [WEB-843](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/0e6b4f0d-651d-4dc0-8373-b64a6ac34d79)

[WEB-843] fix: `chat with us` option not working in command k modal.

---

packages/ui/src/dropdowns/custom-select.tsx

This PR address the issue in color picker, where it was overlapping with the themes dropdown.
This PR is linked to [WEB-836](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/0a876c0a-abdd-4816-9751-9b878fad865c)

[WEB-836] fix: color picker overlapping with themes dropdown issue.

---

web/components/command-palette/shortcuts-modal/modal.tsx

This PR address the issue in shortcut modal not being closed on outside click detection.
This PR is linked to [WEB-834](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/501fe4e0-d05e-4d16-b523-59f19295e9d1)

[WEB-834] fix: close shortcut modal on outside click.

---

packages/editor/core/src/ui/components/editor-container.tsx
packages/editor/core/src/ui/mentions/suggestion.ts
packages/editor/extensions/src/extensions/slash-commands.tsx
yarn.lock

This PR helps us to solve the bug in which Tippy instances (like Slash Commands/Mentions/etc) weren't able to find the correct editor position to append to in case of multiple editor instances. 
It detects the active editor when the editor is editable and focused onto, and adds an "active" class on it. The tippy containers are then appended to the editor with the active class now.

[WEB-876] fix: Multiple editor instances cause weird issues with Tippy

---

web/components/project/create-project-form.tsx
web/components/project/form.tsx

* No error message was displayed in project settings page.
* The project name input was called as `project title` in create project modal leading to inconsistency between the modal and project settings page. 
* Added the error message in project settings page.
* updated `project title` to `project name` in create project modal.
* Before
* After
This PR is linked to [WEB-839](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/b8636810-b7cb-4089-b6e3-4d630e4b53f6)

[WEB-839] fix: display error message in project settings page.

---

web/components/issues/issue-modal/draft-issue-layout.tsx

- When saving a draft issue, it's being titled as "Untitled" despite providing a title during creation.
- A recent change has caused this logic breakdown. I've made the necessary adjustments to ensure it works as intended.

[WEB-879] fix: draft issue title logic

---

web/components/instance/not-ready-view.tsx

chore: add `Get started` button to redirect to `/god-mode` to set up instance.

---

web/components/issues/issue-modal/form.tsx

Removing parent from issue edit modal pop up is not removing the parent child relation.
This was due to the use of `SetValue` to remove `parent_id` when we `click` on the cross icon. Our revalidation mode is set to `onChange` and due this the above logic was not working and `dirtyFields` was not showing `parent_id` as an updated field even if the relation was removed. To fix this, I have updated the logic to use `<Controller />` component with its `onChange` prop to remove the relation.
This PR is linked to [WEB-848](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/34637de9-3ef5-469d-9e69-b5879bbf96e6)

[WEB-848] fix: issue with parent child relation not being removed from update issue modal.

---

web/components/issues/issue-detail/parent-select.tsx

- In the Issue detail page, when we open the peek overview of a sub-issue and remove its parent, the mutation is not reflected on the Issue detail page.
- Resolve this problem by implementing the necessary changes.
| ![before](https://github.com/makeplane/plane/assets/121005188/a112001b-d4e2-4ad6-a495-ab9f25dbc84a) | ![after](https://github.com/makeplane/plane/assets/121005188/ccd5db46-55e6-42af-994f-e53c63bd7dfe) |

[WEB-822] fix: sub issue peek overview mutation

---

web/components/issues/issue-layouts/list/block.tsx

- Presently, in the list layout, the issue block is non-clickable except for the area containing the title.
- Address this by implementing the necessary adjustments to ensure proper functionality as intended.

[WEB-845] chore: list layout improvement

---

web/components/issues/issue-layouts/calendar/quick-add-issue-form.tsx

- Include the option to add existing issues in project calendar layout quick add menu.

[WEB-850] chore: calendar layout add existing issue

---

web/components/cycles/cycle-mobile-header.tsx
web/components/headers/cycle-issues.tsx
web/components/headers/module-issues.tsx
web/components/headers/project-draft-issues.tsx
web/components/headers/project-issues.tsx
web/components/headers/project-view-issues.tsx
web/components/issues/archived-issues-header.tsx
web/components/issues/issue-layouts/filters/header/display-filters/display-filters-selection.tsx
web/components/issues/issue-layouts/filters/header/display-filters/display-properties.tsx
web/components/issues/issue-layouts/filters/header/filters/filters-selection.tsx
web/components/issues/issue-layouts/properties/all-properties.tsx
web/components/issues/issues-mobile-header.tsx
web/components/modules/module-mobile-header.tsx
web/components/views/form.tsx

- Despite disabling cycles and modules from project settings, they remain accessible in certain areas.
- Implemented validation to ensure that when cycles and modules are disabled, they will no longer appear in the following locations:
- Issue cards.
- Issue filter and display filter dropdowns.
- Issue sidebar and peek overview.
- Issue detail page.

[WEB-756] chore: module and cycle feature toggle validation

---

web/components/issues/issue-modal/form.tsx

* There was no horizontal padding in selected assignee component.
* Height difference in the add parent badge as compared to other properties. And text color is also different.
* Add parent button opens a dropdown with a single option of select parent
- Feels like i have to go through an additional step to link to parent.
[scrnli_4_3_2024_4-07-23 PM.webm](https://github.com/makeplane/plane/assets/33979846/9381ca67-f67e-4d94-a565-a1d10f2afdd0)
* Added proper padding in selected assignee component.
* Fixed the height and text color of Add parent button.
* Made necessary changes so that we do not have to go through that additional step to link the parent.
[scrnli_4_3_2024_4-06-16 PM.webm](https://github.com/makeplane/plane/assets/33979846/9538bc23-74c2-4cd0-8e4b-e726f7f113ff)
This PR is …

[WEB-869] chore: fix assignee and parent UI inconsistency in create issue modal.

---

web/components/issues/issue-modal/form.tsx

This PR provides additional fix to #4103  by fixing the same issue in parent select dropdown.
This PR is linked to [WEB-848](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/34637de9-3ef5-469d-9e69-b5879bbf96e6)

[WEB-848] fix: issue with parent child relation not being removed parent select dropwdown.

---

deploy/selfhost/docker-compose.yml
docker-compose-local.yml
docker-compose.yml

According to the docker compose issue 11628 (https://github.com/docker/compose/issues/11628) the 'version' field in docker-compose files is outdated. It shows a warning like the following on hosts with a newer Docker version:
```
WARN[0000] /srv/plane/docker-compose.yaml: `version` is obsolete
```
Also, the specs itself state the version was only informative: https://github.com/compose-spec/compose-spec/blob/master/spec.md#version-and-name-top-level-elements
> The top-level `version` property is defined by the Compose
> Specification for backward compatibility. It is only informative.
> Compose doesn't use version to select an exact schema to
> validate the Compose file, but prefers the most recent schema
> when it's implemented.

Dropped version info from docker-compose files

---

web/components/analytics/custom-analytics/select-bar.tsx
web/components/analytics/custom-analytics/select/segment.tsx
web/components/analytics/custom-analytics/select/x-axis.tsx
web/components/issues/issue-layouts/roots/all-issue-layout-root.tsx
web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
web/components/issues/issue-layouts/spreadsheet/spreadsheet-header.tsx
web/components/issues/issue-layouts/spreadsheet/spreadsheet-table.tsx
web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx

- Despite disabling cycles and modules from project settings, they remain accessible in spreadsheet layout and project analytics.
- Implemented validation to ensure that when cycles and modules are disabled.

[WEB-756] chore: spreadsheet layout cycle and module feature toggle validation

---

web/components/issues/issue-modal/form.tsx
web/components/issues/issue-modal/modal.tsx

This PR fixes the issue that the user is not able to see the issue description in the initial modal open in the issue create/edit modal

[WEB-899] fix: issue description was not rendering in the issue create/edit modal

---

web/components/issues/issue-layouts/gantt/quick-add-issue-form.tsx
web/components/issues/issue-layouts/kanban/quick-add-issue-form.tsx
web/components/workspace/help-section.tsx

Height of sidebar help section and quick add in all issue layout were not consistent leading to poor ui/ ux.
Updated the height for consistency. 
This PR is linked [WEB-854](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/21c9d4e9-f730-4cd1-87d7-ecc15131dfb0)

[WEB-854] style: update height of sidebar help section and quick add across all layout for consistency.

---

web/components/dropdowns/estimate.tsx
web/components/issues/issue-layouts/spreadsheet/columns/estimate-column.tsx

This PR removes placeholder from estimate property button if no estimates are selected in all the layout providing a consistent UI across all properties. 
* Before
* After
This PR is linked to [WEB-912](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/024461e5-e2fc-4548-8502-22940c019d5b)

[WEB-912] chore: remove placeholder from estimate property if no estimates are selected.

---

web/lib/wrappers/crisp-wrapper.tsx

This PR changes the `crisp-wrapper` to only mount `crisp` when there is a `CRISP_WEBSITE_ID` inside the env-variables. With those changes, no call to the website of crisp will be made when there is no usage for it. This improves the privacy of self-hosted instances as mentioned on #3608

Changed the crisp-wrapper to only use crisp when env is set

---

packages/ui/src/icons/priority-icon.tsx
web/components/dropdowns/priority.tsx

Updated the `urgent priority` icon to match the figma designs.
This PR is linked to [WEB-917](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/162170ce-2efc-43d0-96a1-b46b8b74f7e9)

[WEB-917] style: update urgent priority icon design.

---

web/store/issue/issue-details/subscription.store.ts

The subscribe/unsubscribe button wasn't mutating properly due to incorrect updates in the MobX store. The store structure was [issueId] -> [userId] -> boolean (subscribed or not). However, updates were incorrectly performed using `set(this.subscriptionMap, [issueId, currentUserId], { subscribed: true | false });`, resulting in improper state updates mapped to objects instead of boolean values.
Resolved the issue by appropriately setting the state using `set(this.subscriptionMap, [issueId, currentUserId], true | false);`.
* Before
[scrnli_4_9_2024_1-53-45 PM.webm](https://github.com/makeplane/plane/assets/33979846/db4f261a-ba55-4c05-8bc3-96c13ef165ba)
* After
[scrnli_4_9_2024_1-52-31 PM.webm](https://github.com/makeplane/plane/assets/33979846/c06ddd63-3864-4fe6-8291-be75db1f4616)
This PR …

[WEB-903] fix: issue subscription button mutation.

---

web/components/headers/cycle-issues.tsx

* Before
* After
This PR is linked to [WEB-924](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/825dd805-7419-4dfd-897b-20a30e0e7344)

[WEB-924] chore: remove `Add Issues` button from completed cycles header.

---

web/components/dropdowns/date.tsx
web/components/issues/issue-layouts/kanban/block.tsx
web/components/issues/issue-layouts/properties/all-properties.tsx
web/components/issues/issue-layouts/properties/labels.tsx

- Kanban card icon color improvement.
- The entire Kanban card is now clickable for improved functionality.
| ![before](https://github.com/makeplane/plane/assets/121005188/234a897d-44a2-4f58-97f2-bd4374cce49a) | ![after](https://github.com/makeplane/plane/assets/121005188/3933b421-ad23-4fd3-bae5-11a0a946358a) | 
| ![before](https://github.com/makeplane/plane/assets/121005188/25cbce31-8290-48c3-af8d-f754a307ff40) | ![after](https://github.com/makeplane/plane/assets/121005188/640925ef-218a-4d50-9d59-caf7c9d80806) |

[WEB-905] chore: kanban card icon color improvement

---

web/components/issues/issue-layouts/kanban/block.tsx

- There were issues with title padding in the Kanban layout that have been addressed.

[WEB-931] chore: kanban card padding improvement

---

apiserver/plane/license/management/commands/configure_instance.py

The `Turn SSL off/on` setting did not get saved on PATCH because it was missing in config keys.

fix: email ssl setting not getting saved

---

web/components/api-token/modal/form.tsx

- The API token key generation process currently sends NULL as the expiry time, regardless of the selected timeframe from the dropdown menu.
- Identified and resolved the issue by ensuring that the selected timeframe from the dropdown menu is properly reflected in the API token key generation process.

[WEB-932] fix: api token expiry time

---

web/components/issues/peek-overview/view.tsx

1. Drag handles are getting positioned incorrectly in the modal layout of the issue modal overview.
1. Updated the modal layout implementation of the peek overview to support drag handles properly.

[WEB-935] fix: drag handle position in the issue modal overview

---

web/components/issues/issue-layouts/kanban/block.tsx

[WEB-905](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/b056c127-e5f7-4dd7-bdc2-a03d6c60fb48)
This PR fixes the bug that was stopping from making the entire Kanban block as clickable
This also fixes the regression that caused the kanban title tooltip to be aligned center rather than left

[WEB-905] fix: make entire Kanban issue block clickable

---

packages/types/src/inbox.d.ts
web/components/inbox/inbox-filter/applied-filters/index.ts
web/components/inbox/inbox-filter/applied-filters/root.tsx
web/components/inbox/inbox-filter/applied-filters/state.tsx
web/components/inbox/inbox-filter/filters/filter-selection.tsx
web/components/inbox/inbox-filter/filters/index.ts
web/components/inbox/inbox-filter/filters/state.tsx
web/store/inbox/project-inbox.store.ts

This pull request involves the integration of the project state filter into the project inbox issues.
| <img width="467" alt="Screenshot 2024-04-13 at 2 21 53 PM" src="https://github.com/makeplane/plane/assets/28592219/19c108bb-514c-4b6e-87d8-62215d7f7a68"> | <img width="468" alt="Screenshot 2024-04-13 at 2 22 20 PM" src="https://github.com/makeplane/plane/assets/28592219/55fedf85-a273-48db-b2e0-4eebd0e6c4d1">  | 
| <img width="467" alt="Screenshot 2024-04-13 at 2 22 05 PM" src="https://github.com/makeplane/plane/assets/28592219/69eb36d8-346c-4b7a-8953-dfa26d20d79c"> | <img width="469" alt="Screenshot 2024-04-13 at 2 22 33 PM" src="https://github.com/makeplane/plane/assets/28592219/3e87afac-8704-452b-a159-6cec8d38b16c"> |

[WEB-984] feat: integrated state filter in inbox issues filter

---

web/components/pages/list/root.tsx
web/components/pages/list/tab-navigation.tsx
web/components/pages/pages-list-main-content.tsx
web/components/pages/pages-list-view.tsx
web/pages/[workspaceSlug]/projects/[projectId]/pages/index.tsx
web/store/pages/project-page.store.ts

1. Switching between projects did not update the list of pages.
2. Switching between tabs(Public, Private and Archived) rapidly did not update the list of pages.
1. Added the missing `projectId` check to the pages list computed function.
2. Updated the logic to update the active page tab.

[WEB-994] fix: pages list mutation between projects

---

apiserver/plane/app/views/workspace/invite.py

fix: 
- invalidate workspace members cache when someone accepts workspace invitation
[[WEB - 1006]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/4965f4b4-d903-4e70-90f2-4832ea5ca0a9)

[WEB - 1006] fix: remove caching when joining workspace

---

web/components/issues/issue-detail/issue-activity/comments/root.tsx
web/constants/empty-state.ts

- This PR include issue comment section empty state.
| ![before-1](https://github.com/makeplane/plane/assets/121005188/9f839ee0-3592-4769-b4ed-18b20668236e) | ![after-1](https://github.com/makeplane/plane/assets/121005188/1fe61bac-707b-47d3-b782-3f9727d78a30) |
| ![before-2](https://github.com/makeplane/plane/assets/121005188/7376197b-5a70-4c28-b1fd-0fde4801c8c1) | ![after-2](https://github.com/makeplane/plane/assets/121005188/a4e1997d-51c4-49ac-ac43-83d6148d43b1) |

[WEB-863] chore: issue comment empty state added

---

web/components/core/render-if-visible-HOC.tsx

[WEB-1012](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/49e2b94e-f76e-4472-a3ea-73aadc335fc9)
This PR fixes a rare scenario when some issue blocks are blank instead of being rendered. This is done by making sure the intersection observer checks the last(latest) entry instead of the first one

[WEB-1012] fix: empty blocks due to virtualization in rare cases

---

apiserver/plane/db/management/commands/create_instance_admin.py

chore: 
- This pull request introduces a management script responsible for creating an instance admin.
Issue Link: [WEB-1017](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/7d3f2b16-c92c-49d0-ac85-cdcbeb246cb4)

[WEB-1017] chore: instance admin script

---

web/components/issues/issue-detail/issue-activity/comments/comment-create.tsx

- Due to recent editor refactoring, the validation for empty comments was removed, resulting in unintended behavior.
- I have addressed this issue by implementing validation for empty comments.

[WEB-929] fix: issue comment validation

---

packages/editor/core/src/hooks/use-editor.tsx
packages/editor/core/src/ui/extensions/custom-list-keymap/list-keymap.ts
packages/editor/core/src/ui/extensions/index.tsx
packages/editor/document-editor/src/ui/index.tsx
packages/editor/lite-text-editor/src/ui/index.tsx
packages/editor/rich-text-editor/src/ui/index.tsx

Tab key behaviour fixed for `tabIndex` containing editor instances containing while keeping the sane behaviour for lists and code blocks' tab key methods...

[WEB-480] fix: tab key behaviour fixed for tabIndex containing editor instances

---

apiserver/plane/app/views/page/base.py
web/components/pages/dropdowns/quick-actions.tsx
web/components/pages/editor/header/options-dropdown.tsx
web/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx
web/store/pages/page.store.ts
web/store/pages/project-page.store.ts
yarn.lock

1. If a person without access tries to view a private page, the screen gets stuck in a loading state.
2. Admins are able to make a page private.
1. Unauthorized pages now show an error state.
2. Only owners can make a page private/public.
1. All requests in the page store now throw an error from the catch block.
2. Refactored the logic to render items in the page quick actions menu.

[WEB-1019] chore: error state for unauthorized pages

---

packages/ui/src/form-fields/textarea.tsx
packages/ui/src/hooks/use-auto-resize-textarea.ts
web/components/pages/editor/editor-body.tsx
web/components/pages/editor/title.tsx

1. The page title shrinks to single line on the initial load.
2. No validation for maximum length of the page title.
3. Page title overflows in some conditions.
1. Updated the `useAutoResizeTextArea` hook to resize the textarea on initial load as well as content change.
2. Added a title length indicator on the page title textarea with max length validation.
3. Replaced `margin` with `padding` to prevent page title overflow.
https://github.com/makeplane/plane/assets/65252264/49f65cb2-1459-422f-974b-e1834d8c1209

[WEB-1024] fix: textarea component auto-resize

---

web/components/cycles/quick-actions.tsx
web/components/headers/projects.tsx
web/components/inbox/inbox-filter/sorting/order-by.tsx
web/components/modules/dropdowns/order-by.tsx
web/components/modules/modules-list-view.tsx
web/components/modules/quick-actions.tsx
web/components/pages/list/order-by.tsx
web/components/project/dropdowns/order-by.tsx
web/store/cycle_filter.store.ts
web/store/module_filter.store.ts
web/store/pages/project-page.store.ts
web/store/project/project_filter.store.ts

1. When searching for a page, cycle or a module using the input field, the search query persists across projects. The search query also persists for projects list search across workspaces.
1. Added a `reaction` in the respective stores to clear the search query on `projectId` change from the route.
1. Fixed the empty state of modules list page on search via query.

[WEB-1026] chore: clear search query on project change

---

web/components/issues/issue-detail/main-content.tsx
web/components/issues/issue-detail/root.tsx
web/components/issues/peek-overview/issue-detail.tsx
web/components/issues/peek-overview/view.tsx

Comments got disabled for guests/ viewers while we were disabling it for archived issue.
Added separate validation based on user role and issue archival status to only disable comments when issue is archived.
This PR is linked to [WEB-1028 ](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/e5f4c457-bfbf-45ce-8a9b-b68a19ab8242)

[WEB-1028] fix: enable comments and issue reactions for guest/ viewer.

---

web/components/issues/peek-overview/header.tsx

Added tooltips to peek overview `close`, `issue detail` and `toggle layout` icons.
This PR is linked to [WEB-872](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/2dddb829-6c11-4535-8c99-723cd255e12c)

[WEB-872] chore: add tooltip to peek overview header icons.

---

web/components/project/confirm-project-member-remove.tsx

When leaving the project through members settings page, the UX copy was incorrect. 
Updated the UX copy.
* Before
* After
This PR is linked to [WEB-871](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/25613712-a939-4710-9dbb-f7cab1be0a51)

[WEB-871] chore: update leave project modal message in members settings page.

---

packages/ui/src/form-fields/textarea.tsx
web/components/dropdowns/project.tsx
web/components/issues/issue-layouts/filters/applied-filters/cycle.tsx
web/components/issues/issue-layouts/filters/applied-filters/filters-list.tsx
web/components/issues/issue-layouts/filters/applied-filters/module.tsx
web/components/issues/issue-layouts/list/block.tsx
web/components/project/project-feature-update.tsx
web/components/project/sidebar-list-item.tsx

1. List layout issue title overflow fix.
2. Project feature toggle modal project name overflow fix.
3. App sidebar project section alignment fix.
4. Peek overview & Issue detail issue title resize fix.
5. Create issue modal project select overflow fix.
6. Module and Cycle applied filters overflow fix.
| ![1-before](https://github.com/makeplane/plane/assets/121005188/8a2c39dc-31e3-4537-9fb7-0c114ebf83bc) | ![1-after](https://github.com/makeplane/plane/assets/121005188/3c605e79-525c-4398-b5e3-eb3b813cbc86) | 
| ![2-before](https://github.com/makeplane/plane/assets/121005188/0fed688f-44a7-4443-b4c7-b2218c2f56ab) | ![2-after](https://github.com/makeplane/plane/assets/121005188/870dc2ba-3e5d-4970-a24e-cf2765d43546) | 
| …

[WEB-1027] fix: overflow & alignment fixes

---

web/components/dropdowns/priority.tsx

Issue priority text color was not according to custom theme's text color. 
Update the UI to use custom theme's text color.
* Before
* After
This PR is linked to [WEB-857](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/e2587665-7d06-43b6-933f-9b5a9c7e6619)

[WEB-857] chore: update issue priority text color for custom theme in spreadsheet layout.

---

web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
web/components/issues/issue-layouts/kanban/default.tsx
web/components/issues/issue-layouts/kanban/headers/sub-group-by-card.tsx
web/components/issues/issue-layouts/kanban/swimlanes.tsx

- This PR include improvement for kanban layout sub-grouping ui and sub-group icon fix.
| ![before](https://github.com/makeplane/plane/assets/121005188/664595a6-7bd9-44ca-9d9f-9b5eb3f5b993) | ![after](https://github.com/makeplane/plane/assets/121005188/7c7abb89-3646-460e-a210-6e4f8027c362) |

[WEB-911] chore: kanban layout sub-grouping ui improvement

---

space/components/editor/lite-text-editor.tsx
web/components/editor/lite-text-editor/lite-text-editor.tsx

- Recent refactoring of the editor has altered the validation for empty comments, causing the comment button to be disabled when mentioning someone.
- I have addressed this issue by implementing necessary validation.

[WEB-929] fix: comment text editor user mention validation added

---

web/components/issues/issue-layouts/kanban/block.tsx

- User with guest and viewer permission are able to perform drag and drop which is not intended behaviour.
- Addressed this issue by implementing the required validation to kanban.

[WEB-1038] fix: kanban layout drag permission validation

---

web/store/issue/cycle/issue.store.ts
web/store/issue/module/issue.store.ts
web/store/issue/project-views/issue.store.ts
web/store/issue/project/issue.store.ts

- Quick add isn't functioning correctly in the kanban layout when grouped by cycle or module.
- Addressed this issue by implementing the required changes in the store.
| ![2a6f61d4-cd52-438a-be91-a67ebb34a111](https://github.com/makeplane/plane/assets/121005188/e6c733f6-4ec1-4e2f-8f35-316a2d6cd054) | ![39544a49-b542-409a-be0e-60d65dd18c7e](https://github.com/makeplane/plane/assets/121005188/8384b3b6-fb35-4d13-a02d-8b4fed445a6e) |

[WEB-1015] fix: kanban layout cycle and module quick add

---

web/components/issues/issue-modal/form.tsx

- The initial value is not retained when creating an issue with the "create more" toggle enabled.
- Resolve this by adjusting the form reset to include the provided data when the "create more" toggle is active.
| ![93911db0-636e-4a50-bb14-3be5a754e412](https://github.com/makeplane/plane/assets/121005188/28478de4-f7f7-47c8-8f34-e950738d6b78) | ![d7fbb1fe-07c8-406d-b825-c0841f640522](https://github.com/makeplane/plane/assets/121005188/d635e012-b724-4d53-8c7f-077cfa76d7c8) |

[WEB-1041] fix: preserve initial value on create more issues

---

web/components/core/sidebar/single-progress-stats.tsx

In this PR, I've updated the progress stats UI, specifically by removing the circular progress bar.
| ![before](https://github.com/makeplane/plane/assets/121005188/b27ce07b-a720-4191-a7fa-a485f9418fec) | ![after](https://github.com/makeplane/plane/assets/121005188/a4f3b799-a3a3-4ba1-933b-ebd83bde36f7) |

[WEB-1009] chore: active cycle stats improvement

---

web/components/empty-state/empty-state.tsx

- Dashboard empty state button remains disabled upon initial load, even when the user has admin permissions.
- I've resolved this by adding mobx observer into the empty state component.
| ![before](https://github.com/makeplane/plane/assets/121005188/d4aa79ec-335c-4965-a678-47006de089dc) | ![after](https://github.com/makeplane/plane/assets/121005188/681d89f0-bb38-4a23-a31d-76d246843355) |

[WEB-1021] fix: empty state action button permission

---

web/components/labels/delete-label-modal.tsx

- In this PR, I've revised the content of the modal for deleting labels.
| ![before](https://github.com/makeplane/plane/assets/121005188/4a9215d9-e251-406d-806e-b2bc8a059b3b) | ![after](https://github.com/makeplane/plane/assets/121005188/3aa08ac6-1c17-40f6-9898-41a94a7a657a) |

[WEB-870] chore: delete label modal content updated

---

web/components/issues/issue-layouts/filters/header/filters/state.tsx

- Currently, filter state options are listed alphabetically instead of following intended order: 
Backlog group > Unstarted group > Started group > Completed group > Cancelled group.
- I've reordered the filter state options to match the correct sequence.
| ![WEB-1051-B](https://github.com/makeplane/plane/assets/121005188/b53eb83e-f213-4b22-b196-f02e5ba07780) | ![WEB-1051-A](https://github.com/makeplane/plane/assets/121005188/a9f17cdf-5521-45f9-b44f-45416834104c) |

[WEB-1051] fix: filter state option order

---

web/components/core/sidebar/sidebar-progress-stats.tsx
web/components/cycles/sidebar.tsx
web/components/modules/sidebar.tsx

This PR brings back the ability for module and cycle sidebar stats items to apply filters with a click, just like before. Clicking once applies the filter, and clicking again removes it.
| ![before](https://github.com/makeplane/plane/assets/121005188/ff11abb0-ce3e-4c64-a3cb-2a3ed1faebf5) | ![after](https://github.com/makeplane/plane/assets/121005188/d7c940b5-34e0-4747-a8e4-56377d4b14d9) |

[WEB-1053] chore: module and cycle sidebar stats item filter implementation

---

web/components/modules/dropdowns/filters/lead.tsx
web/components/modules/dropdowns/filters/members.tsx
web/components/pages/list/filters/created-by.tsx
web/components/project/dropdowns/filters/lead.tsx
web/components/project/dropdowns/filters/members.tsx

This PR improves the ordering of the member filter options. Previously, they were listed alphabetically. Now, selected members are shown first, followed by the current user, and then the unselected options. This change enhances user experience by making it easier to find and manage members within the filter feature.
| ![before](https://github.com/makeplane/plane/assets/121005188/851611c1-e5d4-42ef-93af-654b0bfb47cc) | ![after](https://github.com/makeplane/plane/assets/121005188/321342d5-c24e-4f99-86bf-64cabdaa05dc) |

[WEB-1057] chore: updated member filter option ordering

---

web/components/command-palette/command-modal.tsx

1. Pressing `Esc` key on the Command K modal when search term is present doesn't do anything.
1. Pressing `Esc` key now clears the search term.

[WEB-1074] chore: clear search term on escape key

---

web/constants/issue.ts

- This PR adds show sub-issues option to profile display filter.
| ![before](https://github.com/makeplane/plane/assets/121005188/fc194128-a9a7-4303-88da-453f733b26cb) | ![after](https://github.com/makeplane/plane/assets/121005188/90488153-b456-4b7f-85a0-8b5d4433d28f) |

[WEB-1071] chore: show sub-issue option added to profile display filter

---

web/constants/cycle.ts

This PR ensures that the colors used for the active cycle linear progress and state list are consistent. Previously, they were different, causing visual inconsistency. This change enhances the overall appearance and user experience of the project.
| ![before](https://github.com/makeplane/plane/assets/121005188/6256ebfc-1ca8-4937-a86a-1c5a6c8c6487) | ![after](https://github.com/makeplane/plane/assets/121005188/bae1f65b-2f73-4896-b19e-029de2bef3c7)

[WEB-1070] chore: project active cycle linear progress and state list color consistency

---

packages/ui/src/control-link/control-link.tsx
web/components/issues/issue-layouts/kanban/block.tsx

[WEB-1073](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/399b618a-bb69-46ff-95df-a8de020036b0)
This PR fixes the Pragmatic Dnd for Firefox and Safari. For the finding i was able to check that because of the Anchor tag, it was interfering with the library's drag and drop implementation. Unless the Anchor tag itself is made into a draggable element.

[WEB-1073] fix: Kanban dnd to work as tested on Chrome, Safari and Firefox

---

web/components/inbox/content/inbox-issue-header.tsx
web/components/inbox/content/inbox-issue-mobile-header.tsx
web/components/inbox/content/index.ts
web/components/inbox/content/root.tsx
web/components/inbox/root.tsx
web/components/inbox/sidebar/inbox-list-item.tsx
web/components/inbox/sidebar/inbox-list.tsx
web/components/inbox/sidebar/root.tsx
web/components/issues/issue-layouts/filters/header/helpers/dropdown.tsx

https://github.com/makeplane/plane/assets/94619783/143f5cf9-160f-41cc-b4d9-9efb3bd6bb15
1. Moved all the header actions into the action menu.
<br/>
This PR is attached to the issue [WEB-704](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/818c1c35-65f3-48b4-97c4-c8d8b255f3f2)

[WEB-704] fix: inbox responsiveness

---

packages/editor/core/src/hooks/use-editor.tsx
packages/editor/core/src/lib/editor-commands.ts
packages/editor/core/src/styles/editor.css
packages/editor/core/src/ui/menus/menu-items/index.tsx
packages/editor/document-editor/src/ui/menu/block-menu.tsx
packages/editor/extensions/src/extensions/drag-drop.tsx
packages/editor/rich-text-editor/src/ui/menus/bubble-menu/index.tsx
packages/editor/rich-text-editor/src/ui/menus/bubble-menu/node-selector.tsx
space/constants/editor.ts
web/components/pages/editor/header/toolbar.tsx
web/constants/editor.ts

1. This PR introduces `H4` to `H6` heading components to the document and the rich-text editors.
2. Updated the UI of the node dropdown of the rich-text editor.
https://github.com/makeplane/plane/assets/65252264/c01e3feb-ebe4-4f9c-9bb6-bcb194efd154

[WEB-436] chore: added h4 to h6 heading options

---

deploy/coolify/coolify-docker-compose.yml
docker-compose-local.yml
docker-compose.yml

The redis version in the selft hosted docker compose file was 7.2.4 while others was 6.2.7, making a commit to set all redis versions to 7.2.4 and make all of them consistent.

make redis version same as the one in selfhosted docker-compose

---

web/constants/page.ts

- This PR removes the "Last Opened" option from the pages order by dropdown.
| ![before](https://github.com/makeplane/plane/assets/121005188/f190b982-0244-419e-8b71-91a9aaefc1ff) | ![after](https://github.com/makeplane/plane/assets/121005188/19ec1733-1f83-4554-bba2-6db709be7d08) |

[WEB-1085] chore: pages order by options

---

web/components/api-token/modal/form.tsx
web/components/estimates/create-update-estimate-modal.tsx
web/components/views/form.tsx
web/components/workspace/views/form.tsx

This PR addresses an issue with the description height in the View, Token, and Estimate Create modal, ensuring consistent and appropriate display of descriptions.
| ![before](https://github.com/makeplane/plane/assets/121005188/8bdaade7-17e9-4f3c-9c4c-3ea096798990) | ![after](https://github.com/makeplane/plane/assets/121005188/dd0dccbd-ff10-4f79-9cbf-f19b8990035b) |
| ![before](https://github.com/makeplane/plane/assets/121005188/8c0d8145-40af-4ef9-8100-c97a3ca4be28) | ![after](https://github.com/makeplane/plane/assets/121005188/f1019c3f-9ede-4943-b607-46396bbc2b6b) |
| ![before](https://github.com/makeplane/plane/assets/121005188/5c95fffd-81d8-4090-8791-a90a334c7e88) | ![after](https://github.com/makeplane/plane/assets/121005188/37136e87-4852-491e-9747 …

[WEB-1078] fix: view, api token and estimate modal description height

---

packages/ui/src/button/toggle-switch.tsx

This PR addresses an issue where the toggle switch component's off state was not appearing as intended. The changes implemented ensure that the off state of the switch toggle component is displayed correctly.
| ![before](https://github.com/makeplane/plane/assets/121005188/5019f09d-ccbe-4ffa-a098-783b65fe6fe7) | ![after](https://github.com/makeplane/plane/assets/121005188/b57c3a41-3ced-4ab1-938b-20185fef8f28) |

[WEB-1090] fix: toggle switch component off state appearance

---

packages/editor/core/src/hooks/use-editor.tsx
packages/editor/core/src/ui/extensions/index.tsx
packages/editor/document-editor/src/ui/index.tsx
packages/editor/lite-text-editor/src/ui/index.tsx
packages/editor/rich-text-editor/src/ui/index.tsx
web/components/inbox/modals/create-edit-modal/issue-description.tsx
web/components/issues/description-input.tsx
web/components/issues/issue-modal/form.tsx
web/helpers/issue.helper.ts

1. When description is not empty, show `Press '/' for commands...` as the placeholder.

[WEB-1115] fix: issue description placeholder

---

web/constants/dashboard.ts

Change _none_ label for _all time_ in dashboard filters
Before 
After

feat(dashboard): improve label readability

---

web/styles/globals.css

[WEB-1096](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/12d4c109-dc99-493d-9671-2e0e7d223fae)
This Fix adds the appropriate missing css to fix the writing mode for kanban collapsed mode

[WEB-1096] fix: kanban collapsed vertical writing mode in firefox

---

apiserver/plane/api/views/issue.py
apiserver/plane/app/views/cycle/issue.py
apiserver/plane/app/views/issue/archive.py
apiserver/plane/app/views/issue/base.py
apiserver/plane/app/views/issue/draft.py
apiserver/plane/app/views/issue/sub_issue.py
apiserver/plane/app/views/module/archive.py
apiserver/plane/app/views/module/base.py
apiserver/plane/app/views/module/issue.py
apiserver/plane/app/views/view/base.py
apiserver/plane/utils/user_timezone_converter.py

fix: 
- This enhancement ensures that DateTime fields are displayed in the format corresponding to the user's time zone.
Issue Link: [WEB-1132](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/ed04d001-f16d-472c-afe2-082680eff694)

[WEB-1132] fix: display datetime fields in user time zone format

---

web/components/issues/issue-layouts/quick-action-dropdowns/all-issue.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/archived-issue.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/cycle-issue.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/draft-issue.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/module-issue.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx
web/components/workspace/views/default-view-quick-action.tsx
web/components/workspace/views/header.tsx
web/components/workspace/views/index.ts
web/components/workspace/views/quick-action.tsx

- Added quick action on clicking active tabs or via right-click.
- Introduced options to open in a new tab and copy view link.
- Issue quick action fix and code refactor. 
| Media |
|--------|
| ![img-1](https://github.com/makeplane/plane/assets/121005188/310f5f2a-d88b-4819-b6c0-7d33e770d139) |
| ![img-2](https://github.com/makeplane/plane/assets/121005188/c6339b6f-44f3-4bf2-9a76-aa2d35846898) |

[WEB-1101] chore: workspace view quick action enhancement

---

web/components/dashboard/widgets/recent-collaborators/collaborators-list.tsx

1. In the recent collaborators page, current user's profile displays `Y` as the avatar instead of the first character of the user's display name.
1. Changed the avatar character to the first character of the current user's display name.

[WEB-1105] chore: show display name's first character in the avatar

---

packages/types/src/pages.d.ts
web/components/pages/editor/editor-body.tsx
web/components/pages/editor/header/mobile-root.tsx
web/components/pages/editor/header/options-dropdown.tsx
web/components/pages/editor/header/root.tsx
web/hooks/use-page-filters.ts
web/store/pages/page.store.ts

1. Store the page full width information in the local storage to make it unique for each user, also now guests and viewers will be able to toggle full width and even a locked or archived page's width can be toggled which was not possible earlier.

[WEB-1135] chore: store page full width information in local storage

---

web/components/modules/modules-list-view.tsx
web/pages/[workspaceSlug]/projects/[projectId]/modules/index.tsx

This PR resolves the sub-header rendering issue on the module list page.
| ![before](https://github.com/makeplane/plane/assets/121005188/36d79e0a-00f8-4cbe-8a50-a4b8527b4141) | ![after](https://github.com/makeplane/plane/assets/121005188/fcc02bda-bd38-406b-a151-86e2f3dc1cad) |

[WEB-1146] fix: module sub-header empty state validation

---

web/components/issues/attachment/attachment-detail.tsx
web/components/issues/attachment/delete-attachment-modal.tsx
web/components/issues/attachment/index.ts
web/store/issue/issue-details/root.store.ts

1. Trying to delete an attachment is not possible, the delete attachment modal only deletes the last attachment on the list.
1. MobX store value to toggle the delete attachment modal was common for all the attachments, resulting in a conflict in the delete modals. Resolved the issue by using `attachmentId` to validate if the delete modal should be opened or not.

[WEB-1154] fix: delete attachment modal logic

---

web/components/cycles/quick-actions.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/all-issue.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/archived-issue.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/cycle-issue.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/draft-issue.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/module-issue.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx
web/components/modules/quick-actions.tsx
web/components/pages/dropdowns/quick-actions.tsx
web/components/project/card.tsx
web/components/views/quick-actions.tsx
web/components/workspace/views/default-view-quick-action.tsx
web/components/workspace/views/quick-action.tsx

1. Hide `Copy link` and `Open in new tab` options from the context menu of archived projects.
2. Disable options are now actually disabled and not just visually disabled in the quick actions drop-downs thorughout.

[WEB-1143] fix: project context menu

---

packages/editor/lite-text-editor/src/ui/index.tsx
web/components/issues/issue-detail/issue-activity/comments/comment-create.tsx
web/components/issues/issue-detail/issue-activity/root.tsx

This PR fixed the add comment card persisting data while switching between inbox issues
https://github.com/makeplane/plane/assets/73993394/2b15218c-de30-4be1-9c39-b7522937ed18
https://github.com/makeplane/plane/assets/73993394/f1299804-0b23-4574-8017-91ccdcc2c853

[WEB-1102 ] fix: inbox create issue comment fixed

---

web/components/issues/attachment/attachment-upload.tsx
web/components/issues/attachment/root.tsx

1. In inbox issues, trying to upload an attachment in any of the issues uploads that attachment to the first loaded issue.
1. Updated the dependencies of the `useCallback` hook to updated the `issueId` on change of issue.

[WEB-1126] fix: inbox issue attachment upload

---

web/constants/issue.ts

1. Hide display properties section from the calendar layout.

[WEB-1109] chore: hide display properties in the calendar layout

---

web/components/gantt-chart/chart/root.tsx
yarn.lock

1. The peek overview doesn't open in Gantt chart full screen view.
1. Decreased the `z-index` of the Gantt chart full screen view to 20.
https://github.com/makeplane/plane/assets/65252264/4d41d8e5-f1b2-48cb-8345-dc6ffd531c80

[WEB-1171] fix: peek overview in Gantt chart full screen view

---

web/components/editor/rich-text-editor/rich-text-editor.tsx
web/components/editor/rich-text-editor/rich-text-read-only-editor.tsx
web/components/inbox/content/issue-root.tsx
web/components/inbox/modals/create-edit-modal/create-root.tsx
web/components/inbox/modals/create-edit-modal/edit-root.tsx
web/components/inbox/modals/create-edit-modal/issue-description.tsx
web/components/issues/issue-detail/main-content.tsx
web/components/issues/issue-modal/form.tsx
web/components/issues/peek-overview/issue-detail.tsx

1. The issue description earlier had a fixed minimum height which made sense when it had a border, now, with this PR, editor takes up the height according to the content height.
https://github.com/makeplane/plane/assets/65252264/39e66af4-6fd1-469a-9559-36470bfe4821

[WEB-1179] style: make editor height according to the content height

---

apiserver/plane/bgtasks/api_logs_task.py
apiserver/plane/celery.py
apiserver/plane/settings/common.py

chore: 
- This pull request addresses the functionality of deleting API logs that are older than 30 days.
Issue Link: [WEB-1206](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/53a28821-eee6-482c-b77b-7e1cc49a2fe3)

[WEB-1206] chore: bulk delete api logs

---

web/components/issues/issue-layouts/kanban/headers/group-by-card.tsx

[WEB-1137](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/ae4f7850-f9f3-4552-a833-c2a62b8dd508)
This PR fixes the Vertical Skewed text of  Kanban header in Firefox.

[WEB-1137] fix: Firefox distorted vertical text

---

web/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx

This PR resolves the issue with invalid issue ID causing an indefinite loading screen and instead renders the proper error page.
| ![before](https://github.com/makeplane/plane/assets/121005188/7937f707-e2e7-49eb-b8b4-345f4a822f4b) | ![after](https://github.com/makeplane/plane/assets/121005188/654d044f-77b7-44ef-8e48-91421ce06326) |

[WEB-1007] chore: invalid issue error empty state added

---

web/components/issues/select/label.tsx
web/components/ui/labels-list.tsx

This PR addresses the inconsistency in the label select  within the create/update issue modal.
| ![before](https://github.com/makeplane/plane/assets/121005188/305dc1c2-77cf-456c-8f96-81ce9f99309a) | ![after](https://github.com/makeplane/plane/assets/121005188/cdae9324-e604-4662-8fdb-1ecd77cdfb6c) |

[WEB-1157] chore: label select improvement

---

apiserver/plane/bgtasks/email_notification_task.py
apiserver/plane/bgtasks/notification_task.py

fix:
- This pull request fixes the bug for sending email notifications to mentioned users.
- Also enables the filter for the mentioned user.

[WEB-1151] fix: email notification for mentions

---

web/components/core/sidebar/links-list.tsx
web/components/modules/sidebar.tsx
web/store/module.store.ts

This PR resolves the module sidebar link creation and deletion mutation.

[WEB-1134] fix: module link create and delete mutation

---

packages/ui/src/dropdowns/custom-search-select.tsx
packages/ui/src/dropdowns/custom-select.tsx

This PR resolves the issue where clicking on an opened dropdown did not close it for custom select and custom search select dropdowns.
| ![before](https://github.com/makeplane/plane/assets/121005188/74f423a0-9b34-4a18-b9b9-46f9c2fcc1c7) | ![after](https://github.com/makeplane/plane/assets/121005188/948c29d3-0910-4d3e-b45e-0b9615f838aa) |

[WEB-1098] chore: dropdowns enhancement

---

web/components/notifications/notification-card.tsx

Tooltip was not being show for Snooze button under notification panel. This was because the Tooltip component was wrapping the entire Menu instead of the Button. 
Made the necessary adjustment to fix this issue.
This PR is linked to [WEB-1117](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/07953785-066d-4a64-93b5-ab1793431d67)

[WEB-1117] chore: add tool tip for Snooze under Notification Panel.

---

web/components/cycles/archived-cycles/header.tsx
web/components/cycles/cycle-mobile-header.tsx
web/components/cycles/cycles-view-header.tsx
web/components/headers/cycle-issues.tsx
web/components/headers/global-issues.tsx
web/components/headers/module-issues.tsx
web/components/headers/project-draft-issues.tsx
web/components/headers/project-issues.tsx
web/components/headers/project-view-issues.tsx
web/components/headers/projects.tsx
web/components/issues/archived-issues-header.tsx
web/components/issues/issue-layouts/filters/header/helpers/dropdown.tsx
web/components/issues/issues-mobile-header.tsx
web/components/modules/archived-modules/header.tsx
web/components/modules/module-mobile-header.tsx
web/components/modules/module-view-header.tsx
web/components/pages/header/root.tsx
web/components/profile/profile-issues-filter.tsx
web/components/profile/profile-issues-mobile-header.tsx
web/components/project/projects-mobile-header.tsx
web/components/views/view-list-item-action.tsx
web/helpers/filter.helper.ts

- Applied filter indicator added to filter select dropdown.
- Code refactor.
| ![before](https://github.com/makeplane/plane/assets/121005188/914e1b44-436d-4927-90a2-5b68123387bd) | ![after](https://github.com/makeplane/plane/assets/121005188/2e7421f0-d3c2-41a9-abc3-cc0bf8ac8136) |

[WEB-1176] chore: filter dropdown indicator and code refactor

---

packages/editor/core/src/ui/plugins/upload-image.tsx

1. After an image is uploaded in any editor, the focus needs to persist, if the focus is changed to some other field while the image is being uploaded, it should stay there even after the upload has completed.
https://github.com/makeplane/plane/assets/65252264/fb73cfe7-2073-4b7b-85fb-14b6db5ca35f

[WEB-1113] fix: set focus on editor conditionally after image upload

---

apiserver/plane/app/views/module/base.py
apiserver/plane/bgtasks/webhook_task.py

fix:
- module webhook triggering multiple times for field update.
- added a check to validate key is present in the current instance.
[WEB - 1213](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/d920d2f2-9cff-40e2-9b46-2730f95ba72c)

[WEB - 1213] fix: module webhook

---

web/components/command-palette/command-palette.tsx

1. Command K modal cannot be triggered from input fields, textarea and editors.
1. Moved `Cmd + K` shortcut logic out of the input field restriction condition. Now, Command K modal can be triggered from anywhere, but cannot be opened if any other modal is open.
https://github.com/makeplane/plane/assets/65252264/1638d512-f0ce-46d5-84e4-b4870982e9ee
https://github.com/makeplane/plane/assets/65252264/c8dc0269-d8b2-4874-82e4-ef0cd9bd7aeb

[WEB-] chore: trigger command k from input fields and editors

---

web/components/modules/applied-filters/root.tsx
web/components/modules/archived-modules/root.tsx
web/components/modules/module-view-header.tsx
web/components/modules/modules-list-view.tsx
web/pages/[workspaceSlug]/projects/[projectId]/modules/index.tsx
web/store/module_filter.store.ts

When `Favorite` filter is applied, it's not being shown in applied filter section.
Made the necessary changes so that favorite filter can be shown and removed from the applied filter section.
[scrnli_5_8_2024_10-10-15 AM.webm](https://github.com/makeplane/plane/assets/33979846/fa0b230b-26cc-4d7d-9a90-f577ea0b879b)
**Plane Link: [WEB-1215](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/f6938d8c-6ee7-415e-981d-dbe7cb62f594)**

[WEB-1215] chore: display `favorite module` filter in applied filter section.

---

web/components/project/create-project-form.tsx

Height of `project type` and `project lead` were inconsistent in create project modal.
Added the required changes to adjust the height. 
* Before
* After
**Plane Link: [WEB-1217](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/f181d357-f60f-4ef1-b646-7baa3a53ed36)**

[WEB-1217] style: fix inconsistency in height of project type and lead dropdown in create project modal.

---

web/components/pages/pages-list-main-content.tsx
web/constants/empty-state.ts

`Create page` button was not available for public and private page empty states.
Added those buttons to the empty states.
* Before
* After
**Plane link: [WEB-1236](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/7b3f27b3-4a96-4001-811b-3da6ec05ec16)**

[WEB-1236] chore: add `Create page` button to public/ private page empty state.

---

packages/editor/core/package.json
packages/editor/document-editor/package.json
packages/editor/extensions/package.json
packages/editor/rich-text-editor/package.json
space/package.json
web/package.json
yarn.lock

This PR upgrades the `lucide-react` icons package version to the latest one- `0.378.0` for all the apps and packages.

dev: upgrade `lucide-react` version to the latest one

---

packages/editor/core/src/styles/editor.css
packages/editor/core/src/ui/extensions/index.tsx
packages/editor/core/src/ui/read-only/extensions.tsx

1. Todo list item sentences now break into next line for longer words.
| <video src="https://github.com/makeplane/plane/assets/65252264/d4b5a1a5-a05b-4d8d-8629-94ede6652b64"></video> | <video src="https://github.com/makeplane/plane/assets/65252264/bf2ecdaf-3f61-4ed1-aadb-4920f9f5dfbb"></video> |

[WEB-1208] fix: todo list item word break

---

web/components/inbox/content/root.tsx

1. Inbox issue description re-fetches on focus, overwriting any saving action going on, specifically image upload.
1. Disable issue details re-fetch on focus.
https://github.com/makeplane/plane/assets/65252264/9e38219d-2eef-4f35-8890-7fc8c757bf16

[WEB-1211] fix: inbox issue description revalidate

---

space/helpers/string.helper.ts
web/helpers/string.helper.ts

1. Uploading only an image as a comment is not supported.
1. Updated the sanitize method to **very strictly** accept `img` tags.
| <video src="https://github.com/makeplane/plane/assets/65252264/96cd1db2-ede3-4b5c-9ec1-899ecdd8a013"></video> | <video src="https://github.com/makeplane/plane/assets/65252264/f7c9d80f-81ea-4967-8d76-d5d09dbb90d5"></video> |

[WEB-1256] fix: accept image as a valid comment

---

web/components/issues/issue-layouts/filters/applied-filters/roots/archived-issue.tsx
web/components/issues/issue-layouts/filters/applied-filters/roots/cycle-root.tsx
web/components/issues/issue-layouts/filters/applied-filters/roots/draft-issue.tsx
web/components/issues/issue-layouts/filters/applied-filters/roots/module-root.tsx
web/components/issues/issue-layouts/filters/applied-filters/roots/project-root.tsx
web/components/issues/issue-layouts/filters/applied-filters/roots/project-view-root.tsx

This PR addresses an issue where the filter action button was incorrectly rendering at the center when the length of the applied filter exceeded 2 lines. This behavior was unintended, and this PR resolves it by making the necessary adjustments.
| ![before](https://github.com/makeplane/plane/assets/121005188/34d375a1-d974-4148-8079-ce77477c0fbd) | ![after](https://github.com/makeplane/plane/assets/121005188/9af43cf6-62c6-4ddc-9fae-a542a042ffe2) |

[WEB-1248] chore: applied filters update view button alignment improvement

---

web/components/modules/sidebar.tsx

[WEB-1134](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/8655410a-d3cb-4887-85ac-10ae8b892c77)
This PR fixes the module link mutation issue by referring the link_module property outside the disclosure. This could be the because of how <Disclosure> component is implemented.

[WEB-1134] fix: module link mutation issue

---

web/components/issues/issue-layouts/spreadsheet/issue-row.tsx

In the spreadsheet layout, the first column was not sticking to the left on horizontal scroll. This PR resolves this issue by implementing necessary changes.

fix: spreadsheet layout sticky column

---

web/components/headers/project-views.tsx
web/components/views/index.ts
web/components/views/view-list-header.tsx
web/components/views/view-list-item-action.tsx
web/components/views/views-list.tsx
web/store/project-view.store.ts

- Moved view list sub header to app header.
- Added creator avatar in view list item.
- Refactored code (moved view list search query to MobX)
| ![before](https://github.com/makeplane/plane/assets/121005188/bb37fdf0-0b46-466f-9db5-cf7532092d62) | ![after](https://github.com/makeplane/plane/assets/121005188/382bd381-7684-4913-bc1f-f8ec73aae95b) |

[WEB-1251] chore: view list enhancement

---

web/components/gantt-chart/chart/header.tsx
web/components/gantt-chart/chart/root.tsx
web/components/headers/modules-list.tsx
web/components/modules/module-card-item.tsx
web/components/modules/module-list-item-action.tsx
web/components/modules/module-list-item.tsx
web/pages/[workspaceSlug]/projects/[projectId]/modules/index.tsx

This PR includes the following module list page modifications:
- Moved the module list sub-header to the application header.
- Removed the Gantt title.
- Reduced the size of the progress indicator.
- Replaced member avatars with module leads.
| ![before](https://github.com/makeplane/plane/assets/121005188/1933ac20-0784-4ba9-9c7f-3e45c7eb38f6) | ![after](https://github.com/makeplane/plane/assets/121005188/1bf4b7e8-7717-4d5b-915d-ddfe257cc957) |
| ![before](https://github.com/makeplane/plane/assets/121005188/fcb02381-b24b-4754-8ed3-387bb2abe6ae) | ![after](https://github.com/makeplane/plane/assets/121005188/bc1c8924-6681-47b3-bfe7-3cc74c2b3a50) |
| ![before](https://github.com/makeplane/plane/assets/121005188/04739573-926d-4246-ba7a-9d856753d763) | …

[WEB-1250] chore: module list enhancement

---

web/components/project/card.tsx

This PR includes the following project list page modifications:
- Replaced the project card edit icon with a settings icon.
- Updated the project context menu option from "edit" to "settings".
| ![before](https://github.com/makeplane/plane/assets/121005188/35cfc5e8-83d1-4cd1-a7ab-35197439003c) | ![after](https://github.com/makeplane/plane/assets/121005188/66099abf-8098-47ee-9851-b54cb68414e5) |

[WEB-1252] chore: project card enhancement

---

web/components/dropdowns/module/index.tsx
web/components/issues/issue-layouts/spreadsheet/columns/cycle-column.tsx
web/components/issues/issue-layouts/spreadsheet/columns/module-column.tsx
web/components/issues/issue-layouts/spreadsheet/index.ts
web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
web/components/issues/issue-layouts/spreadsheet/spreadsheet-header.tsx

This PR contains the following spreadsheet layout adjustments:
- Improved indentation for sub-issues.
- Removed border and background from cycle and module select to maintain consistency with other properties.
| ![before](https://github.com/makeplane/plane/assets/121005188/4066444b-4470-4daa-9469-3b8109916d4c) | ![after](https://github.com/makeplane/plane/assets/121005188/a012dc43-ef64-4052-aff8-2b1e44d76697) |

[WEB-1274] chore: issue spreadsheet enhancement

---

web/components/project/publish-project/modal.tsx

Currently, when the project is published, the modal is closing, which is not intended behavior. The modal should remain open after publishing so that the user can copy the publish URL. I've resolved this issue by making necessary adjustments.
| ![before](https://github.com/makeplane/plane/assets/121005188/2e9f9327-79cb-4d67-a235-890b1fc3d6d8) | ![after](https://github.com/makeplane/plane/assets/121005188/13d2601f-dcb7-4c2e-9913-78521b6e879b) |

[WEB-1265] chore: project publish modal improvement

---

packages/editor/extensions/src/extensions/slash-commands.tsx

Focus of line changes to next line When user tries to create To-do list , Bullet List, Numbered List , Quote, Code using the bubble menu by stopping the `onClick` event propagation to other the editor container.

[WEB-1131] fix: button click propagation stopped

---

packages/editor/core/src/lib/editor-commands.ts
packages/editor/core/src/ui/extensions/table/table/table.ts
packages/editor/core/src/ui/props.tsx
packages/editor/extensions/src/extensions/drag-drop.tsx

1. Selections now occur properly, no matter the level of nesting.
2. Nesting with Tab for list items inside tables work as intended. 
3. Selection works for all kinds of nodes inside tables (or any nest able node)
4. Drag behaviour fixed for tables and block-quotes without clicking on it first.
https://github.com/makeplane/plane/assets/73993394/46931987-5cc8-4b06-8ae3-d981de1a44c7
For eg, this is how GitHub supports nested tables...
|                |ASCII                          |HTML                         |
|----------------|-------------------------------|-----------------------------|
|Single backticks|`'Isn't this fun?'`            |'Isn't this fun?'            |
|Quotes          |`"Isn't this fun?"`            |<table>  <thead>  <tr>  <th></th>  <th>ASCII</th>  <th>HTML</th> …

[WEB-1118] fix: table selections using drag handle fixed

---

web/components/cycles/board/cycles-board-card.tsx
web/components/cycles/list/cycle-list-item-action.tsx
web/components/cycles/list/cycles-list-item.tsx
web/components/headers/cycle-issues.tsx
web/components/headers/cycles.tsx
web/components/headers/global-issues.tsx
web/components/headers/module-issues.tsx
web/components/headers/modules-list.tsx
web/components/headers/page-details.tsx
web/components/headers/pages.tsx
web/components/headers/project-inbox.tsx
web/components/headers/project-issues.tsx
web/components/headers/project-view-issues.tsx
web/components/headers/project-views.tsx
web/components/headers/projects.tsx
web/components/issues/issue-layouts/list/block-root.tsx
web/components/issues/issue-layouts/list/block.tsx
web/components/issues/issue-layouts/list/default.tsx
web/components/issues/issue-layouts/save-filter-view.tsx
web/components/pages/list/block-item-action.tsx

This PR contains the following changes:
- Improved list layout indentation.
- Enhanced cycle list UI for better user experience.
| List layout |
|--------|
| ![listLayout](https://github.com/makeplane/plane/assets/121005188/e23954b4-ceb7-4cca-b10d-f1f90fdd1ba5) |
| Cycles |
|--------|
| ![cycles](https://github.com/makeplane/plane/assets/121005188/c8debd5a-92de-461e-a006-e31e38d056f4) |

[WEB-1254] chore: list layout indentation enhancement and cycle list page ui improvement

---

web/components/issues/issue-layouts/filters/header/filters/project.tsx

1. Project filters shows the list of all the projects, even the un-joined ones.
1. Access `joinedProjectIds` from the project store to display the list of projects.

[WEB-1271] fix: show only joined projects in the filters list

---

admin/app/setup/components/sign-up-form.tsx
space/components/accounts/auth-forms/password.tsx
web/components/account/auth-forms/password.tsx
web/pages/accounts/reset-password.tsx
web/pages/accounts/set-password.tsx
web/pages/profile/change-password.tsx

- Render "Password didn't match" only when the input loses focus (blur). Previously, the error message was displayed on each keystroke.
- Display password fields in a column layout. Previously, they were arranged in a row-wrap layout.
| ![before](https://github.com/makeplane/plane/assets/121005188/9360a587-3213-436b-bb34-148626c47c45) | ![after](https://github.com/makeplane/plane/assets/121005188/99fb60b0-61b7-43f0-86f7-8be83ac7c8f2) |

[WEB-1324] chore: change password page improvement

---

apiserver/plane/app/views/user/base.py
apiserver/plane/authentication/views/app/check.py
apiserver/plane/authentication/views/app/email.py
apiserver/plane/authentication/views/app/magic.py
apiserver/plane/authentication/views/space/magic.py
apiserver/plane/license/api/serializers/instance.py
apiserver/plane/license/api/views/admin.py
apiserver/plane/license/api/views/instance.py

- Fixes: the magic sign up by moving the inactive user check below the fetch.
- Fixes: The `last_workspace_id` redirection by invalidating the cache
- Refactor: remove unused variables and print statement
[[WEB - 1315]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/1645f06f-5e8c-4e0a-a44e-ab58419beae3)

[WEB - 1315] fix: user sign up and sign in on a deactivated account

---

apiserver/plane/authentication/provider/credentials/magic_code.py
apiserver/plane/authentication/views/app/magic.py

chore: 
- this pull request addresses the problem of redirecting to the previously accessed workspace after completing the sign-in process.
- resolved the `magic_` key error in the expired magic link code error message.
Issue Link: [WEB-1328](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/624ecc4f-f13f-4b32-9b9c-508d8427e98c)

[WEB-1328] chore: magic sign-in redirection

---

web/components/profile/overview/activity.tsx

This PR fixes the overflow issue with the user pic in the my activity section.
| ![before](https://github.com/makeplane/plane/assets/121005188/220f16c5-af9d-4e60-9d57-45a554342d7a) | ![after](https://github.com/makeplane/plane/assets/121005188/1091efa6-1521-469f-a33d-870f6cd9a26f) |

[WEB-1260] fix: my activity user image overflow

---

packages/constants/src/auth.ts
space/components/accounts/auth-forms/password.tsx
space/helpers/authentication.helper.tsx
web/components/account/auth-forms/password.tsx
web/helpers/authentication.helper.tsx

1. Added URL encoding before passing the email as a query param to support special characters.

[WEB-1327] chore: encode email before passing it as a query param

---

web/components/dashboard/widgets/recent-collaborators/collaborators-list.tsx

1. HId all bot accounts from the collaborators list widget in the dashboard.

[WEB-1205] chore: hide bot accounts from the collabortors list

---

web/components/issues/issue-modal/modal.tsx

1. After creating an issue, if the user opens the create issue modal again and discard without entering a value, the `Save as draft issue` modal pops up even though there's no data in the form.
1. Resetting the `changesMade` boolean flag to `null` after creating an issue.

[WEB-1210] chore: discard changes made after creating issue

---

web/hooks/use-reload-confirmation.tsx

1. When data is being saved in issue description or pages and the user tries to navigate to some other link, a confirm dialog pops up. If the user cancels the navigation, they still get navigated to that route.
1. Fixed `handleRouteChange` function to now prevent the user from navigating to the new route on Cancel.
https://github.com/makeplane/plane/assets/65252264/6baf0f9e-04e6-4ecf-81c0-823e4aabd6a5

[WEB-1258] chore: prevent route change on canceling confirm dialog

---

apiserver/plane/app/views/search.py
packages/types/src/project/projects.d.ts
web/components/core/modals/existing-issues-list-modal.tsx
web/components/issues/issue-layouts/calendar/day-tile.tsx
web/components/issues/issue-layouts/calendar/quick-add-issue-form.tsx

In the calendar layout, user can add an issue to a due date less than the start date of the issue by dragging or by the selecting issues from the existing issues list.
1. Disable drag and drop when an issue is dropped on a due date which is less than its start date.
2. HId issues with start date more than the due date to which the issues are being added.
1. While using drag and drop-
https://github.com/makeplane/plane/assets/65252264/bfdde885-b6e4-429c-b958-5d748da64ce8
2. While adding issues from the issues list modal-
https://github.com/makeplane/plane/assets/65252264/f56df54c-ecff-413e-bae7-be158008a12e

[WEB-1336] fix: issue dates conflict in the calendar layout

---

web/components/pages/editor/title.tsx
web/components/pages/list/block.tsx
web/helpers/page.helper.ts
web/store/pages/project-page.store.ts

1. Page title can now be blank. Blank titles will be display as `Untitled`.

[WEB-1310] chore: page title can be blank

---

web/components/issues/issue-layouts/kanban/block.tsx
web/components/issues/issue-layouts/kanban/blocks-list.tsx
web/components/issues/issue-layouts/kanban/kanban-group.tsx

[WEB-1249](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/84db6b08-7c33-47c1-9e8d-fe5a5e6be8bd)
This PR looks to improve the existing Kanban UX by,
- Increasing min height to empty sub groups
- not show drop indicator in rare cases when issues are not sorted by manual

[WEB-1249] fix: New Minor UX changes to Kanban

---

apiserver/plane/db/models/favorite.py

chore: 
- this pull request corrects the bug affecting the ability to mark items (e.g., cycle, module, issue, pages and views) as favorites due the key named sort order. 
Issue Link: [WEB-1357](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/04e14470-26fd-4b93-9ba8-b11e644acac3)

[WEB-1357] chore: user favorite sequence

---

web/store/pages/page.store.ts

1. Show `Untitled` for pages without a title.

[WEB-1366] fix: show untitle for blank page titles

---

web/store/pages/page.store.ts

1. Title of pages not being displayed.
1. Fixed the logic to store the page title.

[WEB-1366] fix: page title not appearing on the list

---

web/components/issues/issue-detail/issue-activity/comments/comment-block.tsx
web/components/issues/issue-detail/issue-activity/comments/comment-card.tsx

No mutation happening when comment is changed to public to private and vice verse
This was happening because the comment component was not wrapped around `observer`. 
* Before
[scrnli_5_20_2024_1-24-17 AM.webm](https://github.com/makeplane/plane/assets/33979846/11cbc6b8-de84-4786-97f4-44a2cc9dcac6)
* After
[scrnli_5_20_2024_1-22-57 AM.webm](https://github.com/makeplane/plane/assets/33979846/448d9183-3123-43bb-a228-7ba89d7da256)
This PR is linked to [WEB-1361](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/4bd80be3-abd8-4980-bbaa-fb6495c64ee0)

[WEB-1361] fix: comments access specifier mutation issue.

---

web/components/issues/issue-layouts/list/block.tsx

[WEB-1261](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/8b5fae0c-8731-424a-8aed-058faddfd24f)
This PR adds back the code to enable issue list mutation when an sub issue or parent issue is modified.
Adds back changes that were removed from https://github.com/makeplane/plane/pull/4415
https://github.com/makeplane/plane/assets/71900764/2a770852-e75b-432b-adf4-c56b08515c8a

[WEB-1261] Add back removed code changes to fix sub Issue mutation

---

admin/components/instance/setup-form.tsx
admin/components/login/sign-in-form.tsx
space/components/account/auth-forms/password.tsx
space/components/issues/peek-overview/side-peek-view.tsx
web/components/account/auth-forms/password.tsx
web/components/account/password-strength-meter.tsx
web/pages/accounts/reset-password.tsx
web/pages/accounts/set-password.tsx
web/pages/profile/change-password.tsx

- Instance sign-in page alignment fix.
- Password strength color indicator updated.
- Confirm password input improvement.
- Space app issue sidebar comment section validation added.
| ![before](https://github.com/makeplane/plane/assets/121005188/2b59fc37-4915-4f09-89a7-4af0692e1a78) | ![after](https://github.com/makeplane/plane/assets/121005188/8238e2f6-d8b3-4da8-aa91-c8dc0a4c20f3) |
| ![before](https://github.com/makeplane/plane/assets/121005188/cce2cbc7-6d42-4fca-bb61-cef35740b177) | ![after](https://github.com/makeplane/plane/assets/121005188/60ba4521-4e80-41a5-881f-9c834563b3e2) |
| ![before](https://github.com/makeplane/plane/assets/121005188/0215437e-2f12-474a-b09e-2a5a90dbb914) | …

[WEB-1385] chore: auth screen and space app improvement

---

web/components/issues/issue-detail/issue-activity/activity/actions/helpers/activity-block.tsx
web/components/issues/issue-detail/issue-activity/comments/comment-block.tsx

Issue activity and comment were overflowing.
Add necessary adjustments to fix this issue.
* Before
* After
This PR is linked to [WEB-1063](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/180329a6-b863-4bfa-bf48-b242c091d4b9)

[WEB-1063] style: fix activity/ comment overflow issue.

---

admin/app/layout.tsx

The toast was removed from the admin app after recent refactor.
Re-enabled toast notification on admin app. 
This PR is linked to [WEB-1400](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/8ef0a97a-825e-4e56-b776-84e5e86189ed)

[WEB-1400] fix: enable toast in admin app.

---

web/components/issues/issue-layouts/filters/applied-filters/roots/project-view-root.tsx

After clearing all filters from the view, the "Update View" button was moving to left side.
Added necessary adjustments to fix this issue.
* Before
* After
Issue link [WEB-1386](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/5277d3fe-18ee-44eb-993e-d0aa44e648e0)

[WEB-1386] chore: fix `update view` button to right even if no filters are applied.

---

apiserver/plane/authentication/views/app/signout.py
docker-compose-local.yml
web/store/root.store.ts

Clicking the `Sign Out` from the user profile settings expands the left sidebar menu.
Made changes in `resetOnSignOut` function to not reset ThemeStore.
* Before
https://github.com/makeplane/plane/assets/33979846/b022705c-de28-4c39-841d-ed1903eb3b11
* After
https://github.com/makeplane/plane/assets/33979846/e9772dd0-7611-4a41-9969-4b95c403fcd1
* update sign-out redirect url.
Issue link [WEB-1380](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/48fe0a79-61aa-464b-b1b4-b8075d6e5e50)

[WEB-1380] chore: fix sidebar expanding issue on sign out.

---

packages/ui/src/button/helper.tsx
web/components/onboarding/create-or-join-workspaces.tsx
web/components/onboarding/index.ts
web/components/onboarding/invite-members.tsx
web/components/onboarding/profile-setup.tsx
web/components/onboarding/switch-account-dropdown.tsx
web/components/onboarding/switch-account-modal.tsx
web/pages/workspace-invitations.tsx

* Revamped `Switch Account` modal
* Update `Workspace Invitation` page messages logic.
Issue link [WEB-1404](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/bd9d0367-520a-43aa-9548-342e2f96b88a)

[WEB-1404] chore: auth and onboarding improvements

---

web/components/onboarding/create-workspace.tsx
web/components/workspace/create-workspace-form.tsx

During the onboarding process, when the user reaches the workspace creation page and enters any alphanumeric characters or presses the space bar, the length of each field in the workspace creation window will dynamically adjust to validation length.
Updated `span` to `p` tag to show multiple errors on multiple line.
* Before
* After
Issue link [WEB-1417](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/ab1b851f-ce89-4e2b-9b25-56b326db6f27)

[WEB-1417] chore: fix size updating issue on create workspace form when multiple errors are shown.

---

web/store/issue/issue-details/attachment.store.ts
web/store/issue/issue-details/root.store.ts

After uploading/removing an attachment, the attachment count doesn't mutate.
Added the updateIssue logic to update the attachment count post addition/removal.

[WEB-1415] fix: issue attachment count mutation

---

web/store/issue/cycle/issue.store.ts
web/store/issue/module/issue.store.ts
web/store/issue/project-views/issue.store.ts
web/store/issue/project/issue.store.ts

[WEB-1398](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/0985cc4b-4f34-467e-b31c-482e5b0f4ff6)
[WEB-1402](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/3cfd59b7-348d-4393-b2e4-1c103eb5f7e2)
This PR fixes the quick add issue flicker while grouped by cycles and modules.

[WEB-1398] fix: quick add issue flicker for cycle and module grouping

---

web/components/issues/issue-detail/parent-select.tsx

Redirection to parent issue detail page is throwing error when using a parent from another project. 
This was happening because we were using current project id to redirect instead of parent project id. 
Issue link [WEB-1432](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/3aeb1ab7-c69c-45a2-929d-95e1d2e1c732)

[WEB-1432] fix: redirection to parent issue detail page when it is from another project.

---

web/components/core/sidebar/sidebar-progress-stats.tsx
web/components/cycles/sidebar.tsx
web/components/modules/sidebar.tsx

- Implemented sidebar state filter functionality for both cycle and module.
| Media |
|--------|
| ![1077](https://github.com/makeplane/plane/assets/121005188/b897a652-1151-4fda-a900-f0ff368f1610) |

[WEB-1077] chore: cycle and module sidebar state filter implementation

---

packages/editor/rich-text-editor/src/ui/extensions/enter-key-extension.tsx
packages/editor/rich-text-editor/src/ui/extensions/index.tsx
packages/editor/rich-text-editor/src/ui/index.tsx
web/components/inbox/modals/create-edit-modal/create-root.tsx
web/components/inbox/modals/create-edit-modal/edit-root.tsx
web/components/inbox/modals/create-edit-modal/issue-description.tsx
web/components/issues/issue-modal/form.tsx

- Added an Enter key extension to the RichTextEditorWithRef editor package.
- Implemented Enter-to-submit functionality for the issue and inbox issue modal descriptions.
| Demo |
|--------|
| ![demo]() |

[WEB-1067] chore: enter key entension added to editor package and issue modal description improvement

---

web/components/issues/issue-layouts/kanban/base-kanban-root.tsx

This PR includes a fix for the profile issue in the kanban layout, addressing the problem with group expand and collapse functionality.
| ![1282(B)](https://github.com/makeplane/plane/assets/121005188/490dbd99-ced4-4937-b369-7a1388b28599) | ![1282(A)](https://github.com/makeplane/plane/assets/121005188/af78b055-b59f-4a7d-9d6d-9ec0b7ab93e1) |

[WEB-1282] fix: profile issue kanban group collapse and expand toggle

---

web/components/project/sidebar-list-item.tsx

* Before
* After
Issue link [WEB-1476](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/255ae7d8-3fff-4199-aa96-f36384c95231)

[WEB-1476] style: fix padding on project icon in workspace sidebar.

---

web/components/issues/issue-layouts/kanban/kanban-group.tsx

Display as group by Cycle/modules & sub-group by cycle/modules, assignee, labels, created by user is unable to create issue
We were checking for `groupByKey` instead of `subGroupByKey` while creating the issue in case of cycles and modules.
* Before
https://github.com/makeplane/plane/assets/33979846/a227218f-7190-40be-867c-2559c4c159e1
* After
https://github.com/makeplane/plane/assets/33979846/60ac49fd-2ce8-4028-b1e5-72851ddf0ddc
Issue link [WEB-1445](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/06f732af-0c89-4253-85ac-7bf6950ab817)

[WEB-1445] fix: issue creation on sub groups when cycle/ module grouping is applied.

---

packages/types/src/notifications.d.ts
web/hooks/use-user-notifications.tsx

This PR includes a fix for the notification, specifically addressing the problem where the option to mark all notifications as read was not working in the unread notifications section.

[WEB-1278] fix: notification mark all as read

---

web/store/user/index.ts
web/store/user/profile.store.ts
web/store/user/settings.store.ts

We were running the `user profile`, `user settings` and `list workspaces` API one by one leading to longer initial load time.
Used `Promise.all` to run them in parallel.
* Before
* After
Issue link [WEB-1467](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/29241777-3960-4366-bec0-bc1b327ec398)

[WEB-1467] chore: run the API's required to bootstrap the application in parallel.

---

apiserver/plane/settings/common.py

fix:
- This PR fixes the uploads when a storage other than minio or s3 is used.
- Also disconnects `WEB_URL` and `APP_BASE_URL` configuration. They now need to be independently configured if using different domains for separate services.
**Ticket**: [WEB - 1482](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/45ac674c-1a56-45f8-bf6d-f63e3400f5d0)

[WEB - 1482] fix: uploads when using block storages other than s3 and minio

---

web/components/profile/preferences/email-notification-form.tsx

This PR includes a fix for the email notification preferences state selection bug. Previously, selecting a state would select both the "state change" and "issue complete" options, but only the "state change" field was sent in the payload. I've made the necessary changes to ensure that the selection works as intended.
| ![1494-(1)](https://github.com/makeplane/plane/assets/121005188/7ee534f7-4a30-4be0-b936-02cae79e69ca) | ![1494-(2)](https://github.com/makeplane/plane/assets/121005188/99af77d5-63c9-40da-a758-c0e6fb358a40) |

[WEB-1494] fix: email notification preferences

---

web/components/states/project-setting-state-list-item.tsx

This PR resolves an issue related to state name formatting. Previously, if a user input a state name in camel casing, the state name would appear with spaces. I have made the necessary changes to ensure the state name appears as intended, without unwanted spaces.

[WEB-1470] fix: project state setting state name

---

web/components/modules/form.tsx
web/components/modules/sidebar.tsx

Creating modules with start date older than toady was not allowed previously.
Removed the validation to allow users to set any start date. 
Issue link [WEB-1419](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/7c9010e6-ddbe-4b13-82dc-1a43a7a47d72)

[WEB-1419] chore: enable module creation with dates older than today.

---

web/components/inbox/content/inbox-issue-header.tsx
web/components/inbox/content/root.tsx
web/components/inbox/sidebar/inbox-list-item.tsx
web/components/inbox/sidebar/inbox-list.tsx
web/components/inbox/sidebar/root.tsx
web/hooks/use-intersection-observer.tsx
web/store/inbox/project-inbox.store.ts

Previously, we were using `InboxIssueStore` as the central point for rendering inbox issues which required clearing the store for actions like filtering/sorting in order to re-fetch filtered data. The initial `list` API provides limited issue details required to render issues on the left sidebar, and SWR prevented re-fetching already fetched data, causing complete issue data to be unavailable in the store.
To address this, I refactored the MobX store, introducing `inboxIssueIds` to manage rendering based on current filters/sorting. Now, rendering is handled through this state, eliminating the need to clear `InboxIssueStore`.
Issue link [WEB-1325](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/416a7ec4-9414-4041-bd54-85e4e0abacf3)

[WEB-1325] chore: refactor inbox issue store to avoid data loss.

---

web/components/issues/select/label.tsx

Added a new prop- `buttonClassName` to the labels dropdown.

[WEB-1501] chore: added buttonClassName prop to labels dropdown

---

web/components/workspace/workspace-active-cycles-upgrade.tsx
web/constants/common.ts
web/pages/[workspaceSlug]/settings/billing.tsx

Created two new constants for the marketing website pricing and contact pages and updated all occurrences of the links.

[WEB-1501] chore: created new constants for marketing website page links

---

web/components/dropdowns/state.tsx

The state dropdown now accepts a prop- `showDefaultState`, which when set to `false` will render the placeholder icon and text otherwise render the default state details.

[WEB-1501] chore: render default state conditionally in the state dropdown

---

web/components/api-token/delete-token-modal.tsx
web/components/core/modals/alert-modal.tsx
web/components/cycles/delete-modal.tsx
web/components/estimates/delete-estimate-modal.tsx
web/components/inbox/modals/decline-issue-modal.tsx
web/components/inbox/modals/delete-issue-modal.tsx
web/components/issues/attachment/delete-attachment-modal.tsx
web/components/issues/delete-issue-modal.tsx
web/components/labels/delete-label-modal.tsx
web/components/modules/delete-module-modal.tsx
web/components/pages/modals/delete-page-modal.tsx
web/components/states/delete-state-modal.tsx
web/components/views/delete-view-modal.tsx
web/components/web-hooks/delete-webhook-modal.tsx
web/components/workspace/views/delete-view-modal.tsx

Added `primary` variant to the alert modal core.

[WEB-1501] chore: added primary variant to the alert modal

---

web/constants/empty-state.ts

The primary button in cycle empty state was checking workspace level access of the user to enable / disable the creation action. Because of this any user who is a member of the workspace was able to open up the create cycle modal from that empty state even if the user is a guest at that project level.
* Before
* After
Issue link [WEB-1440](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/da9ad062-e1c9-44ae-9463-656622d5e7a7)

[WEB-1440] chore: update cycle empty state to use project level access.

---

apiserver/plane/license/management/commands/register_instance.py
packages/types/src/instance/base.d.ts

fix: 
- instance register script to remove `api_key` field and `version` field. Instead save the `current_version` and `latest_version`.
- Remove `api_key` and `version` from types. Add `current_version` and `latest_version`.

fix: instance register script 

---

web/store/issue/cycle/issue.store.ts
web/store/issue/module/issue.store.ts
web/store/issue/project-views/issue.store.ts
web/store/issue/project/issue.store.ts

This PR resolves two main issues:
1. **Quick Add Issue Error**: In all issue layouts, when creating an issue using quick add under the "None" category, an error alert is thrown, and an error appears in the request, even though the expected behavior works correctly.
2. **Issue Creation with Filters**: When creating an issue with filters applied for sub_group_by as Module and group_by as Cycle, the issue was switching between multiple filters before returning to the original position.
1. Project issue store
2. Project-view issue store
3. Cycle issue store
4. Module issue store

[WEB-1492] fix: resolved issue creation error in layouts while group_by and sub_group_by filters applied in quick add

---

web/store/inbox/project-inbox.store.ts

Issue details weren't updating properly after filter application, leading to errors.
The issue occured from the removal of non-enumerable `actions` during inbox update. Using lodash's `update` method created a new object without copying these actions. The fix involved switching to `Object.assign` method for proper data transfer.

[WEB-1325] fix: inbox issue store update logic.

---

web/components/core/modals/gpt-assistant-popover.tsx

* Before
* After
Issue link [WEB-1511](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/33ceface-0e9a-4dbc-96c3-1b9b7bdcb077)

[WEB-1511] style: fix overlapping of response container in AI popover.

---

web/components/issues/issue-detail/reactions/reaction-selector.tsx

* Before
* After
Issue link [WEB-1498](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/f93ba0fb-b3fb-461c-92c4-1189349a8590)

[WEB-1498] style: fix comments reaction alignment.

---

apiserver/plane/db/models/asset.py
packages/editor/core/src/ui/plugins/image/image-upload-handler.ts

Currently if the file name is more than 100 words, then the image upload fails in the editor. So now we trim the filename while keeping the extension in place to make it pass.
The image insertion position and the cursor position after the upload completes is now dependent on node before the current cursor position, i.e. if it has any content or not.

[WEB-1312] fix: trim file name before uploading

---

web/components/inbox/root.tsx
web/components/inbox/sidebar/root.tsx
web/hooks/use-intersection-observer.tsx
web/pages/[workspaceSlug]/projects/[projectId]/inbox/index.tsx
web/store/inbox/project-inbox.store.ts

Multiple API calls occurred when reloading the page on the closed issues tab.
The issue stemmed from redundant API calls: one initiated by SWR to fetch closed inbox issues and another triggered by a useEffect to switch the `currentTab` state. To resolve this, I revised the logic to handle both conditions efficiently.
Issue link : [WEB-1481](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/dd573393-1098-425d-8e51-abb167b9136c)

[WEB-1481] fix: multiple API calls in inbox issues on closed issues tab.

---

packages/editor/core/src/hooks/use-editor.tsx

1. The editor's focus sometimes randomly flickers due to syncing caused due to the regression caused by #4331 
2. The editor doesn't persist white spaces on sync.
So the setContent option trims whitespaces, so hence this was causing unexpected issues on repeated reassignments of the value. 
```ts
editor.commands.setContent(value, false, { preserveWhitespace: "full" });
```
By setting `preserveWhitespace` as full while using `.setContent` we can solve this!!

[WEB-1523] regression: focus changing issue with the peek overview editor

---

web/components/gantt-chart/chart/main-content.tsx
web/components/issues/bulk-operations/root.tsx
web/components/issues/issue-layouts/list/default.tsx
web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
web/hooks/use-multiple-select.ts
web/store/multiple_select.store.ts

Whenever the entities list changes, the selected entity ids also need to be updated to handle scenarios where entity group is changed or some filter is applied due to which some of the entities are removed.

[WEB-1501] chore: update selected entity details on entities list change

---

apiserver/plane/authentication/utils/workspace_project_join.py
apiserver/plane/utils/cache.py

fix: 
- cache invalidation on new members invite who don't have account on the platform.
This issue occurs for invited used who does not have an account already on the platform.
Fixes #4166 
**Ticket** - [[WEB - 1518]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/5761717a-bb52-447b-bfb9-69572ab5ba6e)

[WEB - 1518] fix: cache invalidation on new members invite

---

.github/workflows/build-test-pull-request.yml

- The PR adds a check inside the `Build Lint Pull Request` CI to only run the CI if the pull request is `ready_for_review` else the workflow won't run.

fix: `build lint pull request` CI running on draft PRs

---

web/components/issues/issue-layouts/list/block-root.tsx
web/components/issues/issue-layouts/list/block.tsx
web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
web/components/issues/issue-layouts/spreadsheet/spreadsheet-header.tsx

This PR looks to fix alignment issues in List layout and rearrange spreadsheet accordion button layout.
List Layout
Spreadsheet

[WEB-1533] chore: fix alignment issues in List and Spreadsheet view

---

apiserver/plane/space/views/issue.py

chore 
- this pull request corrects the field name to `is_comments_enabled`, `is_reactions_enabled` and `is_votes_enabled`  in the deploy board.

chore: deploy board fields changes

---

packages/editor/core/src/lib/editor-commands.ts
packages/editor/core/src/ui/extensions/code-inline/index.tsx
packages/editor/core/src/ui/extensions/code/utils/replace-code-block-with-text.ts
packages/editor/core/src/ui/extensions/custom-list-keymap/list-keymap.ts

1. Fix the size of the inline code block.
2. And also fixes the issue of the editor losing focus when code block is toggled off
Refactoring the code block toggling feature and persisting focus across the toggle fixed.
1. **Function Separation**:
- **`replaceCodeWithText`**: Main function that identifies code blocks within the selected range and triggers their transformation.
- **`transformCodeBlockToParagraphs`**: Handles the transformation of a code block into multiple paragraph nodes.
- **`getLineNumber`**: Calculates the line number where the cursor is located within the code block.
3. **Newline Handling for varying OS**:
- Updated the `split` method to handle both Unix (`\n`) and Windows (`\r\n`) newline characters using the regular expression `/\r?\n/`.
4. **TypeScript Best …

[WEB-1537] fix: inline code block size fixed for headers, etc

---

packages/editor/core/src/styles/editor.css
packages/editor/core/src/ui/extensions/custom-list-keymap/list-helpers.ts
packages/editor/core/src/ui/extensions/keymap.tsx

1. If you try to delete a task list item from the between, and then join the separated task lists together, the auto merging stops to work which further leads to the `Tab` key not working reliably.
Before
2. Then the tab behavior gets weird if the case is like 
```
[x] item 1
[x] item 2
[x] indented item 1
[x] $
[x] indented item 2
[x] item 4
```
3. Fixed all possible cases for auto merging of lists.
4. Fixes issues with other spacing issues in task lists
Where the $ sign is the cursor position, here the weird infinite loop occurs which is now fixed!

[WEB-1526] feat: add auto merge behaviour to task lists and fix infinite backspace case

---

web/components/core/multiple-select/entity-select-action.tsx
web/components/core/multiple-select/group-select-action.tsx
web/components/core/multiple-select/select-group.tsx
web/components/gantt-chart/chart/main-content.tsx
web/components/issues/bulk-operations/root.tsx
web/components/issues/issue-layouts/gantt/base-gantt-root.tsx
web/components/issues/issue-layouts/list/block.tsx
web/components/issues/issue-layouts/list/default.tsx
web/components/issues/issue-layouts/list/headers/group-by-card.tsx
web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
web/components/issues/issue-layouts/spreadsheet/spreadsheet-header.tsx
web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
web/hooks/use-multiple-select.ts

`MultipleSelectGroup` HOC now accepts a `disabled` prop, which disables the select actions, including keyboard navigations, and can be used to conditionally render checkboxes.

chore: added disabled prop to multiple select components

---

web/components/issues/sub-issues/root.tsx

When trying to create a new issue as a sub-issue, if the user removes the parent issue from the create issue modal, the issue still gets created as the sub-issue.
Added an extra condition to only add the issue as a sub-issue if `parent_id` is present in the response.
| <video src="https://github.com/makeplane/plane/assets/65252264/fdb8a94e-641a-4b7e-a82d-5f163c17c318"></video> | <video src="https://github.com/makeplane/plane/assets/65252264/29f6d56b-41d9-4399-9b16-d6866060809d"></video> |

[WEB-1544] fix: don't add issue as a sub-issue if parent has been removed

---

web/components/issues/title-input.tsx

- Resolved red border flicker on title during initial load.
| ![WEB-1409-Before](https://github.com/makeplane/plane/assets/121005188/10fe3f7c-f297-494d-9ca5-512b97333bb5) | ![WEB-1409-After](https://github.com/makeplane/plane/assets/121005188/b2b39346-4bc7-4ba1-b315-39e08f77cd66) |

[WEB-1409] fix: border flicker on issue title

---

apiserver/plane/api/views/cycle.py
apiserver/plane/app/serializers/module.py
apiserver/plane/app/views/cycle/archive.py
apiserver/plane/app/views/cycle/base.py
apiserver/plane/app/views/module/archive.py
apiserver/plane/app/views/module/base.py
apiserver/plane/utils/analytics_plot.py
packages/types/src/module/modules.d.ts
web/components/analytics/custom-analytics/select/y-axis.tsx
web/components/estimates/points/create.tsx
web/components/estimates/points/update.tsx
web/components/modules/module-card-item.tsx
web/components/modules/module-list-item.tsx

chore: 
- This pull request fixes the issue with the estimates in the analytics.
- The burn-down chart in the cycles and modules can now be plotted based on the `estimate points` only when the estimate type is points.
- In the grid layout, the estimate point percentage is now shown based on the number of estimates completed.
- The estimate point values will now be shown on the x-axis of the custom analytics.
Issue Link: [WEB-412](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/bb16c5ca-dddf-4888-9b5a-574b4cefc3db)

[WEB-412] chore: estimates analytics 

---

web/components/issues/issue-layouts/filters/applied-filters/filters-list.tsx
web/components/issues/issue-layouts/filters/applied-filters/roots/archived-issue.tsx
web/components/issues/issue-layouts/filters/applied-filters/roots/cycle-root.tsx
web/components/issues/issue-layouts/filters/applied-filters/roots/draft-issue.tsx
web/components/issues/issue-layouts/filters/applied-filters/roots/module-root.tsx
web/components/issues/issue-layouts/filters/applied-filters/roots/project-root.tsx
web/components/issues/issue-layouts/filters/applied-filters/roots/project-view-root.tsx
web/components/issues/issue-layouts/save-filter-view.tsx
web/components/issues/issue-layouts/utils.tsx
web/components/views/form.tsx

[WEB-1442](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/52707b83-7ae7-4702-ab39-74cfd94f7463)
This PR is to enabling saving all the filters, display filters and display properties for views.
This also removes saving view for Archived and Draft issues
https://github.com/makeplane/plane/assets/71900764/00e17061-e950-4af5-832d-fef68c05baf7

[WEB-1442] feat: Save all filters and properties for views

---

web/app/profile/page.tsx

- Close the profile picture modal upon image removal.
- Fix a mutation issue where the UI did not reflect image removal from the modal.
| ![WEB-1504 Before](https://github.com/makeplane/plane/assets/121005188/286c95d5-8bcf-49f6-af24-4603d1451948) | ![WEB-1504 After](https://github.com/makeplane/plane/assets/121005188/38dd09c1-ec9b-4409-8464-bc185a2766d9) |

[WEB-1504] chore: profile picture modal improvement and mutation fix

---

web/core/components/account/auth-forms/auth-root.tsx
web/core/components/account/auth-forms/password.tsx
web/core/components/account/auth-forms/unique-code.tsx
web/core/lib/wrappers/authentication-wrapper.tsx

This PR resolves the issue of `next_path` redirections across the entire platform, ensuring users are redirected back to the same route after logging in.
1. sign-in, sign-up pages
2. authentication wrapper

[WEB-1564] chore: handled next_path redirections in auth-wrapper and the form request pages

---

web/app/onboarding/page.tsx

The onboarding workflow required users to create a new workspace, even if they were already part of one.
The issue stemmed from not waiting for the users and workspace lists API responses to determine the onboarding steps. To rectify, I implemented checks to ensure the API responded before calculating total steps. Additionally, I enforced consistency in step count to prevent fluctuations.

[WEB-1565] fix: total onboarding steps logic.

---

web/core/components/onboarding/create-workspace.tsx
web/core/components/workspace/create-workspace-form.tsx

Workspace slugs lack validation, causing errors when attempting to create a workspace exceeding the maximum allowed length.
Implement validation for workspace slugs.

[WEB-1578] chore: add max length validation for workspace slug in create workspace form.

---

web/app/[workspaceSlug]/(projects)/sidebar.tsx
web/app/profile/sidebar.tsx
web/core/components/labels/label-block/label-item-block.tsx
web/core/components/labels/label-block/label-name.tsx
web/core/components/labels/project-setting-label-group.tsx
web/core/components/labels/project-setting-label-item.tsx
web/core/components/project/sidebar-list-item.tsx
web/core/components/project/sidebar-list.tsx

- Restored the drag handler for projects and labels.
- Improved the sidebar:
- Reduced sidebar width.
- Aligned icons and adjusted spacing.
| ![before](https://github.com/makeplane/plane/assets/121005188/dde244b1-ce80-4e39-9b1a-0a04f814e28e) | ![after](https://github.com/makeplane/plane/assets/121005188/4521dc80-23de-4142-823b-120361c93ed4) |
| ![before](https://github.com/makeplane/plane/assets/121005188/d295b6c4-b7d8-4326-ae21-001e0f76572f) | ![after](https://github.com/makeplane/plane/assets/121005188/e0a430cc-3ecd-4c25-9225-060c31c2fafc) |

[WEB-1580] chore: drag handler and sidebar improvement

---

apiserver/plane/authentication/provider/credentials/magic_code.py

fix: 
- error in magic code login when smtp is not configured.
**Ticket** - [[WEB - 1581]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/e60154f5-fbd8-4b4a-9336-bc5d1ab60821)

[WEB - 1581] fix: magic code when smtp is not configured

---

web/app/provider.tsx

The theme for the toast component was not changing as expected.
The issue stemmed from defining the `resolvedTheme` from `next/theme` before the `ThemeProvider` was utilized. This caused the toast component to not receive the resolved theme properly. To address this, I adjusted the structure by placing the `Theme` component within the `ThemeProvider` and utilized the resolved theme from there.
By doing this, the toast component now correctly receives the updated theme, allowing for seamless theme changes without any issues.

[WEB-1597] fix: toast themes.

---

apiserver/plane/utils/grouper.py
apiserver/plane/utils/paginator.py

fix: 
- pagination grouping when grouping by created_by.
Description: When display is set to created by then all the issues created by the user are not displayed.
Steps to recreate: 
- Create multiple issues 
- Now set display as Created by 
- Now we can observe that issues are not displayed
**Ticket** - [[WEB - 1593]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/db04f3a1-3948-4145-9efe-67b642f3d207)

[WEB - 1593] fix: pagination grouping when grouping by created_by

---

README.md
apiserver/plane/license/management/commands/configure_instance.py

Hello guys,
To add little contexte about it, i run a self hosted plane instance and i had the case when my SECRET_KEY has not been defined which occur a lot of weird behavior such as google auth configuration dropped after a container restart or even not retrieve after a uprade.
This is a PR to check mandatory keys such as SECRET_KEY in order to prevent starting it without them.

feat(configure_instance): check mandatory variables before starting

---

web/core/components/issues/issue-layouts/list/list-group.tsx

This PR include fix for list layout load more unwanted styling.
| ![Screenshot 2024-06-12 at 7 03 30 PM](https://github.com/makeplane/plane/assets/121005188/7a925982-3446-4649-a29d-fbc2ec43bd79) | ![Screenshot 2024-06-12 at 7 03 13 PM](https://github.com/makeplane/plane/assets/121005188/a5cf1f62-82ba-494a-bc1a-e554faa3cc89) |

[WEB-1598] style: list layout load more

---

web/core/components/pages/dropdowns/quick-actions.tsx
web/core/components/pages/list/block-item-action.tsx

Add `page` prop to the page quick actions dropdown instead of accessing it via the `usePage` hook.

[WEB-1559] chore: add page prop to the quick actions dropdown

---

space/components/account/auth-forms/email.tsx
space/components/account/auth-forms/password.tsx
space/components/account/auth-forms/unique-code.tsx
web/core/components/account/auth-forms/email.tsx
web/core/components/account/auth-forms/password.tsx
web/core/components/account/auth-forms/unique-code.tsx

- Improved the email input field on authentication pages. Previously, when using the 1Password Chrome extension to input an email, the field behaved unpredictably. This issue has been resolved with the necessary adjustments.
| ![Screen Recording 2024-06-12 at 8 (1)](https://github.com/makeplane/plane/assets/121005188/f14a76d9-92eb-4192-b311-2ed4204d62fc) |  ![Screen Recording 2024-06-12 at 8](https://github.com/makeplane/plane/assets/121005188/2902f286-d9b3-406b-b4b7-97fc76fdb9a9) |

[WEB-1599] chore: auth email input one password extenction improvement

---

README.md
packages/editor/document-editor/src/hooks/use-document-editor.ts
packages/editor/document-editor/src/providers/collaboration-provider.ts

`y-indexeddb` adds a new update to the local database every time you reload the editor creating one unmerged/unapplied update that's unnecessary. In order to solve this, we now wait for the provider to finish indexeddb sync and only then start listening in to the document updates.

fix: extra indexed db update on mount (reload) causing repeated popups of unsaved changes

---

packages/ui/package.json
packages/ui/src/emoji/icons-list.tsx
web/core/components/common/logo.tsx
web/package.json
yarn.lock

This PR includes the following updates:
- Added a skeleton loader for the material symbol logo to prevent the icon name from being displayed briefly when the internet connection is slow.
- App sidebar project list section
- App header breadcrumbs
- Project settings page
- Logo picker modal > icon section
- Common logo component
Path: `web/core/components/common/logo.tsx`
- Material icon list component
Path: `packages/ui/src/emoji/icons-list.tsx`
| ![before](https://github.com/makeplane/plane/assets/121005188/ae709142-51a3-485b-b4d8-8b3929fa1547) | ![after](https://github.com/makeplane/plane/assets/121005188/ea621b23-33f6-4df7-9201-095ae3e796ea) |
| ![before](https://github.com/makeplane/plane/assets/121005188/718e2329-2ae3-419e-b4f4-5c5123f07f4b) | …

[WEB-1613] chore: material logo loader

---

web/core/components/issues/issue-layouts/kanban/default.tsx
web/core/components/issues/issue-layouts/kanban/kanban-group.tsx
web/core/components/issues/issue-layouts/kanban/swimlanes.tsx
web/core/components/issues/issue-layouts/list/list-group.tsx

This PR aims at fixing empty groups for assignees in list and Kanban groupings

[WEB-1596] fix: empty groups for issue list and kanban

---

web/core/components/inbox/sidebar/root.tsx
web/core/components/issues/issue-layouts/kanban/kanban-group.tsx
web/core/components/issues/issue-layouts/list/list-group.tsx
web/core/components/issues/issue-layouts/spreadsheet/spreadsheet-table.tsx
web/core/store/issue/archived/issue.store.ts
web/core/store/issue/cycle/issue.store.ts
web/core/store/issue/draft/issue.store.ts
web/core/store/issue/helpers/base-issues.store.ts
web/core/store/issue/module/issue.store.ts
web/core/store/issue/profile/issue.store.ts
web/core/store/issue/project-views/issue.store.ts
web/core/store/issue/project/issue.store.ts
web/core/store/issue/workspace/issue.store.ts

This PR aims at fixing the scenario where, load more is not working when issues are deleted. This is solved by generating the cursor by using current number of issues rather than utilizing cursor from the server response.

[WEB-1603] fix: load more issues when issues are deleted

---

web/core/store/issue/helpers/base-issues.store.ts

[WEB-1646](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/ee29e610-c802-443e-a1b1-5a2e8e01fae7)
This PR fixes the bug that prevents drag and drop of issues after updating their array like properties via bulk ops.

[WEB-1646] fix: bug that incorrectly updates issue store for array properties during bulk ops

---

web/core/components/estimates/points/create.tsx
web/core/components/estimates/points/update.tsx

This PR fixes the validation logic and alerts for estimate points in the create and update issue modals, ensuring that the estimate points must be greater than 0.
1. Estimate create component
2. Estimate update component

[WEB-1632] fix: validating and showing proper alert estimate point has to be taken greater than 0 in create and update

---

web/core/components/cycles/active-cycle/productivity.tsx

This PR fixes UI inconsistencies in the active cycle estimate dropdown, ensuring a consistent and user-friendly interface.
1. Active cycle product (issue burndown) component

[WEB-1638] fix: updated the ui in-consistancy in active cycle estimate dropdown

---

web/core/components/archives/archive-tabs-list.tsx
web/core/constants/dashboard.ts
web/core/constants/profile.ts
web/core/constants/project.ts
web/core/constants/workspace.ts

Active tab highlights is not working for dashboard/ workspace/ project and profile tabs.
This problem occurred due the the recent changes in `next.config` file where we added `trailingSlash: true` in the configuration. But the highlight logic was checking for the URL pathname without that trailing `/`.

[WEB-1635] style: fix vertical section tabs highlights.

---

packages/types/src/inbox.d.ts
web/core/components/inbox/content/inbox-issue-header.tsx
web/core/components/inbox/content/inbox-issue-mobile-header.tsx
web/core/store/inbox/inbox-issue.store.ts

1. There was no option to un-snooze an issue if it has been snoozed. 
2. Inbox issue snooze till data was inconsistent on initial load and when we go to issue detail.
1. Added option to un-snooze the inbox issue.
2. This inconsistency was because we were updating the `snooze_till` property to date object from date string at the store initialization phase.
https://github.com/makeplane/plane/assets/33979846/77a9c27f-ea83-43d6-b3bd-a0c82acd210c

[WEB-1624] chore: add un-snooze option and minor fixes in inbox issue

---

web/core/store/estimates/estimate.ts

This PR ensures that the issue `estimation_point` is appropriately mutated when an estimate point is deleted from the project.
1. Estimate store

[WEB-1642] chore: mutating issue estimation_point when we delete the estimate point from the project

---

web/core/components/issues/issue-detail/label/create-label.tsx

In this PR, I decreased the size of create label to match our overall UI. 
* Before
* After

[WEB-1663] chore: improve create new label UI.

---

web/core/components/project/form.tsx

This PR fixes the issue where the emoji window was closing unexpectedly when updating a emoji on project settings
1. Project general settings

[WEB-1661] fix: on update project emoji window was closing

---

web/core/components/estimates/points/create.tsx
web/core/components/estimates/points/update.tsx

This PR handles estimation errors when the input field is not empty, ensuring proper validation and error messaging.
1. Estimate point `Create` component
2. Estimate point `Update` component

[WEB-1636] chore: handled estimation error when the input field is not empty

---

apiserver/plane/utils/issue_filters.py

fix: 
- pagination repeat on none filters when grouped by assignees, labels or cycles
**Ticket** - [[WEB - 1664]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/aaf59b4d-7cba-4629-832c-f321e5b8d984)

[WEB - 1664] fix: pagination repeat on none filters when grouped by assignees, labels or cycles

---

apiserver/plane/app/serializers/view.py
apiserver/plane/app/views/view/base.py

chore: 
- Added validation to ensure that only the owner can update a view at both the workspace and project levels.
Issue Link: [WEB-1674](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/9bfcbaaf-6abb-46ef-8c9d-487b9ae8fb5b)

[WEB-1674] chore: views access control

---

web/core/components/issues/peek-overview/properties.tsx

This PR includes a fix for the label overflow issue in the peek overview. Previously, longer labels were overflowing; I have resolved this by making the necessary adjustments.
| ![before](https://github.com/makeplane/plane/assets/121005188/82713128-bbfd-439a-981c-11a465acfdcd) | ![after](https://github.com/makeplane/plane/assets/121005188/87bbe95c-0e9d-4045-80d6-d921787a0053) |

[WEB-1675] fix: issue peek view label with longer title

---

packages/ui/src/emoji/emoji-icon-picker-new.tsx
packages/ui/src/emoji/emoji-icon-picker.tsx
packages/ui/src/emoji/icons-list.tsx
packages/ui/src/emoji/lucide-icons-list.tsx

This PR includes improvements to the icon list section in the emoji picker. Previously, the search and color sections were not sticky. Now, they will stay fixed at the top while scrolling for a better user experience.
| ![before](https://github.com/makeplane/plane/assets/121005188/93fc9d1c-ae11-45f1-a249-33a6610c78ab) | ![after](https://github.com/makeplane/plane/assets/121005188/526b1469-3f65-41da-93b2-0fd3089a38f9) |

[WEB-1667] chore: icon list improvement

---

web/core/components/issues/issue-layouts/calendar/roots/project-view-root.tsx
web/core/components/issues/issue-layouts/kanban/kanban-group.tsx
web/core/components/issues/issue-layouts/kanban/roots/project-view-root.tsx
web/core/components/issues/issue-layouts/list/roots/project-view-root.tsx
web/core/components/issues/issue-layouts/roots/project-view-layout-root.tsx
web/core/components/issues/issue-layouts/spreadsheet/roots/project-view-root.tsx
web/core/hooks/use-issues-actions.tsx
web/core/store/issue/archived/filter.store.ts
web/core/store/issue/archived/issue.store.ts
web/core/store/issue/cycle/filter.store.ts
web/core/store/issue/cycle/issue.store.ts
web/core/store/issue/draft/filter.store.ts
web/core/store/issue/draft/issue.store.ts
web/core/store/issue/helpers/issue-filter-helper.store.ts
web/core/store/issue/module/filter.store.ts
web/core/store/issue/module/issue.store.ts
web/core/store/issue/profile/filter.store.ts
web/core/store/issue/profile/issue.store.ts
web/core/store/issue/project-views/filter.store.ts
web/core/store/issue/project-views/issue.store.ts
web/core/store/issue/project/filter.store.ts
web/core/store/issue/project/issue.store.ts
web/core/store/issue/workspace/filter.store.ts
web/core/store/issue/workspace/issue.store.ts

[WEB-1686](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/a530813d-6465-425d-a093-86968b757174)
This PR fixes the issue where incorrect filters were being applied while switching between projects, modules, cycles etc. This was due to the delayed update of store's Approuter parameters. To solve this, all the API calls are made to rely on the value being passed on rather than reading it from the store.

[WEB-1686] fix: issues incorrect filters while switching between, projects, modules etc

---

web/ce/constants/estimates.ts
web/core/components/estimates/points/create.tsx
web/core/components/estimates/points/update.tsx

This PR handles the maximum number of characters that a user can enter when creating or updating an estimate point, ensuring that inputs are validated and restricted appropriately.
1. Estimate constant
2. Estimate create and update component

[WEB-522] chore: handled maximum no of char that user can enter in estimate point create and update

---

web/core/components/estimates/points/create.tsx
web/core/components/estimates/points/update.tsx

This PR handles the maximum number of characters that a user can enter when creating or updating an estimate point, ensuring that inputs are validated and restricted appropriately.
1. Estimate constant
2. Estimate create and update component

[WEB-522] fix: Input type number validation on estimate in create and update

---

web/core/store/issue/workspace/filter.store.ts

[WEB-1717](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/5e2d5568-3768-48f9-9343-2f4c4e038174)
This PR fixes the order by of a custom global view when applied, by forcing to use spreadsheet as default view regardless of whichever view is stored in the view.

[WEB-1717] fix: order by on issues not updating for custom global views

---

web/core/components/cycles/active-cycle/productivity.tsx
web/core/lib/wrappers/store-wrapper.tsx

This PR handles the issue and estimate point dropdown in the active cycle to render only when the estimate type is points
1. Active cycles in the project

[WEB-522] fix: handling the issue and estimate point dropdown in the active cycle to render only when the estimate type is points

---

web/core/components/account/auth-forms/password.tsx

This PR includes a fix for the password strength banner. Previously, it was also appearing on the sign-in screen. I've added validation to ensure it only renders during the sign-up flow.

[WEB-1726] fix: password strength banner validation

---

web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/[pageId]/page.tsx
web/core/components/inbox/root.tsx
web/core/components/inbox/sidebar/root.tsx
web/core/components/pages/pages-list-view.tsx
web/core/hooks/use-auto-save.tsx
web/core/store/inbox/project-inbox.store.ts
web/core/store/pages/project-page.store.ts

When user's were navigation to the pages route directly from dashboard, we get infinite loader.
This was because we were using the router store to get the values of workspaceSlug and projectId and there was a small delay while updating those values on store wrapper. Due to this projectId was still undefined.
Also added the fix in inbox issues where we might encounter the same issue.

[WEB-1724] fix: initial pages list loading.

---

web/core/components/issues/issue-layouts/spreadsheet/columns/state-column.tsx
web/core/components/issues/issue-layouts/spreadsheet/issue-column.tsx
web/core/components/issues/issue-layouts/spreadsheet/spreadsheet-header-column.tsx

When the user deselects all properties except "State" in the spreadsheet view, the state column does not display correctly. This issue arose from the recent fix in #4859. We added the max width for the state column and did not considered the situation when other properties are hidden, causing the table to expand to full width while the state column remains constrained by a max width, resulting in unusual white space.
Adjusted the CSS logic to ensure the state column expands appropriately when it is the only visible column while also handling the max width.
* Before
* After
](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/fb6c5091-72c4-4e97-9937-12bbd6fb729d)

[WEB-1718] style: fix spreadsheet column width when other properties are hidden.

---

packages/editor/src/core/extensions/drag-drop.tsx
packages/editor/src/styles/table.css

Fixed drag drop issues with h4, h5, h6, images, document's first node and also solved the positioning of drag handles for all the nodes inside tables!
https://github.com/makeplane/plane/assets/73993394/4e989a2e-fe3f-4ee1-bc21-b3d2b7d59a2c
https://github.com/makeplane/plane/assets/73993394/78766769-d39b-45db-90f1-26c8be9993a7

[WEB-1668] fix: drag drop issues with h4, h5, h6, images and nodes inside tables

---

space/app/issues/[anchor]/layout.tsx
space/app/layout.tsx
space/core/constants/seo.ts

Replaced the keyword `Deploy` with `Publish` across the space app.

[WEB-1757] chore: rename deploy to publish

---

web/core/components/views/quick-actions.tsx
web/core/components/views/view-list-item-action.tsx
web/core/components/workspace/views/quick-action.tsx
web/core/store/member/index.ts

This PR takes care of the option to edit and delete access control for views
- Only the owner can edit the views
- The Owner and Admin can delete the views
https://github.com/makeplane/plane/assets/71900764/8ae531b9-af15-4ab2-926f-e9b9fc8443a1

[WEB-1255] fix: edit and delete access control for views

---

packages/editor/src/core/extensions/extensions.tsx

Correctly let the Markdown plugin handle parsing of multiline data except for code blocks on pasting data from external sources
| <img width="792" alt="image" src="https://github.com/makeplane/plane/assets/73993394/0b6e2d8c-c729-43b8-ab98-608b0d69fb1b"> | <img width="792" alt="image" src="https://github.com/makeplane/plane/assets/73993394/dd56a327-ab90-4ff9-814a-03bffbc1e8c8"> |

fix: multiline copy paste

---

web/core/components/issues/issue-detail/issue-detail-quick-actions.tsx

This PR includes a fix for the issue with delete redirection. Previously, deleting an issue from the issue detail page did not redirect to the issue link page. Additionally, deleting an issue was triggering two toast alerts. I have made the necessary changes to ensure it works as intended.
| ![before](https://github.com/makeplane/plane/assets/121005188/bbf5958b-5d60-4635-bede-c386369052a5) | ![after](https://github.com/makeplane/plane/assets/121005188/ec6157d2-a9f1-4cd4-9ca5-a03173e77ce6) |

[WEB-1791] fix: issue delete redirection

---

packages/editor/src/styles/editor.css

Fix the padding inside the blockquotes inside list items (task, numbered and bullet)
|  <img width="157" alt="image" src="https://github.com/makeplane/plane/assets/73993394/a0c731b6-7a84-45a5-b6c7-14c600db077d"> | <img width="228" alt="image" src="https://github.com/makeplane/plane/assets/73993394/3e40c860-7a35-42f4-b0ca-3b2e418dab08"> |

[WEB-1753] fix: padding inside the blockquotes inside list items

---

web/core/components/issues/peek-overview/root.tsx

This PR handles the loader state and empty state in the notification issue peek overview.
1. Issue Root

[WEB-1792] chore: handled Notification empty state

---

web/core/components/dashboard/widgets/recent-collaborators/root.tsx

[issue 4947](https://github.com/makeplane/plane/issues/4937) - Dashboard collaboration card responsiveness issue
new xs screens: 
screen size sm and up: 
old small screen:

responsive styles for recent-collborators

---

web/core/store/estimates/project-estimate.store.ts

This PR fixes the issue of inconsistent estimate type handling by converting and managing the estimate type in lowercase within the store.
1. Project Estimate store

[WEB-522] fix: converted and handled the estimate type to lowercase in the store

---

apiserver/plane/settings/common.py

This fixes #4928 by adding the header "X-API-Key" to the allowed headers in the CORS configuration of `django-cors-headers`.
See: CORS_ALLOW_HEADERS at https://pypi.org/project/django-cors-headers/

fix: api requests cors

---

web/core/components/gantt-chart/sidebar/issues/sidebar.tsx
web/core/components/issues/issue-layouts/kanban/block.tsx
web/core/components/issues/issue-layouts/list/block-root.tsx
web/core/components/issues/issue-layouts/list/list-group.tsx
web/core/components/issues/issue-layouts/spreadsheet/issue-row.tsx
web/core/components/issues/issue-layouts/spreadsheet/spreadsheet-table.tsx

This PR is to tweak the virtualization and pagination Intersection Observer Root Margins to have the issues render over a larger view port, to have a smoother scrolling of issues in list, Kanban, gantt and Spreadsheet layouts.
https://github.com/makeplane/plane/assets/71900764/d6495b81-63e2-40c5-887d-879f58c49684

[WEB-1798] chore: tweak pagination and virtualization thresholds to have a smoother scroll

---

space/core/components/issues/peek-overview/header.tsx

The icons in the layout selection dropdown of the peek overview are broken in the space app.
Lucide icons were being renderd as material icons, causing incorrect rendering of the icons.
| <img width="250" alt="image" src="https://github.com/makeplane/plane/assets/65252264/1b7451f9-46dc-4e4b-867d-2fc2b5c8b1de"> | <img width="250" alt="image" src="https://github.com/makeplane/plane/assets/65252264/2eb04d86-e20f-4c8f-ae97-e727e8d286a7"> |

[WEB-1800] fix: peek overview layout dropdown icons in the space app

---

web/core/constants/dashboard.ts

[WEB-1808] style: fix `settings` highlight on app sidebar.

---

web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/issues/(list)/header.tsx
web/core/components/project/publish-project/modal.tsx

Append `SPACE_BASE_PATH` to the redirection link for the self-hosted instances.

[WEB-1265] fix: project publish redirection

---

packages/ui/src/modals/modal-core.tsx

This PR includes a fix for the onClose functionality of the modal core component. Previously, clicking outside the modal did not close it, which was not the intended behavior. I have made the necessary adjustments to make it work as intended.

[WEB-1836] fix: modal core onClose functionality

---

web/core/components/workspace/sidebar/quick-actions.tsx

This PR includes a fix for the sidebar draft issue and resolves the overlapping quick action problem.
| ![before](https://github.com/makeplane/plane/assets/121005188/b6ee2cc9-73b1-4385-97c9-042ea24fd283) | ![after](https://github.com/makeplane/plane/assets/121005188/949004e9-a7c5-465b-a96e-44b439f5868c) |

[WEB-1807] fix: sidebar quick action overlapping

---

web/core/components/issues/issue-layouts/roots/project-view-layout-root.tsx
web/core/store/project-view.store.ts
web/helpers/project-views.helpers.ts

This PR is to fix issues when issues are queried before completely fetching view filters when the filters are cleared and the page is visited back.  
This also adds default group by for kanban views
https://github.com/makeplane/plane/assets/71900764/4e9d675b-5a41-472d-9142-69ad887fb466
https://github.com/makeplane/plane/assets/71900764/f9bc7aa8-7b2f-46cd-98fb-21cdd290c695

[WEB-1829] fix: stop issues query before fetching the view filters

---

web/core/components/dropdowns/estimate.tsx

This PR handles the dropdown hover ui on estimate dropdown menu options.
1. Estimate dropdown

[WEB-1844] chore: updated dropdown hover ui on estimate dropdown menu options

---

web/core/components/issues/issue-modal/modal.tsx

This PR handles the display of the issue redirection and copy link buttons on the issue creation modal toast when an issue is created from the home page.
1. Issue modal root

[WEB-1847] chore: handled project id on the issue creation modal toast when the issue creation is happening on the home page

---

web/core/store/issue/helpers/base-issues.store.ts
web/core/store/issue/module/issue.store.ts

This PR aims at fixing the quick add for issues in module issues. By using a method without optimistically adding the issue to module. 
Using a optimistic update to add issue to module, this will add the issue while still having the quick added dummy issue.
https://github.com/makeplane/plane/assets/71900764/b6cc419a-ab34-4e39-9d49-244614ed7cf3

[WEB-1853] fix: Module Issue Quick add

---

apiserver/plane/api/views/inbox.py
apiserver/plane/app/views/issue/sub_issue.py

chore: 
- This pull request resolves the issue of ordering sub-issues based on their creation time.
- This also resolves the bug with the creation of an inbox issue with default priority as none.
Issue Link: [WEB-1840](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/ffca2e6d-50ef-4966-bbe8-b10d0a8e3a9e/)

[WEB-1840] chore: corrected the sub issue ordering

---

web/core/components/issues/issue-layouts/kanban/swimlanes.tsx

Fixed the Kanban subgroup layout quick add validation. Previously, the quick add button was being rendered in the completed cycle, which was not the intended behavior. I have made changes to ensure it works as intended.

[WEB-1683] fix: kanban subgroup quick add validation

---

apiserver/plane/app/views/user/base.py

fix: 
- This PR fixes the old workspace still visible on re-login after account deactivation.
**Ticket** - [[WEB - 1879]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/13d8b69e-1467-482f-8b94-2dee03daa7a1)

[WEB - 1879] fix: remove user workspace cache on account deactivation

---

web/core/components/issues/issue-detail-widgets/links/helper.tsx
web/core/components/issues/issue-detail/links/root.tsx

This PR includes an improvement for the issue link toast alert message. Previously, when a user tried to add an existing link, the message "The link could not be created" was rendered, which was not very descriptive. I have now added a more detailed response message.

[WEB-1874] fix: issue link error toast alert

---

web/core/components/issues/issue-layouts/gantt/base-gantt-root.tsx
web/core/components/issues/issue-layouts/roots/cycle-layout-root.tsx

This PR includes a fix for the issue with the Gantt layout's quick add button validation for completed cycles. Previously, the quick add button was rendered for completed cycles, which was not the intended behavior.

[WEB-1872] fix: completed cycle gantt layout quick add issue validation

---

web/core/constants/cycle.ts

- Updated the color of the project active cycle progress state group.
| ![before](https://github.com/makeplane/plane/assets/121005188/ed2e7cd6-7f01-4863-9f23-4de98f99ba00) | ![after](https://github.com/makeplane/plane/assets/121005188/9ba1d64f-8bf4-4a2a-b99b-dbe182875ede) |

[WEB-1510] chore: project active cycle progress state group color updated

---

web/core/components/issues/attachment/attachment-list-item.tsx
web/core/store/issue/issue-details/root.store.ts

This PR addresses the issue with the attachment delete modal. Previously, clicking on delete would close the modal without any action. I have made the necessary changes to ensure it now functions as intended.

[WEB-1899] fix: attachment delete modal

---

web/core/components/issues/attachment/attachment-detail.tsx
web/core/components/issues/attachment/attachment-item-list.tsx
web/core/components/issues/attachment/attachment-list-item.tsx
web/core/components/issues/attachment/delete-attachment-modal.tsx
web/core/store/issue/issue-details/root.store.ts

Changes:
This PR addresses the issue with the attachment delete modal. Previously, clicking on delete would close the modal without any action. I have made the necessary changes to ensure it now functions as intended.
Issue link: [[WEB-1899]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/04a4adf5-8f02-480a-aaef-09da8b18de26/)

[WEB-1899] fix: issue attachment  delete modal and code refactor

---

web/core/components/estimates/points/create.tsx
web/core/components/estimates/points/update.tsx

This PR updates the validation of the estimate input form by changing the input type from number to text, allowing for more flexible validation and input handling.
1. Estimate create component
2. Estimate update component

[WEB-1908] chore: update input type number validation to type text in estimate input form

---

web/core/components/analytics/custom-analytics/select/project.tsx

Truncate project name under custom analytics's project selection dropdown
[[WEB-1820]
](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/18d1a65e-e5c6-43ca-a9d0-45ae8f428d6f)

[WEB-1820] fix: analytics truncate project name

---

web/core/store/issue/archived/filter.store.ts

[[WEB-1876]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/7efbc443-70a4-49a3-a0cc-f1278db25302)

[WEB-1876] fix: "Show sub-issues" checkbox checked by default under Archives

---

apiserver/plane/bgtasks/page_version_task.py

dev:
-  This PR fixes the background task for creating page versions. The error was due to a misspell in creating the versions.
**Ticket** - [[WEB - 1935]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/25f303a5-78eb-431e-bde3-e25bb327df24)

[WEB-1935] dev: fix page versioning task

---

web/core/components/workspace/sidebar/projects-list-item.tsx

Description: When clicking on the projects we get project details(issues, cycles, modules, views etc.) then if we click on the accordion dropdown closes, now if we click on the same project dropdown wont work, we have to click on the accordion only to open the project details.
[[WEB-1759]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/0ac2736a-a496-41e3-82fa-4a40aa7d9954)

[WEB-1759] fix: project dropdown action

---

web/core/store/issue/workspace/filter.store.ts

This PR adds the default sort order as created-at. If the order by is manual, replace it with created-at.
https://github.com/user-attachments/assets/5e8c253a-a6d9-449e-8db7-cce0a4ef63b5

[WEB-1905] fix: sort order for workspace views

---

web/core/components/issues/issue-detail/issue-activity/activity/actions/index.ts
web/core/components/issues/issue-detail/issue-activity/activity/actions/label-activity-chip.tsx
web/core/components/issues/issue-detail/issue-activity/activity/actions/label.tsx

- Fixed the issue with label activity truncation, where labels with longer titles were not rendering properly.
- Added the LabelActivityChip component to avoid repeating the same code multiple times.
| ![before](https://github.com/user-attachments/assets/e9ee4785-5847-4762-a57f-d8fdb47814d1) | ![after](https://github.com/user-attachments/assets/45609cba-2562-4a9a-953c-a6576cddb6fb) |

[WEB-1697] fix: issue label activity truncate fix and chip component added

---

web/core/components/issues/issue-detail-widgets/action-buttons.tsx
web/core/components/issues/issue-detail-widgets/attachments/title.tsx
web/core/components/issues/issue-detail-widgets/links/title.tsx
web/core/components/issues/issue-detail-widgets/relations/title.tsx
web/core/components/issues/issue-detail-widgets/sub-issues/title.tsx
web/core/components/issues/issue-detail-widgets/widget-button.tsx

- Added Guest/Viewer role permissions for issue detail widgets. Previously, users with the Guest/Viewer role could open the issue detail widgets modal and access the quick action menu.
| ![WEB-1937 BEFORE](https://github.com/user-attachments/assets/89e63e76-0a88-4681-a938-67824944fd25) | ![WEB-1937 AFTER](https://github.com/user-attachments/assets/bdc2a160-81f2-4911-a467-ca736dd45bf7) |

[WEB-1937] fix: issue detail widgets permission validation

---

web/core/components/issues/issue-layouts/spreadsheet/issue-row.tsx

- Resolved spreadsheet layout issue quick action event propagation. Previously, clicking outside the delete issue modal triggered the issue peek view.
| ![WEB-1951 BEFORE](https://github.com/user-attachments/assets/20102c4c-12db-4727-a347-940b814c0194) | ![WEB-1951 AFTER](https://github.com/user-attachments/assets/0c30554e-7abd-4c2c-b862-b16c6985cb83) |

[WEB-1951] fix: spreadsheet layout issue quick action event propagation

---

web/core/components/inbox/sidebar/root.tsx

Summary
Inbox - first issue is not displayed on the right panel
[[WEB-647]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/a3391ce0-c811-45c0-9d50-91908eb7187e)

[WEB-647] fix: showing first issue as default inbox state

---

web/core/components/analytics/custom-analytics/table.tsx

Summary
Broken priority icons displayed under custom analytics
[[WEB-1948]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/5e6c7023-6641-4d90-a7e9-2b4b47ee94be)

[WEB-1948] fix: priority icons

---

web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/header.tsx

When trying to change the icon of a Page from the breadcrumb, the page title tooltip persists even when not hovering over the title.
Removed the tooltip as a wrapper to the breadcrumb item and added it only to the page title.
| <video src="https://github.com/user-attachments/assets/757f65f3-dbdd-4c2e-a9f3-919cf706192d"></video> | <video src="https://github.com/user-attachments/assets/554e75d0-2d01-4438-95aa-4404930d43a8"></video> |

[WEB-1799] fix: page breadcrumb tooltip persistence

---

web/core/components/issues/issue-layouts/list/headers/group-by-card.tsx

Users are able to select groups with no issues in them, resulting in some unwanted errors.
Disabled group selection if no issues are present.
| <video src="https://github.com/user-attachments/assets/4dfd0a52-a57c-485b-aa81-c9ac15e64eb5"></video> | <video src="https://github.com/user-attachments/assets/2116ee83-f754-463e-9e25-d81e231f7e76"></video> |

[WEB-1910] fix: disable selection if no issues are present

---

web/core/components/issues/issue-detail-widgets/issue-detail-widget-modals.tsx
web/core/components/issues/issue-detail/links/create-update-link-modal.tsx
web/core/components/issues/issue-detail/links/link-detail.tsx
web/core/components/issues/issue-detail/links/link-item.tsx
web/core/store/issue/issue-details/root.store.ts

When the user tries to update an existing issue link, preloadData is not populating.
The issue was caused by multiple instances of the modal. I removed the duplicate instances and made the necessary adjustments to fix this.
| ![WEB-2000 Before (1)](https://github.com/user-attachments/assets/57e8b49d-f623-4b39-85dc-ad09342828f5) | ![WEB-2000 After (1)](https://github.com/user-attachments/assets/84cc311a-b9a3-4e9e-9064-6e9b1abbffec) |

[WEB-2000] fix: issue link edit modal and mutation fix

---

packages/editor/src/core/components/editors/editor-wrapper.tsx
packages/editor/src/core/extensions/extensions.tsx
packages/editor/src/core/hooks/use-document-editor.ts
packages/editor/src/core/hooks/use-editor.ts

Undo/redo doesn't work in issue descriptions and comment boxes.
When integrating collaboration for the document editor, editor history was disabled for all the editors while it should have been disabled just for the document editor.
To fix this, additional prop, `enableHistory` is now passed to conditionally manage the history extension.

[WEB-1877] fix: editor history(undo/redo) not working for issue descriptions and comments

---

apiserver/plane/app/views/cycle/base.py

chore: 
- added `completed_estimate_points` , `total_estimate_points` and `created_by` detail in the cycle detail endpoint.
Issue Link: [WEB-1693](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/be2cb5b6-9671-43ba-b1ae-d6f868779b02/)

[WEB-1693] chore: added details in cycle detail endpoint

---

packages/editor/src/core/components/menus/menu-items.ts
packages/editor/src/core/extensions/slash-commands.tsx
packages/editor/src/core/hooks/use-editor.ts
packages/editor/src/core/types/editor.ts
packages/editor/src/core/types/slash-commands-suggestion.ts
space/core/components/editor/toolbar.tsx
space/core/constants/editor.ts
web/core/components/editor/lite-text-editor/toolbar.tsx
web/core/components/pages/editor/header/toolbar.tsx
web/core/constants/editor.ts

Headings 4 to 6 are missing in the rich text editor(issue descriptions).
Added the missing heading items in the slash command menu. Also created a common type for all the editor commands for consistency.

[WEB-1797] chore: add missing headings to the rich text editor

---

web/core/components/pages/version/main-content.tsx

This PR fixes the overflow issue in the version history read-only editor when a text without any white spaces is added to the editor.
| <img width="1916" alt="image" src="https://github.com/user-attachments/assets/f678e25c-7a11-4641-953f-7035c2633fa1"> | <img width="1916" alt="image" src="https://github.com/user-attachments/assets/7a4bca34-0f48-4a2f-a313-4cceb63e4935"> |

[WEB-2293] fix: version history editor overflow

---

web/core/components/issues/issue-layouts/filters/applied-filters/roots/workspace-draft-root.tsx
web/core/components/issues/issue-modal/base.tsx
web/core/components/pages/editor/header/color-dropdown.tsx
web/core/hooks/use-group-dragndrop.ts
web/core/hooks/use-issues-actions.tsx
web/core/services/issue/workspace_draft.service.ts
web/core/store/issue/root.store.ts
web/core/store/issue/workspace-draft/issue.store.ts

This PR is a patch to fix the build caused by workspace drafts changes

fix: workspace draft build

---

apiserver/plane/app/views/analytic/base.py
apiserver/plane/app/views/cycle/issue.py

fix: analytics tab for private bucket

fix: analytics tab for private bucket

---

apiserver/plane/bgtasks/analytic_plot_export.py
apiserver/plane/bgtasks/export_task.py

fix: export for analytics and csv

fix: export for analytics and issues

---

apiserver/plane/app/views/workspace/draft.py

chore: 
- now when moving the issue from draft to a new issue, modules and cycles can be added in a single request.
Issue Link: [WEB-2686](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/4236a98b-d2c7-4108-aae7-a058013659ff/)

[WEB-2686] chore: added draft cycle and module in draft issue

---

web/core/components/inbox/content/inbox-issue-header.tsx
web/core/components/inbox/content/issue-root.tsx
web/core/components/issues/description-input.tsx
web/core/store/inbox/inbox-issue.store.ts

Changes:
This PR fixes intake issue description and navigation.
Reference:
[WEB-2709]

[WEB-2709] fix: intake issue description and navigation

---

packages/editor/src/styles/editor.css

**_Problem:_**
Web app UI was broken, due to conflict with editor tailwind CSS base directives.
**_Solution:_**
Removed `@tailwind base;`, `@tailwind components;`, and `@tailwind utilities;` directives.
Issues:
- closes [WEB-2732](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/676990f9-1336-4416-8343-d8b3c8e4b364)

[WEB-2732] fix: global css conflicts

---

web/core/local-db/storage.sqlite.ts

This PR adds missing config for fetching getIssues from server. The config is mainly used for Abort controller to cancel previous api if a new one is called before the Promise is returned.

[WEB-2734] fix: Add missing config to get issues api call

---

web/core/components/inbox/content/root.tsx

This PR resolves a bug with intake issue permissions where users with member-level permissions couldn't edit their own issue immediately after creation without refreshing the page.
[[WEB-2759]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/f52cd0fb-e695-4362-9d68-e0d559854793/)

[WEB-2759] fix: intake issue permission

---

web/ce/components/workflow/state-item-child.tsx
web/core/constants/state.ts

This PR aims at removing unnecessary CTA in UI

chore: Remove Unnecessary CTA

---

web/core/components/pages/editor/editor-body.tsx

In this PR-
1. Updated the dependencies of the `userConfig` being passed to the document editor causing the HocuPocus provider to create multiple new providers without destroying the already existing ones.

fix: user config dependencies

---

web/core/store/theme.store.ts

This PR updates app theme store.
[[WEB-2943]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/78524d67-884a-4077-a236-3df2b35e248c/)

[WEB-2943] chore: app theme store

---

web/core/components/cycles/list/cycle-list-item-action.tsx

In this PR, I have added a check to remove transfer issue option from cycle list when used at global level.

[WEB-3128] fix: hide transfer issues option from cycles list when used outside project scope

---

packages/i18n/src/store/index.ts

fix: add client validation and find similar language from browser config if exact match is not available

---

packages/constants/src/index.ts
packages/constants/src/tab-indices.ts
web/ce/components/projects/create/attributes.tsx
web/core/components/cycles/form.tsx
web/core/components/inbox/modals/create-modal/create-root.tsx
web/core/components/inbox/modals/create-modal/issue-description.tsx
web/core/components/inbox/modals/create-modal/issue-properties.tsx
web/core/components/inbox/modals/create-modal/issue-title.tsx
web/core/components/issues/issue-modal/components/default-properties.tsx
web/core/components/issues/issue-modal/components/description-editor.tsx
web/core/components/issues/issue-modal/components/parent-tag.tsx
web/core/components/issues/issue-modal/components/project-select.tsx
web/core/components/issues/issue-modal/components/title-input.tsx
web/core/components/issues/issue-modal/form.tsx
web/core/components/labels/create-label-modal.tsx
web/core/components/modules/form.tsx
web/core/components/pages/modals/page-form.tsx
web/core/components/project/create/common-attributes.tsx
web/core/components/project/create/header.tsx
web/core/components/project/create/project-create-buttons.tsx
web/core/components/views/form.tsx
web/helpers/tab-indices.helper.ts

- Tab indices constant has been moved to the plane constant package.

chore: tab indices constant refactor

---

packages/i18n/src/locales/en/translations.json
web/app/[workspaceSlug]/(projects)/drafts/header.tsx
web/core/components/issues/issue-layouts/quick-action-dropdowns/draft-issue.tsx
web/core/components/issues/issue-modal/form.tsx
web/core/components/issues/workspace-draft/delete-modal.tsx
web/core/components/issues/workspace-draft/draft-issue-block.tsx
web/core/components/issues/workspace-draft/quick-action.tsx

- Language support has been added for the Workspace drafts constant.

chore: drafts language support

---

packages/i18n/src/locales/en/translations.json
web/app/[workspaceSlug]/(projects)/notifications/page.tsx
web/ce/components/workspace-notifications/notification-card/root.tsx
web/core/components/workspace-notifications/sidebar/filters/applied-filter.tsx
web/core/components/workspace-notifications/sidebar/filters/menu/root.tsx
web/core/components/workspace-notifications/sidebar/header/options/menu-option/root.tsx
web/core/components/workspace-notifications/sidebar/header/options/root.tsx
web/core/components/workspace-notifications/sidebar/header/root.tsx
web/core/components/workspace-notifications/sidebar/notification-card/options/archive.tsx
web/core/components/workspace-notifications/sidebar/notification-card/options/read.tsx
web/core/components/workspace-notifications/sidebar/notification-card/options/snooze/root.tsx

feat: ln support for notifications

---

packages/i18n/src/locales/en/translations.json
web/ce/components/projects/mobile-header.tsx
web/core/components/project/applied-filters/root.tsx
web/core/components/project/card-list.tsx
web/core/components/project/filters.tsx
web/core/components/project/header.tsx
web/core/components/project/project-feature-update.tsx
web/core/components/project/root.tsx
web/core/components/project/search-projects.tsx

Added language translation to projects list page in this update.

feat: language translation  - projects list

---

packages/i18n/src/locales/en/translations.json
web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/modules/(list)/header.tsx
web/core/components/modules/analytics-sidebar/issue-progress.tsx
web/core/components/modules/analytics-sidebar/progress-stats.tsx
web/core/components/modules/analytics-sidebar/root.tsx
web/core/components/modules/form.tsx
web/core/components/modules/module-list-item-action.tsx
web/core/components/modules/quick-actions.tsx

- Language support has been added for the module.

chore: module language support

---

packages/i18n/src/locales/en/translations.json
web/app/[workspaceSlug]/(projects)/workspace-views/header.tsx
web/core/components/issues/issue-layouts/empty-states/global-view.tsx
web/core/components/workspace/views/default-view-quick-action.tsx
web/core/components/workspace/views/quick-action.tsx

- Language support has been added for the Workspace views.

chore: workspace views language support

---

web/core/components/issues/issue-layouts/kanban/default.tsx

This PR include improvement for board layout padding.
| ![before](https://github.com/user-attachments/assets/bd399740-7030-4636-b78c-6de6d8d581c9) | ![after](https://github.com/user-attachments/assets/89617978-7b5a-40a7-80d7-82ac677bf82f) |

chore: board layout padding improvement

---

packages/constants/src/workspace.ts
packages/i18n/src/locales/en/translations.json
web/app/[workspaceSlug]/(projects)/settings/api-tokens/page.tsx
web/app/[workspaceSlug]/(projects)/settings/exports/page.tsx
web/app/[workspaceSlug]/(projects)/settings/members/page.tsx
web/app/[workspaceSlug]/(projects)/settings/sidebar.tsx
web/app/[workspaceSlug]/(projects)/settings/webhooks/page.tsx
web/ce/components/workspace/billing/root.tsx
web/ce/components/workspace/delete-workspace-section.tsx
web/ce/components/workspace/settings/useMemberColumns.tsx
web/core/components/api-token/modal/form.tsx
web/core/components/api-token/modal/generated-token-details.tsx
web/core/components/exporter/export-modal.tsx
web/core/components/exporter/guide.tsx
web/core/components/web-hooks/create-webhook-modal.tsx
web/core/components/web-hooks/form/event-types.tsx
web/core/components/web-hooks/form/form.tsx
web/core/components/web-hooks/form/input.tsx
web/core/components/web-hooks/form/secret-key.tsx
web/core/components/web-hooks/generated-hook-details.tsx
web/core/components/workspace/confirm-workspace-member-remove.tsx
web/core/components/workspace/settings/invitations-list-item.tsx
web/core/components/workspace/settings/members-list-item.tsx
web/core/components/workspace/settings/members-list.tsx
web/core/components/workspace/settings/workspace-details.tsx

Translations for workspace translations

Feat: workspace settings language support

---

packages/i18n/src/locales/en/translations.json
web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/settings/automations/page.tsx
web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/settings/header.tsx
web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/settings/sidebar.tsx
web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/settings/states/page.tsx
web/ce/constants/project/settings/tabs.ts
web/core/components/automation/auto-archive-automation.tsx
web/core/components/automation/auto-close-automation.tsx
web/core/components/estimates/empty-screen.tsx
web/core/components/estimates/root.tsx
web/core/components/labels/create-update-label-inline.tsx
web/core/components/labels/project-setting-label-list.tsx
web/core/components/project/form.tsx
web/core/components/project/member-list.tsx
web/core/components/project/project-settings-member-defaults.tsx
web/core/components/project/send-project-invitation-modal.tsx

- Language support has been added for the project settings.

chore project settings language support

---

packages/i18n/src/locales/en/translations.json
packages/i18n/src/locales/es/translations.json
packages/i18n/src/locales/fr/translations.json
packages/i18n/src/locales/ja/translations.json
packages/i18n/src/locales/zh-CN/translations.json
web/core/components/home/home-dashboard-widgets.tsx
web/core/components/inbox/modals/create-modal/issue-description.tsx
web/core/components/issues/description-input.tsx
web/core/components/issues/issue-modal/components/description-editor.tsx
web/helpers/issue.helper.ts

This update adds language support for description placeholder.

feat: language support description

---

space/core/components/issues/filters/priority.tsx
web/app/profile/sidebar.tsx
web/core/components/dropdowns/cycle/cycle-options.tsx
web/core/components/inbox/inbox-filter/filters/priority.tsx
web/core/components/issues/issue-layouts/filters/header/filters/priority.tsx

This update fixes i18n key naming.

fix: language support

---

packages/i18n/src/locales/en/translations.json
web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/cycles/(list)/header.tsx
web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/cycles/(list)/page.tsx
web/ce/components/cycles/active-cycle/root.tsx
web/ce/components/cycles/analytics-sidebar/base.tsx
web/core/components/cycles/active-cycle/cycle-stats.tsx
web/core/components/cycles/active-cycle/productivity.tsx
web/core/components/cycles/active-cycle/progress.tsx
web/core/components/cycles/analytics-sidebar/issue-progress.tsx
web/core/components/cycles/analytics-sidebar/progress-stats.tsx
web/core/components/cycles/analytics-sidebar/sidebar-details.tsx
web/core/components/cycles/analytics-sidebar/sidebar-header.tsx
web/core/components/cycles/cycles-view-header.tsx
web/core/components/cycles/cycles-view.tsx
web/core/components/cycles/form.tsx
web/core/components/cycles/list/cycle-list-item-action.tsx
web/core/components/cycles/list/root.tsx
web/core/components/cycles/quick-actions.tsx
web/core/components/issues/issue-detail/subscription.tsx
web/core/components/project/search-projects.tsx

Added language support for cycles

Feat ln cycles

---

packages/i18n/src/locales/en/translations.json
web/ce/constants/project/settings/tabs.ts
web/core/components/exporter/export-modal.tsx
web/core/components/issues/issue-detail-widgets/sub-issues/helper.tsx
web/core/components/workspace/views/delete-view-modal.tsx

fix: updated keys

---

packages/i18n/src/locales/en/translations.json
web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/cycles/(list)/header.tsx
web/core/components/issues/create-issue-toast-action-items.tsx
web/core/components/modules/form.tsx
web/core/components/modules/quick-actions.tsx

fix: langauge support keys

---

packages/i18n/src/locales/en/translations.json
space/app/layout.tsx
space/app/provider.tsx
space/core/components/account/auth-forms/auth-header.tsx
space/core/components/instance/instance-failure-view.tsx
space/core/components/issues/issue-layouts/issue-layout-HOC.tsx
space/core/components/issues/issue-layouts/properties/all-properties.tsx
space/core/components/issues/issue-layouts/utils.tsx
space/core/components/issues/peek-overview/header.tsx
space/core/components/issues/peek-overview/issue-properties.tsx
space/public/site.webmanifest.json
web/core/components/inbox/modals/delete-issue-modal.tsx
web/core/components/inbox/root.tsx
web/core/components/issues/archive-issue-modal.tsx
web/core/components/issues/issue-detail/links/create-update-link-modal.tsx
web/core/components/issues/issue-layouts/calendar/quick-add-issue-actions.tsx
web/core/components/issues/issue-modal/draft-issue-layout.tsx
web/core/components/modules/analytics-sidebar/root.tsx
web/core/components/modules/module-card-item.tsx
web/core/components/project/form.tsx
web/core/components/workspace/views/default-view-quick-action.tsx

fix: language support keys

---

apiserver/plane/app/views/issue/label.py

fix:
- cache invalidation by adding `multiple` True to remove all instances of the workspace label cache on creating a label.

fix: cache invalidation for workspace labels endpoint

---

web/core/components/command-palette/actions/search-results.tsx
web/core/components/command-palette/command-modal.tsx

This PR, fixed an issue where workspace level search toggle was not working. This happened due to recent changes in the command palette where we update the project id from `router` to `workItemDetai.projectId`. Due to this change now the projectId was alway `undefined` until we are inside a work item detail page, breaking other logics which are dependent on projectId. To fix this, I have added `routerProjectId` as a fallback case.

fix: command palette search

---

packages/i18n/src/locales/en/translations.json
packages/i18n/src/locales/es/translations.json
packages/i18n/src/locales/fr/translations.json
packages/i18n/src/locales/ja/translations.json
packages/i18n/src/locales/zh-CN/translations.json
web/app/[workspaceSlug]/(projects)/browse/[workItem]/header.tsx

chore: update breadcrumb translation of work item detail page

---

apiserver/plane/db/management/commands/update_deleted_workspace_slug.py
apiserver/plane/db/models/workspace.py

This releases the slug of a soft deleted workspace to be used again.

[WEB-3744] Append the deleted_at timestamp to workspace slug when it is deleted

---

apiserver/plane/bgtasks/issue_activities_task.py
web/core/components/issues/issue-detail/issue-activity/activity/activity-list.tsx

This PR will change estimate activity's field dynamically based on the type.

[WEB-3826] feat: estimate activitites

---

setup.sh

This PR enhances the `setup.sh` script to provide better feedback during the environment setup process. The current script runs silently without any output, making it difficult for new contributors to know if the setup completed successfully or troubleshoot any issues that might occur. The improved script includes color-coded output messages, proper error handling, and verification of all created environment files to make the onboarding process smoother.
**Before:**
```
$ ./setup.sh
$
```
**After:**
```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Plane - Project Management Tool                    
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Setting up your development environment...
Setting up environment files...
✓ Copied ./.env
✓ …
```

Improve setup.sh script with better error handling and user feedback

---

space/core/components/issues/filters/state.tsx

This PR updated space app filters state color size.
[[WEB-3973]](https://app.plane.so/plane/browse/WEB-3973/)

[WEB-3973] chore: space app state icon size

---

web/app/layout.tsx

This PR adds the `metadataBase` property to the Next.js metadata configuration to properly resolve absolute URLs for social media card images.
[[WEB-4274]](https://app.plane.so/plane/browse/WEB-4274/)

[WEB-4274] fix: metadata base url warning

---

packages/constants/src/event-tracker/core.ts
web/app/(all)/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/cycles/(list)/header.tsx
web/app/(all)/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/cycles/(list)/page.tsx
web/app/(all)/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/modules/(list)/header.tsx
web/ce/helpers/command-palette.ts
web/core/components/command-palette/actions/project-actions.tsx
web/core/components/command-palette/command-palette.tsx
web/core/components/cycles/analytics-sidebar/sidebar-header.tsx
web/core/components/cycles/archived-cycles/modal.tsx
web/core/components/cycles/delete-modal.tsx
web/core/components/cycles/form.tsx
web/core/components/cycles/list/cycle-list-item-action.tsx
web/core/components/cycles/modal.tsx
web/core/components/cycles/quick-actions.tsx
web/core/lib/posthog-provider.tsx
web/core/store/event-tracker.store.ts
web/helpers/event-tracker.helper.ts

refactor: cycle events

---

packages/utils/src/string.ts
web/core/components/settings/sidebar/nav-item.tsx

This update refactors the `joinUrlPth` function to use string methods instead of regular expressions.

refactor: string url path utility

---

packages/propel/package.json
packages/propel/src/context-menu/context-menu.stories.tsx
packages/propel/src/context-menu/context-menu.tsx
packages/propel/src/context-menu/index.ts
packages/propel/tsdown.config.ts

This PR introduces the toolbar component in propel.
| Media |
|--------|
| ![media](https://github.com/user-attachments/assets/7ee2580d-aaa2-4213-8254-1d0d03f3a5e5) |

[WEB-4730] dev: propel context menu component

---

apps/api/plane/authentication/views/space/email.py
apps/api/plane/authentication/views/space/github.py
apps/api/plane/authentication/views/space/gitlab.py
apps/api/plane/authentication/views/space/google.py
apps/api/plane/authentication/views/space/magic.py
apps/api/plane/utils/path_validator.py

* Updated MagicSignInSpaceEndpoint and MagicSignUpSpaceEndpoint to directly construct redirect URLs using formatted strings instead of the get_safe_redirect_url function.
* Enhanced get_safe_redirect_url to use quote for safer URL encoding of parameters.
- test all space authentication for correct redirection
[WEB-4943](https://app.plane.so/plane/browse/WEB-4943)

[WEB-4943] refactor: streamline URL construction in authentication views
