makeplane/plane

contexts/user.context.tsx
package.json
pages/index.tsx

fix: 
- redirecting users from the index page to sign in page if they are not signed in 
- else redirecting them to the workspaces page or invitation page

fix: redirection from index page

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/project.py

feat: create a dedicated endpoint to view to the logged in user's project attributes

feat: create a dedicated endpoint to view to the logged in user's project attributes

---

Procfile
app.json

build: create procfile for deployments to heroku

build: create procfile for deployments to heroku

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/cycle.py

refactor: remove bulk assign endpoint, merge it into a single create endpoint and update the create endpoint to maintain db integrity

refactor: remove bulk assign endpoint, merge it into a single create endpoint and update the create endpoint to maintain db integrity

---

apps/app/components/project/issues/issue-detail/issue-detail-sidebar/index.tsx
apps/app/components/project/issues/list-view/index.tsx
apps/app/pages/projects/[projectId]/issues/[issueId].tsx

refractor: 
- removed unnecessary code
- organized imports

fix: mutation on issue details

---

apiserver/plane/api/views/module.py

refactor: bulk assign issues to module

refactor: bulk assign issues to module

---

apps/app/components/project/issues/create-update-issue-modal/index.tsx
apps/app/constants/common.ts
apps/app/constants/index.ts
apps/app/contexts/theme.context.tsx
apps/app/pages/projects/[projectId]/cycles/[cycleId].tsx
apps/app/pages/projects/[projectId]/issues/index.tsx
apps/app/ui/emoji-icon-picker/index.tsx

refractor: 
- moved all filter options to the constants file,
feat:
- hydrating emoji-icon-picker with a random emoji if none is chosen
style:
- UI/UX improvement on the create-update-issue model when there's a similar issue
- add 'None' as an option in order by

fix: mutation on set new default button

---

apps/app/components/common/board-view/single-issue.tsx
apps/app/components/project/create-project-modal.tsx
apps/app/components/project/cycles/list-view/index.tsx
apps/app/components/project/issues/issue-detail/activity/index.tsx
apps/app/components/project/issues/issue-detail/comment/IssueCommentSection.tsx
apps/app/components/project/issues/issue-detail/issue-detail-sidebar/index.tsx
apps/app/components/project/issues/issue-detail/issue-detail-sidebar/select-cycle.tsx
apps/app/components/project/issues/list-view/index.tsx
apps/app/lib/hooks/useIssuesProperties.tsx
apps/app/lib/hooks/useMyIssueFilter.tsx
apps/app/pages/me/my-issues.tsx
apps/app/pages/projects/[projectId]/issues/[issueId].tsx
apps/app/pages/projects/[projectId]/settings/index.tsx
apps/app/types/issues.d.ts
apps/app/ui/Breadcrumbs/index.tsx
apps/app/ui/emoji-icon-picker/index.tsx

refractor:
- changed from target date to due date in the UI,
- moved all local states, & components to their respective component on the issue detail page
- using dynamic import wherever required

fix: made description optional in project settings page, randomly selecting emoji

---

apiserver/plane/api/views/module.py

fix: typo is module issue create

fix: typo is module issue create

---

apiserver/plane/api/views/cycle.py
apiserver/plane/api/views/module.py

refactor: make both cycle issue and module issue view consistent

refactor: make both cycle issue and module issue view consistent

---

apiserver/plane/api/views/cycle.py

fix: status code on issue cycle create

fix: status code on issue cycle create

---

apiserver/plane/api/serializers/module.py
apiserver/plane/api/views/module.py
apiserver/plane/db/models/__init__.py
apiserver/plane/db/models/module.py

feat: links in modules

---

apiserver/plane/api/serializers/issue.py
apiserver/plane/api/views/module.py
apiserver/plane/db/models/module.py

fix: issues can be attached to only one module

fix: issues can be attached to only one module

---

apiserver/plane/api/views/issue.py
apiserver/plane/api/views/project.py
apiserver/plane/api/views/workspace.py

refactor: integrate permission layer in endpoints

refactor: integrate permission layer in endpoints

---

apiserver/plane/bgtasks/magic_link_code_task.py
apiserver/plane/bgtasks/project_invitation_task.py
apiserver/plane/bgtasks/workspace_invitation_task.py
apiserver/plane/db/models/user.py
apiserver/templates/emails/auth/magic_signin.html
apiserver/templates/emails/auth/user_welcome_email.html
apiserver/templates/emails/invitations/project_invitation.html
apiserver/templates/emails/invitations/workspace_invitation.html

feat: create product email html templates

feat: create product email html templates

---

apiserver/plane/api/views/people.py

feat: workspace details on user endpoint

feat: workspace details on user endpoint

---

apps/app/components/project/issues/create-update-issue-modal/index.tsx
apps/app/components/rich-text-editor/index.tsx
apps/app/styles/editor.css

- issue description context is updated with editor manager
- Editor minimum height has been set to 150px

refactor: issue description context is updated with manager

---

apiserver/plane/api/views/people.py

revert: user endpoint changes

---

apiserver/Procfile
apiserver/plane/asgi.py

build: setup asgi

---

apiserver/plane/api/views/people.py

refactor: get workspace slug on user endpoint

refactor: get workspace slug on user endpoint

---

apps/app/components/project/create-project-modal.tsx
apps/app/components/project/cycles/confirm-cycle-deletion.tsx
apps/app/components/project/cycles/create-update-cycle-modal.tsx
apps/app/components/project/issues/BoardView/state/create-update-state-modal.tsx
apps/app/components/project/issues/confirm-issue-deletion.tsx
apps/app/components/project/issues/create-update-issue-modal/index.tsx
apps/app/components/project/issues/create-update-issue-modal/select-cycle.tsx
apps/app/components/project/modules/create-update-module-modal/index.tsx
apps/app/components/project/modules/create-update-module-modal/select-status.tsx
apps/app/components/project/modules/single-module-card.tsx
apps/app/pages/404.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/index.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/modules/[moduleId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/modules/index.tsx
apps/app/types/issues.d.ts

fix:
- showing loader for rich text editor
refractor: 
- changed from sprint to cycle in the issue type

fix: create cycle and state coming below issue modal, 

---

apiserver/plane/api/views/workspace.py

refactor: update invitation endpoint to do bulk operations

refactor: update invitation endpoint to do bulk operations

---

apiserver/plane/api/views/auth_extended.py
apiserver/plane/api/views/authentication.py
apiserver/plane/api/views/base.py
apiserver/plane/api/views/cycle.py
apiserver/plane/api/views/issue.py
apiserver/plane/api/views/module.py
apiserver/plane/api/views/people.py
apiserver/plane/api/views/project.py
apiserver/plane/api/views/workspace.py

refactor: move all 500 errors to 400

refactor: move all 500 errors to 400

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/workspace.py
apiserver/plane/db/models/workspace.py

feat: endpoint and column to store my issue props

feat: endpoint and column to store my issue props

---

apiserver/plane/api/serializers/issue.py

feat: return project details on modules and cycles

feat: return project details on modules and cycles

---

apiserver/plane/db/models/user.py

feat: user role in model

---

apiserver/back_migration.py
apiserver/plane/db/models/issue.py
apiserver/plane/utils/html_processor.py

refactor: add extra columns for json and html description and script for back migrating old issues

refactor: add extra columns for json and html description and script for back migrating old issues

---

apiserver/plane/api/urls.py

fix: add url for workspace availability check

fix: add url for workspace availability check

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/workspace.py
apiserver/plane/db/models/workspace.py

fix: workspace onboarding process

fix: workspace onboarding process

---

apps/app/components/project/create-project-modal.tsx
apps/app/components/project/cycles/board-view/index.tsx
apps/app/components/project/cycles/board-view/single-board.tsx
apps/app/components/project/issues/BoardView/index.tsx
apps/app/components/project/modules/board-view/index.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/modules/[moduleId].tsx
apps/app/ui/emoji-icon-picker/index.tsx

fix:
- select "Public" default in the project 
- mutation on issue count on kanban view 
- removed fetch dependence on project & workspace details, directly using workspace slug and project id from URL

feat: close emoji picker after select

---

apps/app/components/project/issues/issue-detail/activity/index.tsx
apps/app/components/project/issues/issue-detail/comment/issue-comment-section.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx
apps/app/types/issues.d.ts

- feat: Added prop types for IssueActivity

fix: issue activities and issue comments mutation handled at issue detail 

---

apiserver/plane/api/views/workspace.py

fix: update last workspace id on user invitation accept

fix: update last workspace id on user invitation accept

---

apiserver/back_migration.py
apiserver/plane/db/models/issue.py

feat: add json and html column in issue comments

feat: add json and html column in issue comments

---

apiserver/plane/api/views/project.py

fix: update error in project creation

fix: update error in project creation

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/asset.py
apiserver/plane/db/models/asset.py

refactor: file asset upload directory

refactor: file asset upload directory

---

apps/app/components/command-palette/index.tsx
apps/app/components/project/create-project-modal.tsx
apps/app/components/project/issues/create-update-issue-modal/index.tsx
apps/app/components/project/issues/issue-detail/issue-detail-sidebar/select-blocked.tsx
apps/app/components/project/issues/issue-detail/issue-detail-sidebar/select-blocker.tsx
apps/app/components/workspace/send-workspace-invitation-modal.tsx
apps/app/layouts/app-layout.tsx
apps/app/layouts/settings-layout.tsx
apps/app/pages/[workspaceSlug]/me/my-issues.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/control.tsx
apps/app/ui/emoji-icon-picker/index.tsx

fix:
- an issue not getting updated & created on modal
- emoji picker not getting closed on all emoji select
- shortcuts not getting opened in settings pages
- add issue button not working on my issue page
style:
- showing sidebar on unauthorized page
- changed to outline button on blocker and blocked

fix: mutation on project control settings

---

apiserver/plane/api/views/workspace.py
apiserver/plane/db/models/workspace.py

refactor: check for workspace slug on workspace creation

refactor: check for workspace slug on workspace creation

---

apiserver/plane/api/consumers/issue_consumer.py

fix: description activity logging

fix: description activity logging

---

apiserver/plane/db/models/workspace.py

fix: workspace name uniqueness

fix: workspace name uniqueness

---

apiserver/plane/api/serializers/workspace.py

fix: remove workspace slug from read only field

fix: remove workspace slug from read only field

---

apps/app/components/common/list-view/single-issue.tsx
apps/app/components/onboarding/workspace.tsx
apps/app/components/project/issues/create-update-issue-modal/index.tsx
apps/app/components/project/issues/issue-detail/activity/index.tsx
apps/app/components/project/issues/list-view/index.tsx
apps/app/components/rich-text-editor/index.tsx
apps/app/constants/api-routes.ts
apps/app/lib/services/file.service.ts
apps/app/lib/services/workspace.service.ts
apps/app/pages/[workspaceSlug]/me/profile.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx
apps/app/pages/[workspaceSlug]/settings/index.tsx
apps/app/pages/onboarding.tsx
apps/app/types/issues.d.ts
apps/app/types/workspace.d.ts

fix:
- file upload endpoint updated.
- workspace slug check added.
- description_html in remirror added.
- activity description updated.

fix: file upload endpoint, workspace slug check

---

apps/app/components/core/view.tsx
apps/app/components/onboarding/workspace.tsx
apps/app/components/project/create-project-modal.tsx
apps/app/components/project/cycles/create-update-cycle-modal.tsx
apps/app/components/project/modules/single-module-card.tsx
apps/app/layouts/navbar/header.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/index.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/modules/[moduleId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/modules/index.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/control.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/index.tsx
apps/app/pages/invitations.tsx
apps/app/ui/emoji-icon-picker/index.tsx

style:
- updated dropdowns in create project modal, create cycle modal, and project control settings.
feat:
- converted view dropdown to a global component.

style: create project, cycle modal, view dropdown

---

apiserver/plane/api/views/issue.py

refactor: issue activity api to return comments combined

refactor: issue activity api to return comments combined

---

apps/docs/src/components/Navigation.jsx
apps/docs/src/components/Resources.jsx
apps/docs/src/pages/index.mdx
apps/docs/src/pages/quick-start.mdx
apps/docs/src/pages/workspace.mdx

docs: added workspace, quickstart documentation

docs: added workspace, quickstart documentation

---

apps/app/components/project/issues/create-update-issue-modal/index.tsx
apps/app/components/project/issues/issue-detail/comment/issue-comment-card.tsx
apps/app/components/project/issues/issue-detail/comment/issue-comment-section.tsx
apps/app/components/rich-text-editor/index.tsx
apps/app/components/sidebar/workspace-options.tsx
apps/app/pages/[workspaceSlug]/me/profile.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx
apps/app/pages/[workspaceSlug]/settings/index.tsx

fix: reading editor values on focus out

fix: workspace avatar has been updated while loading and remirror onBlur property

---

apiserver/plane/api/views/issue.py
apiserver/plane/api/views/workspace.py

fix: workspace member 500 error and remove pagination from the issue list

fix: workspace member 500 error and remove pagination from the issue list

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

feat: create code of conduct and contributing guidelines

feat: create code of conduct and contributing guidelines

---

apiserver/plane/api/views/issue.py

revert: bring back pagination to avoid breaking

revert: bring back pagination to avoid breaking

---

apiserver/.env.example
apiserver/plane/settings/production.py
apiserver/plane/settings/redis.py

fix: update docker setup to check handle redis

fix: update docker setup to check handle redis

---

README.md
apps/docs/src/components/Header.jsx
apps/docs/src/pages/self-hosting.mdx

docs: added self hosting docs and updated Readme

docs: added self hosting docs and updated Readme

---

apiserver/plane/api/serializers/workspace.py
apiserver/plane/api/views/workspace.py

feat: return workspace member count on user workspace endpoint

feat: return workspace member count on user workspace endpoint

---

apps/app/layouts/navbar/main-sidebar.tsx

feat:
- closing need help dropdown on outside click detections

fix: sidebar dropdown content going below kanban items

---

apps/app/components/common/image-upload-modal.tsx
apps/app/next.config.js
apps/app/pages/[workspaceSlug]/me/profile.tsx

style:
- increased image modal height
- increased z index to highlight image upload modal over the sidebar

fix: added new s3 bucket url in next.config.js file

---

apiserver/plane/api/views/oauth.py

fix: oauth key error

---

apiserver/plane/api/permissions/project.py

fix: fix nomenclature update on permission filter attributes

fix: fix nomenclature update on permission filter attributes

---

apps/docs/src/components/Resources.jsx
apps/docs/src/pages/architecture.mdx
apps/docs/src/pages/cycles.mdx
apps/docs/src/pages/index.mdx
apps/docs/src/pages/issues.mdx
apps/docs/src/pages/modules.mdx

- fixed all the missing page on docs
- removed title text from the template

added missing pages, and title text

---

apps/app/components/command-palette/index.tsx
apps/app/components/common/board-view/single-issue.tsx
apps/app/components/common/list-view/single-issue.tsx
apps/app/components/core/view.tsx
apps/app/components/issues/list-item.tsx
apps/app/components/project/cycles/board-view/single-board.tsx
apps/app/components/project/cycles/list-view/index.tsx
apps/app/components/project/issues/BoardView/single-board.tsx
apps/app/components/project/issues/issue-detail/issue-detail-sidebar/select-assignee.tsx
apps/app/components/project/issues/list-view/index.tsx
apps/app/components/project/join-project.tsx
apps/app/components/project/modules/board-view/single-board.tsx
apps/app/components/project/modules/list-view/index.tsx
apps/app/components/ui/avatar/avatar.tsx
apps/app/components/ui/avatar/index.ts
apps/app/components/ui/index.ts
apps/app/contexts/issue-view.context.tsx
apps/app/pages/[workspaceSlug]/index.tsx
apps/app/pages/[workspaceSlug]/me/my-issues.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/index.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/modules/[moduleId].tsx
apps/app/pages/[workspaceSlug]/settings/index.tsx
apps/app/types/cycles.d.ts
apps/app/types/modules.d.ts

fix:
- added assignees list wherever required.
- added sub-issues count wherever required.
- added priority icons wherever required.
- removed unnecessary props and API calls from list views.

fix: ui fixes

---

apiserver/plane/db/models/issue.py

fix: make issue description null

fix: make issue description null

---

apiserver/plane/api/serializers/cycle.py
apiserver/plane/api/serializers/issue.py
apiserver/plane/api/serializers/module.py
apiserver/plane/api/views/cycle.py
apiserver/plane/api/views/issue.py
apiserver/plane/api/views/module.py
apiserver/plane/api/views/workspace.py

refactor: add annotations in queryset to return sub_issues_count and total members in workspace

refactor: add annotations in queryset to return sub_issues_count and total members in workspace

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/issue.py

feat: endpoint to fetch all sub issues of an issue

feat: endpoint to fetch all sub issues of an issue

---

apiserver/plane/api/views/workspace.py

fix: typo in invitation query

---

apps/app/components/command-palette/index.tsx
apps/app/components/common/board-view/single-issue.tsx
apps/app/components/cycles/modal.tsx
apps/app/components/issues/form.tsx
apps/app/components/issues/modal.tsx
apps/app/components/issues/select/label.tsx
apps/app/components/issues/select/project.tsx
apps/app/components/issues/select/state.tsx
apps/app/components/issues/sub-issue-list.tsx
apps/app/components/project/cycles/confirm-cycle-deletion.tsx
apps/app/components/project/issues/BoardView/index.tsx
apps/app/components/project/issues/BoardView/single-board.tsx
apps/app/components/project/issues/issue-detail/issue-detail-sidebar/index.tsx
apps/app/components/project/issues/issue-detail/issue-detail-sidebar/select-cycle.tsx
apps/app/components/project/issues/list-view/index.tsx
apps/app/components/project/modules/module-detail-sidebar/index.tsx
apps/app/components/ui/avatar/avatar.tsx
apps/app/layouts/app-layout/app-sidebar.tsx
apps/app/layouts/app-layout/index.tsx
apps/app/layouts/settings-layout.tsx
apps/app/lib/auth.ts
apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/index.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/modules/[moduleId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/index.tsx

fix:
- typo in settings auth api

fix: settings auth breaking

---

apps/app/components/command-palette/index.tsx
apps/app/components/common/board-view/single-issue.tsx
apps/app/components/cycles/modal.tsx
apps/app/components/issues/form.tsx
apps/app/components/issues/modal.tsx
apps/app/components/issues/select/label.tsx
apps/app/components/issues/select/project.tsx
apps/app/components/issues/select/state.tsx
apps/app/components/issues/sub-issue-list.tsx
apps/app/components/project/cycles/confirm-cycle-deletion.tsx
apps/app/components/project/issues/BoardView/index.tsx
apps/app/components/project/issues/BoardView/single-board.tsx
apps/app/components/project/issues/issue-detail/issue-detail-sidebar/index.tsx
apps/app/components/project/issues/issue-detail/issue-detail-sidebar/select-blocked.tsx
apps/app/components/project/issues/issue-detail/issue-detail-sidebar/select-blocker.tsx
apps/app/components/project/issues/issue-detail/issue-detail-sidebar/select-cycle.tsx
apps/app/components/project/issues/issue-detail/issue-detail-sidebar/select-parent.tsx
apps/app/components/project/issues/issues-list-modal.tsx
apps/app/components/project/issues/list-view/index.tsx
apps/app/components/project/modules/module-detail-sidebar/index.tsx
apps/app/components/ui/avatar/avatar.tsx
apps/app/layouts/app-layout/app-sidebar.tsx
apps/app/layouts/app-layout/index.tsx
apps/app/layouts/settings-layout.tsx
apps/app/lib/auth.ts
apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/index.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/modules/[moduleId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/index.tsx

refactor:
- changed the way of fetching data on the issue details page.
fix:
- added remove from cycle option.
- blocking and blocked by modals' checkbox error.
- mutation of properties on the issue details page.

refactor: issue details page

---

apps/app/components/ui/tooltip/index.tsx

feat: tooltip component added

---

apiserver/plane/api/serializers/__init__.py
apiserver/plane/api/serializers/api_token.py
apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/api_token.py
apiserver/plane/db/models/__init__.py
apiserver/plane/db/models/api_token.py
apiserver/plane/db/models/user.py

feat: plane API gateway

---

apps/app/components/account/email-code-form.tsx
apps/app/components/account/email-password-form.tsx
apps/app/components/command-palette/index.tsx
apps/app/components/project/card.tsx
apps/app/components/project/cycles/stats-view/single-stat.tsx
apps/app/components/project/modules/single-module-card.tsx
apps/app/components/workspace/help-section.tsx
apps/app/layouts/navbar/main-sidebar.tsx
apps/app/pages/signin.tsx

fix : 
- help option ui improved
- copy shortcut command fix
feat : 
- auth toast added
- card title ellipsis added

fix: ui improvement 

---

apps/app/components/account/email-signin-form.tsx
apps/app/components/common/bulk-delete-issues-modal.tsx
apps/app/components/cycles/select.tsx
apps/app/components/issues/form.tsx
apps/app/components/project/cycles/stats-view/single-stat.tsx
apps/app/components/project/issues/issue-detail/add-as-sub-issue.tsx
apps/app/components/project/issues/issue-detail/comment/issue-comment-card.tsx
apps/app/components/project/issues/issue-detail/comment/issue-comment-section.tsx
apps/app/components/project/issues/issue-detail/issue-detail-sidebar/select-cycle.tsx
apps/app/components/rich-text-editor/toolbar/index.tsx
apps/app/components/workspace/sidebar-dropdown.tsx
apps/app/layouts/app-layout/app-header.tsx
apps/app/layouts/app-layout/app-sidebar.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx
apps/app/pages/[workspaceSlug]/settings/index.tsx
apps/app/styles/editor.css

fix:
- bulk delete issues modal checkbox selection issue.
- sub issues mutation error.
- create issue modal discard glitch.
style:
- consistent cycle icons everywhere.
- removed link option from remirror.
- fixed remirror height issue.
- workspace total members typo.

fix: consistent icons and modal fixes

---

apps/app/components/project/card.tsx
apps/app/components/project/sidebar-list.tsx
apps/app/components/sidebar/projects-list.tsx
apps/app/pages/[workspaceSlug]/index.tsx
apps/app/pages/onboarding/index.tsx

fix: text ellipsis fix

---

apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx

fix: added PROJECT_ISSUES_LIST on the imports

fix: added PROJECT_ISSUES_LIST on the imports

---

apps/app/components/command-palette/index.tsx
apps/app/components/command-palette/shortcuts.tsx
apps/app/components/workspace/help-section.tsx
apps/app/layouts/navbar/main-sidebar.tsx

fix : 
- Update Shortcut event for uppercase key
- Align shortcut buttons 
- Copy issue url shortcut fix
style : 
- change shortcut label to Uppercase

fix: shortcut modal fix

---

apps/app/components/ui/progress-bar/index.tsx

feat: 
- custom progress bar added

feat: custom progress bar added

---

apiserver/plane/api/views/api_token.py
apiserver/plane/db/models/api_token.py

feat: segregate api token workspace

feat: segregate api token workspace

---

apiserver/plane/db/models/issue.py

refactor: update nomenclature for consistency

refactor: update nomenclature for consistency

---

apiserver/plane/api/views/cycle.py
apiserver/plane/api/views/module.py
apiserver/plane/bgtasks/issue_activites_task.py

refactor: update cycle and module create operation

refactor: update cycle and module create operation

---

.gitignore
apps/app/components/issues/sidebar-select/blocker.tsx
apps/app/components/issues/sidebar.tsx
apps/app/components/issues/sub-issues-list-modal.tsx
apps/app/components/rich-text-editor/index.tsx
apps/app/components/rich-text-editor/toolbar/index.tsx
apps/app/components/rich-text-editor/toolbar/link.tsx
apps/app/components/rich-text-editor/toolbar/undo.tsx
apps/app/next.config.js
apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx
apps/app/styles/editor.css

feat:
- added floating link option to remirror.
fix:
- blocked by issues mutation.
- sub-issues mutation.
- modules option in issue details sidebar.

feat: link option in remirror

---

apiserver/back_migration.py
apiserver/plane/api/views/authentication.py

fix: update empty passwords to hashed string and add hashing for magic sign in

fix: update empty passwords to hashed string and add hashing for magic sign in 

---

apiserver/plane/api/views/module.py

fix:  module issue assignment

---

apiserver/plane/db/models/project.py

feat: module and cycle settings under project

feat: module and cycle settings under project

---

apiserver/plane/db/models/issue.py

fix: description and comment_json default value to remove warnings

fix: description and comment_json default value to remove warnings

---

apps/app/components/core/bulk-delete-issues-modal.tsx
apps/app/components/core/sidebar/sidebar-progress-stats.tsx
apps/app/components/issues/sidebar-select/blocked.tsx
apps/app/components/issues/sidebar-select/blocker.tsx
apps/app/components/project/cycles/cycle-detail-sidebar/index.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/modules/[moduleId].tsx

fix:
- create issue modal not working on cycles and modules pages.

fix: create issue modal bugs

---

apps/app/components/core/sidebar/sidebar-progress-stats.tsx
apps/app/components/modules/sidebar.tsx
apps/app/components/project/cycles/cycle-detail-sidebar/index.tsx
apps/app/hooks/use-local-storage.tsx

feat: 
- progress chart render validation added  
- sidebar stats tab validation added
- storing sidebar stats tab context in local storage

feat : sidebar progress improvement

---

apiserver/plane/api/views/project.py
apiserver/plane/api/views/state.py
apiserver/plane/db/models/issue.py
apiserver/plane/db/models/state.py

feat: default state for project

feat: default state for project

---

apiserver/requirements/base.txt

build: add channels requirement for the asgi configuration

build: add channels requirement for the asgi configuration

---

apps/app/components/command-palette/command-pallette.tsx

fix: shortcut command

---

apiserver/templates/admin/base_site.html

refactor: update django admin panel heading

refactor: update django admin panel heading

---

apps/app/components/command-palette/shortcuts-modal.tsx
apps/app/components/workspace/help-section.tsx

fix: 
- search case insensitive
style: 
- email icon updated

fix: shortcut search 

---

apiserver/plane/api/serializers/issue.py
apiserver/plane/api/views/issue.py
apiserver/plane/db/models/__init__.py
apiserver/plane/db/models/issue.py
apps/app/components/core/index.ts
apps/app/components/core/link-modal.tsx
apps/app/components/issues/index.ts
apps/app/components/issues/links-list.tsx
apps/app/components/issues/sub-issues-list.tsx
apps/app/components/modules/index.ts
apps/app/components/modules/sidebar.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx
apps/app/types/issues.d.ts

feat: issue links

---

apps/app/components/issues/select/label.tsx
apps/app/components/issues/sidebar.tsx
apps/app/components/labels/create-label-modal.tsx
apps/app/components/labels/create-update-label-inline.tsx
apps/app/components/labels/single-label.tsx
apps/app/components/project/settings/single-label.tsx
apps/app/components/states/create-state-modal.tsx
apps/app/components/states/create-update-state-inline.tsx

fix:
- old labels can now be assigned a color.
- default color for labels with no color will be set to black.

fix: default label color

---

apps/app/hooks/use-local-storage.tsx

fix: 
- try/catch for invalid values stored in local storage

fix: try/catch for invalid values stored in local storage

---

apps/app/components/account/email-code-form.tsx

style: 
- not showing pointer & theme color on resend code button disabled

style: not showing pointer & theme color on resend code button disabled

---

apps/app/components/core/board-view/board-header.tsx
apps/app/components/core/board-view/single-issue.tsx
apps/app/components/core/bulk-delete-issues-modal.tsx
apps/app/components/core/existing-issues-list-modal.tsx
apps/app/components/core/issues-view.tsx
apps/app/components/core/list-view/single-issue.tsx
apps/app/components/core/list-view/single-list.tsx
apps/app/components/issues/delete-issue-modal.tsx
apps/app/components/issues/modal.tsx
apps/app/components/issues/sidebar-select/blocked.tsx
apps/app/components/issues/sidebar-select/blocker.tsx
apps/app/components/issues/sidebar-select/parent.tsx
apps/app/components/issues/sidebar.tsx
apps/app/components/issues/sub-issues-list.tsx
apps/app/components/project/cycles/stats-view/single-stat.tsx
apps/app/components/states/delete-state-modal.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/index.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/modules/[moduleId].tsx
apps/app/services/issues.service.ts
apps/app/types/issues.d.ts

fix:
- updated types and mutation according to new project issues response.

fix: new project issues response

---

apps/app/components/modules/single-module-card.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/modules/index.tsx

feat:
edit module option added in module card

feat: edit module

---

apps/app/components/core/issues-view.tsx

refactor:
- removed redundancy from the drag and drop function.

refactor: dnd function

---

apps/app/components/core/board-view/single-issue.tsx
apps/app/components/core/list-view/single-issue.tsx
apps/app/components/issues/form.tsx
apps/app/components/issues/modal.tsx
apps/app/types/issues.d.ts

refactor:
- create issue modal input fields according to get request keys.

refactor: create issue modal input fields

---

apiserver/plane/api/serializers/issue.py
apiserver/plane/api/views/issue.py

feat: created_by details for links

feat: created_by details for links

---

apiserver/plane/db/models/state.py

fix: state ordering in group

---

apiserver/plane/api/serializers/issue.py

feat: assignee and label details in cycle and module issues

feat: assignee and label details in cycle and module issues

---

apps/app/components/core/index.ts
apps/app/components/core/multi-level-select.tsx

feat: 
- made a new multi-level select list-box

feat: multi-level select box

---

apps/app/components/core/index.ts
apps/app/components/core/multi-level-select.tsx

style:
- added direction for multi-level drop-down
refractor:
- renamed the component to make more sense

style: added direction for multi-level drop-down

---

apps/app/contexts/issue-view.context.tsx

fix: 
- issue view not updating order_by value

fix: issue view not updating order_by value

---

apps/app/components/issues/modal.tsx

fix: 
- create issue modal close on escape click

fix: create issue modal close on escape click

---

apps/app/components/breadcrumbs/index.tsx
apps/app/components/core/board-view/single-issue.tsx
apps/app/components/core/sidebar/links-list.tsx
apps/app/components/issues/view-select/assignee.tsx
apps/app/components/issues/view-select/priority.tsx
apps/app/components/issues/view-select/state.tsx
apps/app/components/popup/index.tsx
apps/app/components/ui/custom-select.tsx
apps/app/helpers/string.helper.ts
apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/modules/[moduleId].tsx
apps/app/pages/[workspaceSlug]/settings/integrations.tsx

style:
- kanban dropdowns.
- loaders for github integrations.

style: kanban dropdowns

---

apps/app/components/core/link-modal.tsx
apps/app/components/core/sidebar/links-list.tsx
apps/app/components/issues/modal.tsx
apps/app/components/issues/sidebar.tsx
apps/app/components/modules/sidebar.tsx
apps/app/services/issues.service.ts
apps/app/services/modules.service.ts
apps/app/types/issues.d.ts
apps/app/types/modules.d.ts

chore:
- updated issue and module link create and delete endpoints.

chore: new link endpoints

---

apiserver/plane/api/views/cycle.py
apiserver/plane/api/views/module.py
apiserver/plane/utils/grouper.py

feat: filtering for cycle and module issue and updated grouper function for grouping in modules and cycles

feat: filtering for cycle and module issue and updated grouper function for grouping in modules and cycles

---

apps/docs/src/components/Navigation.jsx
apps/docs/src/pages/integrations.mdx
yarn.lock

Added all details, configuration and steps to use GitHub integration on Plane

docs: github integration

---

apiserver/plane/api/views/integration/github.py

fix: add pagination for github repositories endpoint

fix: add pagination for github repositories endpoint

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/cycle.py
apiserver/plane/db/models/cycle.py

refactor: create new endpoints for date checking getting current upcoming and past cycles

refactor: create new endpoints for date checking getting current upcoming and past cycles

---

apiserver/plane/db/models/project.py

fix: remove project slug

---

apiserver/plane/api/serializers/__init__.py
apiserver/plane/api/serializers/issue.py
apiserver/plane/api/serializers/module.py
apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/issue.py
apiserver/plane/api/views/module.py
apiserver/plane/db/models/issue.py
apiserver/plane/db/models/module.py

refactor: update links to different endpoints

refactor: update links to different endpoints

---

apps/app/components/states/single-state.tsx
apps/app/components/ui/tooltip.tsx

chore:
- user cannot delete the last state of a group.

chore: cannot have empty state group

---

apps/app/components/ui/button/index.ts
apps/app/components/ui/button/primary-button.tsx

style: 
- new primary button design

style: new primary button design

---

apps/app/components/core/index.ts
apps/app/components/core/unsplash-modal.tsx
apps/app/components/project/create-project-modal.tsx
apps/app/next.config.js
apps/app/services/file.service.ts
apps/app/types/projects.d.ts

feat: 
- cover image selector for project create

feat: cover image selector for project create

---

apps/app/layouts/app-layout/app-header.tsx

style:
- changed app header color to white

style: changed app header color to white

---

apps/app/pages/[workspaceSlug]/settings/index.tsx

fix:
- UX of workspace settings image upload
- upload button on the workspace settings page not working

fix: upload button on workspace settings page not working

---

apps/app/components/cycles/completed-cycles-list.tsx
apps/app/components/cycles/cycles-list.tsx
apps/app/components/cycles/form.tsx
apps/app/components/cycles/index.ts
apps/app/components/cycles/modal.tsx
apps/app/components/cycles/sidebar.tsx
apps/app/constants/cycle.ts
apps/app/constants/fetch-keys.ts
apps/app/helpers/date-time.helper.ts
apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx
apps/app/services/cycles.service.ts
apps/app/types/cycles.d.ts

feat: 
- cycle validation added
- draft cycle added

feat: cycle validations

---

apps/app/components/popup/index.tsx
apps/app/components/project/single-integration-card.tsx
apps/app/layouts/settings-navbar.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/members.tsx
apps/app/pages/[workspaceSlug]/settings/index.tsx
apps/app/pages/[workspaceSlug]/settings/integrations.tsx
apps/app/pages/[workspaceSlug]/settings/members.tsx

style:
- workspace settings pages.

style: workspace settings pages

---

apps/app/components/project/sidebar-list.tsx
apps/app/components/project/single-project-card.tsx
apps/app/services/project.service.ts
apps/app/types/projects.d.ts

chore:
- updated convention from `favourite` to `favorite`

chore: updated project favorites endpoints

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/asset.py

feat: delete file assets from storage

feat: delete file assets from storage

---

apiserver/plane/api/views/cycle.py

chore: rename past cycle to completed cycle

chore: rename past cycle to completed cycle

---

apiserver/plane/api/views/workspace.py

fix: workspace member listing endpoint

fix: workspace member listing endpoint

---

apiserver/plane/api/views/module.py

fix: module issue viewset typo

fix: module issue viewset typo

---

apiserver/plane/api/serializers/__init__.py
apiserver/plane/api/serializers/project.py
apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/project.py
apiserver/plane/db/models/__init__.py
apiserver/plane/db/models/project.py

feat: add project to favourites

feat: add project to favourites

---

apiserver/plane/db/models/project.py

feat: add cover image to project

feat: add cover image to project

---

apiserver/plane/api/views/cycle.py

fix: cycle date filtering for current and upcoming cycle

fix: cycle date filtering for current and upcoming cycle

---

apiserver/plane/api/views/cycle.py
apiserver/plane/api/views/module.py

fix: cycle and module issue filtering

fix: cycle and module issue filtering

---

apiserver/plane/api/serializers/issue.py

feat: already exisiting  url validation

feat: already exisiting  url validation

---

apiserver/plane/api/serializers/__init__.py
apiserver/plane/api/serializers/module.py
apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/module.py
apiserver/plane/db/models/__init__.py
apiserver/plane/db/models/module.py

feat: module favourites for user

feat: module favourites for user

---

apps/app/components/command-palette/command-pallette.tsx
apps/app/components/core/existing-issues-list-modal.tsx
apps/app/components/cycles/completed-cycles-list.tsx
apps/app/components/cycles/cycles-list.tsx
apps/app/components/cycles/modal.tsx
apps/app/components/cycles/single-cycle-card.tsx
apps/app/components/issues/modal.tsx
apps/app/helpers/date-time.helper.ts
apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx
apps/app/types/cycles.d.ts

chore:
- cycles list loading screen.
fix:
- cycles add to favorites and remove from favorites mutation.
- modals scrolling issue.

chore: cycles loading, fix: cycles favorite mutation

---

apps/app/components/rich-text-editor/index.tsx

fix: 
- text selection moving when typing in between

fix: text selection moving when typing in between

---

apps/app/components/ui/custom-menu.tsx

fix:
- custom menu link item display.

fix: custom menu link item

---

apps/app/components/issues/comment/add-comment.tsx
apps/app/components/modules/form.tsx
apps/app/components/modules/modal.tsx
apps/app/components/modules/select/select-lead.tsx
apps/app/components/modules/select/select-members.tsx
apps/app/components/modules/single-module-card.tsx
apps/app/components/rich-text-editor/index.tsx

chore:
- updated lead and members dropdowns for module modal.

chore: update module dropdowns

---

apiserver/plane/api/views/project.py

fix: project member filter for bot accounts

fix: project member filter for bot accounts

---

apiserver/plane/api/serializers/api_token.py
apiserver/plane/api/views/api_token.py

fix: make api token only view once

fix: make api token only view once

---

apiserver/back_migration.py

dev: add back migration for project cover images

dev: add back migration for project cover images

---

apps/app/components/core/board-view/single-board.tsx
apps/app/components/core/board-view/single-issue.tsx
apps/app/components/issues/sidebar-select/assignee.tsx
apps/app/components/issues/sidebar-select/cycle.tsx
apps/app/components/issues/sidebar-select/module.tsx
apps/app/components/issues/sidebar-select/priority.tsx
apps/app/components/issues/sidebar-select/state.tsx

fix:
- kanban overlay z-index.
- issue sidebar dropdowns position.

fix: drag overlay z-index, sidebar dropdowns

---

apps/app/components/core/board-view/single-board.tsx

fix:
- order by text for kanban overlay.

fix: order by text

---

apiserver/.env.example
apiserver/plane/settings/production.py
apps/app/.env.example
docker-compose.yml
nginx/Dockerfile
nginx/nginx.conf
setup.sh

refactor: self hosting setup

---

apps/app/components/cycles/cycles-list.tsx
apps/app/components/cycles/empty-cycle.tsx
apps/app/components/cycles/index.ts

style:
- design empty cycle state

style: empty cycle state

---

apps/app/components/core/board-view/all-boards.tsx
apps/app/components/cycles/sidebar.tsx
apps/app/components/cycles/single-cycle-card.tsx
apps/app/components/issues/my-issues-list-item.tsx
apps/app/components/modules/sidebar.tsx
apps/app/components/modules/single-module-card.tsx
apps/app/pages/[workspaceSlug]/me/my-issues.tsx

fix: 
- kanban view vertical scroll fix
chore:
- delete option remove from my issue page
- my issue page filter key renamed to id.
style: 
- design my issue page list view
- icon  added in cycle & module card options.
- sidebar ellipsis alignment
- cycle card favorite & progress icon alignment for longer title.

style : ui fixes

---

apps/app/components/workspace/sidebar-dropdown.tsx

style: workspace dropdown

---

apps/app/components/project/single-integration-card.tsx
apps/app/services/api.service.ts
apps/app/services/project.service.ts
apps/app/styles/globals.css

feat:
- added load more button to github repos dropdown.

feat: added load more button to github repos dropdown

---

apps/app/components/ui/avatar.tsx
apps/app/components/workspace/sidebar-dropdown.tsx
apps/app/components/workspace/sidebar-menu.tsx
apps/app/layouts/app-layout/app-sidebar.tsx

style:
- design workspace  sidebar navigation

style: workspace sidebar

---

.github/ISSUE_TEMPLATE/--bug-report.yaml
.github/ISSUE_TEMPLATE/--feature-request.yaml
.github/ISSUE_TEMPLATE/config.yaml

feat: new issue templates

---

apiserver/plane/api/views/cycle.py
apiserver/plane/api/views/integration/base.py
apiserver/plane/api/views/integration/github.py
apiserver/plane/api/views/module.py

chore: permissions for api endpoints

chore: permissions for api endpoints

---

apps/app/components/modules/sidebar.tsx

fix:
- lead select not working on the modules sidebar.

fix: modules sidebar lead select not working

---

apps/app/helpers/string.helper.ts

fix:
- truncate text function to handle undefined or null strings.

fix: truncate text function

---

apps/app/components/core/board-view/all-boards.tsx
apps/app/components/core/board-view/board-header.tsx
apps/app/components/core/board-view/single-issue.tsx
apps/app/components/core/list-view/single-issue.tsx
apps/app/components/cycles/cycles-list.tsx
apps/app/components/cycles/single-cycle-card.tsx
apps/app/components/issues/my-issues-list-item.tsx
apps/app/components/modules/single-module-card.tsx
apps/app/components/ui/custom-menu.tsx
apps/app/components/ui/custom-search-select.tsx
apps/app/components/ui/custom-select.tsx
apps/app/components/ui/linear-progress-indicator.tsx
apps/app/components/ui/tooltip.tsx
apps/app/components/workspace/sidebar-dropdown.tsx
apps/app/components/workspace/sidebar-menu.tsx
apps/app/layouts/app-layout/index.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/modules/index.tsx

style:
optimized spacing and text sizes for--
- cycle card.
- module card.
- issue card in kanban view.
- issue card in list view.
- app sidebar workspace menu.
- custom select.
- custom search select.

style: made the paddings and text sizes smaller

---

apps/app/pages/[workspaceSlug]/projects/index.tsx

fix: 
- made project list authenticated

fix: made project list authenticated

---

apps/app/components/ui/custom-search-select.tsx

refactor:
- custom search select multiple prop condition.

refactor: custom search select component

---

apps/app/components/views/delete-view-modal.tsx
apps/app/components/views/form.tsx
apps/app/components/views/index.ts
apps/app/components/views/modal.tsx
apps/app/constants/fetch-keys.ts
apps/app/pages/[workspaceSlug]/projects/[projectId]/views/[viewId].tsx
apps/app/services/views.service.ts
apps/app/types/index.d.ts
apps/app/types/views.d.ts

feat:
- views boilerplate created.

feat: views boilerplate created

---

apps/app/components/cycles/form.tsx

fix: 
- current cycle date checker fix

fix: date checker edge case fix

---

apps/app/components/core/list-view/single-list.tsx
apps/app/components/cycles/single-cycle-card.tsx
apps/app/components/modules/single-module-card.tsx

feat:
- progress bar for modules.
fix:
- progress stats for cycles according to the new response.

feat: progress bar for module

---

apps/app/components/modules/single-module-card.tsx
apps/app/components/workspace/sidebar-dropdown.tsx

fix:
- app sidebar workspace dropdown links width.
- round off module progress percentage to 2 decimal places.

fix: workspace dropdown

---

apiserver/plane/api/views/people.py

refactor: users endpoint to return invites and assigned issues count

refactor: users endpoint to return invites and assigned issues count

---

apiserver/plane/api/views/cycle.py

dev: add cycle date validation

dev: add cycle date validation

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/workspace.py

feat: user activity graph

---

apiserver/plane/api/views/cycle.py
apiserver/plane/api/views/module.py
apiserver/plane/api/views/project.py

refactor: update favorites for project, cycle and module

refactor: update favorites for project, cycle and module

---

apiserver/plane/api/serializers/issue.py
apiserver/plane/api/views/cycle.py
apiserver/plane/api/views/module.py

refactor: update response structure for cycle issue and module issues

refactor: update response structure for cycle issue and module issues

---

apiserver/plane/utils/grouper.py

refactor: grouper function to fix priority keys

refactor: grouper function to fix priority keys

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/asset.py
apiserver/plane/db/models/asset.py

refactor: separate endpoints for workspace assets and user assets

refactor: separate endpoints for workspace assets and user assets

---

apps/app/contexts/user.context.tsx
apps/app/pages/[workspaceSlug]/me/profile.tsx

chore:
- update profile page stats to all workspaces.

chore: update user profile stats

---

apps/app/components/issues/description-form.tsx

fix:
- description changed from github not appearing issue.

fix: github description not appearing

---

apps/app/components/core/issues-view-filter.tsx
apps/app/components/core/issues-view.tsx
apps/app/components/ui/index.ts
apps/app/components/ui/multi-level-dropdown.tsx

style: 
- made new issue filter dropdown

style: made new issue filter dropdown

---

apps/app/components/core/board-view/single-issue.tsx
apps/app/components/core/issues-view.tsx
apps/app/components/core/list-view/single-issue.tsx
apps/app/constants/fetch-keys.ts
apps/app/contexts/issue-view.context.tsx
apps/app/hooks/use-issues-view.tsx

refractor: 
- added params to fetch key

refractor: added params to fetch key

---

apps/app/components/core/sidebar/links-list.tsx
apps/app/components/issues/activity.tsx
apps/app/components/issues/comment/comment-card.tsx
apps/app/types/issues.d.ts
apps/app/types/users.d.ts

fix:
- wrong name in activity and comment from the github bot

fix: bot activity and comment log name

---

apps/app/components/breadcrumbs/index.tsx
apps/app/components/cycles/sidebar.tsx
apps/app/components/issues/description-form.tsx
apps/app/components/modules/sidebar.tsx
apps/app/components/modules/single-module-card.tsx

fix:
- modules and sidebar loader padding.
- modules progress should show percentage in integer.
- issue details page description saving status ui.

fix: minor ui fixes

---

apiserver/plane/bgtasks/importer_task.py

refactor: update importer task to create user automatically and adding it to project and workspace

refactor: update importer task to create user automatically and adding it to project and workspace

---

apiserver/plane/db/models/project.py

feat: add flag for toggling issue views

feat: add flag for toggling issue views

---

apiserver/plane/api/views/workspace.py

chore: update the endpoint to return last 6 months data

chore: update the endpoint to return last 6 months data

---

apiserver/plane/api/views/workspace.py

fix: workspace invitation datetime import

fix: workspace invitation datetime import

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/workspace.py

feat: user workspace dashboard endpoint

feat: user workspace dashboard endpoint

---

apiserver/plane/api/views/issue.py

feat: sub issue toggle

---

apiserver/plane/api/views/cycle.py
apiserver/plane/api/views/module.py
apiserver/plane/api/views/view.py

feat: add issue filters for cycles and modules

feat: add issue filters for cycles and modules

---

apiserver/plane/api/serializers/cycle.py
apiserver/plane/api/serializers/module.py
apiserver/plane/api/views/cycle.py
apiserver/plane/api/views/module.py

feat: cycles and modules issues state group percentages

feat: cycles and modules issues state group percentages

---

apps/app/components/cycles/single-cycle-card.tsx
apps/app/components/modules/single-module-card.tsx
apps/app/components/project/sidebar-list.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
apps/app/types/cycles.d.ts
apps/app/types/modules.d.ts

chore:
- updated modules and cycles issue stats calculation from frontend to backend.

chore: new modules and cycles response

---

apps/app/package.json
apps/app/pages/_app.tsx
apps/app/styles/nprogress.css

feat: 
- showing progress while the page is being loaded

feat: showing progress while page is being loaded

---

apps/app/components/core/issues-view.tsx

style: kanban loader

---

apps/app/components/command-palette/shortcuts-modal.tsx
apps/app/components/workspace/help-section.tsx

fix:
- sidebar collapse state shortcut ordering
-  shortcut modal cmd / ctrl fix

fix: sidebar and shortcut modal

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/asset.py
apiserver/plane/db/models/asset.py

fix: file asset uploading and deleting

fix: file asset uploading and deleting

---

apps/app/components/command-palette/shortcuts-modal.tsx
apps/app/components/workspace/help-section.tsx

Revert "fix: sidebar and shortcut modal"

---

apps/app/components/core/issues-view-filter.tsx
apps/app/components/icons/index.ts
apps/app/components/views/form.tsx
apps/app/components/views/index.ts
apps/app/components/views/select-filters.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/views/index.tsx

chore:
- created a new global select filters component for the create view modal and issue filters.

chore: new global select filters component

---

apps/app/components/core/board-view/all-boards.tsx
apps/app/components/core/board-view/single-board.tsx

refactor: 
- states with the group 'completed' or 'canceled' are collapsed by default

refactor: states with the group 'completed' or 'canceled' are collapsed by default

---

apps/app/components/core/issues-view.tsx

fix:
- drag and drop into empty groups.

fix: kanban drag and drop

---

apps/app/pages/create-workspace.tsx

style: 
- create workspace bg fix

style: create workspace bg fix

---

apps/app/pages/[workspaceSlug]/me/profile.tsx

chore:
- updated my issues quick link text on my profile page.

chore: updated my issues text

---

apps/app/components/core/image-upload-modal.tsx
apps/app/components/ui/linear-progress-indicator.tsx

fix:
- delete image preview after modal close.

fix: delete image preview after modal close

---

apps/app/components/core/issues-view.tsx
apps/app/hooks/use-issues-view.tsx

fix:
- kanban loading state.
- shoe empty state if no issues are present.

fix: kanban loading state

---

apiserver/plane/utils/issue_filters.py

fix: issue filtering keyerror

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/page.py
apiserver/plane/db/models/page.py

dev: endpoints for my, other, recent and favorite pages, add sort order and color for pages

dev: endpoints for my, other, recent and favorite pages, add sort order and color for pages

---

apiserver/plane/api/views/workspace.py

fix: dashboard endpoint for overdue and upcoming issues

fix: dashboard endpoint for overdue and upcoming issues

---

apps/app/components/core/issues-view.tsx

chore:
- update view button in the list and Kanban view.

chore: update view button

---

apps/app/components/workspace/completed-issues-graph.tsx
apps/app/components/workspace/issues-pie-chart.tsx
apps/app/components/workspace/issues-stats.tsx
apps/app/pages/[workspaceSlug]/index.tsx
apps/app/services/user.service.ts
apps/app/types/users.d.ts

fix:
- completed issues graph.
style:
- issue stats.

fix: workspace dashboard

---

apps/app/components/labels/create-label-modal.tsx

style: 
- removed color text from label modal
- also closing the color picker on the color selection

style: removed color text from label modal

---

apps/app/components/core/issues-view-filter.tsx

fix:
- deselecting filter option when clicked again

fix: deselecting filter option when clicked again

---

apiserver/plane/api/serializers/page.py
apiserver/plane/api/views/page.py

dev: update recent pages endpoint and return blocks on page listing

dev: update recent pages endpoint and return blocks on page listing

---

apiserver/plane/api/views/workspace.py

fix: dashboard issues filters

---

apiserver/plane/api/views/cycle.py
apiserver/plane/api/views/importer.py
apiserver/plane/api/views/issue.py
apiserver/plane/api/views/module.py
apiserver/plane/api/views/page.py
apiserver/plane/api/views/project.py
apiserver/plane/api/views/view.py
apiserver/plane/api/views/workspace.py

fix: model ordering

---

apiserver/plane/utils/issue_filters.py

fix: start date and target date issue filter

fix: start date and target date issue filter

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/gpt.py
apiserver/plane/settings/local.py
apiserver/plane/settings/production.py
apiserver/plane/settings/staging.py
apiserver/requirements/base.txt

feat: GPT integration

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/search.py

feat: global search endpoint for workspace

feat: global search endpoint for workspace

---

apiserver/plane/api/serializers/__init__.py
apiserver/plane/api/serializers/issue.py
apiserver/plane/api/serializers/project.py
apiserver/plane/api/serializers/state.py
apiserver/plane/api/views/issue.py
apiserver/plane/api/views/page.py
apiserver/plane/api/views/view.py

perf: update issue serializer

---

apiserver/plane/api/serializers/page.py

fix: page labels update

---

apiserver/plane/api/views/page.py

fix: pages endpoint for dates and access

fix: pages endpoint for dates and access

---

apiserver/plane/utils/issue_filters.py

fix: issue filters for start date and target date

fix: issue filters for start date and target date

---

apps/app/components/modules/single-module-card.tsx

fix:
- display module progress percentage.

fix: module progress bar

---

apps/app/components/project/create-project-modal.tsx
apps/app/layouts/app-layout/index.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/index.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/modules/[moduleId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/modules/index.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/pages/index.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/views/[viewId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/views/index.tsx
apps/app/pages/[workspaceSlug]/projects/index.tsx

fix:
- join project screen flicker before page load.

fix: join project screen flicker

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/search.py

fix: global search endpoint to show entities within projects and add filtering through identifiers

fix: global search endpoint to show entities within projects and add filtering through identifiers

---

apiserver/plane/api/views/gpt.py

fix: gpt task and prompt

---

apiserver/requirements/base.txt

fix: add slack sdk in requirements file

fix: add slack sdk in requirements file

---

apiserver/plane/db/models/project.py

feat: page view toggle in project settings

feat: page view toggle in project settings

---

apiserver/plane/api/views/page.py

fix: date for earlier this week

fix: date for earlier this week

---

apiserver/plane/db/models/page.py

feat: sync flag for syncing issues with page blocks

feat: sync flag for syncing issues with page blocks

---

apps/app/components/workspace/issues-list.tsx
apps/app/components/workspace/issues-pie-chart.tsx

style: 
- workspace cards height.

style: workspace cards

---

apps/app/components/modules/single-module-card.tsx
apps/app/components/views/index.ts
apps/app/components/views/single-view-item.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/views/index.tsx
apps/app/services/modules.service.ts
apps/app/services/views.service.ts
apps/app/types/views.d.ts

style: 
- view list page.
refactor:
- single-view-item component.
chore:
- toggle favorite for views.

style: views list page, chore: views favorite

---

apiserver/plane/api/views/gpt.py

chore: return gpt response in html

chore: return gpt response in html

---

apiserver/plane/api/views/cycle.py

fix: cycle validation for completed cycles

fix: cycle validation for completed cycles

---

apps/app/components/core/sidebar/sidebar-progress-stats.tsx
apps/app/components/modules/sidebar.tsx

fix: 
- module sidebar link section relocation

fix: module sidebar link section relocation

---

apps/app/components/command-palette/command-pallette.tsx

feat: 
- add crisp chat with us option in cmdk

feat: add crisp chat with us option in cmdk

---

apps/app/pages/[workspaceSlug]/index.tsx
yarn.lock

style:
- changed dashboard header background color

style: dashboard color

---

apps/app/pages/[workspaceSlug]/me/profile.tsx

fix: 
- profile page header fix

fix: profile page header fix

---

apps/app/pages/api/track-event.ts
apps/app/services/track-event.service.ts
apps/app/types/cycles.d.ts
apps/app/types/issues.d.ts
apps/app/types/modules.d.ts
apps/app/types/projects.d.ts
apps/app/types/state.d.ts
apps/app/types/workspace.d.ts

fix: 
- transmitting selective data for analytics

fix: transmitting selective data for analytics

---

apps/app/components/cycles/cycles-list.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx

feat: 
- in cycle list page message  added when no current cycle is available .

feat: cycle list page

---

apps/app/components/pages/single-page-block.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx

style:
- added divider to the pages block

style: added divider to the pages block

---

apps/app/components/core/existing-issues-list-modal.tsx
apps/app/components/issues/modal.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/modules/[moduleId].tsx
apps/app/types/issues.d.ts

fix:
- mutation issues while adding issues to cycle or module.

fix: mutation while adding issue to cycle or module

---

apps/app/components/issues/sidebar-select/cycle.tsx
apps/app/constants/fetch-keys.ts
apps/app/services/cycles.service.ts

feat : 
- incomplete cycle endpoint added
fix :
- issue sidebar cycle fix

feat: incomplete cycle endpoint added , issue sidebar cycle fix

---

apps/app/components/views/form.tsx

feat: 
- add label to create view modal

feat: add label to create view modal

---

apiserver/plane/api/views/gpt.py
apiserver/plane/settings/local.py
apiserver/plane/settings/production.py
apiserver/plane/settings/staging.py

feat: add API limit for AI assistance

feat: add API limit for AI assistance

---

apiserver/plane/api/serializers/issue.py
apiserver/plane/api/views/issue.py

chore: add cycle id and module id in issues list endpoint

chore: add cycle id and module id in issues list endpoint

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/people.py

feat: user activities endpoint

feat: user activities endpoint

---

apiserver/plane/api/views/gpt.py

chore: return user request count from logger

chore: return user request count from logger

---

apps/app/components/modules/single-module-card.tsx

fix:
- module status line break

fix: module status line break

---

apps/app/components/modules/single-module-card.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/modules/index.tsx

style:
-fixed height issue in module card

style: fixed height issue in module card

---

apps/app/components/onboarding/invite-members.tsx
apps/app/components/onboarding/workspace.tsx
apps/app/components/ui/buttons/danger-button.tsx
apps/app/components/ui/buttons/primary-button.tsx
apps/app/components/ui/buttons/secondary-button.tsx
apps/app/components/workspace/create-workspace-form.tsx
apps/app/constants/workspace.ts

fix:
- padding in the onboarding screens.

fix: minor bugs in the onboarding screens

---

apps/app/pages/[workspaceSlug]/settings/members.tsx

feat:
-added invitation pill for members invitation status in setting members

feat: added invitation pending pills

---

apiserver/plane/api/serializers/issue.py
apiserver/plane/api/views/issue.py
apiserver/plane/api/views/people.py

chore: workspace detail on issue activity serializer

chore: workspace detail on issue activity serializer

---

apiserver/plane/api/serializers/project.py

fix: project update for identifier

fix: project update for identifier

---

apps/app/components/core/calendar-view/calendar.tsx
apps/app/constants/fetch-keys.ts
apps/app/services/cycles.service.ts
apps/app/services/modules.service.ts
apps/app/types/issues.d.ts

fix:
- fetching the correct list of issues on the calendar view.

fix: fetch correct list of issues on the calendar view

---

apps/app/components/onboarding/user-details.tsx
apps/app/constants/workspace.ts
apps/app/pages/[workspaceSlug]/me/profile/index.tsx

fix:
- role input on my profile page

fix: role input on my profile page

---

apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/index.tsx

fix:
- project identifier check in project settings

fix: project identifier check in project settings

---

apps/app/components/issues/sidebar-select/assignee.tsx
apps/app/components/ui/datepicker.tsx
apps/app/components/views/select-filters.tsx

fix:
- issue details sidebar dropdowns height.

fix: sidebar dropdowns height

---

apps/app/components/core/gpt-assistant-modal.tsx
apps/app/services/ai.service.ts

chore:
- show an error if the user reaches the maximum limit of the ai assistant.

chore: ai assistant limit error

---

apiserver/plane/api/views/page.py

chore: create activity when a block is converter into an issue

chore: create activity when a block is converter into an issue

---

apps/app/components/cycles/delete-cycle-modal.tsx
apps/app/components/modules/delete-module-modal.tsx
apps/app/components/workspace/delete-workspace-modal.tsx

fix: 
-modal inconsistency
-fixed typo in cycle card

fix: modal width inconsistency

---

apps/app/components/cycles/sidebar.tsx

fix: 
- sidebar pending issue stats fix

fix: sidebar pending issue stats fix

---

apps/app/components/workspace/delete-workspace-modal.tsx

style: 
- delete workspace modal

style: delete workspace modal

---

apps/app/components/core/board-view/single-issue.tsx
apps/app/components/core/list-view/single-issue.tsx
apps/app/components/cycles/sidebar.tsx
apps/app/components/cycles/single-cycle-card.tsx
apps/app/components/issues/my-issues-list-item.tsx
apps/app/components/modules/sidebar.tsx
apps/app/components/modules/single-module-card.tsx
apps/app/components/project/single-project-card.tsx
apps/app/components/project/single-sidebar-project.tsx
apps/app/components/ui/context-menu.tsx
apps/app/components/ui/custom-menu.tsx

style: 
- consistent  ellipsis menu styling

style: ellipsis consistent style

---

apps/app/components/cycles/form.tsx
apps/app/components/cycles/sidebar.tsx
apps/app/components/modules/form.tsx

fix: 
- invalid date toast message updated

fix: invalid date toast message updated

---

apps/app/components/core/list-view/single-issue.tsx
apps/app/components/cycles/delete-cycle-modal.tsx
apps/app/components/issues/delete-issue-modal.tsx
apps/app/components/modules/delete-module-modal.tsx
apps/app/hooks/use-issues-view.tsx

fix:
- delete mutations for issues, cycles and modules

fix: delete mutations for issues, cycles and modules

---

apps/app/components/core/board-view/single-issue.tsx
apps/app/components/core/list-view/single-issue.tsx
apps/app/components/core/sidebar/sidebar-progress-stats.tsx
apps/app/components/cycles/sidebar.tsx
apps/app/components/modules/sidebar.tsx

refactor:
- cycle and module sidebar stats mutation after editing an issue.

refactor: sidebar stats mutation

---

apps/app/components/core/list-view/single-list.tsx
apps/app/components/pages/create-update-page-modal.tsx
apps/app/components/pages/pages-list/recent-pages-list.tsx
apps/app/components/pages/pages-view.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/pages/index.tsx

chore:
- pages content update.
- empty state for recent pages.
- after creating a new page, redirect to that page.
- list view heading font size decreased.

chore: pages content update, empty state for recent pages

---

apps/app/components/core/issues-view.tsx
apps/app/components/workspace/sidebar-dropdown.tsx
apps/app/pages/_error.js

style: custom error page

---

apps/app/components/cycles/sidebar.tsx
apps/app/pages/_error.js

chore:
- cycle sidebar content updated for progress chart.
- go back button fixed for the custom error page.

chore: cycle sidebar content updated

---

apiserver/plane/api/views/page.py

fix: recent pages endpoint

---

apps/app/components/issues/sidebar-select/blocked.tsx
apps/app/components/issues/sidebar-select/blocker.tsx

fix:
- blocked and blocking issue pills in issue details sidebar.

fix: blocked and blocking in issue details sidebar

---

apps/app/components/core/image-upload-modal.tsx
apps/app/pages/[workspaceSlug]/me/profile/index.tsx
apps/app/pages/[workspaceSlug]/settings/index.tsx

fix:
- delete old image after uploading new image.

fix: image upload

---

apps/app/components/issues/activity.tsx

fix: 
- set and remove activity logs are showing problems
- removing due date is showing static value of 1 Jan.
- old labels to have black color.
- word 'Description' should be bold

fix: issue activity logs

---

apps/app/components/core/filter-list.tsx
apps/app/components/icons/priority-icon.tsx
apps/app/components/pages/delete-page-modal.tsx
apps/app/components/pages/single-page-detailed-item.tsx
apps/app/components/pages/single-page-list-item.tsx
apps/app/components/views/single-view-item.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/views/index.tsx

fix:
-added + icon to create view button. 
-delete page modal formatted.
-page list and kanban view ellipses is formatted.
-fixed color of priority filter > none.

fix: style and bugs

---

apps/app/components/onboarding/workspace.tsx
apps/app/components/workspace/create-workspace-form.tsx
apps/app/pages/create-workspace.tsx

fix:
- switching between new & invite workspaces is resetting the values

fix: persist data on tab switch in workspace

---

apps/app/components/pages/single-page-block.tsx

chore:
- remove edit and push issue from page block.

chore: remove edit and push issue from page block

---

apps/app/components/cycles/single-cycle-card.tsx

refactor:
- cycles toggle favorite mutation.

refactor: cycles toggle favorite

---

apps/app/components/issues/sidebar-select/cycle.tsx
apps/app/components/issues/sidebar-select/module.tsx
apps/app/components/issues/sidebar.tsx

fix: 
- issue sidebar module , cycle and label dropdown fix

fix: issue sidebar module , cycle and label dropdown fix

---

apps/app/components/cycles/transfer-issues-modal.tsx

style: 
- transfer issue modal empty state added

style: transfer issue modal empty state added

---

apps/app/helpers/date-time.helper.ts

fix: cycle status bug fix

---

apps/app/components/pages/delete-page-modal.tsx
apps/app/components/project/confirm-project-member-remove.tsx
apps/app/components/states/delete-state-modal.tsx
apps/app/components/views/delete-view-modal.tsx
apps/app/components/views/single-view-item.tsx
apps/app/components/workspace/confirm-workspace-member-remove.tsx

fix:
- single view list link not working 
- fixed all delete modal inconsistency

fix: view list link

---

apps/app/components/core/board-view/board-header.tsx
apps/app/components/core/list-view/single-list.tsx

feat: 
- list and kanban view group by header icon

feat: list and kanban view group by header icon

---

apps/app/components/core/feeds.tsx
apps/app/components/core/index.ts
apps/app/pages/[workspaceSlug]/me/profile/activity.tsx

style: 
- designed user activity

style: designed user activity.

---

apps/app/components/core/feeds.tsx

fix: 
- missing icon on deleting issue in user activity

fix: missing deleted icon in user activity

---

apps/app/components/command-palette/command-pallette.tsx
apps/app/components/command-palette/shortcuts-modal.tsx
apps/app/components/ui/empty-state.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/pages/index.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/views/index.tsx

feat: 
-added shortcut keys for view and page modal.
-updated shortcut modal.
-added shortcut key  description in their respective empty state.

feat: shortcuts

---

apps/app/components/account/email-code-form.tsx
apps/app/components/core/board-view/single-issue.tsx
apps/app/components/views/single-view-item.tsx
apps/app/constants/issue.ts
apps/app/hooks/use-issues-view.tsx

fix: signin page typo

---

apps/app/components/core/image-picker-popover.tsx

fix: 
- search button not working on the image picker popover

fix: search button not working on image picker popover

---

apps/app/components/core/issues-view.tsx
apps/app/components/cycles/index.ts
apps/app/components/cycles/transfer-issues.tsx

feat: 
- completed cycle transfer issue validation added

feat: completed cycle transfer issue validation added

---

apps/app/components/issues/sidebar.tsx
apps/app/components/modules/sidebar.tsx
apps/app/services/issues.service.ts
apps/app/services/modules.service.ts

fix:
- user cannot create duplicate links for an issue or module.

fix: user cannot create duplicate links

---

apps/app/pages/api/track-event.ts

fix: 
- tracker not creating user alias

fix: tracker not creating user alias

---

apps/app/hooks/use-issues-view.tsx

fix:
- kanban always showing empty state.

fix: kanban empty issues

---

apps/app/components/command-palette/change-issue-assignee.tsx
apps/app/components/command-palette/change-issue-priority.tsx
apps/app/components/command-palette/change-issue-state.tsx
apps/app/components/command-palette/command-pallette.tsx
apps/app/styles/command-pallette.css

fix:
- user can navigate using arrow keys

fix: cmdk arrow key navigation

---

apps/app/components/core/board-view/single-issue.tsx
apps/app/components/core/list-view/single-issue.tsx

feat:
-added open in new tab for list and kanban issue.

feat: issue redirect

---

apps/app/styles/command-pallette.css

fix: cmdk hover style

---

apiserver/plane/api/serializers/module.py

fix: module link create url validation

fix: module link create url validation

---

apiserver/back_migration.py

dev: back migration to update label colors

dev: back migration to update label colors

---

apiserver/plane/api/views/people.py

chore: return user role in user onboard endpoint

chore: return user role in user onboard endpoint

---

apiserver/plane/api/serializers/issue.py

chore: add workspace details on comment serializer

chore: add workspace details on comment serializer

---

apiserver/plane/bgtasks/importer_task.py

fix: add check if the users need to be imported

fix: add check if the users need to be imported

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/estimate.py
apiserver/plane/db/models/estimate.py

feat: bulk create endpoint for estimate points

feat: bulk create endpoint for estimate points

---

apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/index.tsx

feat: 
- update project cover image

feat: update project cover image

---

apps/app/components/integration/delete-import-modal.tsx
apps/app/components/integration/guide.tsx
apps/app/components/integration/index.ts
apps/app/components/integration/single-import.tsx
apps/app/services/integration/index.ts

chore: delete import

---

apiserver/plane/api/serializers/issue.py

fix: default assignee for issues

fix: default assignee for issues

---

apiserver/Procfile
apiserver/bin/worker
apiserver/plane/api/views/cycle.py
apiserver/plane/api/views/issue.py
apiserver/plane/api/views/module.py
apiserver/plane/bgtasks/email_verification_task.py
apiserver/plane/bgtasks/forgot_password_task.py
apiserver/plane/bgtasks/importer_task.py
apiserver/plane/bgtasks/issue_activites_task.py
apiserver/plane/bgtasks/magic_link_code_task.py
apiserver/plane/bgtasks/project_invitation_task.py
apiserver/plane/bgtasks/workspace_invitation_task.py
apiserver/plane/settings/__init__.py
apiserver/plane/settings/celery.py
apiserver/plane/settings/common.py
apiserver/plane/settings/local.py
apiserver/plane/settings/production.py
apiserver/plane/settings/redis.py
apiserver/plane/settings/staging.py
apiserver/requirements/base.txt
docker-compose.yml

refactor: move all background task from rqworker to celery

refactor: move all background task from rqworker to celery

---

apiserver/plane/api/serializers/issue.py

chore: add workspace and project details on label endpoints

chore: add workspace and project details on label endpoints

---

apiserver/plane/api/serializers/importer.py
apiserver/plane/api/views/importer.py

chore: add project details on importer service endpoint

chore: add project details on importer service endpoint

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/importer.py

feat: delete endpoint for importers

feat: delete endpoint for importers

---

apiserver/plane/api/views/search.py

fix: project issue search endpoint

fix: project issue search endpoint

---

apiserver/plane/api/views/importer.py
apiserver/plane/utils/importers/jira.py

chore: rename project name to project key for jira issue imports

chore: rename project name to project key for jira issue imports

---

apps/app/components/core/image-picker-popover.tsx
apps/app/components/emoji-icon-picker/index.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/index.tsx

fix:
- added image popover for settings cover.
- fixed style for icon emoji picker.

fix: added image popover for settings cover

---

apps/app/components/command-palette/command-pallette.tsx

fix :
- shortcut combination key bug fix

fix: shortcut combination key bug fix

---

apps/app/components/integration/github/import-users.tsx
apps/app/components/integration/github/single-user-select.tsx

fix:
- fetch selected project members in the import users section.

fix: fetch selected project members

---

apps/app/components/estimates/estimate-points-modal.tsx
apps/app/components/estimates/single-estimate.tsx
apps/app/components/issues/form.tsx
apps/app/components/issues/select/estimate.tsx
apps/app/components/issues/sidebar-select/estimate.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/estimates.tsx

fix: 
-fixed inconsistency in style of estimates

fix: inconsistency in style of estimates

---

apps/app/pages/[workspaceSlug]/index.tsx

fix:
- check for workspace slug in the dashboard workspace activity mutation.

fix: dashboard workspace activity mutation

---

apps/app/constants/workspace.ts
apps/app/pages/[workspaceSlug]/index.tsx

chore:
- remove jira importer from workspace settings.

chore: disable jira importer

---

apps/app/layouts/auth-layout/project-authorization-wrapper.tsx
apps/app/layouts/auth-layout/user-authorization-wrapper.tsx
apps/app/layouts/auth-layout/workspace-authorization-wrapper.tsx
apps/app/pages/[workspaceSlug]/index.tsx
apps/app/pages/signin.tsx

style:
- workspace, project and user loading screens.

style: loading screens

---

apps/app/components/issues/attachment-upload.tsx

feat: 
- upload button validation

feat: upload button validation

---

apiserver/plane/api/views/issue.py
apiserver/plane/bgtasks/issue_activites_task.py

feat: activity for issue attachments and links

feat: activity for issue attachments and links

---

apiserver/plane/api/views/cycle.py

fix: cycle date check endpoint

fix: cycle date check endpoint

---

setup.sh

Fixes #715 setup.sh causing `tr Illegal byte sequence`

dev: fix setup.sh causing tr Illegal byte sequence

---

apps/app/components/issues/attachment-upload.tsx

style: 
- attachment upload button improvement

style: attachment upload button

---

apps/app/components/views/single-view-item.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/views/index.tsx

style:
- redesign view
feat:
- add no of filters

style: redesign view

---

apiserver/bin/worker

fix: worker script

---

apps/app/components/onboarding/workspace.tsx

fix: 
- workspace join button fix

fix: workspace join button fix

---

apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/index.tsx

fix: 
- project setting identifier validation added

fix: project setting identifier

---

apps/app/pages/[workspaceSlug]/settings/index.tsx

chore:
- added remove workspace image in workspace settings.

chore: added remove workspace image in workspace settings

---

apps/app/components/auth-screens/project/join-project.tsx

fix: 
- workspace joining state fix

fix: workspace joining state fix

---

apps/app/components/core/feeds.tsx
apps/app/components/issues/activity.tsx

feat: 
- attachment, link and estimate activity log added in profile activity section & issue detail page.

feat: issue activity logs

---

apps/app/components/issues/select/date.tsx
apps/app/components/issues/select/estimate.tsx

style: 
- create issue modal icon

style: create issue modal icon

---

apiserver/plane/api/views/importer.py

fix: jira importer info endpoint to get query params

fix: jira importer info endpoint to get query params

---

apps/app/components/core/issues-view.tsx
apps/app/components/views/delete-view-modal.tsx
apps/app/components/views/form.tsx
apps/app/components/views/modal.tsx
apps/app/components/views/single-view-item.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/views/index.tsx

feat:
- edit view
fix: 
- consistent edit view modals

feat: now user can edit view

---

apps/app/components/core/board-view/single-issue.tsx
apps/app/components/core/list-view/single-issue.tsx
apps/app/hooks/use-issue-properties.tsx
apps/app/hooks/use-my-issues-filter.tsx
apps/app/types/issues.d.ts

feat :
- attachment and link display properties

feat: attachment and link display properties

---

apps/app/components/pages/pages-view.tsx
apps/app/components/pages/single-page-block.tsx
apps/app/components/pages/single-page-detailed-item.tsx
apps/app/components/pages/single-page-list-item.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx

feat :
- page info icon
- page block dropdown menu improvement
- page label improvement 
fix :
- page title & label overflow fix

feat: page improvement

---

apps/app/components/command-palette/command-pallette.tsx

feat: 
- add create page option in cmdk menu

feat: add create page option in cmdk menu

---

apps/app/components/workspace/sidebar-dropdown.tsx
apps/app/pages/index.tsx

fix: 
- unusual redirection in index page

fix: unusual redirection in index page

---

apiserver/plane/api/views/issue.py

fix: issue attachment delete

---

apiserver/plane/api/views/issue.py
apiserver/plane/bgtasks/issue_activites_task.py

fix: attachment activity

---

apiserver/plane/bgtasks/issue_activites_task.py

fix: issue link activity

---

apiserver/plane/api/serializers/issue.py

fix: remove length check condition when updating issue property

fix: remove length check condition when updating issue property

---

apiserver/plane/api/views/importer.py

fix: error message for jira importers

fix: error message for jira importers

---

apps/app/pages/index.tsx

fix: 
- unusual redirection on onboarding

fix: unusual redirection on onboarding

---

apps/app/components/workspace/activity-graph.tsx

fix:
- workspace dashboard duplicate keys.

fix: workspace dashboard duplicate keys

---

apps/app/components/workspace/create-workspace-form.tsx
apps/app/pages/[workspaceSlug]/settings/index.tsx

style: 
- removed static 'app.plane.so'

style: removed static 'app.plane.so'

---

apps/app/components/workspace/create-workspace-form.tsx

style: workspace url

---

apps/app/components/cycles/single-cycle-card.tsx

fix: 
- cycle card redirection

fix: cycle card redirection

---

apps/app/components/core/issues-view.tsx

refactor: drag function

---

apps/app/components/cycles/sidebar.tsx
apps/app/components/modules/sidebar.tsx

fix: 
- cycle and module sidebar fix

fix: cycle and module sidebar fix

---

apiserver/plane/db/models/issue.py

chore: set default value as null for estimate point

chore: set default value as null for estimate point

---

apiserver/plane/api/views/search.py

fix: parent issue search

---

apiserver/plane/settings/production.py

chore: production settings for celery

chore: production settings for celery

---

apiserver/plane/settings/redis.py

fix: connection error when signing in with code

fix: connection error when signing in with code

---

apiserver/plane/api/serializers/__init__.py
apiserver/plane/api/serializers/workspace.py
apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/workspace.py
apiserver/plane/db/models/__init__.py
apiserver/plane/db/models/user.py
apiserver/plane/db/models/workspace.py

feat: workspace themes

---

apps/app/components/core/existing-issues-list-modal.tsx
apps/app/components/core/issues-view.tsx
apps/app/components/issues/modal.tsx
apps/app/components/issues/view-select/assignee.tsx
apps/app/components/issues/view-select/due-date.tsx
apps/app/components/issues/view-select/estimate.tsx
apps/app/components/issues/view-select/priority.tsx
apps/app/components/issues/view-select/state.tsx

fix:
- cycles and modules sidebar mutation.

fix: cycles and modules sidebar mutation

---

apps/app/components/auth-screens/project/join-project.tsx

fix: join project mutation

---

apps/app/components/estimates/single-estimate.tsx

fix: 
- removed extra spaces form estimate points brackets

fix: removed extra spaces form estimate points brackets

---

apiserver/plane/api/serializers/view.py

chore: remove view filter validation while creating or updating view

chore: remove view filter validation while creating or updating view

---

apps/app/components/issues/select/state.tsx

chore: 
- added default state for issues

chore: added default state for issues

---

apps/app/pages/[workspaceSlug]/me/my-issues.tsx

chore:
- remove estimate option from my issues.

chore: remove estimate option from my issues

---

apps/app/components/core/issues-view.tsx
apps/app/components/views/form.tsx
apps/app/components/views/modal.tsx

fix: 
- create update view modal fix

fix: create update view modal fix

---

apps/app/hooks/use-local-storage.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/pages/index.tsx

feat: page tab context

---

apps/app/components/core/issues-view.tsx

fix:
- drop to delete box z-index.

fix: drop to delete box z-index

---

apps/app/components/core/filter-list.tsx

fix:
- clear all filters function.
- clear issue type filter function.

fix: remove filters function

---

apps/app/components/integration/github/import-users.tsx
apps/app/components/integration/github/single-user-select.tsx

chore:
- show workspace members in import users section of github importer.

chore: show workspace members

---

apps/app/contexts/issue-view.context.tsx

fix:
- show proper issues list if no filters are present.

fix: show proper issues list if no filters are present

---

apps/app/components/pages/create-update-block-inline.tsx

fix:
- undefined block content when using `I'm feeling lucky`.

fix: undefined block content

---

apps/app/pages/[workspaceSlug]/index.tsx

style: dashboard content

---

apiserver/plane/api/views/issue.py

chore: my issues endpoint to return attachment and link count

chore: my issues endpoint to return attachment and link count

---

apps/app/components/core/issues-view.tsx
apps/app/components/issues/my-issues-list-item.tsx
apps/app/pages/[workspaceSlug]/me/my-issues.tsx

chore: filters spacing

---

apps/app/contexts/project-member.context.tsx
apps/app/layouts/auth-layout/project-authorization-wrapper.tsx

fix: 
- project authorization API fetch keys

fix: project authorization api fetch keys

---

apps/app/components/integration/delete-import-modal.tsx
apps/app/services/integration/index.ts

fix:
- delete import new endpoint.

fix: delete import

---

apps/app/components/integration/delete-import-modal.tsx
apps/app/contexts/project-member.context.tsx
apps/app/hooks/use-project-details.tsx
apps/app/layouts/auth-layout/project-authorization-wrapper.tsx
apps/app/services/integration/index.ts

promote: patches from develop to stage-release

promote: patches from develop to stage-release

---

apps/app/components/core/board-view/board-header.tsx
apps/app/components/core/list-view/all-lists.tsx
apps/app/components/core/list-view/single-issue.tsx
apps/app/components/core/list-view/single-list.tsx
apps/app/components/issues/view-select/assignee.tsx
apps/app/components/ui/datepicker.tsx

style:
- list view spacing reduced.

style: list view spacing reduced

---

apps/app/components/account/email-password-form.tsx
apps/app/components/core/issues-view.tsx
apps/app/components/cycles/sidebar.tsx
apps/app/components/estimates/create-update-estimate-modal.tsx
apps/app/components/issues/activity.tsx
apps/app/components/labels/create-update-label-inline.tsx
apps/app/components/labels/labels-list-modal.tsx
apps/app/components/modules/sidebar.tsx
apps/app/components/onboarding/invite-members.tsx
apps/app/components/project/single-integration-card.tsx
apps/app/components/rich-text-editor/toolbar/float-tool-tip.tsx
apps/app/components/workspace/send-workspace-invitation-modal.tsx
apps/app/helpers/string.helper.ts
apps/app/pages/[workspaceSlug]/projects/[projectId]/modules/[moduleId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/labels.tsx

chore:
- remove redundant console logs.

chore: remove redundant console logs

---

apps/app/components/states/create-state-modal.tsx
apps/app/components/states/create-update-state-inline.tsx
apps/app/components/states/delete-state-modal.tsx
apps/app/services/state.service.ts

chore:
- create/update state duplicate name error.

chore: create/update state duplicate name error

---

apps/app/components/estimates/estimate-points-modal.tsx
apps/app/components/estimates/single-estimate.tsx

chore:
- create/update estimate points validation.

chore: create/update estimate points validation

---

apps/app/components/auth-screens/project/join-project.tsx

fix: join project button

---

apiserver/plane/api/views/state.py

chore: update state create endpoint to send error response on integrity error

chore: update state create endpoint to send error response on integrity error

---

apps/app/components/rich-text-editor/index.tsx
apps/app/package.json
yarn.lock

fix: 
- added TLDs like ".app" and many more

fix: add tlds

---

apps/app/components/issues/select/assignee.tsx
apps/app/components/issues/select/label.tsx
apps/app/components/ui/labels-list.tsx

fix :
- assignee and label count removed
- label list bug fix

fix : create issue modal

---

apps/app/components/onboarding/invite-members.tsx
apps/app/components/onboarding/workspace.tsx
apps/app/components/workspace/create-workspace-form.tsx

fix : 
- invite button validation
style: 
- workspace screen tab

fix: invite button validation , style: workspace screen

---

apps/app/components/onboarding/invite-members.tsx
apps/app/layouts/auth-layout/project-authorization-wrapper.tsx
apps/app/layouts/auth-layout/workspace-authorization-wrapper.tsx

chore: 
- changed workspace and project loading text.
- changed case of email id placeholder.

chore: changed loading text

---

apps/app/components/estimates/create-update-estimate-modal.tsx

fix:
- reset estimates modal form after create/update.

fix: reset estimates modal form after create/update

---

apps/app/components/pages/single-page-detailed-item.tsx
apps/app/components/pages/single-page-list-item.tsx

chore: changed pages icon

---

apps/app/components/pages/pages-view.tsx

fix: pages access mutation

---

apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx

feat: 
- cycle list tab context

feat: cycle list tab context

---

apps/app/components/issues/attachment-upload.tsx
apps/app/pages/[workspaceSlug]/index.tsx

chore: 
- attachment upload button text updated
- dashboard github banner text updated

chore: upload button and github banner text update

---

apps/app/components/workspace/sidebar-dropdown.tsx

fix:
- sidebar workspace dropdown logo character.

fix: sidebar workspace dropdown logo

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/state.py

chore: state delete validations endpoint

chore: state delete validations endpoint

---

apiserver/plane/api/views/issue.py

feat: sub issue state distribution

feat: sub issue state distribution

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/estimate.py

chore: single endpoint to create estimate and estimate points

chore: single endpoint to create estimate and estimate points

---

apps/app/components/core/board-view/single-board.tsx
apps/app/components/core/sidebar/links-list.tsx
apps/app/components/issues/activity.tsx
apps/app/components/issues/sidebar-select/assignee.tsx
apps/app/components/issues/sidebar-select/blocked.tsx
apps/app/components/issues/sidebar-select/blocker.tsx
apps/app/components/issues/sidebar-select/cycle.tsx
apps/app/components/issues/sidebar-select/estimate.tsx
apps/app/components/issues/sidebar-select/module.tsx
apps/app/components/issues/sidebar-select/parent.tsx
apps/app/components/issues/sidebar-select/priority.tsx
apps/app/components/issues/sidebar-select/state.tsx
apps/app/components/issues/sidebar.tsx
apps/app/components/project/single-sidebar-project.tsx
apps/app/components/ui/custom-select.tsx
apps/app/layouts/app-layout/app-header.tsx
apps/app/layouts/auth-layout/project-authorization-wrapper.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx

style:
- issue details page theming.

style: issue details page

---

apps/app/components/core/calendar-view/calendar.tsx
apps/app/components/core/issues-view-filter.tsx
apps/app/components/core/issues-view.tsx
apps/app/contexts/issue-view.context.tsx

feat: calendar filters

---

apps/app/components/pages/single-page-detailed-item.tsx
apps/app/components/pages/single-page-list-item.tsx

feat: copy page link added

---

apps/app/components/project/sidebar-list.tsx
apps/app/components/ui/datepicker.tsx
apps/app/components/ui/loader.tsx
apps/app/constants/issue.ts
apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/index.tsx
apps/app/styles/globals.css

fix:
- dark mode text color.
- datepicker style.

fix: theming fixes

---

apps/app/components/pages/single-page-list-item.tsx
apps/app/components/views/single-view-item.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/views/index.tsx

style: views theming

---

apps/app/components/workspace/create-workspace-form.tsx

chore:
- added new restricted workspace slugs.

chore: added new restricted workspace slugs

---

apiserver/plane/api/views/base.py
apiserver/plane/api/views/importer.py
apiserver/plane/api/views/issue.py
apiserver/plane/api/views/oauth.py
apiserver/plane/api/views/page.py
apiserver/plane/api/views/search.py
apiserver/plane/api/views/workspace.py
apiserver/plane/bgtasks/issue_activites_task.py
apiserver/plane/bgtasks/magic_link_code_task.py
apiserver/plane/bgtasks/project_invitation_task.py

remove: print exception instead use capture to log it

remove: print exception instead use capture to log it

---

apiserver/plane/api/serializers/__init__.py
apiserver/plane/api/serializers/estimate.py
apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/estimate.py

chore: added estimate bulk endpoint for retrieving and updating

chore: added estimate bulk endpoint for retrieving and updating

---

apiserver/plane/db/models/cycle.py

feat: cycle view props

---

apiserver/plane/db/models/module.py

feat: module view props

---

apps/app/components/cycles/form.tsx
apps/app/helpers/date-time.helper.ts

fix: cycle date validation

---

apiserver/back_migration.py

dev: back migration for integrations

dev: back migration for integrations

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/state.py

remove:  state delete issue validation endpoint

remove:  state delete issue validation endpoint

---

apps/app/components/command-palette/change-issue-state.tsx
apps/app/components/core/filter-list.tsx
apps/app/components/core/issues-view.tsx
apps/app/components/issues/select/state.tsx
apps/app/components/issues/sidebar-select/state.tsx
apps/app/components/issues/view-select/state.tsx
apps/app/components/states/create-state-modal.tsx
apps/app/components/states/create-update-state-inline.tsx
apps/app/components/states/delete-state-modal.tsx
apps/app/components/states/single-state.tsx
apps/app/components/views/select-filters.tsx
apps/app/constants/fetch-keys.ts
apps/app/helpers/state.helper.ts
apps/app/hooks/use-issues-view.tsx
apps/app/hooks/use-my-issues-filter.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/states.tsx
apps/app/services/state.service.ts
apps/app/types/state.d.ts

chore:
- state delete validation.
- create and delete state mutations.

chore: state delete validation

---

apiserver/plane/settings/staging.py

dev: add s3 url for staging

---

apps/app/components/labels/create-update-label-inline.tsx
apps/app/components/labels/single-label-group.tsx
apps/app/components/labels/single-label.tsx
apps/app/components/project/single-integration-card.tsx
apps/app/components/states/create-update-state-inline.tsx
apps/app/components/states/single-state.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/features.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/members.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/states.tsx
apps/app/pages/[workspaceSlug]/settings/members.tsx
apps/app/services/project.service.ts
apps/app/services/track-event.service.ts
apps/app/styles/globals.css

style:
- project settings' pages theming.

style: project settings theming

---

apps/app/components/estimates/create-update-estimate-modal.tsx
apps/app/types/estimate.d.ts

fix:
- points not updating while editing estimate.

fix: points not updating while editing estimate

---

apps/app/components/account/email-code-form.tsx
apps/app/components/account/email-password-form.tsx
apps/app/components/account/github-login-button.tsx
apps/app/components/ui/input/index.tsx
apps/app/layouts/default-layout/index.tsx
apps/app/pages/signin.tsx

style: signin page theming

---

apps/app/components/core/filter-list.tsx

style:
- filters list theming.

style: filters list theming

---

apps/app/components/auth-screens/not-authorized-view.tsx
apps/app/components/auth-screens/project/join-project.tsx
apps/app/components/auth-screens/workspace/not-a-member.tsx

style: auth pages theming

---

apps/app/components/core/board-view/single-issue.tsx
apps/app/components/core/list-view/single-issue.tsx
apps/app/components/cycles/sidebar.tsx
apps/app/components/issues/sidebar-select/parent.tsx
apps/app/components/issues/sidebar.tsx
apps/app/components/issues/view-select/due-date.tsx
apps/app/components/modules/sidebar-select/select-lead.tsx
apps/app/components/modules/sidebar.tsx
apps/app/helpers/date-time.helper.ts
apps/app/styles/globals.css

chore:
- updated empty input fields' text.

chore: empty input fields text

---

apps/app/components/integration/delete-import-modal.tsx
apps/app/components/integration/github/import-configure.tsx
apps/app/components/integration/github/import-confirm.tsx
apps/app/components/integration/github/import-data.tsx
apps/app/components/integration/github/import-users.tsx
apps/app/components/integration/github/repo-details.tsx
apps/app/components/integration/github/root.tsx
apps/app/components/integration/github/select-repository.tsx
apps/app/components/integration/github/single-user-select.tsx
apps/app/components/integration/guide.tsx
apps/app/components/integration/jira/confirm-import.tsx
apps/app/components/integration/jira/give-details.tsx
apps/app/components/integration/jira/import-users.tsx
apps/app/components/integration/jira/jira-project-detail.tsx
apps/app/components/integration/jira/root.tsx
apps/app/components/integration/single-import.tsx

style:
- github/jira importers theming.

style: importers theming

---

apps/app/components/emoji-icon-picker/index.tsx
apps/app/components/integration/single-integration-card.tsx
apps/app/layouts/auth-layout/project-authorization-wrapper.tsx
apps/app/layouts/auth-layout/workspace-authorization-wrapper.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/control.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/index.tsx
apps/app/pages/[workspaceSlug]/settings/billing.tsx
apps/app/pages/[workspaceSlug]/settings/index.tsx

style:
- workspace and project settings.

style: workspace and project settings

---

apps/app/components/core/calendar-view/calendar.tsx
apps/app/components/core/issues-view.tsx

style: calendar view

---

apps/app/components/core/calendar-view/calendar.tsx
apps/app/components/core/issues-view-filter.tsx
apps/app/components/integration/github/import-data.tsx
apps/app/components/issues/form.tsx
apps/app/components/ui/toggle-switch.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/features.tsx

chore:
- added custom toggle switch everywhere.

chore: added custom toggle switch everywhere

---

apps/app/components/ui/empty-state.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/estimates.tsx
apps/app/public/empty-state/empty-estimate.svg

chore:
- empty state for estimates.

chore: empty state for estimates

---

apps/app/components/core/feeds.tsx
apps/app/components/issues/activity.tsx
apps/app/components/issues/comment/comment-card.tsx
apps/app/pages/[workspaceSlug]/me/profile/index.tsx

style:
- profile settings, activity theming.

style: profile settings, activity theming

---

apps/app/components/onboarding/invite-members.tsx
apps/app/components/workspace/create-workspace-form.tsx

chore:
- updated invite modal text

chore: invite text update

---

apps/app/components/ui/custom-search-select.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx

chore: 
- added create label inside of pages label select

chore: added create label inside of pages label select

---

apps/app/components/project/single-sidebar-project.tsx
apps/app/components/workspace/sidebar-menu.tsx

chore: 
- fixed sidebar highlight not working

chore: fixed sidebar highlight not working

---

apps/app/components/issues/sub-issues-list.tsx

fix: sub issues list fix

---

apps/app/components/core/image-picker-popover.tsx
apps/app/components/project/create-project-modal.tsx

style:
- create project modal.

style: create project modal

---

apps/app/components/onboarding/invite-members.tsx

chore:
- removed email span from invite member page

chore: removed email span from invite member page

---

apps/app/hooks/use-integration-popup.tsx

fix: 
- added the decoded url for slack integration popup

fix: added the decoded url for slack integration popup

---

apps/app/components/command-palette/command-pallette.tsx
apps/app/components/icons/cycle-icon.tsx

style: 
- command k item and cycle icon theming

style: command k item and cycle icon theming

---

apps/app/components/onboarding/invite-members.tsx
apps/app/components/onboarding/onboarding-card.tsx
apps/app/components/onboarding/user-details.tsx
apps/app/components/onboarding/workspace.tsx
apps/app/components/workspace/create-workspace-form.tsx
apps/app/pages/invitations.tsx
apps/app/pages/onboarding.tsx
yarn.lock

style:
- onboarding screens.
- invitations page.
- create workspace form.
chore:
- updated restricted workspace slugs' list.

style: onboarding screens, invitations page

---

apps/app/components/estimates/create-update-estimate-modal.tsx

refactor:
- estimates payload generate function.

refactor: estimates payload generate function

---

apiserver/plane/utils/issue_filters.py

feat: filter issues by estimate points

feat: filter issues by estimate points

---

apiserver/plane/api/views/page.py

fix: page access update

---

apiserver/plane/bgtasks/importer_task.py
apiserver/plane/bgtasks/user_welcome_task.py

chore: importer user invite email

chore: importer user invite email

---

apiserver/plane/api/views/importer.py

fix: bulk modules importer

---

apiserver/plane/api/views/importer.py
apiserver/plane/db/models/importer.py

feat: delete imported data as well when the import is deleted

feat: delete imported data as well when the import is deleted

---

apiserver/plane/api/views/cycle.py
apiserver/plane/bgtasks/issue_activites_task.py

chore: log cycle delete and cycle issue delete activities

chore: log cycle delete and cycle issue delete activities

---

apiserver/plane/bgtasks/importer_task.py
apiserver/plane/bgtasks/user_welcome_task.py

fix: import user invite emails

fix: import user invite emails

---

apps/app/components/account/google-login.tsx
apps/app/pages/signin.tsx

promote: develop to stage-release

promote: develop to stage-release

---

apps/app/Dockerfile.web

dev:: update docker file for frontend

dev:: update docker file for frontend

---

Dockerfile
start.sh

fix: single docker file

---

README.md

docs: update self hosting section in readme

docs: update self hosting section in readme

---

apiserver/plane/api/serializers/importer.py

feat: workspace detail for imports

feat: workspace detail for imports

---

apiserver/plane/api/serializers/estimate.py
apiserver/plane/api/views/estimate.py

feat: return workspace and project details in estimate endpoints

feat: return workspace and project details in estimate endpoints

---

apiserver/plane/api/views/estimate.py
apiserver/plane/db/models/estimate.py

fix: estimate points update

---

apiserver/plane/api/serializers/cycle.py
apiserver/plane/api/views/cycle.py

chore: add assignee avatar in cycle endpoint

chore: add assignee avatar in cycle endpoint

---

apiserver/plane/api/views/cycle.py

fix: cycle date check endpoint for updation

fix: cycle date check endpoint for updation

---

apps/app/components/integration/guide.tsx
apps/app/components/integration/single-import.tsx
apps/app/services/estimates.service.ts
apps/app/services/integration/github.service.ts
apps/app/services/integration/index.ts
apps/app/services/integration/jira.service.ts
apps/app/services/track-event.service.ts
apps/app/types/estimate.d.ts

chore:
- track events for estimates and importers.

chore: track events for estimates and importers

---

apps/app/services/api.service.ts

fix: handled token expiry validation

fix: handled token expiry validation

---

apps/app/components/core/gpt-assistant-modal.tsx
apps/app/components/issues/description-form.tsx
apps/app/components/issues/form.tsx
apps/app/styles/editor.css

fix: 
- placeholder and ai response not getting appended in textarea

fix: placeholder and ai response not getting appended in textarea

---

apiserver/plane/api/views/importer.py
apiserver/plane/api/views/project.py
apiserver/plane/api/views/workspace.py
apiserver/plane/bgtasks/importer_task.py

fix: created by null for bulk operations

fix: created by null for bulk operations

---

apps/app/components/issues/view-select/due-date.tsx

style: 
- issue due date selector width fix

style: issue due date selector width fix

---

apiserver/plane/api/views/analytic.py
apiserver/plane/utils/issue_filters.py

fix: analytics

---

apps/app/components/core/calendar-view/single-issue.tsx
apps/app/components/cycles/sidebar.tsx
apps/app/components/modules/sidebar.tsx
apps/app/components/modules/single-module-card.tsx
apps/app/components/pages/single-page-block.tsx
apps/app/layouts/app-layout/app-sidebar.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/modules/[moduleId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx
apps/app/styles/react-datepicker.css

style: 
- calendar border added
- page detail page padding and spacing
fix:
- calendar view ellipsis position
- help section option overflow fix
- module card overflow fix
- cycle and module sidebar collapse fix

fix: ui and bug fix

---

apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/control.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/estimates.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/features.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/index.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/integrations.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/labels.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/members.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/states.tsx
apps/app/pages/[workspaceSlug]/settings/billing.tsx
apps/app/pages/[workspaceSlug]/settings/import-export.tsx
apps/app/pages/[workspaceSlug]/settings/index.tsx
apps/app/pages/[workspaceSlug]/settings/integrations.tsx
apps/app/pages/[workspaceSlug]/settings/members.tsx
apps/app/types/projects.d.ts
apps/app/types/workspace.d.ts

chore:
- user cannot update their own role.
style:
- settings pages' padding.

chore: user cannot update their own role

---

apiserver/plane/bgtasks/analytic_plot_export.py
apiserver/plane/utils/analytics_plot.py

fix: analytics export and send month and year when dimension in date

fix: analytics export and send month and year when dimension in date

---

apiserver/plane/api/serializers/project.py
apiserver/plane/api/views/project.py

chore: project members, cycles and modules count

chore: project members, cycles and modules count

---

apiserver/plane/api/views/analytic.py

chore: return assignee avatars when x axis in assignee_email

chore: return assignee avatars when x axis in assignee_email

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/project.py
apiserver/plane/api/views/workspace.py

fix: workspace and project member update

fix: workspace and project member update

---

apiserver/plane/bgtasks/analytic_plot_export.py
apiserver/plane/utils/analytics_plot.py

chore: rename effort to estimate

chore: rename effort to estimate

---

apiserver/plane/api/views/analytic.py

chore: user first name and last name for default analytics

chore: user first name and last name for default analytics

---

apiserver/plane/utils/analytics_plot.py

chore: analytics data ordering

chore: analytics data ordering

---

apiserver/plane/api/views/analytic.py

chore: analytics assignee email for default analytics

chore: analytics assignee email for default analytics

---

apiserver/plane/api/views/analytic.py

fix: issue assignee multiple values

fix: issue assignee multiple values

---

apps/app/components/analytics/custom-analytics/sidebar.tsx
apps/app/components/analytics/project-modal.tsx
apps/app/components/analytics/scope-and-demand/leaderboard.tsx
apps/app/components/analytics/scope-and-demand/scope.tsx
apps/app/components/analytics/scope-and-demand/year-wise-issues.tsx
apps/app/components/core/issues-view.tsx
apps/app/components/issues/attachment-upload.tsx
apps/app/components/issues/sidebar.tsx

fix:
- issue trash box positioning and styling.
style:
- labels dropdown theming.
chore:
- analytics sidebar and header content and layout.
- empty state for scope and demand analytics.

 chore: update analytics sidebar and header content, fix: trash box positioning

---

apps/app/components/core/calendar-view/calendar-header.tsx
apps/app/components/core/calendar-view/calendar.tsx
apps/app/components/project/settings-header.tsx
apps/app/components/workspace/settings-header.tsx
apps/app/layouts/settings-navbar.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/modules/index.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/pages/index.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/control.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/estimates.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/features.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/index.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/integrations.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/labels.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/members.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/states.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/views/index.tsx
apps/app/pages/[workspaceSlug]/settings/billing.tsx
apps/app/pages/[workspaceSlug]/settings/import-export.tsx
apps/app/pages/[workspaceSlug]/settings/index.tsx
apps/app/pages/[workspaceSlug]/settings/integrations.tsx
apps/app/pages/[workspaceSlug]/settings/members.tsx

fix:
- consistent layout padding.
- settings tabs size.
- page headings' font size.

fix: layout padding, tabs size and page headings font size

---

apiserver/plane/api/views/analytic.py
apiserver/plane/utils/analytics_plot.py

fix: default analytic estimate points and sorting for custom analytics

fix: default analytic estimate points and sorting for custom analytics

---

apiserver/plane/bgtasks/analytic_plot_export.py

fix: analytics segmented export

fix: analytics segmented export

---

apps/app/components/analytics/custom-analytics/graph/index.tsx
apps/app/components/analytics/select/project.tsx
apps/app/components/ui/custom-search-select.tsx
apps/app/components/ui/custom-select.tsx
apps/app/helpers/analytics.helper.ts
apps/app/helpers/string.helper.ts

fix:
- analytics colors when segmented by cycle, module, dates, and assignees.

fix: analytics colors when segmented by cycle, module, dates, and assignees

---

apiserver/back_migration.py
apiserver/plane/db/models/issue.py

chore: start date for issues

---

apps/app/components/pages/create-update-block-inline.tsx

fix: 
- pages 'I'm feeling lucky' not working

fix: pages 'I'm feeling lucky' not working

---

apps/app/components/core/board-view/single-issue.tsx
apps/app/components/core/calendar-view/single-issue.tsx
apps/app/components/core/list-view/single-issue.tsx
apps/app/components/cycles/cycles-view.tsx
apps/app/components/issues/my-issues-list-item.tsx
apps/app/components/issues/view-select/assignee.tsx
apps/app/styles/react-datepicker.css

style: 
- assignee, sub-issue and due date display properties styling
- active cycle view state indication added

style: ui improvement

---

apps/app/components/issues/modal.tsx

fix: 
- module and cycle create issue in calendar view mutation fix

fix: module and cycle create issue in calendar view mutation fix

---

apps/app/components/analytics/custom-analytics/sidebar.tsx
apps/app/components/emoji-icon-picker/index.tsx
apps/app/components/emoji-icon-picker/types.d.ts
apps/app/components/project/create-project-modal.tsx
apps/app/components/project/single-project-card.tsx
apps/app/components/project/single-sidebar-project.tsx
apps/app/helpers/analytics.helper.ts
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/control.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/index.tsx
apps/app/types/projects.d.ts

fix:
- icon picker not working.

fix: icon picker not working

---

apiserver/plane/db/models/project.py

chore: project emoji and icons

chore: project emoji and icons

---

apps/app/components/cycles/completed-cycles.tsx
apps/app/components/cycles/cycles-view.tsx

feat: 
- cycle gantt view option added

feat: cycle gantt view option added

---

apps/app/components/issues/form.tsx

fix: 
- create issue state not clearing on 'create more'

fix: create issue state not clearing on create more

---

apps/app/components/core/board-view/single-issue.tsx

feat: 
- kanban board issue menu context

feat: kanban board issue menu context

---

apps/app/components/labels/create-label-modal.tsx
apps/app/components/labels/create-update-label-inline.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx

fix: 
- inconsistency for create label, select label getting closed on select

fix: inconsistency for create label, select label getting closed on select

---

apps/app/components/pages/create-update-block-inline.tsx

fix: 
- ai response not coming for page

fix: ai response not coming for page

---

apps/app/components/core/board-view/single-board.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx

style: 
- added theme in the color picker

style: added theme in color picker

---

apps/app/components/pages/create-update-block-inline.tsx

fix: 
- ai response not coming when using the 'AI' button

fix: ai response not coming when using 'AI' button

---

apps/app/hooks/use-issues-view.tsx

fix:
- show only filtered states when the state filter is selected.

fix: show only filtered states when the state filter is selected

---

apps/app/components/cycles/active-cycle-details.tsx
apps/app/components/cycles/active-cycle-stats.tsx

style: 
- active cycle stats tab sticky

style: active cycle stats tab sticky

---

apiserver/plane/bgtasks/analytic_plot_export.py

chore: assignee names in analytics export

chore: assignee names in analytics export

---

apps/app/components/analytics/custom-analytics/sidebar.tsx
apps/app/components/core/board-view/single-board.tsx
apps/app/components/integration/github/import-data.tsx
apps/app/components/integration/github/single-user-select.tsx
apps/app/components/integration/jira/import-users.tsx
apps/app/components/issues/select/assignee.tsx
apps/app/components/issues/sidebar-select/assignee.tsx
apps/app/components/issues/view-select/assignee.tsx
apps/app/components/modules/select/lead.tsx
apps/app/components/modules/select/members.tsx
apps/app/components/modules/sidebar-select/select-lead.tsx
apps/app/components/modules/sidebar-select/select-members.tsx
apps/app/components/ui/custom-search-select.tsx
apps/app/helpers/string.helper.ts

fix:
- custom search select will now show a loading text until the options are loaded.
- Kanban board y-scroll.

fix: make custom search select handle undefined options

---

apps/app/components/cycles/completed-cycles.tsx
apps/app/components/cycles/cycles-view.tsx
apps/app/components/labels/create-label-modal.tsx

fix: 
- create label modal error message updated
- cycle view board view fix 
feat: 
- on gantt view set all cycle tab as default

fix: cycle view & create label modal

---

apiserver/templates/emails/exports/analytics.html

chore: analytic export mail

---

apps/app/hooks/use-my-issues-filter.tsx
apps/app/pages/[workspaceSlug]/me/my-issues.tsx
apps/app/services/workspace.service.ts
apps/app/types/workspace.d.ts

fix: 
- storing my issue view display properties

fix: storing my issue view display properties

---

apps/app/components/account/email-code-form.tsx

fix: 
- fix send code button behavior on enter key press

fix: send code

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/cycle.py

refactor: cycle views endpoint

refactor: cycle views endpoint

---

apiserver/plane/api/views/project.py
apiserver/plane/api/views/workspace.py

fix: project member delete when deleting user from workspace
This fixes  Issue #1063

fix: project member delete when deleting user from workspace

---

apps/app/helpers/array.helper.ts
apps/app/hooks/use-projects.tsx

fix: 
- project ordering messing up on the projects page

fix: project ordering messing up in projects page

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/page.py

refactor: page views endpoint

---

apiserver/plane/api/serializers/issue.py
apiserver/plane/api/views/issue.py

fix: issue ordering for priority and updated_by parameters

fix: issue ordering for priority and updated_by parameters

---

apps/app/components/pages/pages-list/all-pages-list.tsx
apps/app/components/pages/pages-list/favorite-pages-list.tsx
apps/app/components/pages/pages-list/my-pages-list.tsx
apps/app/components/pages/pages-list/other-pages-list.tsx
apps/app/services/pages.service.ts

chore: 
- pages endpoint updated

chore: pages endpoint updated

---

README.md

docs: update self hosting setup script

docs: update self hosting setup script

---

apps/app/constants/workspace.ts

A few of the phrases were worded in ways that took a bit longer to process. These changes should make onboarding more comfortable.

Update text during the onboarding process

---

docker-compose-hub.yml
docker-compose.yml

chore: email settings for docker setup

chore: email settings for docker setup

---

apiserver/plane/api/serializers/workspace.py
apiserver/plane/api/views/workspace.py

chore: total members in user workspace invites

chore: total members in user workspace invites

---

.env.example
apiserver/plane/api/views/asset.py
apiserver/plane/api/views/issue.py
apiserver/plane/db/models/asset.py
apiserver/plane/db/models/issue.py
apiserver/plane/settings/local.py
apiserver/plane/settings/production.py
apiserver/plane/settings/staging.py
docker-compose-hub.yml
docker-compose.yml
setup.sh

chore:
- Specify `DEFAULT_EMAIL` and `DEFAULT_PASSWORD` in environment for the default user.
- Update image uploads using minio.
- Custom file limits using environment variables.
- Update setup script to generate only alphanumeric characters for `SECRET_KEY`.

chore: improve docker setup

---

apps/app/components/issues/modal.tsx
apps/app/contexts/issue-view.context.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/modules/[moduleId].tsx

fix: 
- empty module mutation 
- issue view flicker fix

fix: empty module mutation and issue view flicker fix

---

apps/app/components/modules/form.tsx
apps/app/components/modules/modal.tsx

fix: 
- default status set for module form

fix: default status set for module form

---

apps/app/pages/_app.tsx

fix: theme provider fix

---

apiserver/plane/api/views/workspace.py

fix: workspace member role update
Fixes #1188

fix: workspace member role update

---

apiserver/plane/api/views/asset.py
apiserver/plane/api/views/issue.py
apiserver/plane/settings/production.py

chore: update docker uploads

---

apiserver/plane/api/views/search.py
apiserver/plane/utils/issue_search.py

fix: issue search for blocking and blocked_by condition

fix: issue search for blocking and blocked_by condition

---

apiserver/plane/settings/local.py
apiserver/plane/settings/production.py
apiserver/plane/settings/staging.py

fix: minio settings

---

.env.example
docker-compose-hub.yml
docker-compose.yml

feat: plane proxy setup

---

apiserver/plane/api/views/project.py

fix: project member role update

fix: project member role update

---

.env.example
docker-compose-hub.yml
docker-compose.yml

fix: email tls when selfhosting

fix: email tls when selfhosting

---

.env.example
apiserver/plane/settings/production.py

chore: move minio endpoint url to environment configuration

chore: move minio endpoint url to environment configuration

---

apiserver/plane/api/urls.py
apiserver/plane/bgtasks/forgot_password_task.py

chore: reset password url

---

apiserver/plane/api/serializers/workspace.py
apiserver/plane/api/views/workspace.py

chore: workspace invite created detail

chore: workspace invite created detail

---

.env.example
apiserver/plane/settings/production.py
apps/app/components/account/email-password-form.tsx
apps/app/components/account/email-reset-password-form.tsx
apps/app/components/account/index.ts
apps/app/components/workspace/create-workspace-form.tsx
apps/app/pages/reset-password.tsx
apps/app/services/user.service.ts

feat:
- reset password page for self-hosted added.

feat: reset password page for self-hosted added

---

apps/app/.eslintrc.js
apps/app/components/analytics/scope-and-demand/leaderboard.tsx
apps/app/components/core/feeds.tsx
apps/app/components/core/image-picker-popover.tsx
apps/app/components/cycles/active-cycle-details.tsx
apps/app/components/cycles/active-cycle-stats.tsx
apps/app/components/cycles/sidebar.tsx
apps/app/components/cycles/single-cycle-card.tsx
apps/app/components/cycles/single-cycle-list.tsx
apps/app/components/integration/github/single-user-select.tsx
apps/app/components/issues/activity.tsx
apps/app/components/issues/comment/comment-card.tsx
apps/app/components/onboarding/workspace.tsx
apps/app/components/project/create-project-modal.tsx
apps/app/components/project/single-project-card.tsx
apps/app/components/search-listbox/index.tsx
apps/app/components/ui/avatar.tsx
apps/app/components/workspace/sidebar-dropdown.tsx
apps/app/components/workspace/single-invitation.tsx
apps/app/pages/[workspaceSlug]/me/profile/index.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/control.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/index.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/members.tsx
apps/app/pages/[workspaceSlug]/settings/index.tsx
apps/app/pages/[workspaceSlug]/settings/members.tsx

chore:
- replace nextjs Image element with HTML image tag.

chore: replace nextjs Image element

---

apiserver/plane/api/views/asset.py

fix: file asset uploads in workspace

fix: file asset uploads in workspace

---

apps/app/pages/onboarding.tsx

fix: last workspace id

---

apps/app/components/account/email-code-form.tsx
apps/app/components/issues/view-select/assignee.tsx
apps/app/pages/onboarding.tsx

fix: 
- assignee dropdown, sign in button, and onboarding flicker fix

fix: assignee dropdown, sign in button, and onboarding flicker fix

---

apps/app/components/cycles/active-cycle-details.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx
apps/app/services/cycles.service.ts

refactor:
- fetch only high priority issues for the active cycle.

refactor: fetch only high priority issues for the active cycle

---

apps/app/pages/[workspaceSlug]/me/profile/index.tsx
apps/app/pages/[workspaceSlug]/settings/index.tsx

fix:
- user profile data mutation.

fix: user profile data mutation

---

apiserver/plane/api/views/project.py
apiserver/plane/api/views/workspace.py

fix: workspace and project member user deletion
Fixes #1240

fix: workspace and project member user deletion

---

apiserver/plane/bgtasks/workspace_invitation_task.py

chore: update workspace invitation email redirection url

chore: update workspace invitation email redirection url

---

apps/app/components/core/image-upload-modal.tsx
apps/app/pages/[workspaceSlug]/me/profile/index.tsx
apps/app/pages/[workspaceSlug]/settings/index.tsx
apps/app/services/file.service.ts

chore:
- update remove file function logic.
fix:
- workspace file delete endpoint.

chore: update remove file function logic

---

apps/app/components/core/image-upload-modal.tsx
apps/app/pages/[workspaceSlug]/me/profile/index.tsx
apps/app/pages/[workspaceSlug]/settings/index.tsx
apps/app/services/file.service.ts

* chore: update remove file function logic
* fix: workspace file delete endpoint

promote: develop to stage-relaease

---

.env.example
apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/authentication.py
apiserver/plane/api/views/workspace.py
apiserver/plane/settings/local.py
apiserver/plane/settings/production.py
apiserver/plane/settings/staging.py
docker-compose.yml

chore: disable signup in self hosted environments

chore: enable/disable signup in self hosted environments

---

.env.example
apiserver/plane/settings/common.py
docker-compose.yml

fix: email ssl setting for docker environment

fix: email ssl setting for docker environment

---

apiserver/plane/api/serializers/cycle.py
apiserver/plane/api/views/cycle.py
apiserver/plane/utils/analytics_plot.py

chore: add labels data in cycles

chore: add labels data in cycles

---

apiserver/plane/api/views/workspace.py

fix: member invite

---

apiserver/plane/api/serializers/workspace.py
apiserver/plane/api/views/workspace.py

chore: workspace issue count

---

apiserver/plane/api/serializers/issue.py

chore: link and attachment count for cycles and modules

chore: link and attachment count for cycles and modules

---

apps/app/components/project/send-project-invitation-modal.tsx
apps/app/components/workspace/send-workspace-invitation-modal.tsx
apps/app/contexts/workspace-member.context.tsx
apps/app/layouts/auth-layout/workspace-authorization-wrapper.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/members.tsx
apps/app/pages/[workspaceSlug]/settings/members.tsx

fix:
- lower role user cannot invite higher role user.

fix: lower role user cannot invite higher role user

---

apiserver/plane/api/views/workspace.py
apps/app/components/project/send-project-invitation-modal.tsx
apps/app/components/workspace/send-workspace-invitation-modal.tsx
apps/app/contexts/workspace-member.context.tsx
apps/app/layouts/auth-layout/workspace-authorization-wrapper.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/members.tsx
apps/app/pages/[workspaceSlug]/settings/members.tsx

fix: workspace member invite to avoid lower permission user to invite higher permission member

fix: workspace member invite to avoid lower permission user to invite higher permission member

---

apiserver/plane/api/views/workspace.py
apps/app/components/project/send-project-invitation-modal.tsx
apps/app/components/workspace/send-workspace-invitation-modal.tsx
apps/app/contexts/workspace-member.context.tsx
apps/app/layouts/auth-layout/workspace-authorization-wrapper.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/members.tsx
apps/app/pages/[workspaceSlug]/settings/members.tsx

promote: staging to master

---

apps/app/components/issues/index.ts
apps/app/components/issues/main-content.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx

fix:
- issue details page title and description fields authorization.

fix: issue details page auth

---

apiserver/plane/api/views/importer.py

fix: importer delete when imported_data is None

fix: importer delete when imported_data is None

---

apiserver/plane/api/views/cycle.py

chore: add assignee avatar in cycle list and retrieve endpoint

chore: add assignee avatar in cycle list and retrieve endpoint

---

apiserver/plane/api/serializers/__init__.py
apiserver/plane/api/serializers/issue.py
apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/issue.py
apiserver/plane/db/models/__init__.py
apiserver/plane/db/models/issue.py

remove: time line issues

---

apiserver/plane/api/views/inbox.py

fix: inbox issue activity

---

apiserver/plane/api/views/issue.py
apiserver/plane/utils/issue_filters.py

chore: toggle sub issue view and sub issue count in sub issues

chore: toggle sub issue view and sub issue count in sub issues

---

apiserver/plane/api/views/module.py
apiserver/plane/utils/analytics_plot.py

chore: add assignee, label and burndown plot in module details

chore: add assignee, label and burndown plot in module details

---

apiserver/plane/api/views/search.py

chore: update issue search for cycle and modules

chore: update issue search for cycle and modules

---

apps/app/components/inbox/delete-issue-modal.tsx
apps/app/components/inbox/inbox-action-headers.tsx
apps/app/components/inbox/inbox-issue-card.tsx
apps/app/components/inbox/inbox-main-content.tsx
apps/app/components/inbox/select-duplicate.tsx
apps/app/components/issues/sidebar.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/inbox/[inboxId].tsx
apps/app/styles/react-datepicker.css

fix:
- mutation after inbox status change.
- inbox issue activity mutation.
chore:
- delete inbox issue modal's content update.
- disable older dates for snoozing.
- extend snooze date option.

fix: inbox mutation fixes

---

apps/app/components/inbox/filters-dropdown.tsx
apps/app/components/inbox/filters-list.tsx
apps/app/components/inbox/inbox-action-headers.tsx
apps/app/components/inbox/index.ts
apps/app/components/inbox/issues-list-sidebar.tsx
apps/app/constants/inbox.ts
apps/app/contexts/inbox-view-context.tsx
apps/app/contexts/issue-view.context.tsx
apps/app/hooks/use-inbox-view.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/inbox/[inboxId].tsx

chore:
- show the list of applied inbox filters.
fix:
- inbox, issue filters flicker.

chore: show inbox applied filters list, fix: filters flicker

---

apps/app/components/inbox/decline-issue-modal.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/inbox/[inboxId].tsx

chore:
- decline issue mutation.

chore: decline issue mutation

---

apps/app/components/inbox/filters-list.tsx

fix:
- clear inbox status filter button.

fix: clear inbox status filter button

---

apiserver/plane/api/views/issue.py

chore: link and attachment count in sub issues

chore: link and attachment count in sub issues

---

apiserver/plane/api/views/inbox.py

chore: inbox issue permissions

chore: inbox issue permissions

---

apiserver/plane/bgtasks/analytic_plot_export.py
apiserver/plane/bgtasks/email_verification_task.py
apiserver/plane/bgtasks/forgot_password_task.py
apiserver/plane/bgtasks/importer_task.py
apiserver/plane/bgtasks/issue_activites_task.py
apiserver/plane/bgtasks/magic_link_code_task.py
apiserver/plane/bgtasks/project_invitation_task.py
apiserver/plane/bgtasks/user_welcome_task.py
apiserver/plane/bgtasks/workspace_invitation_task.py

chore: enable print logs for background workers when in DEBUG mode

chore: enable print logs for background workers when in DEBUG mode

---

apiserver/plane/api/views/people.py

chore: updated user onboarded response

chore: updated user onboarded response

---

.env.example
docker-compose-hub.yml
docker-compose.yml

chore: set sentry dsn from environment variable

chore: set sentry dsn from environment variable

---

apps/app/components/core/board-view/all-boards.tsx
apps/app/components/core/board-view/board-header.tsx
apps/app/components/core/board-view/single-board.tsx
apps/app/components/core/existing-issues-list-modal.tsx
apps/app/components/core/issues-view.tsx
apps/app/components/issues/select/label.tsx

fix:
- create new issue when grouped by `label`.
chore:
- hide the add issue button when grouped by `created by`.

fix: create new issue when grouped by label

---

apps/app/pages/[workspaceSlug]/me/profile/activity.tsx
apps/app/pages/[workspaceSlug]/me/profile/index.tsx
apps/app/pages/[workspaceSlug]/me/profile/preferences.tsx

style:
- profile settings, activity, and preference page padding made consistent.

style: profile settings, activity, and preference page padding made consistent

---

apps/app/components/core/sidebar/progress-chart.tsx
apps/app/components/cycles/active-cycle-details.tsx
apps/app/components/cycles/active-cycle-stats.tsx
apps/app/components/cycles/single-cycle-list.tsx
apps/app/helpers/date-time.helper.ts

fix:
- show empty states for cycle stats.
- x-axis values for burndown charts in cycles and modules.

fix: cycle stats empty state

---

apps/app/components/core/board-view/single-issue.tsx

fix:
- issue title breaking in the issue card on the Kanban board.

fix: issue title breaking in the issue card

---

apps/app/components/core/issues-view.tsx
apps/app/components/issues/form.tsx
apps/app/components/issues/modal.tsx

fix:
- description not loading while editing an issue.

fix: description not loading while editing an issue

---

apps/app/components/core/bulk-delete-issues-modal.tsx

fix:
- bulk delete issues mutation.

fix: bulk delete issues mutation

---

apps/app/components/workspace/activity-graph.tsx
apps/app/components/workspace/issues-stats.tsx

chore:
- brief information for the activity graph.

chore: brief information for the activity graph

---

apiserver/plane/api/views/inbox.py

refactor: inbox issues

---

apiserver/plane/api/views/analytic.py
apiserver/plane/api/views/importer.py
apiserver/plane/api/views/issue.py
apiserver/plane/api/views/state.py
apiserver/plane/db/models/issue.py

chore: triage state filtering

---

apiserver/plane/api/views/inbox.py

fix: inbox issue update

---

apiserver/plane/api/views/authentication.py

fix: auth error messages

---

apps/app/services/user.service.ts

fix: onboarding tracker

---

apps/app/components/issues/form.tsx
apps/app/components/pages/create-update-block-inline.tsx
apps/app/components/pages/single-page-block.tsx

fix:
- remove `project management context` from ai requests.

fix: update task for ai requests

---

apps/app/components/analytics/custom-analytics/sidebar.tsx
apps/app/components/analytics/project-modal.tsx
apps/app/components/analytics/scope-and-demand/leaderboard.tsx
apps/app/components/breadcrumbs/index.tsx
apps/app/components/core/board-view/single-issue.tsx
apps/app/components/core/sidebar/links-list.tsx
apps/app/components/cycles/active-cycle-details.tsx
apps/app/components/cycles/delete-cycle-modal.tsx
apps/app/components/cycles/single-cycle-card.tsx
apps/app/components/cycles/single-cycle-list.tsx
apps/app/components/estimates/delete-estimate-modal.tsx
apps/app/components/inbox/decline-issue-modal.tsx
apps/app/components/inbox/delete-issue-modal.tsx
apps/app/components/integration/delete-import-modal.tsx
apps/app/components/issues/delete-issue-modal.tsx
apps/app/components/issues/sub-issues-list.tsx
apps/app/components/modules/delete-module-modal.tsx
apps/app/components/modules/single-module-card.tsx
apps/app/components/pages/delete-page-modal.tsx
apps/app/components/pages/single-page-block.tsx
apps/app/components/project/delete-project-modal.tsx
apps/app/components/project/single-project-card.tsx
apps/app/components/ui/multi-level-dropdown.tsx
apps/app/components/views/delete-view-modal.tsx
apps/app/components/workspace/delete-workspace-modal.tsx

fix:
- words breaking abruptly.

fix: words breaking abruptly

---

apps/app/pages/index.tsx
apps/app/pages/reset-password.tsx
apps/app/pages/sign-up.tsx
apps/app/services/authentication.service.ts

chore:
- show error messages from requests.

chore: show error messages from requests

---

apps/app/components/command-palette/command-pallette.tsx
apps/app/components/inbox/accept-issue-modal.tsx
apps/app/components/inbox/inbox-action-headers.tsx
apps/app/components/inbox/inbox-main-content.tsx
apps/app/components/inbox/index.ts
apps/app/components/inbox/issues-list-sidebar.tsx
apps/app/components/issues/sidebar-select/state.tsx
apps/app/components/ui/multi-level-dropdown.tsx
apps/app/styles/command-pallette.css

chore:
- accept issue confirmation modal.
- add the `Open Inbox` option to the command menu.
fix:
- inbox status colors not loading.

chore: accept issue confirmation modal

---

apps/app/components/core/spreadsheet-view/single-issue.tsx
apps/app/components/core/spreadsheet-view/spreadsheet-columns.tsx
apps/app/components/core/spreadsheet-view/spreadsheet-view.tsx
apps/app/constants/spreadsheet.ts

feat: 
- spreadsheet view ui improvements
- quick menu added
- sorting indicator added
style: 
- spreadsheet column
fix: 
- z-index issue fix

feat: spreadsheet view improvements

---

apiserver/plane/api/views/issue.py

fix: state and priority ordering

fix: state and priority ordering

---

apps/app/components/core/spreadsheet-view/single-issue.tsx
apps/app/components/core/spreadsheet-view/spreadsheet-issues.tsx
apps/app/components/issues/delete-issue-modal.tsx
apps/app/components/issues/modal.tsx
apps/app/constants/spreadsheet.ts

fix: 
- due date sorting fix
- update and delete sub issue mutation fix

fix: spreadsheet view bug fixes

---

apps/app/components/issues/delete-issue-modal.tsx
apps/app/constants/spreadsheet.ts

fix: 
- sub issue accordion mutation fix
chore: 
- assignees sort order params updated

fix: spreadsheet bug fixes

---

apiserver/plane/api/views/issue.py

fix: issue duplication when ordering by labels and assignee

fix: issue duplication when ordering by labels and assignee

---

apps/app/layouts/app-layout/app-header.tsx
apps/app/layouts/auth-layout/project-authorization-wrapper.tsx
apps/app/layouts/auth-layout/workspace-authorization-wrapper.tsx

fix:
- show the sidebar toggle button on the workspace dashboard.

fix: sidebar toggle button on the workspace dashboard

---

apps/app/components/core/spreadsheet-view/single-issue.tsx
apps/app/components/core/spreadsheet-view/spreadsheet-view.tsx
apps/app/components/ui/multi-level-dropdown.tsx

fix:
- multi level dropdown fix
- spreadsheet view sub-issue label mutation
style:
- spreadsheet view add issue button

fix: bug fixes

---

apps/app/components/issues/form.tsx
apps/app/components/issues/modal.tsx

fix:
- create issue modal not working on the workspace level.
chore:
- preset the current user as the assignee when creating an issue from my issues page.

fix: create issue modal not working on the workspace level

---

apps/app/components/analytics/scope-and-demand/year-wise-issues.tsx
apps/app/components/core/sidebar/progress-chart.tsx
apps/app/components/workspace/completed-issues-graph.tsx

chore:
- added tooltip to all the line graphs.

chore: add tooltip to line graphs

---

apps/app/components/core/issues-view.tsx
apps/app/components/core/spreadsheet-view/spreadsheet-view.tsx
apps/app/components/ui/custom-menu.tsx

feat: 
- add existing issue option added in spreadsheet view

feat: add existing issue option added in spreadsheet view

---

apps/app/components/core/spreadsheet-view/single-issue.tsx
apps/app/components/core/spreadsheet-view/spreadsheet-issues.tsx
apps/app/components/core/spreadsheet-view/spreadsheet-view.tsx
apps/app/layouts/app-layout/app-header.tsx
apps/app/styles/globals.css

fix: 
- resolve z-index issue with quick action menu and disable it for completed cycles

fix:  quick action menu and z-index fix 

---

apps/app/components/core/filters-list.tsx
apps/app/components/inbox/filters-dropdown.tsx

fix:
- show the proper label when priority none filter is selected.

fix: priority none filter

---

apps/app/components/core/sidebar/progress-chart.tsx
apps/app/components/cycles/active-cycle-details.tsx

fix:
- progress chart x-axis values.
chore:
- loader for active cycle.

fix: progress chart x-axis values

---

apiserver/plane/api/views/importer.py
apiserver/plane/utils/integrations/github.py

fix: github importer

---

apiserver/plane/api/views/importer.py
apiserver/plane/utils/integrations/github.py

fix: github importer issue (#1414)

fix: github importer issue (#1414)

---

apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx

style: 
-issue detail page layout

style: issue detail page layout

---

apps/app/components/core/board-view/single-issue.tsx
apps/app/components/core/spreadsheet-view/single-issue.tsx
apps/app/components/core/spreadsheet-view/spreadsheet-issues.tsx
apps/app/components/core/spreadsheet-view/spreadsheet-view.tsx
apps/app/components/issues/view-select/assignee.tsx
apps/app/components/issues/view-select/due-date.tsx
apps/app/components/issues/view-select/estimate.tsx
apps/app/components/issues/view-select/label.tsx
apps/app/components/issues/view-select/priority.tsx
apps/app/components/issues/view-select/state.tsx

style: 
- adjust tooltip position and spacing in workspace id and title in spreadsheet

style: spreadsheet

---

apps/app/components/core/board-view/single-issue.tsx
apps/app/components/core/list-view/single-issue.tsx
apps/app/components/core/spreadsheet-view/single-issue.tsx
apps/app/components/workspace/issues-pie-chart.tsx

fix:
- dashboard pie chart overlapping issue.
- sidebar burndown chart mutation.

fix: charts design and mutation

---

CONTRIBUTING.md
README.md

docs: update readme.md for self hosting setup and remove pnpm from contribution guidelines

docs: update readme.md for self hosting setup and remove pnpm from contribution guidelines

---

apiserver/plane/api/serializers/project.py

fix: project member list endpoint n+1

fix: project member list endpoint n+1

---

apiserver/plane/utils/issue_filters.py

chore: due date filter

---

apps/app/components/core/feeds.tsx
apps/app/components/cycles/sidebar.tsx
apps/app/components/inbox/inbox-issue-card.tsx
apps/app/components/inbox/inbox-main-content.tsx
apps/app/components/issues/activity.tsx
apps/app/components/issues/select/date.tsx
apps/app/components/issues/view-select/due-date.tsx
apps/app/components/modules/sidebar.tsx
apps/app/components/project/single-project-card.tsx
apps/app/components/ui/date.tsx
apps/app/components/ui/datepicker.tsx
apps/app/components/views/single-view-item.tsx
apps/app/components/workspace/activity-graph.tsx
apps/app/helpers/date-time.helper.ts

refactor: 
- standardized date format throughout the platform

refactor: standardized date format throughout the platform

---

apps/app/types/projects.d.ts

chore:
- update project members' type in accordance with the new response.

chore: update project members' type in accordance with the new response

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/workspace.py

fix: workspace invitation delete for self hosted

fix: workspace invitation delete for self hosted

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/workspace.py

promote: stage-release to master

promote: stage-release to master

---

apiserver/plane/api/views/project.py

chore: project members endpoint to support bulk operations

chore: project members endpoint to support bulk operations

---

apiserver/plane/settings/production.py
apiserver/plane/settings/staging.py

fix: static and media files storages

fix: static and media files storages

---

apps/app/components/project/send-project-invitation-modal.tsx
apps/app/services/project.service.ts
apps/app/types/projects.d.ts

feat: 
- bulk invite for project

feat: bulk invite for project

---

docker-compose-hub.yml

chore:  environment variables for worker and api

chore:  environment variables for worker and api

---

apps/app/components/analytics/custom-analytics/sidebar.tsx
apps/app/components/core/board-view/single-issue.tsx
apps/app/components/core/filters/issues-view-filter.tsx
apps/app/components/cycles/single-cycle-card.tsx
apps/app/components/cycles/single-cycle-list.tsx
apps/app/components/estimates/single-estimate.tsx
apps/app/components/issues/view-select/due-date.tsx
apps/app/components/issues/view-select/label.tsx
apps/app/components/issues/view-select/state.tsx
apps/app/components/modules/single-module-card.tsx
apps/app/components/project/create-project-modal.tsx
apps/app/components/project/single-sidebar-project.tsx
apps/app/components/ui/custom-menu.tsx
apps/app/components/ui/custom-search-select.tsx
apps/app/components/ui/custom-select.tsx
apps/app/components/ui/datepicker.tsx
apps/app/components/ui/empty-space.tsx
apps/app/components/ui/multi-level-dropdown.tsx
apps/app/components/workspace/sidebar-dropdown.tsx
apps/app/constants/issue.ts
apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/index.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/modules/[moduleId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/estimates.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/features.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/integrations.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/states.tsx
apps/app/styles/globals.css
apps/app/tailwind.config.js

fix:
- updated text colors.
- updated new primary background color.

fix: updated text and background colors

---

apps/app/components/issues/modal.tsx

fix:
- add the missing argument.

fix: add the missing argument

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/people.py
apiserver/plane/db/models/user.py

feat: flag for onboarding tour completion

feat: flag for onboarding tour completion

---

apps/app/components/inbox/filters-dropdown.tsx
apps/app/components/inbox/inbox-issue-card.tsx
apps/app/components/issues/modal.tsx
apps/app/components/workspace/help-section.tsx

style: inbox

---

apiserver/requirements/base.txt

chore: upgrade psycopg to 3

---

apiserver/plane/api/views/authentication.py

fix: magic code casing

---

apps/app/components/issues/modal.tsx
apps/app/components/issues/select/project.tsx
apps/app/components/project/create-project-modal.tsx
apps/app/components/project/delete-project-modal.tsx
apps/app/components/project/sidebar-list.tsx
apps/app/components/project/single-project-card.tsx
apps/app/components/project/single-sidebar-project.tsx
apps/app/constants/fetch-keys.ts
apps/app/hooks/use-projects.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/control.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/features.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/index.tsx
apps/app/services/project.service.ts
apps/app/types/projects.d.ts

chore:
- update favorite projects endpoint.

chore: update favorite projects endpoint

---

apiserver/plane/api/serializers/issue.py
apiserver/plane/api/serializers/module.py
apiserver/plane/api/serializers/project.py

refactor: serializers to avoid getting child items

refactor: serializers to avoid getting child items

---

apps/app/components/core/board-view/single-board.tsx
apps/app/components/core/filters/issues-view-filter.tsx
apps/app/components/issues/attachments.tsx
apps/app/components/pages/single-page-detailed-item.tsx
apps/app/components/pages/single-page-list-item.tsx
apps/app/components/project/delete-project-modal.tsx
apps/app/components/project/sidebar-list.tsx
apps/app/components/project/single-project-card.tsx
apps/app/components/project/single-sidebar-project.tsx
apps/app/components/ui/tooltip.tsx
apps/app/components/workspace/activity-graph.tsx
apps/app/layouts/app-layout/app-sidebar.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/automations.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/control.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/features.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/index.tsx
apps/app/styles/globals.css

chore:
- updated the tooltip design.
fix:
- due date popup overflow issue on the Kanban board.
refactor:
- favorite projects fetch function,

refactor: favorite projects fetch function, chore: update tooltip design

---

apiserver/plane/api/views/issue.py

chore: update bridge id to cycle and module id

chore: update bridge id to cycle and module id

---

apps/app/components/issues/form.tsx
apps/app/components/labels/create-label-modal.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx

fix: 
- selecting label once create using modal

fix: selecting label once create using modal

---

apps/app/components/workspace/create-workspace-form.tsx

fix: 
- show alert on-change rather than on-submit if in-valid characters are added to the input.

fix: create workspace validation 

---

apps/app/components/account/email-code-form.tsx
apps/app/components/account/email-password-form.tsx
apps/app/components/account/email-reset-password-form.tsx
apps/app/components/account/github-login-button.tsx
apps/app/components/account/google-login.tsx
apps/app/pages/reset-password.tsx

fix:
- auth screens' button and input heights.

fix: auth screens' button and input heights

---

apps/app/components/core/issues-view.tsx

fix: 
- same empty state coming for all issue list-related UI

fix: same empty state coming for all issue list related UI

---

apps/app/components/core/issues-view.tsx
apps/app/styles/globals.css

chore:
- update high contrast theme colors.
fix:
- archived issues empty state.

chore: high contrast theming

---

apps/app/components/ui/product-updates-modal.tsx
apps/app/pages/[workspaceSlug]/index.tsx

chore: dashboard navbar

---

apps/app/components/analytics/scope-and-demand/year-wise-issues.tsx

fix:
- scope and demand line graph y-axis values.

fix: scope and demand line graph y axis values

---

apps/app/components/core/theme/theme-switch.tsx

fix:
- update border colors on theme switch.

fix: update border colors on theme switch

---

apiserver/plane/api/views/notification.py
apiserver/plane/bgtasks/issue_activites_task.py

fix: issue created notification

fix: issue created notification

---

apiserver/bin/takeoff
apiserver/plane/settings/local.py
apiserver/plane/settings/production.py
apiserver/plane/settings/staging.py
apiserver/requirements/base.txt
apiserver/requirements/production.txt

fix: psycopg import errors

---

apiserver/plane/bgtasks/issue_automation_task.py

fix: issue automation

---

apiserver/Dockerfile.api
apiserver/bin/beat
docker-compose-hub.yml
docker-compose.yml

feat: beat worker for configuration

feat: beat worker for configuration

---

apps/app/components/account/email-code-form.tsx
apps/app/components/notifications/notification-card.tsx
apps/app/components/onboarding/join-workspaces.tsx
apps/app/constants/graph.ts
apps/app/pages/index.tsx
apps/app/pages/invitations.tsx

fix:
- onboarding invitations overflow.
- auth page content width.
- invitations page empty state flicker.
- user avatar size in the notification card.
- graph grid color.

fix: onboarding invitations overflow

---

apps/app/components/notifications/notification-card.tsx
apps/app/components/notifications/notification-popover.tsx

style: 
- tooltip on the notification header and card action buttons.

style: tooltip on notification header actions

---

apiserver/plane/db/migrations/0037_issue_archived_at_project_archive_in_and_more.py

fix: user migrations for back population

fix: user migrations for back population

---

apiserver/plane/api/views/notification.py

chore: notification ordering

---

apiserver/plane/bgtasks/issue_activites_task.py

fix: uuid error when cycle and module updates

fix: uuid error when cycle and module updates

---

apps/app/components/notifications/notification-popover.tsx

fix:
- snooze dropdown overflow.

fix: snooze dropdown overflow

---

apiserver/plane/api/views/notification.py

fix: issues count to remove archived issues

fix: issues count to remove archived issues

---

apiserver/plane/settings/production.py
apiserver/requirements/base.txt

dev: add server monitoring configuration

dev: add server monitoring configuration

---

apps/app/components/issues/activity.tsx
apps/app/components/issues/comment/comment-card.tsx
apps/app/types/issues.d.ts
apps/app/types/users.d.ts

refactor:
- issue activity message logic.

refactor: issue activity message logic

---

apps/app/pages/[workspaceSlug]/me/profile/index.tsx

chore:
- show proper error messages on the profile form submit.

chore: show proper error messages on the profile form submit

---

replace-env-vars.sh

chore: fix typo in replace-env-vars.sh

---

apiserver/plane/api/views/project.py

chore: add project lead as project member

chore: add project lead as project member

---

apiserver/plane/db/models/project.py

chore: project identifiers length

chore: project identifiers length

---

apiserver/plane/api/views/project.py

chore: return total members, cycle and modules

chore: return total members, cycle and modules

---

apps/app/components/issues/activity.tsx

fix:
- remove issue link activity.

fix: remove issue link activity

---

apiserver/plane/api/views/notification.py

fix: notification select related fields

fix: notification select related fields

---

apps/app/components/issues/form.tsx

fix:
- create issue modal resetting on project change.

fix: create issue modal resetting

---

apiserver/plane/api/views/search.py

chore: global search endpoint for workspace

chore: global search endpoint for workspace

---

apiserver/plane/api/views/issue.py

chore: ability to comment for guests and viewers

chore: ability to comment for guests and viewers

---

apiserver/plane/bgtasks/issue_activites_task.py

chore: project issue link activity

chore: project issue link activity

---

README.md

Updated all the images in readme from s3.

Updated all README.md images 

---

apiserver/plane/db/models/issue.py

fix: make title as optional for issue links

fix: make title as optional for issue links

---

apiserver/plane/db/models/project.py

feat: project preferences

---

apiserver/plane/bgtasks/issue_activites_task.py

fix: handle model save error in issue activity

fix: handle model save error in issue activity

---

apiserver/plane/api/views/authentication.py

fix: email magic sign in integrity error

fix: email magic sign in integrity error

---

apiserver/plane/api/serializers/page.py

fix: pages n plus 1

---

apps/app/components/core/image-picker-popover.tsx

feat: 
- upload cover image for project

feat: upload cover image for project

---

apps/app/contexts/issue-view.context.tsx

fix: 
- show-sub issue filter is true now by default

fix: show-sub issue filter is true now by default

---

apps/app/components/automation/auto-close-automation.tsx
apps/app/components/command-palette/issue/change-issue-state.tsx
apps/app/components/core/views/all-views.tsx
apps/app/components/core/views/issues-view.tsx
apps/app/components/issues/select/state.tsx
apps/app/components/issues/sidebar-select/state.tsx
apps/app/components/issues/view-select/state.tsx
apps/app/components/views/form.tsx
apps/app/components/views/select-filters.tsx
apps/app/helpers/state.helper.ts
apps/app/hooks/use-issues-view.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/states.tsx

fix:
- fetch states only when the dropdown is opened.

fix: fetch states only when the dropdown is opened

---

apps/app/components/core/image-picker-popover.tsx

fix: invalid isOpen flag

---

apps/app/components/notifications/notification-popover.tsx

style: 
- spacing bottom on load more button

style: spacing bottom on load more button

---

apps/app/components/core/modals/gpt-assistant-modal.tsx
apps/app/components/issues/form.tsx

fix: 
- displaying API error for AI response

fix: displaying API error for AI response

---

apps/app/components/core/filters/filters-list.tsx
apps/app/components/core/views/issues-view.tsx
apps/app/components/issues/my-issues/my-issues-view.tsx
apps/app/contexts/issue-view.context.tsx
apps/app/hooks/my-issues/use-my-issues-filter.tsx
apps/app/types/issues.d.ts
apps/app/types/projects.d.ts
apps/app/types/state.d.ts
apps/app/types/workspace.d.ts

refactor:
- filters list component.

refactor: filters list component

---

apiserver/plane/utils/issue_filters.py

fix: issue filters

---

apps/app/components/views/form.tsx

fix: create view form

---

apiserver/plane/utils/issue_filters.py

dev: revert issue filters query parameters

dev: revert issue filters query parameters

---

apiserver/plane/api/views/workspace.py

fix: workspace member only admin delete
Fixes Issue #1693

fix: workspace member only admin delete

---

apps/app/components/notifications/notification-popover.tsx
apps/app/hooks/use-user-notifications.tsx

refactor: 
- fetching notification only when the popover is open

refactor: fetching notification only when popover is open

---

apps/app/components/core/reaction-selector.tsx
apps/app/components/issues/comment/comment-reaction.tsx
apps/app/components/issues/issue-reaction.tsx

style: 
- reactions ui improvement

style: reactions ui improvement

---

apiserver/plane/api/views/project.py

chore: project preferences

---

apiserver/plane/api/serializers/__init__.py
apiserver/plane/api/serializers/issue.py
apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/issue.py
apiserver/plane/db/models/__init__.py
apiserver/plane/db/models/issue.py

feat: issue and comments reaction

feat: issue and comments reaction

---

apps/app/components/core/filters/issues-view-filter.tsx
apps/app/components/issues/main-content.tsx

style: 
- sibling issues ui
- view dropdown ui

style: ui improvements

---

apps/app/components/core/image-picker-popover.tsx
apps/app/components/project/create-project-modal.tsx

fix: 
- popover close on image upload
- overflow

fix: project cover image upload

---

apps/app/components/workspace/create-workspace-form.tsx
apps/app/pages/[workspaceSlug]/settings/index.tsx

fix: 
- workspace name validation added

fix: workspace name validation added

---

apps/app/components/core/image-picker-popover.tsx
apps/app/components/core/modals/image-upload-modal.tsx
apps/app/components/rich-text-editor/index.tsx

fix: 
- image upload accepting non-image format

fix: image upload accepting non-image format

---

apps/app/components/workspace/send-workspace-invitation-modal.tsx

fix: 
- workspace member invitation mutate

fix: workspace member invitation mutate

---

apps/app/components/project/sidebar-list.tsx
apps/app/components/project/single-sidebar-project.tsx
apps/app/services/project.service.ts
apps/app/types/projects.d.ts

feat: 
- sidebar project ordering functionality added

feat: sidebar project ordering functionality added

---

apps/app/components/project/send-project-invitation-modal.tsx

refactor: 
- move mutate project invitations to the finally block.
chore: 
- success message after successfully adding a member to the project.

refactor: moved mutate to 'finally' block

---

apiserver/plane/api/views/workspace.py

feat: user cycle stats

---

apiserver/plane/api/permissions/__init__.py
apiserver/plane/api/permissions/workspace.py
apiserver/plane/api/views/workspace.py

chore: profile page permission

chore: profile page permission

---

apps/app/components/project/single-sidebar-project.tsx
apps/app/components/workspace/sidebar-dropdown.tsx
apps/app/hooks/use-profile-issues.tsx
apps/app/layouts/profile-layout.tsx
apps/app/styles/globals.css

fix:
- show project drag handle only when uncollapsed.
- profile page breadcrumbs.
- fetch user profile issues authorization.
chore:
- update new theme colors.

fix: show project drag handle only when uncollapsed

---

apiserver/plane/api/views/workspace.py

fix: my issues duplication

---

apps/app/constants/fetch-keys.ts
apps/app/hooks/use-user-notifications.tsx

refactor: 
- changed per_page to 30

refactor: changed per_page to 30

---

apps/app/components/core/views/board-view/single-issue.tsx
apps/app/components/core/views/calendar-view/single-issue.tsx
apps/app/components/core/views/list-view/single-issue.tsx
apps/app/components/core/views/spreadsheet-view/single-issue.tsx

fix:
- issue redirection from my issues and user profile.

fix: issue redirection from my issues and user profile

---

apps/app/components/project/sidebar-list.tsx

style: 
- sidebar project disclosure list open by default

style: sidebar project improvement

---

apiserver/plane/api/views/project.py
apiserver/plane/db/models/project.py

chore: project create to return sort order

chore: project create to return sort order

---

apiserver/plane/api/views/notification.py

chore: show created by empty for viewers and guests

chore: show created by empty for viewers and guests

---

apps/app/components/core/filters/issues-view-filter.tsx

style: view dropdown

---

apps/app/pages/[workspaceSlug]/settings/members.tsx

fix: 
- showing an alert on error while deleting workspace member or invited member
style: 
- showing 'Leave' for the current user

fix: showing alert on error while deleting workspace member or invited member

---

apiserver/plane/api/serializers/issue.py
apiserver/plane/api/views/issue.py
apiserver/plane/api/views/people.py
apiserver/plane/api/views/project.py
apiserver/plane/api/views/workspace.py

chore: issue and project details in activity

chore: issue and project details in activity

---

apps/app/styles/globals.css

style: 
- primary color variable added in global css file

style: global styling

---

apps/app/components/workspace/sidebar-dropdown.tsx

style: 
- profile dropdown updated

style: profile dropdown updated

---

apps/app/components/core/feeds.tsx

fix:
- profile activity workspace slug.

fix: profile activity workspace slug

---

apps/app/components/project/single-sidebar-project.tsx

style: 
- sidebar project list styling

style: sidebar project list styling

---

apiserver/plane/db/migrations/0040_projectmember_preferences_user_cover_image_and_more.py

fix: project identifier migration

fix: project identifier migration

---

apiserver/plane/db/migrations/0040_projectmember_preferences_user_cover_image_and_more.py

fix: project identifier length

fix: project identifier length

---

apiserver/plane/api/views/project.py

fix: project invite

---

apps/app/hooks/use-comment-reaction.tsx

fix: 
- comment reaction mutation

fix: comment reaction mutation

---

apiserver/plane/api/views/workspace.py

fix: user profiles n plus 1

---

apiserver/plane/api/views/importer.py

fix: bulk issue import

---

apps/app/components/issues/my-issues/my-issues-view.tsx
apps/app/constants/fetch-keys.ts
apps/app/contexts/issue-view.context.tsx
apps/app/contexts/profile-issues-context.tsx
apps/app/hooks/my-issues/use-my-issues-filter.tsx
apps/app/hooks/my-issues/use-my-issues.tsx
apps/app/hooks/use-profile-issues.tsx
apps/app/pages/[workspaceSlug]/me/my-issues.tsx
apps/app/types/issues.d.ts

chore:
- subscribed by me tab on my issues page.

chore: subscribed by me tab on my issues page

---

apps/app/components/ui/multi-level-dropdown.tsx

fixed: Label filter should show something if there is no label #1779

Fixed problem with empty label filter

---

apps/app/components/issues/modal.tsx

refactor: 
- removed escape key-down listener

refactor: removed escape keydown listener

---

apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/members.tsx
apps/app/pages/[workspaceSlug]/settings/members.tsx

style: 
- displaying email on members page depending on user role

style: displaying email in members page depending on user role

---

apps/app/components/integration/jira/import-users.tsx

fix: 
- import user using endpoint with email

fix: import user using endpoint with email

---

apps/app/components/command-palette/command-pallette.tsx

refactor: 
- both delete or backspace can be used to open modal

refactor: both delete or backspace can be used to open modal

---

apiserver/plane/api/views/issue.py
apiserver/plane/api/views/view.py

fix: issues n plus 1

---

apiserver/plane/db/models/issue.py

remove: auto start date configuration

remove: auto start date configuration

---

apiserver/plane/api/serializers/__init__.py
apiserver/plane/api/serializers/cycle.py
apiserver/plane/api/views/cycle.py
apiserver/plane/api/views/module.py
apiserver/plane/api/views/project.py

fix: project members endpoint email

fix: project members endpoint email

---

apiserver/plane/api/views/analytic.py

fix: user id for default analytics

fix: user id for default analytics

---

apiserver/plane/api/serializers/project.py
apiserver/plane/api/views/project.py

chore: project member role

---

apiserver/plane/api/views/project.py

fix: project states create

---

apiserver/plane/api/views/cycle.py
apiserver/plane/api/views/module.py

chore: 
- sort order for cycle and module list endpoints

chore: sort order for cycle and modules

---

apiserver/plane/utils/issue_filters.py

fix:
- issue date filtering (created_at, updated_at, start_date, target_date, completed_at)
- unified save for get and post

fix: issue date filtering
