lib/hoc/withAuthWrapper.tsx
lib/redirect.ts
pages/invitations.tsx
pages/signin.tsx
pages/workspace-member-invitation/[invitationId].tsx
pages/workspace/index.tsx

fix:
- workspace invitation page, showing all the workspaces if there's no invitation to the user
- user has the option to choose from existing workspaces instead of the "create workspace" button
- made auth wrapper working
- added wrapper in protected routes and removed from public pages

fix: workspace invitation page not showing workspaces

---

components/command-palette/shortcuts.tsx
components/project/issues/BoardView/SingleBoard.tsx
components/project/issues/ListView/index.tsx
components/project/issues/PreviewModal/index.tsx
layouts/Navbar/Sidebar.tsx
pages/me/my-issues.tsx
pages/projects/[projectId]/issues/index.tsx
pages/projects/[projectId]/settings.tsx
styles/globals.css
ui/CustomListbox/index.tsx
ui/Input/index.tsx
ui/SearchListbox/index.tsx
ui/Select/index.tsx
ui/TextArea/index.tsx

feat:
- Added a preview issue modal when we hover over an issue and press the spacebar.
style:
- Redesigned the global search list boxes.
- Changed the font to 'Inter'.
fix:
- Fixed the overflowing issues in the sidebar.

feat: preview modal, style: issues page

---

apps/app/components/project/confirm-project-deletion.tsx
apps/app/components/workspace/confirm-workspace-deletion.tsx
apps/app/constants/api-routes.ts
apps/app/constants/fetch-keys.ts
apps/app/lib/services/user.service.ts
apps/app/lib/services/workspace.service.ts
apps/app/pages/me/my-issues.tsx
apps/app/pages/me/profile.tsx
apps/app/pages/workspace/index.tsx
apps/app/pages/workspace/settings.tsx
apps/app/types/workspace.d.ts

feat: 
- confirm workspace deletion by typing workspace name and 'delete my workspace'
- showing toast alert on workspace & project deletion
- email can't be edited on the profile page
fix:
- 404 error for my issues, since the API endpoint was changed to be isolated to the workspace
refractor:
- fixed inconsistent imports 
- made services for fetching details related to the last active workspace
- made the confirm-workspace-delete model better by handling functions and props in a more reusable manner

feat: confirm workspace deletion 

---

apiserver/plane/api/serializers/issue.py

fix: return sequence id on issue flat serializer

fix: return sequence id on issue flat serializer

---

apiserver/plane/api/urls.py

fix: typo on workspace url check

fix: typo on workspace url check

---

apiserver/plane/settings/staging.py

fix: add dockerized variable to staging as magic links are failing in staging

fix: add dockerized variable to staging as magic links are failing in staging

---

apiserver/plane/api/permissions/project.py
apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/asset.py
apiserver/plane/api/views/issue.py
apiserver/plane/api/views/people.py

refactor: backend code cleanup

refactor: backend code cleanup

---

apiserver/plane/api/permissions/project.py
apiserver/plane/api/permissions/workspace.py
apiserver/plane/api/serializers/__init__.py
apiserver/plane/api/serializers/issue.py
apiserver/plane/api/views/base.py
apiserver/plane/api/views/cycle.py
apiserver/plane/api/views/issue.py
apiserver/plane/api/views/module.py
apiserver/plane/api/views/project.py
apiserver/plane/api/views/workspace.py
apiserver/plane/settings/staging.py
apiserver/requirements/base.txt

refactor: performance booster optimization

refactor: performance booster optimization

---

apps/app/components/common/board-view/single-issue.tsx
apps/app/components/core/view.tsx
apps/app/components/issues/list-item.tsx
apps/app/components/project/cycles/board-view/single-board.tsx
apps/app/components/project/issues/BoardView/single-board.tsx
apps/app/components/project/issues/issue-detail/issue-detail-sidebar/select-assignee.tsx
apps/app/components/project/issues/list-view/index.tsx
apps/app/components/project/modules/board-view/single-board.tsx
apps/app/components/ui/avatar/avatar.tsx
apps/app/components/ui/avatar/index.ts
apps/app/contexts/issue-view.context.tsx
apps/app/pages/[workspaceSlug]/me/my-issues.tsx

refactor:
- global component for assignees list

refactor: assignees list component

---

apps/app/components/common/board-view/single-issue.tsx
apps/app/components/project/issues/issue-detail/issue-detail-sidebar/index.tsx
apps/app/components/project/issues/issue-detail/issue-detail-sidebar/select-cycle.tsx
apps/app/components/project/modules/module-detail-sidebar/index.tsx
apps/app/components/ui/avatar/avatar.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx

fix:
- slow cycle mutation in issue details page.
- assignee list build fix.

fix: cycle mutation in issue details page

---

apps/app/components/command-palette/index.tsx
apps/app/components/common/board-view/single-issue.tsx
apps/app/components/cycles/modal.tsx
apps/app/components/issues/form.tsx
apps/app/components/issues/modal.tsx
apps/app/components/issues/select/label.tsx
apps/app/components/issues/select/project.tsx
apps/app/components/issues/select/state.tsx
apps/app/components/issues/sub-issue-list.tsx
apps/app/components/project/cycles/confirm-cycle-deletion.tsx
apps/app/components/project/issues/BoardView/index.tsx
apps/app/components/project/issues/BoardView/single-board.tsx
apps/app/components/project/issues/issue-detail/issue-detail-sidebar/index.tsx
apps/app/components/project/issues/issue-detail/issue-detail-sidebar/select-cycle.tsx
apps/app/components/project/issues/list-view/index.tsx
apps/app/components/project/modules/module-detail-sidebar/index.tsx
apps/app/components/ui/avatar/avatar.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/index.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/modules/[moduleId].tsx

fix:
- create issue modal not working on the home page.
- removed unnecessary props

fix: create issue modal

---

apps/app/components/command-palette/index.tsx
apps/app/components/command-palette/shortcuts.tsx
apps/app/components/common/bulk-delete-issues-modal.tsx
apps/app/components/common/existing-issues-list-modal.tsx
apps/app/components/issues/description-form.tsx
apps/app/components/project/cycles/board-view/index.tsx
apps/app/components/project/cycles/cycle-detail-sidebar/index.tsx
apps/app/components/project/cycles/stats-view/index.tsx
apps/app/components/project/issues/BoardView/index.tsx
apps/app/components/project/issues/issue-detail/issue-detail-sidebar/select-blocked.tsx
apps/app/components/project/issues/issue-detail/issue-detail-sidebar/select-blocker.tsx
apps/app/components/project/issues/issues-list-modal.tsx
apps/app/components/project/modules/board-view/index.tsx
apps/app/components/project/modules/module-detail-sidebar/index.tsx
apps/app/components/project/modules/single-module-card.tsx
apps/app/components/rich-text-editor/index.tsx
apps/app/components/workspace/help-section.tsx
apps/app/layouts/navbar/main-sidebar.tsx
apps/app/package.json
apps/app/pages/[workspaceSlug]/index.tsx
apps/app/pages/[workspaceSlug]/me/my-issues.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/index.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/modules/index.tsx
apps/app/pages/[workspaceSlug]/projects/index.tsx
apps/app/styles/editor.css
pnpm-lock.yaml

fix :
- shortcut ui fix
- issue title resizing fix
- comment resizing fix
- kanban view scroll fix
feat :
- progress bar added
- module card delete added
chore: 
- shortcut command updated

fix: ui changes

---

apiserver/plane/api/serializers/module.py

fix: typo while updating members in a module

fix: typo while updating members in a module

---

apps/app/components/issues/description-form.tsx
apps/app/components/issues/form.tsx
apps/app/components/project/create-project-modal.tsx
apps/app/components/project/cycles/create-update-cycle-modal.tsx
apps/app/components/project/issues/BoardView/state/create-update-state-inline.tsx
apps/app/components/project/modules/create-update-module-modal/index.tsx
apps/app/components/ui/datepicker.tsx

fix:
- added 255 characters validation to titles.
- added validations to the issue details page.

fix: form validations

---

apiserver/plane/db/models/issue.py

fix: update remirror description to save empty string and empty paragraph

fix: update remirror description to save empty string and empty paragraph

---

apiserver/plane/api/serializers/issue.py
apiserver/plane/db/models/issue.py

feat: manual ordering for issues in kanban

feat: manual ordering for issues in kanban

---

apps/app/components/core/bulk-delete-issues-modal.tsx
apps/app/components/core/existing-issues-list-modal.tsx
apps/app/components/issues/parent-issues-list-modal.tsx
apps/app/components/issues/sidebar-select/blocked.tsx
apps/app/components/issues/sidebar-select/blocker.tsx
apps/app/components/project/cycles/stats-view/index.tsx
apps/app/components/workspace/help-section.tsx
apps/app/layouts/navbar/main-sidebar.tsx
apps/app/pages/[workspaceSlug]/index.tsx
apps/app/pages/[workspaceSlug]/me/my-issues.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/index.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/modules/index.tsx
apps/app/pages/[workspaceSlug]/projects/index.tsx

style: 
- shortcut command label bg color change
fix:
- sidebar shortcut ui fix

fix: ui fixes

---

apiserver/plane/db/models/issue.py

feat: record issue completed at date when the issues are moved to completed group

feat: record issue completed at date when the issues are moved to completed group

---

apps/app/components/project/cycles/cycle-detail-sidebar/index.tsx
apps/app/components/project/cycles/index.ts
apps/app/components/project/cycles/sidebar-select/index.ts
apps/app/components/project/cycles/sidebar-select/select-status.tsx
apps/app/constants/cycle.ts

feat: 
- cycle status and dates added
- cycle status update controller added

feat: cycle status

---

apps/app/components/states/single-state.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/states.tsx

fix: state reordering

---

apps/app/components/core/board-view/all-boards.tsx
apps/app/components/core/board-view/single-board.tsx
apps/app/components/core/board-view/single-issue.tsx
apps/app/components/core/issues-view.tsx

feat:
- drag an issue in kanban view and drop in the trash box to delete.

feat: drag and drop an issue to delete

---

apps/app/components/account/email-code-form.tsx
apps/app/components/core/board-view/single-board.tsx
apps/app/components/issues/view-select/state.tsx
apps/app/components/project/card.tsx
apps/app/components/project/cycles/confirm-cycle-deletion.tsx
apps/app/components/project/cycles/cycle-detail-sidebar/index.tsx
apps/app/components/states/single-state.tsx
apps/app/components/workspace/home-cards-list.tsx
apps/app/pages/[workspaceSlug]/me/my-issues.tsx

chore:
- added delete cycle option to cycle sidebar.
- improved ui of project card on the projects page.
- modified states dropdown.
- added user authorization to drag and drop.

chore: removed minor bugs

---

apps/app/components/command-palette/shortcuts-modal.tsx
apps/app/components/workspace/help-section.tsx

fix: 
- shortcut modal ui fixes
-  shortcut search fix
- email us label change

fix: ui bug

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/auth_extended.py
apiserver/plane/api/views/authentication.py

refactor: combine sign in and sign up endpoint to a single endpoint

refactor: combine sign in and sign up endpoint to a single endpoint

---

apps/app/components/issues/activity.tsx
apps/app/components/issues/comment/add-comment.tsx
apps/app/components/issues/sub-issues-list.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx

refactor:
- sub-issues list component.
- activity component.

refactor: issue details page

---

apps/app/components/modules/sidebar.tsx

feat:
- range date picker added
- ui improvement for module status & date controllers

feat: module sidebar revamp

---

apps/app/components/breadcrumbs/index.tsx
apps/app/components/command-palette/command-pallette.tsx
apps/app/pages/create-workspace.tsx

refactor: 
- command palette
fix: 
- workspace name trim
- breadcrumb title responsiveness added

fix: workspace name and breadcrumb title , refactor: command palette

---

apps/app/components/core/board-view/single-issue.tsx
apps/app/components/core/list-view/single-issue.tsx
apps/app/components/modules/single-module-card.tsx
apps/app/components/project/cycles/stats-view/single-stat.tsx

feat: 
- copy issue , module & cycle option added
- ellipsis added in module card

feat: copy link option

---

apps/app/components/core/bulk-delete-issues-modal.tsx
apps/app/components/issues/form.tsx
apps/app/components/issues/modal.tsx

fix:
- remirror image not working while creating a new issue.

fix: remirror image not updating

---

apps/app/components/account/email-code-form.tsx
apps/app/hooks/use-timer.tsx

feat:
- users can request a new magic login code if they need one
- handling limit exhausted error on magic link login

feat: resend login magic code 

---

apps/app/components/issues/form.tsx
apps/app/components/issues/modal.tsx
apps/app/components/issues/select/assignee.tsx
apps/app/components/issues/sidebar-select/assignee.tsx
apps/app/types/issues.d.ts

fix:
- assignee and labels field were not showing values while editing an issue.

fix: assignee and labels field while editing an issue

---

apps/app/components/issues/description-form.tsx
apps/app/components/modules/single-module-card.tsx
apps/app/layouts/app-layout/app-header.tsx

fix : 
- issue title resizing fix
- header ui fix and no date label updated

fix: issue title resizing fix

---

apps/app/components/issues/modal.tsx

fix:
-  create issue modal closing by clicking on Grammarly recommendation

fix: create issue modal closing on clicking on Grammarly recommendation

---

apps/app/components/core/board-view/single-board.tsx
apps/app/components/core/board-view/single-issue.tsx
apps/app/components/core/issues-view-filter.tsx
apps/app/components/core/issues-view.tsx
apps/app/components/cycles/modal.tsx
apps/app/constants/issue.ts
apps/app/contexts/issue-view.context.tsx
apps/app/hooks/use-issue-view.tsx
apps/app/types/issues.d.ts

feat:
- user can manually reorder the issues in the kanban view.

feat: manual ordering of issues

---

apps/app/components/core/board-view/single-board.tsx
apps/app/components/core/board-view/single-issue.tsx
apps/app/components/core/issues-view.tsx

fix:
- manual ordering while dropping in the same group between two issues.

fix: manual ordering bug

---

apiserver/back_migration.py
apiserver/plane/api/views/issue.py
apiserver/plane/db/models/issue.py
apiserver/plane/utils/grouper.py

feat: updated issue grouping and filtering

feat: updated issue grouping and filtering

---

apps/app/components/core/list-view/single-issue.tsx
apps/app/components/issues/my-issues-list-item.tsx
apps/app/components/issues/view-select/assignee.tsx
apps/app/components/issues/view-select/due-date.tsx
apps/app/components/issues/view-select/priority.tsx
apps/app/components/issues/view-select/state.tsx
apps/app/components/states/single-state.tsx
apps/app/components/ui/avatar.tsx
apps/app/components/ui/tooltip.tsx
apps/app/package.json

feat: 
- tooltip added for issues
fix: 
- ellipsis added to issue in list view
- assignee avatar fix

feat: issues tooltip , fix: ui improvement

---

apps/app/pages/[workspaceSlug]/index.tsx
apps/app/pages/[workspaceSlug]/me/profile.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/index.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/modules/[moduleId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/modules/index.tsx
apps/app/pages/onboarding/index.tsx

fix: 
- redirection after login, showing API response

fix: redirection after login

---

apps/app/components/core/board-view/single-board.tsx
apps/app/components/cycles/single-cycle-card.tsx
apps/app/components/emoji-icon-picker/index.tsx
apps/app/components/issues/my-issues-list-item.tsx
apps/app/components/issues/view-select/assignee.tsx
apps/app/components/modules/single-module-card.tsx
apps/app/components/project/confirm-project-deletion.tsx
apps/app/components/ui/tooltip.tsx
apps/app/pages/[workspaceSlug]/index.tsx
apps/app/styles/globals.css

- emoji picker overflow fix 
- project delete modal text overflow fix
- cycle card ellipsis alignment 
- assignees tooltips positioning fix 
- module card image & label added for no lead & members
- my issue and home page ,tooltips and responsiveness added

fix: ui improvements 

---

apps/app/components/issues/my-issues-list-item.tsx
apps/app/components/project/card.tsx

- project card identifier remove
- copy issue option added to my issue page

fix: ui fix

---

apps/app/components/modules/modal.tsx
apps/app/components/modules/select/select-status.tsx
apps/app/components/modules/single-module-card.tsx
apps/app/components/ui/custom-search-select.tsx

fix:
- mutation error after editing module.

fix: edit module mutation error

---

apps/app/components/core/sidebar/progress-chart.tsx
apps/app/components/cycles/form.tsx
apps/app/components/cycles/sidebar.tsx
apps/app/components/modules/sidebar.tsx
apps/app/helpers/date-time.helper.ts
apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx

fix: 
- sidebar overflow 
- current cycle date

fix: ui improvement

---

apiserver/.env.example

fix: rename db host name for docker setup

fix: rename db host name for docker setup

---

apps/app/components/core/list-view/all-lists.tsx
apps/app/components/core/list-view/single-issue.tsx
apps/app/components/core/list-view/single-list.tsx

style: list view

---

.github/workflows/push-image-backend.yml
.github/workflows/push-image-frontend.yml

Add Github Actions that will build and publish Frontend and Backend images of plane to Github's registry.
Things to note:
1. This is my first time with Github Actions, and wanted to give it a shot, so any feedback/commit is welcomed.
2. ARM jobs take longer, specially Backend, specially because the [Gevent](https://github.com/gevent/gevent) dependency does not have any wheels for arm64, and as it builds it from source on the spot, increases build time notoriusly.
3. The auto generated labes/tags from the `docker/metadata-action` job might not be accurate or adequate.

Github actions to push images

---

apiserver/plane/api/serializers/__init__.py
apiserver/plane/api/serializers/view.py
apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/issue.py
apiserver/plane/api/views/view.py
apiserver/plane/db/models/__init__.py
apiserver/plane/db/models/view.py
apiserver/plane/utils/issue_filters.py

feat: issue filter views 

---

apiserver/plane/api/views/authentication.py
apiserver/plane/api/views/oauth.py
apiserver/plane/settings/local.py
apiserver/plane/settings/production.py
apiserver/plane/settings/staging.py

feat: jitsu events for sign in and sign up

feat: jitsu events for sign in and sign up

---

apps/app/components/core/issues-view-filter.tsx
apps/app/components/core/issues-view.tsx
apps/app/components/issues/select/priority.tsx
apps/app/components/project/single-sidebar-project.tsx
apps/app/components/ui/multi-level-dropdown.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/features.tsx
apps/app/types/projects.d.ts

style:
- filter issues dropdown.
- multi-level dropdown.

style: filter issues dropdown

---

apiserver/plane/api/serializers/page.py
apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/page.py
apiserver/plane/db/models/__init__.py
apiserver/plane/db/models/page.py

feat: page labels and favorites

feat: page labels and favorites

---

apps/app/pages/[workspaceSlug]/me/profile.tsx

style:
- my profiles page responsiveness

style: my profiles page responsiveness

---

apps/app/components/workspace/help-section.tsx
apps/app/contexts/issue-view.context.tsx

fix:
- sidebar arrow positioning in the collapsed state.
- show empty groups option set to `true` by default.

fix: minor ui fixes

---

apps/app/components/workspace/completed-issues-graph.tsx

fix: 
- prevent decimal value in the y axis of completed issues graph

fix: don't allow decimal in the y axis of completed issues graph

---

apps/app/components/views/select-filters.tsx

fix:
- old labels color set to black in the filters dropdown.

fix: old labels color set to black

---

apps/app/components/core/calendar-view/calendar.tsx

refactor:
- calendar view mutation and other improvements.

refactor: calendar view

---

apps/app/components/issues/form.tsx

fix:
- title of issue modal is resetting itself also when switching tabs and on AI popover closes.

fix: issue modal title text field reset

---

apps/app/components/labels/labels-list-modal.tsx

fix: 
- old labels must have black color in project settings

fix: old labels must have black color in project settings

---

apps/app/components/workspace/create-workspace-form.tsx

chore:
- restrict users from creating a workspace with restricted slugs.

chore: restrict users from creating a workspace with restricted slugs

---

apps/app/layouts/settings-navbar.tsx

chore:
- remove GitHub importer tab from workspace settings.

chore: remove github importer tab

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/search.py
apiserver/plane/utils/issue_search.py

feat: issue search endpoint

---

apiserver/plane/api/serializers/__init__.py
apiserver/plane/api/serializers/issue.py
apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/asset.py
apiserver/plane/api/views/issue.py
apiserver/plane/db/models/__init__.py
apiserver/plane/db/models/issue.py

feat: issue attachments

---

README.md

docs: update readme to include default email and password for self hosting setup

docs: update readme to include default email and password for self hosting setup

---

apps/app/components/ui/buttons/danger-button.tsx
apps/app/components/ui/buttons/primary-button.tsx

style:
- disabled state for buttons.

style: disabled state for buttons

---

apps/app/components/issues/attachment-upload.tsx
apps/app/components/issues/delete-attachment-modal.tsx
apps/app/pages/[workspaceSlug]/index.tsx

fix:
- issue attachments mutation for create and delete operations.

fix: issue attachments mutation

---

apiserver/Procfile
apiserver/plane/__init__.py
apiserver/plane/bgtasks/issue_activites_task.py
apiserver/plane/celery.py
apiserver/plane/settings/__init__.py
apiserver/plane/settings/common.py

fix: celery worker for issue activities

fix: celery worker for issue activities

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/estimate.py

feat: bulk update estimate endpoint

feat: bulk update estimate endpoint

---

apiserver/bin/worker

fix: remove migrate command from worker script

fix: remove migrate command from worker script

---

apps/app/contexts/user.context.tsx
apps/app/pages/[workspaceSlug]/index.tsx
apps/app/pages/onboarding.tsx
apps/app/services/user.service.ts
apps/app/types/users.d.ts

fix: onboarding loop

---

apiserver/plane/bgtasks/issue_activites_task.py

feat: track estimate points in issue activity

feat: track estimate points in issue activity

---

apiserver/plane/api/urls.py

fix: typo in url for bulk creating labels

fix: typo in url for bulk creating labels

---

apps/app/components/core/feeds.tsx
apps/app/components/core/issues-view.tsx
apps/app/components/issues/activity.tsx
apps/app/components/issues/form.tsx
apps/app/components/issues/select/estimate.tsx
apps/app/components/issues/sidebar-select/estimate.tsx
apps/app/components/issues/sidebar.tsx
apps/app/components/issues/view-select/estimate.tsx
apps/app/hooks/use-estimate-option.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx
apps/app/types/issues.d.ts

chore:
- no estimates option.
- estimates activity.

chore: no estimates option, estimates activity

---

apps/app/components/core/issues-view.tsx
apps/app/components/core/list-view/all-lists.tsx
apps/app/components/core/list-view/single-issue.tsx

chore: 
- worked on making issue list filter padding consistent

chore: made issues list filter padding consistent

---

apiserver/plane/settings/production.py

fix: redis url for docker in production settings

fix: redis url for docker in production settings

---

apps/app/contexts/issue-view.context.tsx
apps/app/services/cycles.service.ts
apps/app/services/modules.service.ts
apps/app/types/cycles.d.ts
apps/app/types/modules.d.ts

feat:
- separate filters for projects, cycles and modules.

feat: separate filters for cycles and modules

---

apps/app/components/core/board-view/board-header.tsx
apps/app/components/core/board-view/single-issue.tsx
apps/app/components/core/issues-view-filter.tsx
apps/app/components/core/list-view/single-issue.tsx
apps/app/components/core/list-view/single-list.tsx
apps/app/components/issues/view-select/assignee.tsx
apps/app/components/issues/view-select/priority.tsx
apps/app/components/ui/avatar.tsx
apps/app/components/ui/custom-menu.tsx
apps/app/components/ui/custom-search-select.tsx
apps/app/components/ui/custom-select.tsx
apps/app/components/ui/datepicker.tsx
apps/app/components/ui/multi-level-dropdown.tsx
apps/app/components/views/select-filters.tsx
apps/app/components/workspace/sidebar-dropdown.tsx
apps/app/layouts/auth-layout/project-authorization-wrapper.tsx
apps/app/styles/globals.css
apps/app/tailwind.config.js

style:
- list and kanban view theming.

style: list and kanban view theming

---

apps/app/components/cycles/single-cycle-card.tsx
apps/app/components/modules/single-module-card.tsx

style:
- cycle and module theming

style: cycle and module theming

---

apps/app/components/core/sidebar/progress-chart.tsx
apps/app/components/cycles/sidebar.tsx
apps/app/components/modules/sidebar-select/select-lead.tsx
apps/app/components/modules/sidebar-select/select-members.tsx
apps/app/components/modules/sidebar.tsx
apps/app/components/ui/progress-bar.tsx
apps/app/components/workspace/sidebar-dropdown.tsx
apps/app/styles/globals.css

style:
- module & cycle sidebar theming

style: sidebar theming

---

apps/app/components/workspace/activity-graph.tsx
apps/app/components/workspace/completed-issues-graph.tsx
apps/app/components/workspace/issues-list.tsx
apps/app/components/workspace/issues-pie-chart.tsx
apps/app/components/workspace/issues-stats.tsx
apps/app/pages/[workspaceSlug]/index.tsx

style: dashboard theming

---

apps/app/components/command-palette/command-pallette.tsx
apps/app/layouts/settings-navbar.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/index.tsx
apps/app/pages/[workspaceSlug]/settings/billing.tsx
apps/app/pages/[workspaceSlug]/settings/import-export.tsx

fix: 
- breadcrumbs heading updated for workspace settings
- workspace settings tab updated
style: 
- project settings cover photo description

fix: breadcrumbs and tab updated

---

apps/app/components/core/board-view/single-issue.tsx
apps/app/components/core/calendar-view/calendar-header.tsx
apps/app/components/core/calendar-view/calendar.tsx
apps/app/components/core/calendar-view/index.ts
apps/app/components/core/calendar-view/single-date.tsx
apps/app/components/core/calendar-view/single-issue.tsx
apps/app/components/core/index.ts
apps/app/components/core/issues-view-filter.tsx
apps/app/components/core/issues-view.tsx
apps/app/components/core/list-view/single-issue.tsx
apps/app/components/issues/delete-issue-modal.tsx
apps/app/components/issues/modal.tsx
apps/app/components/issues/my-issues-list-item.tsx
apps/app/components/issues/view-select/assignee.tsx
apps/app/components/issues/view-select/due-date.tsx
apps/app/components/issues/view-select/estimate.tsx
apps/app/components/issues/view-select/priority.tsx
apps/app/components/issues/view-select/state.tsx
apps/app/types/calendar.ts
apps/app/types/index.d.ts

fix: 
- calendar view mutation fix.
feat: 
- calendar view display property added.
- calendar header, single date and single-issue component added.
- ellipsis menu added in calendar issue.
chore:
- code refactored.

feat: calendar view display properties

---

apps/app/components/core/board-view/single-board.tsx

fix:
- kanban horizontal scroll not working while dragging.

fix: kanban board horizontal scroll

---

apps/app/components/analytics/scope-and-demand/scope.tsx
apps/app/components/core/board-view/single-board.tsx
apps/app/components/labels/delete-label-modal.tsx
apps/app/components/labels/index.ts
apps/app/components/labels/single-label-group.tsx
apps/app/components/labels/single-label.tsx
apps/app/components/workspace/issues-list.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/labels.tsx

chore:
- delete label confirmation modal.
- show completed and canceled states by default on the Kanban board.
- update scope analytics graph tooltip content.
fix:
- negative days on upcoming issues list on the dashboard.

chore: delete label confirmation modal

---

apps/app/components/analytics/custom-analytics/graph/custom-tooltip.tsx
apps/app/components/analytics/custom-analytics/graph/index.tsx

fix:
- show the assignee name in the custom analytics tooltip.

fix: show the assignee name in the custom analytics tooltip

---

setup.sh

fix: auto generated secret key to only generate hexadecimal characters
This PR should fix #1127

fix: auto generated secret key to only generate hexadecimal characters

---

apiserver/plane/api/views/project.py
apiserver/plane/api/views/workspace.py

fix: role updation

---

.env.example
app.json
deploy/heroku/Dockerfile
docker-compose-hub.yml
docker-compose.yml
heroku.yml

chore: update single click deployments

chore: update single click deployments

---

apps/app/components/cycles/active-cycle-details.tsx
apps/app/components/cycles/completed-cycles.tsx
apps/app/components/cycles/cycles-view.tsx
apps/app/components/cycles/delete-cycle-modal.tsx
apps/app/components/cycles/modal.tsx
apps/app/components/cycles/select.tsx
apps/app/components/cycles/single-cycle-card.tsx
apps/app/components/cycles/single-cycle-list.tsx
apps/app/components/cycles/transfer-issues-modal.tsx
apps/app/components/issues/sidebar-select/cycle.tsx
apps/app/constants/fetch-keys.ts
apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx
apps/app/services/cycles.service.ts
apps/app/types/cycles.d.ts

chore: 
- cycles endpoint updated and code refactor

chore: cycles endpoint updated and code refactor

---

.env.example
docker-compose-hub.yml
docker-compose.yml

chore: configuration for nginx port.
This is related to #1140

chore: configuration for nginx port

---

replace-env-vars.sh

The previous implementation of this script uses `find` to enumerate *all files* under the app directory, then reads all of those files in a single while loop to apply `sed`. This is extremely slow with ~80k files during build time. We don't need to read all these files like that; we can use grep to search for files that we actually need to update and then parallelize the sed command to do it.
I ran `shellcheck` against the script to make sure I didn't introduce any obvious new footguns and made sure `docker-compose -f docker-compose.yml up --build` still built the image and ran without issues.

chore: speedup replace-env-vars.sh

---

apps/app/components/pages/pages-list/all-pages-list.tsx
apps/app/components/pages/pages-list/favorite-pages-list.tsx
apps/app/components/pages/pages-list/my-pages-list.tsx
apps/app/components/pages/pages-list/other-pages-list.tsx
apps/app/components/pages/pages-list/recent-pages-list.tsx
apps/app/components/pages/pages-view.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/pages/index.tsx

fix:
- pages empty space vertical alignment.
- pages y-axis overflow.

fix: pages layout and alignment issues

---

README.md

There were missing files (E.g. `.env.example`, `nginx` directory, etc...). Cloning the repository prevents such issues.

docs: fix docker compose quick start

---

apps/app/components/onboarding/user-details.tsx
apps/app/components/onboarding/workspace.tsx
apps/app/components/workspace/create-workspace-form.tsx

fix: onboarding ui fix

---

apiserver/plane/bgtasks/forgot_password_task.py
apiserver/templates/emails/auth/forgot_password.html

fix: forgot password email subject and update template
Fixes #1230

fix: forgot password email subject and update template

---

apps/app/components/core/board-view/single-issue.tsx
apps/app/components/core/calendar-view/single-issue.tsx
apps/app/components/core/list-view/single-issue.tsx
apps/app/components/core/spreadsheet-view/single-issue.tsx
apps/app/components/issues/my-issues-list-item.tsx
apps/app/components/issues/view-select/assignee.tsx
apps/app/components/issues/view-select/due-date.tsx
apps/app/components/issues/view-select/estimate.tsx
apps/app/components/issues/view-select/index.ts
apps/app/components/issues/view-select/label.tsx
apps/app/components/issues/view-select/priority.tsx
apps/app/components/issues/view-select/state.tsx

feat: 
- editable label option added in all view
fix: 
- view page list and kanban view mutation fix 
chore: 
- code refactor

feat: editable label option added in all view , fix: view page list and kanban view mutation fix, chore: code refactor

---

apps/app/components/core/spreadsheet-view/single-issue.tsx
apps/app/components/core/spreadsheet-view/spreadsheet-columns.tsx
apps/app/components/core/spreadsheet-view/spreadsheet-view.tsx
apps/app/styles/globals.css

fix: 
- spreadsheet quick action menu fix

fix: spreadsheet quick action menu fix

---

apps/app/Dockerfile.web

Inside of the Dockerfile.web, the yarn install command is susceptible to encountering a ECONNECT timeout error on aarch64 and ARM devices (such as a raspberry pi). This explicit overwrite of the default network timeout extends the window for low power CPU devices.
Fixes #1213

Add network timeout option to yarn install

---

docker-compose.yml

* chore: Use docker compose extensions to dry up duplicate environment variables between worker and api services.
See: https://docs.docker.com/compose/compose-file/11-extension/

chore: Dry up docker compose environment variables

---

apiserver/plane/api/views/workspace.py
apiserver/plane/db/models/workspace.py

chore: workspace char name and slug maximum length

chore: workspace char name and slug maximum length

---

apps/app/components/core/board-view/board-header.tsx
apps/app/components/core/list-view/single-list.tsx

fix:
- state icon color on group titles.

fix: state icon color on group titles

---

apiserver/plane/api/views/issue.py
apiserver/plane/settings/production.py
apiserver/plane/urls.py
apiserver/requirements/base.txt
apiserver/requirements/local.txt
apiserver/requirements/production.txt

chore: upgrade backend dependencies

chore: upgrade backend dependencies

---

apps/app/components/analytics/custom-analytics/sidebar.tsx
apps/app/components/emoji-icon-picker/index.tsx
apps/app/components/project/create-project-modal.tsx
apps/app/components/project/single-project-card.tsx
apps/app/components/project/single-sidebar-project.tsx
apps/app/helpers/common.helper.ts
apps/app/helpers/emoji.helper.ts
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/index.tsx

fix: emoji render function

---

apps/app/components/core/board-view/board-header.tsx
apps/app/components/core/calendar-view/single-issue.tsx
apps/app/components/core/spreadsheet-view/single-issue.tsx
apps/app/components/issues/view-select/state.tsx
apps/app/components/ui/custom-search-select.tsx

fix: 
- resolved overflow issue with longer state names.

fix: resolved overflow issue with longer state names

---

apiserver/plane/api/serializers/notification.py
apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/notification.py
apiserver/plane/bgtasks/issue_activites_task.py

chore: add triggered by details for notifications

chore: notifications

---

apps/app/components/account/email-code-form.tsx
apps/app/components/account/google-login.tsx
apps/app/components/issues/modal.tsx
apps/app/components/onboarding/tour/sidebar.tsx
apps/app/components/ui/dropdowns/custom-menu.tsx
apps/app/components/workspace/sidebar-dropdown.tsx
apps/app/pages/_app.tsx
apps/app/pages/index.tsx
apps/app/pages/reset-password.tsx
apps/app/pages/sign-up.tsx
apps/app/services/issues.service.ts

fix:
- tour sidebar icons.
- auth pages scroll.
chore:
- set theme to `dark` on sign out.

fix: tour sidebar icons, auth pages scroll

---

apps/app/pages/[workspaceSlug]/projects/[projectId]/archived-issues/[archivedIssueId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx

fix:
- archived issue details page overflow.
- restore button loading.

fix: archived issue details page overflow, restore button loading

---

apps/app/components/notifications/notification-popover.tsx
apps/app/hooks/use-user-notifications.tsx

refactor: 
- the height of popover & API fetch call

refactor: height of popover & api fetch call

---

apiserver/plane/bgtasks/issue_activites_task.py

fix: restrict notifications for created by when the actor is same

fix: restrict notifications for created by when the actor is same

---

apps/app/components/automation/auto-archive-automation.tsx
apps/app/components/automation/auto-close-automation.tsx
apps/app/components/notifications/notification-popover.tsx
apps/app/components/workspace/help-section.tsx

style:
- added tooltip for the notification icon in the collapsed sidebar.
- border style of the automation settings has been updated.
- cursor style for the free plane label in the sidebar has been updated.

style: ui improvements

---

apps/app/components/core/modals/existing-issues-list-modal.tsx
apps/app/components/issues/parent-issues-list-modal.tsx

refactor: issue search

---

apps/app/components/core/modals/existing-issues-list-modal.tsx
apps/app/components/issues/form.tsx
apps/app/components/issues/main-content.tsx
apps/app/components/issues/parent-issues-list-modal.tsx
apps/app/components/issues/sidebar-select/blocked.tsx
apps/app/components/issues/sidebar-select/blocker.tsx
apps/app/components/issues/sidebar-select/parent.tsx
apps/app/components/issues/sidebar.tsx
apps/app/components/issues/sub-issues-list.tsx
apps/app/components/ui/dropdowns/custom-menu.tsx
apps/app/components/ui/toggle-switch.tsx
apps/app/components/ui/tooltip.tsx
apps/app/components/workspace/help-section.tsx
apps/app/types/issues.d.ts
apps/app/types/projects.d.ts
apps/app/types/state.d.ts

feat:
- cross-project issue linking for parent, sub-issues, blocking, and blocked by issues.

feat: cross-project issue linking

---

apps/app/components/core/issues-view.tsx
apps/app/components/core/modals/existing-issues-list-modal.tsx
apps/app/components/issues/sidebar-select/blocked.tsx
apps/app/components/issues/sidebar-select/blocker.tsx
apps/app/components/issues/sub-issues-list.tsx
apps/app/components/ui/empty-state.tsx

chore:
- remove workspace level toggle from cycle and module issues.

chore: remove workspace level toggle from cycle and module issues

---

apps/app/components/issues/description-form.tsx
apps/app/components/issues/form.tsx
apps/app/components/issues/modal.tsx
apps/app/components/issues/select/project.tsx

fix:
- project select not working on the create issue modal.
refactor:
- issue details page description form.

fix: project select not working on the create issue modal

---

apps/app/components/core/modals/link-modal.tsx
apps/app/components/core/sidebar/links-list.tsx

fix:
- add link form not submitting on pressing `Enter`.
refactor:
- remove `Link` tag from the link card.

fix: add link form not submitting on pressing `Enter`

---

apps/app/components/analytics/custom-analytics/sidebar.tsx
apps/app/components/core/image-picker-popover.tsx
apps/app/components/emoji-icon-picker/index.tsx
apps/app/components/emoji-icon-picker/types.d.ts
apps/app/components/integration/jira/import-users.tsx
apps/app/components/issues/select/assignee.tsx
apps/app/components/modules/sidebar-select/select-members.tsx
apps/app/components/project/create-project-modal.tsx
apps/app/components/project/delete-project-modal.tsx
apps/app/components/project/single-project-card.tsx
apps/app/components/ui/dropdowns/custom-search-select.tsx
apps/app/components/ui/dropdowns/custom-select.tsx
apps/app/components/ui/text-area/index.tsx
apps/app/constants/project.ts
apps/app/hooks/use-workspace-members.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/control.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/index.tsx
apps/app/types/projects.d.ts

style:
- create project modal.
refactor:
- custom search select props.
- delete project mutation.

style: create project modal

---

apps/app/components/cycles/active-cycle-details.tsx
apps/app/components/cycles/cycles-view.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx

style:
- new cycles list page design with empty states.

style: new cycles list page design with empty states

---

apiserver/plane/api/views/notification.py

feat: notification pagination

---

apiserver/plane/api/serializers/issue.py
apiserver/plane/api/views/issue.py
apiserver/plane/api/views/notification.py

fix: issue create update n+1 and issue activity get n+1

fix: issue create update n+1 and issue activity get n+1

---

apps/app/components/cycles/delete-cycle-modal.tsx
apps/app/components/cycles/modal.tsx
apps/app/hooks/use-issue-properties.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx

chore:
- set all issue properties as true by default.

chore: set all issue properties as true by default

---

apps/app/components/project/create-project-modal.tsx
apps/app/components/ui/dropdowns/custom-menu.tsx
apps/app/components/ui/dropdowns/custom-search-select.tsx
apps/app/components/ui/dropdowns/custom-select.tsx

chore:
- increase project identifier max length to 12.

chore: increase project identifier max length to 12

---

apps/app/components/core/board-view/single-issue.tsx
apps/app/components/core/list-view/single-issue.tsx
apps/app/components/core/spreadsheet-view/single-issue.tsx
apps/app/components/issues/index.ts
apps/app/components/issues/label.tsx

style: 
- issue label ui updated.

style: issue label ui updated

---

apps/app/components/core/filters/issues-view-filter.tsx
apps/app/constants/fetch-keys.ts
apps/app/contexts/issue-view.context.tsx
apps/app/hooks/use-issues-view.tsx

feat: 
- show sub-issue on list-view

feat: show sub-issue on list-view

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/search.py

chore: project identifier for all the search items and take project id as query params

chore: project identifier for all the search items and take project id as query params

---

apiserver/plane/api/serializers/__init__.py
apiserver/plane/api/serializers/cycle.py
apiserver/plane/api/views/cycle.py

fix: cycles n+1

---

apiserver/templates/emails/auth/magic_signin.html
apiserver/templates/emails/invitations/project_invitation.html
apiserver/templates/emails/invitations/workspace_invitation.html

The email invitation url's for self-hosted plane had a fixed `https://app.plane.so/` link instead of invitation url when viewed in Outlook or certain MS email clients.
This PR fixes the templates to use the appropriate template variables for the links

handle email invitation urls in outlook clients properly

---

README.md

The commits per month badge had the wrong alt text.

Changed alt text for badges in Readme

---

apiserver/plane/api/serializers/project.py
apiserver/plane/api/views/project.py
apiserver/plane/db/migrations/0039_auto_20230723_2203.py
apiserver/plane/db/models/project.py

feat: user project sorting

---

apps/app/components/project/sidebar-list.tsx
apps/app/components/project/single-sidebar-project.tsx
apps/app/components/workspace/sidebar-menu.tsx
apps/app/hooks/use-profile-issues.tsx
apps/app/hooks/use-user.tsx
apps/app/types/projects.d.ts

style:
- sidebar projects list design.
chore:
- separate joined and unjoined projects' sections.

style: sidebar projects design

---

apps/app/components/core/views/all-views.tsx
apps/app/components/core/views/issues-view.tsx
apps/app/components/issues/delete-issue-modal.tsx
apps/app/components/issues/my-issues/my-issues-view.tsx
apps/app/components/pages/pages-list/recent-pages-list.tsx
apps/app/components/pages/pages-view.tsx
apps/app/components/profile/profile-issues-view.tsx
apps/app/components/ui/empty-state.tsx
apps/app/layouts/auth-layout/project-authorization-wrapper.tsx
apps/app/pages/[workspaceSlug]/analytics.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/modules/index.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/estimates.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/integrations.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/labels.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/views/index.tsx
apps/app/pages/[workspaceSlug]/projects/index.tsx
apps/app/pages/invitations.tsx

chore:
- update empty states.
fix:
- delete issue modal.

chore: update empty states, fix: delete issue modal

---

apps/app/components/core/activity.tsx
apps/app/components/core/index.ts
apps/app/components/issues/activity.tsx
apps/app/components/issues/comment/comment-card.tsx
apps/app/components/issues/comment/comment-reaction.tsx
apps/app/components/profile/overview/activity.tsx
apps/app/types/issues.d.ts
apps/app/types/users.d.ts

refactor:
- issue activity component.
chore:
- show issue details on the profile activity.

refactor: issue activity component

---

apps/app/components/issues/my-issues/my-issues-view-options.tsx
apps/app/components/profile/profile-issues-view-options.tsx

style: 
- my issue and profile page view dropdown

style: my issue and profile page view dropdown

---

apps/app/components/project/single-sidebar-project.tsx

chore:
- show a message if dragging an unjoined project.

chore: show a message if dragging an unjoined project

---

apps/app/components/project/sidebar-list.tsx
apps/app/components/project/single-sidebar-project.tsx

style: 
- consistent padding to match the sidebar's layout applied.
- implemented dynamic length title on hover, allowing it to expand and occupy available space, while shrinking upon hovering to reveal quick action icon.

style: sidebar project list improvement

---

apps/app/components/ui/empty-state.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/modules/[moduleId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/views/[viewId].tsx

chore:
- add non-existing states for project entities.

chore: add non existing states for project entities

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/issue.py
apiserver/plane/bgtasks/project_issue_export.py
apiserver/templates/emails/exports/issues.html

feat: created issue export csv

feat: issue export csv

---

apps/app/package.json
yarn.lock

I've added the `sharp` package to speed up image resizing since Next.js warns about it being missing during the build process.

chore(frontend): add `sharp`

---

apps/app/components/ui/multi-level-dropdown.tsx

chore:
- empty state for multi-level dropdown.

chore: empty state for multi-level dropdown

---

apps/app/pages/[workspaceSlug]/me/profile/index.tsx

style: 
- option to edit display name in profile page

style: option to edit display name in profile page

---

apps/app/pages/[workspaceSlug]/me/profile/index.tsx

refactor: 
- added validation for display_name

refactor: added validation for display_name

---

apps/app/components/project/single-project-card.tsx
apps/app/types/projects.d.ts

refactor: 
- not making calls to member's endpoint to get membership status

refactor: not making calls to member's endpoint to get membership status

---

apps/app/components/command-palette/command-k.tsx

fix: 
- cmdk modal not closing when choosing an option

fix: cmdk modal not closing when choosing an option

---

apps/app/hooks/my-issues/use-my-issues.tsx

This PR fixes empty state groups not appearing on the My Issues page Kanban board.
Before the fix-
After the fix-

fix: empty groups not appearing on the my issues Kanban board

---

apps/app/components/core/modals/image-upload-modal.tsx

This PR addresses the aspect ratio issue within the image uploader for the workspace logo and profile picture.
Before the fix:-
After the fix:-

style: image upload modal aspect ratio

---

apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/members.tsx
apps/app/pages/[workspaceSlug]/settings/members.tsx

fix: 
- gray background if the image being used is in png format
Before:
After:

fix: gray background if the image being used is in png format

---

apiserver/plane/bgtasks/analytic_plot_export.py

fix: 
- Export CSV when the `x_axis` is assignee showing `ids` in the CSV with `first_name` and `last_name`.
- Export CSV when the `segment` is assignee showing `ids` in the CSV with `first_name` and `last_name`.

fix: analytics export

---

apps/app/components/notifications/notification-card.tsx

fix: 
- notification card not redirecting to archive issue detail for archived issue

fix: notification card not redirecting to archive issue detail for archived issue

---

apps/space/app/[workspace_slug]/[project_slug]/layout.tsx
apps/space/app/page.tsx
apps/space/components/issues/navbar/index.tsx
apps/space/package.json
apps/space/store/types/project.ts

In this pull request, we have updated the meta tags and favicon for Plane Deploy.

chore: updated meta tags for project issues

---

README.md

This PR adds a new section in the Quick Start Setup document to include an installation guide for Tiptap Pro. 
I have created an issue for this,(#1869) since I was stuck on the Tiptap Pro installation error. Got some help and feedback on the issue and was able to resolve it.

document: Update local setup document 

---

apps/app/components/core/modals/link-modal.tsx
apps/app/components/core/sidebar/links-list.tsx
apps/app/components/issues/sidebar.tsx
apps/app/components/modules/sidebar.tsx
apps/app/services/issues.service.ts
apps/app/services/modules.service.ts
apps/app/types/issues.d.ts
apps/app/types/modules.d.ts

This PR introduces functionality to edit links for both issues and modules.
https://github.com/makeplane/plane/assets/121005188/1bb872cc-ef84-4e14-9926-7b2939943bf4

chore: link edit functionality

---

apps/app/components/cycles/single-cycle-card.tsx
apps/app/components/cycles/single-cycle-list.tsx
apps/app/components/ui/avatar.tsx

- completed cycle validation fix in both the cycle list and card, preventing users from attempting edit or deletion actions on completed cycles.
- adjustment of the assignee count alignment within the cycle card.

fix: completed cycle validation , style: assignee count alignment fix 

---

apps/app/constants/analytics.ts

chore:
- start date property for custom analytics' x-axis and group.

chore: start date property for custom analytics' x-axis and group

---

apps/app/contexts/issue-view.context.tsx

https://github.com/makeplane/plane/assets/65252264/0096a66c-532f-4f4a-9696-133bc8e02278
https://github.com/makeplane/plane/assets/65252264/d6ca3652-709d-4fa0-9897-a44dfb17c35a

chore: set order by to manual on gantt chart

---

apps/app/components/issues/activity.tsx
apps/app/components/issues/comment/comment-card.tsx
apps/app/components/notifications/notification-card.tsx

style: 
- showing the first name for the bot profiles

style: showing first name for bot profile

---

apps/app/components/issues/select/assignee.tsx
apps/app/components/issues/select/date.tsx
apps/app/components/issues/select/label.tsx
apps/app/components/ui/labels-list.tsx

This PR includes consistent ui for create/update issue modal properties.

style: consistent ui for create update issue modal

---

apps/app/components/project/create-project-modal.tsx
apps/app/components/project/sidebar-list.tsx

chore: 
- add favorite project from sidebar.

chore: add favorite project from sidebar

---

apps/app/components/profile/overview/priority-distribution.tsx
apps/app/components/profile/overview/state-distribution.tsx

style: 
- responsive empty state for profile stats

style: responsive empty state for profile stats

---

apps/app/components/core/views/board-view/single-issue.tsx
apps/app/components/core/views/list-view/single-issue.tsx
apps/app/components/ui/dropdowns/context-menu.tsx
apps/app/hooks/use-outside-click-detector.tsx

Before the fix-
https://github.com/makeplane/plane/assets/65252264/c7206472-d656-4a93-b5cb-08fc4e6569c6
After the fix-
https://github.com/makeplane/plane/assets/65252264/ab7b1038-1006-4ee6-beaf-cdf1ec24d3a6
1. Refactored props structure of the context menu component.
2. Refactored `useOutsideClickDetector` hook to call the callback function on `mousedown` instead of `click`.

fix: context menu dynamic positioning, multiple context menus opening issue

---

apps/app/components/project/delete-project-modal.tsx
apps/app/components/ui/input/index.tsx
apps/app/components/ui/input/types.d.ts
apps/app/components/workspace/delete-workspace-modal.tsx

This PR converts the project and workspace delete modals to `react-hook-form` to enable form submission on `Enter` and also optimizes the components.

refactor: project and workspace delete modals

---

apps/app/components/issues/select/date.tsx
apps/app/components/modules/form.tsx

This PR adds the validation on the start date and target date selects in the create module form, restricting the user from selecting an invalid date range.

fix: create module form start and target date validations

---

apps/app/components/project/sidebar-list.tsx

fix:
- create project button not appearing on the sidebar.

fix: create project button not appearing on the sidebar

---

docker-compose-hub.yml
docker-compose.yml
nginx/nginx.conf.template

dev: deploy docker containers

---

apps/app/components/issues/sidebar-select/label.tsx
apps/app/components/issues/sidebar.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx

fix: label color select popover overflow

---

apps/app/components/project/join-project-modal.tsx
apps/app/components/project/sidebar-list.tsx
apps/app/pages/[workspaceSlug]/projects/index.tsx

https://github.com/makeplane/plane/assets/65252264/323216de-b59d-4f7c-86e6-664662be2cde

fix: mutate sidebar projects list after joining

---

apps/app/components/issues/sidebar-select/label.tsx
apps/app/components/issues/sidebar.tsx
apps/app/components/project/join-project-modal.tsx
apps/app/components/project/sidebar-list.tsx
apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx
apps/app/pages/[workspaceSlug]/projects/index.tsx

Promote: Develop to Stage Release

Promote: Develop to Stage Release

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/project.py

feat: 
- Endpoint to list all public boards for a workspace

feat: project deploy boards list endpoint 

---

apps/app/components/core/filters/date-filter-modal.tsx
apps/app/components/core/filters/date-filter-select.tsx
apps/app/components/core/filters/filters-list.tsx
apps/app/components/core/filters/index.ts
apps/app/components/core/filters/issues-view-filter.tsx
apps/app/components/core/views/issues-view.tsx
apps/app/components/issues/my-issues/my-issues-select-filters.tsx
apps/app/components/issues/my-issues/my-issues-view-options.tsx
apps/app/components/issues/my-issues/my-issues-view.tsx
apps/app/components/profile/profile-issues-view-options.tsx
apps/app/components/profile/profile-issues-view.tsx
apps/app/components/views/form.tsx
apps/app/components/views/select-filters.tsx
apps/app/constants/fetch-keys.ts
apps/app/constants/filters.ts
apps/app/contexts/issue-view.context.tsx
apps/app/contexts/profile-issues-context.tsx
apps/app/hooks/my-issues/use-my-issues-filter.tsx
apps/app/hooks/my-issues/use-my-issues.tsx
apps/app/hooks/use-issues-view.tsx
apps/app/hooks/use-profile-issues.tsx
apps/app/types/issues.d.ts
apps/app/types/views.d.ts

1. Project issues
2. My issues page
3. Profile issues
4. Views
https://github.com/makeplane/plane/assets/65252264/bd55be9d-fee6-457e-a75d-7a608eb17aba

feat: start date filter across the platform

---

apps/app/components/core/views/board-view/board-header.tsx
apps/app/components/core/views/issues-view.tsx
apps/app/components/core/views/list-view/single-list.tsx
apps/app/components/issues/my-issues/my-issues-view-options.tsx
apps/app/components/profile/profile-issues-view-options.tsx
apps/app/constants/issue.ts
apps/app/types/issues.d.ts

chore:
- group by assignees option for project issues.

chore: group by assignees option for project issues

---

.github/workflows/push-image-backend.yml
.github/workflows/push-image-deploy.yml
.github/workflows/push-image-frontend.yml
.github/workflows/push-image-proxy.yml

- When a release is PUBLISHED, from draft to release or a direct release, the workflow will be triggered, generating new tags based on the current release ( for release `0.1.1` , the images are tagged as `plane-<frontend/backend/proxy/deploy>:0.1.1`  ) and the image will be marked latest.
- When a pull request get merged in develop branch, all the existing images will be updated with tag develop, still develop won't be the latest tag for the image, the latest tag will be the release tag above.
- `DOCKERHUB_USERNAME` - Username for the dockerhub account ( makeplane ), henit0885 in my case
- `DOCKERHUB_TOKEN` - `ITS NOT DOCKERHUB_PASSWORD!` New PAT Token generated at Dockerhub for Push, Pull Action
- `TIPTAP_TOKEN` - Tiptap Pro Extension token for the main frontend app, actions generate …

[chore] Fixed Github Workflows for Building and Pushing, frontend, backend, proxy & plane-deploy 

---

apps/app/components/tiptap/index.tsx

fix: tiptap editor max width

---

apps/app/pages/[workspaceSlug]/settings/members.tsx

Fixing the order of members visibility, Moving invited members to be rendered at the top of the list instead of bottom.
before:
after:

fix: workspace members reordering

---

apps/app/components/notifications/notification-header.tsx
apps/app/components/notifications/notification-popover.tsx
apps/app/hooks/use-user-notifications.tsx
apps/app/services/notifications.service.ts
apps/app/types/notifications.d.ts

feat: mark all notifications as read

---

apps/app/pages/[workspaceSlug]/me/profile/activity.tsx
apps/app/services/user.service.ts

fix:
- added `workspaceSlug` to the my profile activity endpoint.
- activity loader position.

fix: my profile activity endpoint

---

space/Dockerfile.space
web/Dockerfile.web

- As we are not going forward with the monorepo architecture, the Docker Images are built in the context of the project, which means, that while building web, the context should not be `.` instead it should be `./web`, same for space, the context should be `./space`. Hence the build command will be `docker build ./web -f ./web/Dockerfile.web -t plane-web:latest` and `docker build ./space -f ./space/Dockerfile.space`

chore: modified dockerfiles for space and web

---

apiserver/plane/api/views/issue.py
apiserver/plane/bgtasks/issue_automation_task.py

fix: 
- n+1 in issue history endpoint for comment reactions
- n+1 in issue automation tasks for auto closing and auto archiving issues

fix: n+1 in issue history and issue automation tasks

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/notification.py

feat: created api for marking all unread notifications as read

feat: mark all read notifications

---

apiserver/plane/api/views/issue.py

fix: only external comments will show in deploy boards

fix: external comments in deploy boards

---

apiserver/plane/api/serializers/issue.py

fix:
- Comments are categorised into two types internal and external  that are only visible to external public

fix: access creation in comments

---

apps/app/components/issues/comment/add-comment.tsx
apps/app/components/issues/main-content.tsx
apps/app/services/issues.service.ts
apps/app/types/issues.d.ts
apps/app/types/projects.d.ts

Access specifier will only be visible if the project is published/deployed.

feat: access selector for comment

---

apps/app/components/profile/sidebar.tsx
apps/app/contexts/profile-issues-context.tsx
apps/app/hooks/use-profile-issues.tsx

1. Project progress calculation logic in the profile sidebar
2. Kanban layout empty state.
3. Group by property persistence when changing the layout.

fix: bugs on the user profile page

---

apiserver/plane/api/serializers/issue.py
apiserver/plane/api/views/issue.py
apiserver/plane/db/models/issue.py

chore:
- Make comments GET Apis Public
- rename `issue_reactions` to `reactions`
- add a reverse accessor for comments to issues

chore: public board endpoints

---

apps/app/components/issues/delete-issue-modal.tsx
apps/app/components/issues/peek-overview/issue-properties.tsx
apps/app/components/issues/peek-overview/layout.tsx
apps/app/components/issues/sidebar-select/assignee.tsx
apps/app/components/issues/sidebar-select/priority.tsx
apps/app/components/ui/dropdowns/custom-select.tsx
apps/app/store/issues.ts

1. Side peek shaking animation when opened.
2. Date selector not working when no date is selected.
3. Activity mutation on change.
4. Assignees not mutating after change.
1. Delete issue handler.
2. Peek overview layout.

fix: peek overview bugs

---

apiserver/plane/api/urls.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/project.py
apiserver/plane/api/views/workspace.py

feat: leave project and workspace endpoint

feat: leave project and workspace endpoint

---

apps/space/components/issues/board-views/kanban/index.tsx
apps/space/pages/_document.tsx
apps/space/pages/index.tsx

style:
1. Sign in page bg color.
2. Kanban empty state.

style: sign in page bg color

---

.husky/pre-push
package.json
yarn.lock

Before Every Push, in any Branch, husky will run a pre-push script which includes linting and building of the modified project directories, ensuring that no code in any branch of the repository breaks while building. ✌🏼

[chore] Added Husky for Automating Building and Linting Projects Before Push

---

apiserver/plane/api/views/issue.py

dev
- updated error handling for project deploy board attributes when deploy board is not enabled

dev: updated error handling for project deploy board attributes

---

space/components/issues/board-views/kanban/block.tsx
space/components/issues/board-views/list/block.tsx
space/components/issues/navbar/index.tsx
space/components/issues/navbar/issue-board-view.tsx

Redirections fixes when clicking on the issues.

fix: space redirections

---

space/components/issues/peek-overview/header.tsx
space/components/issues/peek-overview/issue-properties.tsx
space/components/issues/peek-overview/layout.tsx
space/layouts/project-layout.tsx
web/components/issues/peek-overview/issue-properties.tsx

fix:
- copy link button not working on the peek overview.

fix: copy link button not working on the peek overview

---

web/components/profile/sidebar.tsx

fix:
- show profile time according to the user's timezone.

fix: show profile time according to the user's timezone

---

apiserver/plane/api/views/gpt.py

According to OpenAI[^1] , GPT-3.5 Turbo & GPT-4 is not working on **Legacy** Completions API
[^1]: https://platform.openai.com/docs/guides/gpt/chat-completions-vs-completions

fix: replace `Completion` with `ChatCompletion` to use `gpt-3.5-turbo` model

---

web/components/web-view/create-update-link-form.tsx
web/components/web-view/index.ts
web/components/web-view/issue-attachments.tsx
web/components/web-view/issue-link-list.tsx
web/components/web-view/issue-properties-detail.tsx
web/components/web-view/issue-web-view-form.tsx
web/components/web-view/label.tsx
web/components/web-view/select-priority.tsx
web/components/web-view/select-state.tsx
web/components/web-view/sub-issues.tsx
web/components/web-view/web-view-modal.tsx
web/constants/fetch-keys.ts
web/pages/m/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx

feat: 
- issue detail for web-view

feat: issue detail for web-view

---

space/components/accounts/sign-in.tsx
space/store/user.ts

This PR fixes redirection after a user signs in on Plane Space if `next_path` is present in the URL.
Fixes-
1. Correct `next_path` to send when redirecting to the sign in page while voting and reacting.
2. On the sign in page, fix the function to fetch the `next_path` from the URL.

fix: redirection after signing in on space

---

web/components/cycles/gantt-chart/cycles-list-layout.tsx
web/components/gantt-chart/helpers/block-structure.tsx
web/components/modules/gantt-chart/modules-list-layout.tsx

fix:
- blocks with start date greater than the target date won't be rendered on the Gantt chart.

fix: don't render invalid dated blocks on the gantt chart

---

web/components/web-view/add-comment.tsx
web/components/web-view/create-update-link-form.tsx
web/components/web-view/index.ts
web/components/web-view/issue-activity.tsx
web/components/web-view/issue-attachments.tsx
web/components/web-view/issue-link-list.tsx
web/components/web-view/issue-properties-detail.tsx
web/components/web-view/select-assignee.tsx
web/components/web-view/select-estimate.tsx
web/components/web-view/select-priority.tsx
web/components/web-view/web-view-modal.tsx
web/constants/fetch-keys.ts
web/pages/m/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx

feat:
- view, create, update, and delete comments
- update and delete the link
fix:
- image not being uploaded on mobile devices

feat: view, create, update and delete comment

---

space/store/issue_details.ts

fix:
- edit issue comment mutation on Plane deploy.

fix: edit issue comment mutation on Plane deploy

---

web/components/tiptap/extensions/index.tsx
web/components/tiptap/plugins/delete-image.tsx
web/components/tiptap/plugins/upload-image.tsx

- Closes #1998 
Here I focus on resolving three issues: 
1. The first issue addressed is the range errors experienced during bulk image deletion from S3. 
2. The second issue pertains to the random changes in image IDs between two transactions in modals. 
3. Really bad Time Complexity during checking for deleted image nodes hence really bad performance concerns in large docs.
The changes proposed significantly improve the time complexity of checking if a node still exists in the new state, from O(n) to O(1).
The original S3 image deletion logic involved a complex process that included iterating through all nodes in the old state, checking for image nodes, and then traversing the entire new state for each node in the old state. This process was not only complex but also inefficient with a …

fix: Improved Image Deletion Logic, Image ID Issue in Modals and Performance Optimization in Editor

---

web/components/inbox/inbox-issue-activity.tsx
web/components/issues/activity.tsx
web/components/issues/comment/comment-card.tsx
web/components/issues/main-content.tsx
web/components/issues/peek-overview/issue-activity.tsx
web/services/issues.service.ts

Users can now change the access of the comment that they posted and also will be able to view whether the comment is public or private after posting it.
Other improvements-
1. Users can now post access specific comments from the peek overview as well.

chore: option to switch access of a comment

---

apiserver/plane/api/views/issue.py

fix: remove triage issue status from public boards

fix: remove triage issue status from public boards

---

web/components/core/filters/date-filter-modal.tsx
web/components/issues/my-issues/my-issues-select-filters.tsx
web/components/views/select-filters.tsx

fix: custom date filters not working on my issues and profile issues

---

web/components/exporter/guide.tsx

fix:
- handleClose function of the export modal.

fix: handleClose function of the export modal

---

space/pages/[workspace_slug]/[project_slug]/index.tsx
web/pages/installations/[provider]/index.tsx

chore:
- remove `getServerSideProps` from the app installations page.

chore: remove `getServerSideProps`

---

package.json

currently, _docker compose up -d_, triggers this error:
```
[4/4] Building fresh packages...
$ husky install
/bin/sh: husky: not found
error Command failed with exit code 127.
```

fix: husky was removed in commit #2086, but prepare still uses it

---

web/pages/m/[workspaceSlug]/editor.tsx

fix: 
- the logic should be to check if an object exist not if it's true or false

fix: query checking

---

web/components/onboarding/user-details.tsx
web/helpers/date-time.helper.ts

feat: 
- users can select a timezone during onboarding 
- their timezone is automatically selected which they can change

feat: users can select timezone during onboarding

---

web/components/profile/profile-issues-view-options.tsx
web/components/profile/profile-issues-view.tsx
web/contexts/issue-view.context.tsx
web/contexts/profile-issues-context.tsx
web/hooks/my-issues/use-my-issues-filter.tsx
web/hooks/use-profile-issues.tsx
web/types/view-props.d.ts

fix:
- handle error when view props are undefined.

fix: handle undefined view props

---

web/components/core/filters/issues-view-filter.tsx
web/components/core/views/all-views.tsx
web/components/core/views/board-view/all-boards.tsx
web/components/core/views/board-view/single-board.tsx
web/components/core/views/board-view/single-issue.tsx
web/components/core/views/issues-view.tsx
web/components/core/views/list-view/all-lists.tsx
web/components/core/views/list-view/single-issue.tsx
web/components/core/views/list-view/single-list.tsx
web/components/issues/delete-draft-issue-modal.tsx
web/components/issues/form.tsx
web/components/issues/index.ts
web/components/workspace/sidebar-quick-action.tsx
web/pages/[workspaceSlug]/projects/[projectId]/draft-issues/index.tsx

fix: 
- edit/delete for draft issue 
- styling issue
- workflow

fix: edit/delete for draft issue 

---

web/components/command-palette/command-pallette.tsx
web/components/core/views/issues-view.tsx
web/components/issues/delete-draft-issue-modal.tsx
web/components/issues/draft-issue-modal.tsx
web/components/issues/form.tsx
web/components/issues/modal.tsx
web/components/ui/buttons/type.d.ts
web/components/workspace/sidebar-quick-action.tsx
web/services/issues.service.ts
web/store/draft-issue.ts
web/store/root.ts

fix: 
- hydration error and draft issue workflow

fix: hydration error and draft issue workflow

---

web/components/core/activity.tsx
web/components/issues/sidebar-select/blocked.tsx
web/components/issues/sidebar-select/blocker.tsx
web/components/issues/sidebar-select/duplicate.tsx
web/components/issues/sidebar-select/relates-to.tsx
web/components/issues/sidebar.tsx
web/components/web-view/activity-message.tsx
web/components/web-view/issue-properties-detail.tsx
web/services/issues.service.ts
web/types/issues.d.ts

fix: 
- activity not coming for blocking/blocked, 'related to', and duplicate
refactor: 
- mutation logic to use relation id instead of issue id

fix: activity not coming for blocking/blocked, 'related to' and duplicate

---

.github/workflows/Build_Test_Pull_Request.yml
.github/workflows/Update_Docker_Images.yml
README.md
setup.sh
space/components/tiptap/extensions/index.tsx
space/package.json
web/components/tiptap/extensions/index.tsx
web/package.json
yarn.lock

The Tiptap token was used only for downloading an extension that previously "enabled" us to manage image deletions efficiently so that s3 storage is cleaned up properly if an image gets deleted in the editor, but now we're using the source from s3 to detect this instead since with the new approach I figured out a way to do that.
Here's a PR that got us one step forward toward that by removing the dependency https://github.com/makeplane/plane/pull/2092

[fix]: Removing dependency on tiptap pro extension

---

web/components/core/activity.tsx

fix: label color in the activity logs coming as black

---

web/components/core/views/board-view/all-boards.tsx
web/components/profile/profile-issues-view.tsx
web/contexts/profile-issues-context.tsx

fix:
1. Unable to switch layout in profile issues.
2. Unable to toggle display properties in profile issues.
style:
1. Secondary background color for the Kanban board throughout the platform.

fix: profile issues layout switch

---

apiserver/plane/api/views/cycle.py
apiserver/plane/api/views/inbox.py
apiserver/plane/api/views/issue.py
apiserver/plane/api/views/module.py
apiserver/plane/bgtasks/issue_automation_task.py

chore: added epoch in draft

---

web/components/ui/toggle-switch.tsx
web/pages/[workspaceSlug]/me/profile/activity.tsx
web/pages/[workspaceSlug]/me/profile/preferences.tsx
web/pages/[workspaceSlug]/settings/billing.tsx

This PR includes settings page typo fix and toggle switch component improvement.

style: settings page improvement

---

web/components/core/views/board-view/single-board.tsx
web/components/core/views/board-view/single-issue.tsx
web/components/core/views/calendar-view/single-date.tsx
web/components/core/views/calendar-view/single-issue.tsx
web/components/core/views/list-view/single-issue.tsx
web/components/core/views/list-view/single-list.tsx
web/components/core/views/spreadsheet-view/single-issue.tsx
web/components/core/views/spreadsheet-view/spreadsheet-issues.tsx
web/components/project/label-select.tsx
web/components/project/members-select.tsx
web/components/states/state-select.tsx

fix: 
- bug fix related to fetching dropdown options for the profile issue

fix: bug fix related to fetching dropdown options for the profile issue

---

web/components/core/filters/issues-view-filter.tsx
web/components/issues/my-issues/my-issues-view-options.tsx
web/components/profile/profile-issues-view-options.tsx
web/pages/[workspaceSlug]/projects/[projectId]/modules/index.tsx

The PR includes renaming all tooltips that reflect the issue layouts across the platform from `View` to `Layout`.

chore: renamed all the issues view tooltips content from View to Layout

---

web/components/cycles/single-cycle-list.tsx
web/components/labels/single-label.tsx
web/pages/[workspaceSlug]/me/profile/index.tsx
web/pages/[workspaceSlug]/settings/index.tsx

This PR includes following changes: 
- completed cycle percentage bug fix.
- label setting action menu fix.
- profile setting > first and last name character limit to 24.
- workspace setting > delete workspace typo fix.

fix: bug fixes and ui improvement

---

web/components/core/views/board-view/single-board.tsx
web/components/core/views/inline-issue-create-wrapper.tsx
web/components/core/views/list-view/inline-create-issue-form.tsx
web/components/core/views/list-view/single-list.tsx
web/components/core/views/spreadsheet-view/spreadsheet-view.tsx
web/components/gantt-chart/sidebar.tsx
web/components/profile/profile-issues-view.tsx
web/layouts/app-layout/app-sidebar.tsx
web/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
web/pages/[workspaceSlug]/projects/[projectId]/modules/[moduleId].tsx

feat: 
- quick-add placement in the spreadsheet and Gantt layout
fix: 
- opening create issue modal instead of quick-add in draft-issues, my-issue, and profile page

feat: quick-add placement in spreadsheet and gantt 

---

web/components/issues/activity.tsx

chore: add tooltip to show full time on activity logs

---

apiserver/plane/bgtasks/issue_automation_task.py

fix: 
- Notification not getting triggered for auto archive and auto closed issues

fix: issue automation iterable error

---

CONTRIBUTING.md

To help developers who don't understand how to setup the development environment.
Following discussion #1222 and issue #2216.

chore: add instructions to contributing guide

---

web/components/core/filters/issues-view-filter.tsx
web/components/core/views/board-view/board-header.tsx
web/components/core/views/list-view/single-list.tsx
web/components/issues/my-issues/my-issues-view-options.tsx
web/components/profile/profile-issues-view-options.tsx
web/pages/[workspaceSlug]/index.tsx

fix:
- Dashboard greeting time to be in the user selected timezone.
- Group by labels not working on the my issues and user profile pages.
- Rename `Show empty states` to `Show empty groups` on the display filters dropdown.

fix: user dashboard greeting timezone

---

web/components/gantt-chart/helpers/draggable.tsx

fix:
- gantt block getting clicked while moving the block.

fix: gantt block getting clicked while moving the block

---

web/components/core/views/calendar-view/calendar-header.tsx
web/components/core/views/calendar-view/calendar.tsx
web/components/core/views/calendar-view/single-date.tsx
web/contexts/issue-view.context.tsx
web/helpers/calendar.helper.ts
web/hooks/use-calendar-issues-view.tsx
web/types/view-props.d.ts

This PR removes the logic of saving the last active calendar date range in the database and handle date range logic in the frontend.

chore: handle calendar date range in frontend

---

web/components/gantt-chart/chart/index.tsx
web/components/gantt-chart/sidebar.tsx
web/components/issues/gantt-chart/blocks.tsx

chore:
- remove empty state from the sidebar.
- add header to the sidebar.

chore: gantt chart empty state

---

web/components/core/views/board-view/single-board.tsx
web/components/core/views/calendar-view/inline-create-issue-form.tsx
web/components/core/views/calendar-view/single-date.tsx
web/components/core/views/inline-issue-create-wrapper.tsx
web/components/core/views/list-view/single-list.tsx
web/components/core/views/spreadsheet-view/spreadsheet-view.tsx

style: 
- calendar quick-add same width as a single date
- reduced margin left in calendar quick-add
- margin-bottom for text in spreadsheet view
fix:
- quick add opening in list-view plus button

style: calender quick-add same width as single date

---

apiserver/plane/api/permissions/workspace.py
apiserver/plane/api/views/issue.py
apiserver/plane/api/views/view.py

- `order_by` for all the `GET` requests
- updated permission layer

chore: views

---

web/hooks/use-calendar-issues-view.tsx

chore:
- fetch issues from previous, current and next month in the calendar view.

chore: fetch issues from previous, current and next month in the calendar view

---

web/components/core/activity.tsx
web/hooks/use-estimate-option.tsx

This PR includes fix for the problem with activity issue, ensuring that the estimate value is now rendered correctly.

fix: issue activity estimate value bug fix

---

web/components/core/views/spreadsheet-view/issue-column/issue-column.tsx
web/components/core/views/spreadsheet-view/spreadsheet-view.tsx
web/components/issues/my-issues/my-issues-view-options.tsx
web/components/issues/workspace-views/workpace-view-issues.tsx
web/components/issues/workspace-views/workspace-all-issue.tsx
web/components/issues/workspace-views/workspace-assigned-issue.tsx
web/components/issues/workspace-views/workspace-issue-view-option.tsx
web/components/views/single-view-item.tsx
web/components/workspace/views/workpace-view-navigation.tsx
web/constants/fetch-keys.ts
web/contexts/workspace-view-context.tsx
web/pages/[workspaceSlug]/workspace-views/all-issues.tsx
web/types/view-props.d.ts

- Rectified the no filter bug in workspace view.
- Resolved the display properties bug.
- Addressed the mutation issue in workspace view.
- Conducted code refactoring.
- Rectified the sub-issue nesting bug.
- Applied a mutation fix for the workspace view.
- Enhanced the UI in the spreadsheet view.
- Addition of a toast alert for updated workspace view.

chore: workspace view mutation fix ,bug fixes and code refactor

---

web/components/core/views/spreadsheet-view/spreadsheet-view.tsx

chore: 
- workspace view order by removed.

chore: workspace view order by removed

---

web/components/core/filters/workspace-filters-list.tsx
web/components/views/single-view-item.tsx
web/components/workspace/views/single-workspace-view-item.tsx
web/pages/[workspaceSlug]/projects/[projectId]/views/index.tsx
web/pages/[workspaceSlug]/workspace-views/index.tsx

fix: 
- workspace view filters count fix.

fix: workspace view filters count fix

---

web/components/core/views/spreadsheet-view/spreadsheet-view.tsx
web/components/workspace/views/modal.tsx

fix: 
- workspace view redirection fix.
style: 
- spreadsheet view scroll shadow fix.

fix: workspace view redirection fix, style: spreadsheet view shadow scroll fix

---

apiserver/.env.example
apiserver/plane/settings/production.py

dev: update apiserver configuration files

dev: update apiserver configuration files

---

web/lib/mobx/store-init.tsx

In this pull request, we have addressed the issue of theming not being set to undefined.

fix: themening  validation in store init.

---

web/components/tiptap/index.tsx
web/components/tiptap/table-menu/index.tsx

fix: table options menu positioning

---

web/components/automation/auto-archive-automation.tsx
web/components/automation/auto-close-automation.tsx
web/components/project/member-select.tsx
web/components/ui/dropdowns/custom-menu.tsx
web/components/ui/empty-state.tsx
web/components/ui/toggle-switch.tsx
web/pages/[workspaceSlug]/projects/[projectId]/settings/automations.tsx
web/pages/[workspaceSlug]/projects/[projectId]/settings/features.tsx
web/pages/[workspaceSlug]/projects/[projectId]/settings/integrations.tsx
web/pages/[workspaceSlug]/projects/[projectId]/settings/members.tsx

This PR includes solution for project setting validation concerning members. Now, only admin have the capability to execute automation, features, and member-related actions.

fix: project setting member role validation

---

web/components/project/card.tsx

This PR includes the following modifications:
- remove the custom menu and relocate the icon to the card itself.
- fix the add and remove favorite mutation by implementing mobx.
- replace icon with lucide icon and apply the required styling changes.

chore: project card revamp and refactor

---

web/components/pages/pages-list/recent-pages-list.tsx

This pull request solves the hiding last item from pages > Recent tab
the container not scrolling till the bottom
issues was : 
after Solve: 
thank you :)
fixes: #1468

[bug]: fix recent page hiding last item on scroll #1468

---

web/components/issues/activity.tsx
web/components/profile/sidebar.tsx
web/components/web-view/issue-activity.tsx
web/pages/[workspaceSlug]/me/profile/activity.tsx

This PR addresses the profile picture dimension issue that was causing problems when users set a longer profile picture.
Before:
---
After:

fix: profile pic dimension bug fix

---

packages/ui/package.json
packages/ui/src/button/button.tsx
packages/ui/src/tooltip/tooltip.tsx

- removal of the next-theme and clsx packages from the plane/ui package.
- resolution of naming convention issues in the button component.

chore: ui package code refactor

---

web/components/project/card.tsx
web/components/project/form.tsx

- adjusted project card title font weight to semibold.
- "joined" indicator added in the project card.
- resolved member tooltip issue; it now displays the total number of members rather than their names.
- implemented a linear gradient on the project cover image in the project settings page for better visibility.

style: project page ui improvement

---

web/components/headers/cycle-issues.tsx
web/components/headers/global-issues.tsx
web/components/headers/module-issues.tsx
web/components/headers/project-issues.tsx
web/components/headers/project-view-issues.tsx
web/components/profile/profile-issues-filter.tsx

This PR fixes the display properties and filters dropdown overflow issue on the global views.
Other fixes-
1. Renamed `View` to `Display`.
2. Made the gap between the dropdowns in the header consistent.

fix: global view filters dropdown overflow issue

---

web/components/issues/select/project.tsx

1. Emojis and icons are now visible along with the project name in the dropdown.
2. Refactored the select component to get the list of projects from the project store.

chore: add emoji to projects list

---

web/components/issues/issue-layouts/gantt/cycle-root.tsx
web/components/issues/issue-layouts/gantt/module-root.tsx
web/components/issues/issue-layouts/gantt/project-view-root.tsx
web/components/issues/issue-layouts/gantt/root.tsx
web/store/cycle/cycle_issue.store.ts
web/store/issue/issue.store.ts
web/store/module/module_issue.store.ts
web/store/project-view/project_view_issues.store.ts

Created new action in the issues store to update the gantt chart blocks with the new logic to implement draggable and resizable blocks in the Gantt chart.

fix: Gantt chart blocks drag and resize logic

---

web/components/headers/project-view-issues.tsx
web/components/headers/project-views.tsx
web/components/issues/issue-layouts/roots/cycle-layout-root.tsx
web/components/issues/issue-layouts/roots/global-view-layout-root.tsx
web/components/issues/issue-layouts/roots/module-layout-root.tsx
web/components/issues/issue-layouts/roots/project-layout-root.tsx
web/components/issues/issue-layouts/roots/project-view-layout-root.tsx
web/layouts/auth-layout/project-wrapper.tsx
web/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
web/pages/[workspaceSlug]/projects/[projectId]/issues/index.tsx
web/pages/[workspaceSlug]/projects/[projectId]/views/[viewId].tsx
web/pages/[workspaceSlug]/projects/[projectId]/views/index.tsx

1. Removed the unnecessary API calls.
2. Wrapped the project view details page with the project wrapper.

refactor: cycle, module and view layout roots

---

web/store/command-palette.store.ts

This PR addresses the problem with the command palette store, which was causing the bulk delete modal to function incorrectly.

fix: command palette fix

---

packages/editor/core/package.json
packages/ui/package.json
space/package.json

While running `docker-compose` for building and running the docker setup for plane, the build was failing because of missing dependencies in the newely added, `plane-ui` and `editor-core` packages.

[fix] `docker-compose` failing to build images

---

.gitignore
space/next.config.js
space/package.json
web/next.config.js
web/package.json

This enables the user to build and configure nextjs applications using SSG, which works like a single-page application.
By running the following command
```
next export 
```
Out folder will be generated with a static site build, which enables users to configure their app directly in Nginx.

fix: enabling the nextjs static site generation for web and space

---

apiserver/plane/api/views/issue.py

Removed duplicated issues for multiple assignees or labels
Steps to reproduce
- Go in the issues page
- Add multiple labels to a single issue
- apply filters -> labels -> select all the labels for that issue

chore: removed duplicate issues for multiple assignees or labels

---

web/components/integration/github/single-user-select.tsx
web/components/integration/jira/import-users.tsx
web/components/issues/attachment/attachments.tsx
web/components/issues/select/assignee.tsx
web/components/issues/sidebar-select/assignee.tsx
web/components/modules/select/lead.tsx
web/components/modules/select/members.tsx
web/components/modules/sidebar-select/select-lead.tsx
web/components/modules/sidebar-select/select-members.tsx
web/components/pages/pages-view.tsx
web/components/project/member-select.tsx
web/components/project/send-project-invitation-modal.tsx
web/components/ui/avatar.tsx
web/components/views/select-filters.tsx
web/components/web-view/select-assignee.tsx
web/constants/fetch-keys.ts
web/hooks/use-project-members.tsx
web/hooks/use-workspace-members.tsx
web/layouts/auth-layout/project-wrapper.tsx
web/layouts/auth-layout/workspace-wrapper.tsx
web/pages/[workspaceSlug]/projects/[projectId]/settings/members.tsx
web/pages/workspace-invitations/index.tsx
web/services/project/project.service.ts
web/services/project/project_invitation.service.ts
web/services/workspace.service.ts
web/store/project/project.store.ts
web/store/workspace/workspace.store.ts
web/types/projects.d.ts

1. Only one endpoint to fetch members list for workspace and members.
2. Updated bulk add members to project endpoint and naming convention.
3. Added auth to fetch member request so that only admin and members can access it.
4. Removed unnecessary fetch keys.

chore: update members endpoint

---

web/components/gantt-chart/chart/index.tsx
web/components/headers/project-issues.tsx
web/components/issues/issue-layouts/roots/cycle-layout-root.tsx
web/components/issues/issue-layouts/roots/global-view-layout-root.tsx
web/components/issues/issue-layouts/roots/module-layout-root.tsx
web/components/issues/issue-layouts/roots/project-layout-root.tsx
web/components/issues/issue-layouts/roots/project-view-layout-root.tsx

1. Added a loading state for all the layouts.
2. Hide the issue count for inbox if no issues are present.

chore: loading state for all layouts

---

web/components/issues/form.tsx
web/components/issues/modal.tsx
web/components/issues/select/cycle.tsx
web/components/issues/select/index.ts
web/components/issues/select/module.tsx

In this pull request, we've made an enhancement by introducing two new properties to the issue creation modal. Users can now select a module and a cycle based on their project selection, providing greater flexibility and customization when creating issues

enhancement: Added Module and Cycle Selection to Issue Creation Modal

---

web/components/issues/select/cycle.tsx
web/components/issues/select/date.tsx
web/components/issues/select/label.tsx
web/components/issues/select/module.tsx

In this pull request, we've fixed a bug related to the issue properties dropdown. It was causing overflow issues for date and labels in the issue creation modal.

fix: Resolved Issue Property Dropdown Overflow in Issue Create Modal

---

web/store/issue/issue_filters.store.ts

This PR fixes the calendar layout not being rendered by setting the default `calendar display_filters` if not already present.

fix: calendar layout not being rendered

---

web/components/workspace/create-workspace-form.tsx
web/constants/workspace.ts

This PR fixes the following bug-
1. Users not being able to manually type the `workspace slug` in the create workspace form.
https://github.com/makeplane/plane/assets/65252264/3207e033-1b1c-4200-8015-493ca35f2e11

fix: slug field not working in the create workspace form

---

web/components/issues/issue-layouts/spreadsheet/columns/issue/issue-column.tsx
web/components/issues/issue-layouts/spreadsheet/columns/issue/spreadsheet-issue-column.tsx
web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
web/components/issues/issue-peek-overview/root.tsx
web/components/issues/issue-peek-overview/view.tsx

This PR addresses following things:
- resolves a z-index problem with the peek overview component.
- fixes an issue with the peekover view in spreadsheet mode.

fix: resolve z-index and peek overview component bug

---

web/components/notifications/notification-card.tsx
web/components/notifications/notification-header.tsx
web/components/notifications/notification-popover.tsx
web/components/notifications/select-snooze-till-modal.tsx
web/hooks/use-user-notifications.tsx

fix:
- marking notification as read doesn't remove it from the un-read notification list
- past snooze notifications coming in the snooze tab

fix: notification read and snooze bugs

---

web/components/issues/issue-layouts/properties/assignee.tsx
web/components/issues/issue-layouts/properties/labels.tsx
web/components/issues/issue-layouts/properties/state.tsx
web/components/project/card.tsx

- project card avatar rendering fix.  
- loading state added to  state, assignee, and label selection dropdown.

chore : dropdown loading state added and project card avatar fix

---

packages/editor/core/src/ui/mentions/MentionList.tsx
packages/editor/lite-text-editor/src/ui/extensions/index.tsx
packages/editor/lite-text-editor/src/ui/read-only/index.tsx
web/components/issues/comment/comment-card.tsx
web/components/issues/issue-peek-overview/activity/comment-card.tsx

fix: mentions enter error

---

web/components/issues/issue-peek-overview/root.tsx
web/components/issues/issue-peek-overview/view.tsx
web/store/cycle/cycle_issue_kanban_view.store.ts
web/store/issue/issue_kanban_view.store.ts
web/store/module/module_issue_kanban_view.store.ts

In this pull request, we've made several fixes. We've improved the drag-and-drop functionality, resolved the Gantt hover issue in the issue peek overview, and added a React fragment around the peek overview component.

chore: improved Drag and Drop Functionality, Gantt Hover in Issue Peek Overview

---

web/components/issues/issue-layouts/list/headers/group-by-card.tsx
web/components/notifications/notification-popover.tsx
web/store/issue/issue_filters.store.ts

Before fix- 
https://github.com/makeplane/plane/assets/65252264/d6ade89a-746d-4d2f-8ef9-6d79c38f1152
After fix-
https://github.com/makeplane/plane/assets/65252264/cf352176-6202-4fb9-94c5-85b35d83092f

fix: notifications option in the sidebar menu not collapsing

---

web/components/issues/issue-layouts/empty-states/cycle.tsx
web/components/issues/issue-layouts/empty-states/module.tsx
web/components/issues/issue-layouts/roots/cycle-layout-root.tsx
web/components/issues/issue-layouts/roots/module-layout-root.tsx
web/components/issues/issue-peek-overview/properties.tsx
web/components/issues/modal.tsx
web/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
web/pages/[workspaceSlug]/projects/[projectId]/modules/[moduleId].tsx
web/store/cycle/cycle_issue.store.ts
web/store/module/module_issue.store.ts

This PR focuses on implementing MobX actions for adding existing issues to cycle and module.

fix: existing issues modal for cycle and module

---

packages/ui/src/avatar/avatar-group.tsx

Updated the logic to render the avatars in an avatar group-
Render the count of avatars, only if the avatars are more than `max + 1`, where `max` is the number passed as prop.
Example-
1. If `max = 3`, and 4 avatars are passed, then render only 2 avatars and show a count of +2.
2. If `max = 3`, and 2 avatars are passed, then render both of the avatars. 
3. If `max = 3`, and 3 avatars are passed, then render all the 3 avatars without showing any count.

chore: update avatar group logic

---

web/components/automation/auto-archive-automation.tsx
web/components/automation/auto-close-automation.tsx
web/components/estimates/estimate-list-item.tsx
web/components/estimates/estimate-list.tsx
web/components/exporter/guide.tsx
web/components/integration/guide.tsx
web/components/integration/single-integration-card.tsx
web/components/labels/project-setting-label-group.tsx
web/components/labels/project-setting-label-list-item.tsx
web/components/labels/project-setting-label-list.tsx
web/components/project/member-list.tsx
web/components/project/project-settings-member-defaults.tsx
web/components/project/settings/delete-project-section.tsx
web/components/project/settings/features-list.tsx
web/components/states/project-setting-state-list-item.tsx
web/components/states/project-setting-state-list.tsx
web/components/ui/integration-and-import-export-banner.tsx
web/components/workspace/settings/workspace-details.tsx
web/pages/[workspaceSlug]/me/profile/activity.tsx
web/pages/[workspaceSlug]/me/profile/preferences.tsx
web/pages/[workspaceSlug]/projects/[projectId]/settings/automations.tsx
web/pages/[workspaceSlug]/projects/[projectId]/settings/features.tsx
web/pages/[workspaceSlug]/projects/[projectId]/settings/states.tsx
web/pages/[workspaceSlug]/settings/billing.tsx
web/pages/[workspaceSlug]/settings/exports.tsx
web/pages/[workspaceSlug]/settings/imports.tsx
web/pages/[workspaceSlug]/settings/members.tsx

This PR updates the border style in project and workspace settings to match our design specifications.

style: update border across workspace and project settings.

---

web/components/project/card.tsx

This PR updates the project description style in Projects as per our design.
Before:
After:

style: update project description as per design.

---

apiserver/plane/api/views/integration/slack.py

fix:
- Slack Integration on project level due to missing project_id when creating the sync object.

fix: slack project integration

---

web/components/project/form.tsx

The PR updates the font weight in project general setting as per our design.
Before:
After:

style: update font weight in project general setting section.

---

packages/ui/src/avatar/avatar.tsx
web/components/workspace/sidebar-dropdown.tsx

This PR focuses on following changes in user profile button:
* fix button alignment.
* decrease the button size.
* increase the font size.
Before:
After Changes:

style: update user profile button alignment.

---

web/components/issues/sidebar-select/label.tsx
web/components/labels/create-label-modal.tsx
web/components/labels/create-update-label-inline.tsx

This PR contains changes to throw an error while creating or updating a label to a duplicate label.
This PR fixes  [FED-761](https://app.plane.so/plane/projects/6cd3f18f-93a9-4e8b-97c8-d501c8d5543c/issues/6f1cd66c-738d-4005-a3c6-c30c7b6108df)
The changes have been added to the following locations,
* creation or updation of duplicate labels from labels page
* creation of duplicate labels in modal
* creation of duplicate labels from within the issue
After fix,

fix: Error messages for creating or updating duplicate labels

---

packages/ui/src/spinners/circular-spinner.tsx

style: 
- spinner component improvement

style: spinner component improvement

---

web/components/issues/issue-layouts/calendar/inline-create-issue-form.tsx
web/components/issues/issue-layouts/gantt/inline-create-issue-form.tsx
web/components/issues/issue-layouts/kanban/inline-create-issue-form.tsx
web/components/issues/issue-layouts/list/inline-create-issue-form.tsx
web/components/issues/issue-layouts/spreadsheet/inline-create-issue-form.tsx
web/constants/issue.ts
web/helpers/issue.helper.ts

fix: 
- quick add not working for labels & assignee

fix: quick add not working for labels & assignee

---

packages/ui/src/dropdowns/custom-search-select.tsx
packages/ui/src/dropdowns/custom-select.tsx
web/components/cycles/form.tsx
web/components/issues/form.tsx
web/components/issues/modal.tsx
web/components/issues/select/assignee.tsx
web/components/issues/select/cycle.tsx
web/components/issues/select/date.tsx
web/components/issues/select/estimate.tsx
web/components/issues/select/label.tsx
web/components/issues/select/module.tsx
web/components/issues/select/priority.tsx
web/components/issues/select/project.tsx
web/components/issues/select/state.tsx
web/components/modules/select/lead.tsx
web/components/modules/select/members.tsx
web/components/project/create-project-modal.tsx
web/components/ui/date.tsx
web/components/ui/labels-list.tsx
web/components/views/form.tsx
web/components/workspace/member-select.tsx

This PR includes modal ui consistency change and select component improvement.

style: ui consistency and improvement

---

web/components/issues/issue-layouts/empty-states/global-view.tsx
web/components/issues/issue-layouts/roots/global-view-layout-root.tsx

**fix:**
- Added empty project state in all-issues page, when no project exists, instead of empty issues state.

fix: added empty project state when no project exists.

---

web/components/issues/issue-layouts/properties/estimates.tsx
web/components/issues/issue-layouts/properties/labels.tsx
web/components/issues/issue-layouts/properties/state.tsx
web/components/issues/issue-peek-overview/properties.tsx

fix:
- Issue properties have inconsistent height
- Issue peek view border radius of start date and due date is inconsistent with other elements

fix: issue property height and peek view date picker border radius

---

web/components/modules/delete-module-modal.tsx
web/components/project/delete-project-modal.tsx
web/components/views/modal.tsx

fix:
- Toast not showing when deleting module
- Toast not showing when creating view
- Toast not showing when deleting project

fix: toast alert inconsistency

---

apiserver/plane/api/serializers/state.py
apiserver/plane/api/urls/state.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/state.py

feat:
- State list endpoint v2 without the grouping

feat: state list endpoint

---

web/components/analytics/custom-analytics/graph/index.tsx

**fix:**
Fixed the alignment of custom analytics bar graph indexes.
**Before:**
**After:**

fix: custom analytics bar graph index alignment

---

web/components/project/sidebar-list-item.tsx
web/components/workspace/sidebar-dropdown.tsx
web/components/workspace/sidebar-quick-action.tsx

This PR focuses on multiple UI Improvements in the Sidebar design.
* updated font weight and color as per designs.
* removed background color from workspace with logo.
* updated dropdown design.
Before: 
After: 
On hover:

style: sidebar UI improvements

---

web/components/integration/single-integration-card.tsx
web/components/labels/create-label-modal.tsx

* [fix: automatically focus input box in pages add label modal.](https://github.com/makeplane/plane/commit/ac094b95bbbf1ee466d8ad7b596b1cf523cdc27d)
* [style: update check icon colors to in workspace integration settings to match our design.](https://github.com/makeplane/plane/commit/03f115d6f24eb02dceb94d71ec2c9965af6430ad)
Before:
After:

fix: UI improvements.

---

apiserver/plane/api/serializers/issue.py
apiserver/plane/api/urls/issue.py
apiserver/plane/api/views/__init__.py
apiserver/plane/api/views/issue.py

feat: issues v2 endpoint

---

web/pages/[workspaceSlug]/settings/exports.tsx

This PR contains the fix for the duplicate rendering of the workspace settings layout in the exports list screen.

fix: workspace settings layout render in export

---

web/components/workspace/sidebar-dropdown.tsx

This PR addresses and resolves the redirection issue in the sidebar dropdown. Previously, when clicking on the workspace settings or my profile from dropdown, it did not close as expected.

fix: app sidebar dropdown

---

packages/ui/src/icons/priority-icon.tsx
packages/ui/src/icons/type.d.ts
web/components/inbox/issue-card.tsx
web/components/issues/issue-layouts/filters/header/filters/priority.tsx
web/components/issues/issue-layouts/kanban/headers/priority.tsx
web/components/issues/sidebar-select/priority.tsx
web/components/project/priority-select.tsx

There are 2 types of icon sets:
Type-1: With border and Urgent icon has background color treatment
Type-2: Without border and no background for Urgent icon 
- New prop " transparentBg " added to priority icon / ui component to handle above use cases
- If prop is false (default),  Type-1 will be rendered
- If prop is true, Type-2 will be rendered
- Reflect changes to all places where priority icon is getting shown.

Standardising priority icons across the platform

---

packages/ui/src/dropdowns/custom-menu.tsx

This PR fixes issue with delete popup not closing by resolving custom menu item closure.
Before Fix:
https://github.com/makeplane/plane/assets/33979846/5c92702b-32fd-41c2-9893-87485c3ade63
After Fix:
https://github.com/makeplane/plane/assets/33979846/234cdab4-e9a0-4cb9-b248-00ba9ed01183

Fix: Custom menu item not automatically closing, affecting delete popup behavior.

---

web/components/workspace/sidebar-dropdown.tsx

This PR includes improvement for workspace sidebar dropdown.
Before: 
After:

fix: workspace setting dropdown improvement

---

web/pages/_error.tsx

chore: update exception detected screen action button

---

packages/editor/document-editor/src/ui/components/page-renderer.tsx
web/components/pages/create-update-page-modal.tsx
web/components/pages/page-form.tsx
web/components/pages/pages-list/recent-pages-list.tsx
web/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx
web/pages/[workspaceSlug]/projects/[projectId]/pages/index.tsx
web/store/page.store.ts
web/types/pages.d.ts

**Bug fixes-**
1. Pages editor clickable only on the space occupied by the text.
2. Create/update page modal getting reset even before the page gets created/updated.
**Improvements-**
1. Recent pages computed function logic to calculate pages for `Today`, `Yesterday`, `This week` and `Older`.
2. Pages store computed functions to return undefined if pages are not present for a particular project.

fix: complete pages editor not clickable, recent pages calculation logic

---

packages/editor/document-editor/src/ui/components/page-renderer.tsx
packages/editor/document-editor/src/ui/components/summary-popover.tsx
packages/editor/document-editor/src/ui/index.tsx
packages/editor/document-editor/src/ui/readonly/index.tsx
web/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx

**Improvements-**
1. Include the lateral white space in the page scroll area
https://github.com/makeplane/plane/assets/65252264/410d9285-145f-4294-a00c-9da4961df936
****
2. Add bottom padding for better visibility of content
****
3. Added a spinner loader

fix: page details scroll area

---

web/components/issues/sidebar-select/state.tsx

This PR addresses the overflow problem in the issue peek overview state select dropdown when the state name is longer.

[FED-886] fix: issue peek overview state select dropdown 

---

web/components/command-palette/command-pallette.tsx

This PR contains a fix for the problem of modals overlapping. Previously, when one modal was open and we triggered a shortcut key for another modal, they overlap.

[FED-867] fix:modal overlapping issue

---

web/components/cycles/sidebar.tsx
web/components/modules/sidebar.tsx

- By default cycle & module sidebar progress panel will be open.

fix: progress panel default open

---

web/layouts/user-profile-layout/layout.tsx

**Before-**  User role was earlier fetched using `useSWR`.
https://github.com/makeplane/plane/assets/65252264/771ddcae-d343-4f3e-805a-ac35c7b3ef22
****
**After-** Using the user role from the user store.
https://github.com/makeplane/plane/assets/65252264/e6ed6d05-bdd2-4d30-a401-a5d4db014d69

fix: profile layout flicker

---

deploy/selfhost/docker-compose.yml

removed container names for selfhosting

removed container names for selfhosting

---

web/components/issues/issue-layouts/gantt/base-gantt-root.tsx
web/components/workspace/send-workspace-invitation-modal.tsx
web/components/workspace/settings/members-list-item.tsx
web/components/workspace/settings/members-list.tsx
web/components/workspace/settings/workspace-details.tsx
web/constants/workspace.ts
web/layouts/settings-layout/workspace/sidebar.tsx
web/pages/[workspaceSlug]/settings/api-tokens.tsx
web/pages/[workspaceSlug]/settings/billing.tsx
web/pages/[workspaceSlug]/settings/exports.tsx
web/pages/[workspaceSlug]/settings/imports.tsx
web/pages/[workspaceSlug]/settings/integrations.tsx
web/pages/[workspaceSlug]/settings/members.tsx
web/store/workspace/workspace-member.store.ts
web/types/workspace.d.ts

**Page-wise authorization-**
1. General-
- Anyone can view the page.
- Only admins can edit and delete the workspace
2. Members-
- Anyone can view the page.
- Only members and admins can add new members.
- Only admins can remove existing members. 
- Anyone can leave the workspace.
- Users cannot add a new member with a role higher than theirs.
3. Billing and plans-
- Only admins can view the page.
4. Integrations-
- Only admins can view the page.
5. Imports-
- Only admins can view the page.
6. Exports-
- Only members and admins can view the page and export issues.
7. Webhooks-
- Only admins can view the page.
8. API tokens-
- Only admins can view the page.

fix: workspace settings pages authorization

---

web/components/account/email-code-form.tsx
web/components/account/google-login.tsx

- Added alignment to Google auth button content.
- Added responsiveness to sign-in heading paragraph text.
**When a Google account exists:**
**When a Google account doesn't exist:**

fix: google auth button content alignment

---

web/components/issues/issue-layouts/kanban/default.tsx
web/components/issues/issue-layouts/kanban/quick-add-issue-form.tsx
web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx

This fixes the positioning of the quick add for kanban and speadsheet view.
Before:
After:

fix: quick add positioning

---

web/components/issues/issue-layouts/kanban/properties.tsx
web/components/issues/issue-layouts/list/properties.tsx
web/components/issues/issue-layouts/properties/assignee.tsx
web/components/issues/issue-layouts/properties/labels.tsx
web/components/issues/issue-layouts/properties/state.tsx
web/components/issues/issue-layouts/spreadsheet/columns/assignee-column.tsx
web/components/issues/issue-layouts/spreadsheet/columns/label-column.tsx
web/components/issues/issue-layouts/spreadsheet/columns/state-column.tsx
web/store/project/project-label.store.ts

In this pull request, we've addressed an issue related to the rendering of workspace-level labels, members, and states in the project view.

fix: corrected rendering of workspace-level labels, members, and states in project view

---

web/components/core/image-picker-popover.tsx
web/components/issues/issue-layouts/properties/assignee.tsx
web/components/issues/issue-layouts/spreadsheet/spreadsheet-column.tsx
web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
web/components/issues/issue-peek-overview/properties.tsx
web/components/issues/sidebar.tsx
web/constants/spreadsheet.ts

- style: spreadsheet view title is missing icons from figma
- style: fixing inconsistent icons
- style: Issue empty assignee logo should be changed to cycle list empty assignee logo
- style: fix Image picker upload tab buttons are cutted in half

style: image picker, spreadsheet view title, icons

---

web/components/onboarding/invitations.tsx
web/pages/invitations/index.tsx
web/pages/onboarding/index.tsx

**FIXES:**
1. Empty invitation state flickering on accepting the only invitation
2. Onboarding STEP 1 should be skipped after accepting an invite from email.
3. From `/invitations` user should be redirected to `/onboarding` if onboarding is not completed.

chore: email invite accept validation

---

.github/workflows/codeql.yml

Hello from [GitHub Security Lab](https://securitylab.github.com/)!
Your repository is critical to the security of the Open Source Software (OSS) ecosystem, and as part of our mission to make OSS safer, we are contributing a [CodeQL configuration for code scanning](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning-for-a-repository#setting-up-code-scanning-manually) to your repository. By enabling code scanning with CodeQL, you will be able to continuously analyze your code and surface potential vulnerabilities [before they can even reach your codebase](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/triaging-code-scanning-alert …

feat: add CodeQL workflow

---

web/components/analytics/custom-analytics/graph/custom-tooltip.tsx

fix: custom analytic grouped bar tooltip value as ID

---

web/components/instance/email-form.tsx
web/pages/god-mode/authorization.tsx

1. Disabled magic link toggle option from **SSO and OAuth** settings.
2. Removed SSL toggle option from **Email** settings.

chore: remove unused fields from the god mode

---

web/components/issues/peek-overview/properties.tsx
web/store/issues/project-issues/cycle/issue.store.ts
web/store/issues/project-issues/module/issue.store.ts

1. Unable to update cycle and module of an issue from the peek overview.
2. Estimates field is displayed in the peek overview even if it is disabled for the project.
1. Updated the cycle and module store logic to add/update cycle and module of an issue.
2. Conditionally render the estimates field.

[FED-1116] bug: cycle and module change not working from the peek overview

---

apiserver/Dockerfile.dev
apiserver/plane/app/views/config.py
apiserver/plane/app/views/oauth.py
apiserver/plane/app/views/user.py
apiserver/plane/license/api/views/instance.py

- user cannot deactivate himself if he is an instance admin and the only admin for the instance.
- remove logic for auto assigning of user to workspace and project if the email is different from `captain@plane.so`.

fix: user deactivation if instance admin and remove auto assigning of user on workspace and project

---

web/components/issues/issue-layouts/calendar/base-calendar-root.tsx
web/components/issues/issue-layouts/calendar/roots/cycle-root.tsx
web/components/issues/issue-layouts/calendar/roots/module-root.tsx
web/components/issues/issue-layouts/calendar/roots/project-root.tsx
web/components/issues/issue-layouts/calendar/roots/project-view-root.tsx
web/components/issues/issue-layouts/gantt/quick-add-issue-form.tsx
web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
web/store/issues/base-issue-calendar-helper.store.ts

1. Calendar layout drag & drop for **GUEST/VIEWER** roles, not showing failed toast.
2. Kanban layout drag & drop for **GUEST/VIEWER** roles, not showing failed toast.

chore: error handling for user permission while issue drag & drop

---

space/components/accounts/github-sign-in.tsx
space/components/accounts/google-sign-in.tsx
space/components/accounts/index.ts
space/components/accounts/sign-in-forms/o-auth-options.tsx
space/components/common/latest-feature-block.tsx
web/components/account/github-sign-in.tsx
web/components/account/google-sign-in.tsx
web/components/account/index.ts
web/components/account/sign-in-forms/o-auth-options.tsx
web/components/common/latest-feature-block.tsx
web/components/workspace/sidebar-quick-action.tsx

1. Latest features image has a different background color in light mode.
2. OAuth buttons alignment issue.
1. FIxed the different background colors using `resolvedTheme` from the `next-themes` package.
2. Gave a fixed width to the Google sign in button according to the container width.
1. Updated the file names of the Google and GItHub sign-in buttons.
2. Fixed the hydration error due to the `ChevronDown` icon from `lucide-react`.

style: update OAuth buttons UI in the web and space apps

---

apiserver/plane/app/views/oauth.py

- oauth configuration check at medium level instead of global level so even if one is configured it should not throw error.

fix: oauth configuration check

---

web/components/cycles/form.tsx
web/components/issues/form.tsx
web/components/issues/issue-layouts/kanban/properties.tsx
web/components/issues/issue-layouts/list/properties.tsx
web/components/issues/issue-layouts/properties/assignee.tsx
web/components/issues/issue-layouts/properties/date.tsx
web/components/issues/issue-layouts/properties/labels.tsx
web/components/issues/issue-layouts/spreadsheet/columns/label-column.tsx
web/components/issues/select/project.tsx
web/components/issues/view-select/due-date.tsx
web/components/issues/view-select/start-date.tsx
web/constants/spreadsheet.ts

1. Icons are inconsistent for the issue properties.
2. Issue title getting reset on project change in the create issue modal.
1. Updated the icons for the following properties for all the layouts- `Labels`, `Assignees`, `Start date`, and `Target date`.
2. Removed unnecessary dependency from the `useEffect` which caused a reset of the issue form.
1. New property icons-
2. Issue modal fix-
https://github.com/makeplane/plane/assets/65252264/c81d8423-0199-4bfa-a1ac-57dcbae5e894
1. Show only joined projects in the project dropdown of the create issue modal.

fix: icon consistency for issue properties

---

web/components/issues/issue-layouts/spreadsheet/columns/assignee-column.tsx
web/components/issues/issue-layouts/spreadsheet/columns/attachment-column.tsx
web/components/issues/issue-layouts/spreadsheet/columns/created-on-column.tsx
web/components/issues/issue-layouts/spreadsheet/columns/due-date-column.tsx
web/components/issues/issue-layouts/spreadsheet/columns/estimate-column.tsx
web/components/issues/issue-layouts/spreadsheet/columns/label-column.tsx
web/components/issues/issue-layouts/spreadsheet/columns/link-column.tsx
web/components/issues/issue-layouts/spreadsheet/columns/priority-column.tsx
web/components/issues/issue-layouts/spreadsheet/columns/start-date-column.tsx
web/components/issues/issue-layouts/spreadsheet/columns/state-column.tsx
web/components/issues/issue-layouts/spreadsheet/columns/sub-issue-column.tsx
web/components/issues/issue-layouts/spreadsheet/columns/updated-on-column.tsx
web/components/issues/issue-layouts/spreadsheet/spreadsheet-column.tsx

fix: spreadsheet layout sub issues overlapping

---

web/pages/profile/activity.tsx
web/pages/profile/change-password.tsx

**Problems:**
- password change redirection in the profile setting sidebar wasn't functioning.
- profile redirection in the Profile activity section was also not working properly.
- There were issues with the redirection logic which have now been addressed.
- Previously, the code expected Workspace slug from the router, resulting in an undefined slug. The code has been updated to retrieve the slug from the activity_item.

chore: profile setting bug fixes

---

web/components/labels/project-setting-label-group.tsx
web/components/labels/project-setting-label-list.tsx

1. Dropping a label into a child label made the dragged label disappear.
1. Disabled combining labels inside a group.
Before fix:
https://github.com/makeplane/plane/assets/65252264/5e7a7601-8f89-4dca-b872-0b07f0b214db
After fix:
https://github.com/makeplane/plane/assets/65252264/769ec15f-ef98-4c5c-aff7-7cb0eedfdf84

fix: disable label combining for labels inside a group

---

web/components/issues/issue-layouts/quick-action-dropdowns/cycle-issue.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/module-issue.tsx

1. When editing an issue inside a cycle or a module, the cycle/module details were not being pre-filled in the issue modal.
1. Fixed it by passing the cycle/module id from the router along with other issue details.

fix: pre-fill cycle and module details when editing an issue

---

web/services/api.service.ts

1. Access and refresh tokens getting removed from the cookies on closing the browser.
1. Set an expiry of 30 days for the tokens while setting them.

chore: set an expiry of 30 days for the access and refresh tokens

---

web/components/issues/issue-layouts/gantt/base-gantt-root.tsx
web/components/issues/issue-layouts/gantt/cycle-root.tsx
web/components/issues/issue-layouts/gantt/module-root.tsx

1. Unable to update an issue from the peek overview in the Gantt layout.
1. Added the missing update issue handler to the `base-gantt-root` component.
1. Removed hardcoded `router.query` type declarations from cycle and module gantt roots.

fix: gantt issues not getting updated

---

web/components/analytics/project-modal/modal.tsx

1. Analytics modal's size not changing when switching from full screen to side peek mode.
1. Moved the size logic from `headlessui`'s `Dialog.Panel` to the `div` tag.
Before fix-
https://github.com/makeplane/plane/assets/65252264/63111c9a-81c8-488d-b27c-6f52d283b2db
****
After fix-
https://github.com/makeplane/plane/assets/65252264/ef108b9d-83c6-461c-b31d-a91ee0bc2d03

[FED-1185] fix: analytics modal's size not changing when switching between modes

---

apiserver/plane/urls.py

fix: debug toolbar import error when running in production settings with `DEBUG=1`

fix: debug tool bar import

---

space/components/accounts/sign-in-forms/self-hosted-sign-in.tsx
web/components/account/sign-in-forms/self-hosted-sign-in.tsx

1. Self-hosted instances' sign in form button text.
1. Updated the button text to `Continue`.

chore: update self hosted sign in form cta in the web and space apps

---

web/components/headers/cycle-issues.tsx
web/components/headers/module-issues.tsx
web/components/headers/project-issues.tsx
web/components/workspace/sidebar-menu.tsx
web/components/workspace/sidebar-quick-action.tsx

This PR include following changes: 
- Analytics option removed from app sidebar for user with guest & viewer permission.
- In sidebar add issue option removed for user with guest & viewer permission.
- Analytics button removed from app header for user r with guest & viewer permission.
---

chore: analytics permission validation added

---

web/components/cycles/active-cycle-details.tsx
web/store/cycle/cycles.store.ts

**Problem:**
1. If there are more than 0 cycles, and no active cycle exists, then the active cycle section has infinite loading.
2. If the active cycle gets deleted, then the UI of the active cycle section is not updated until the page is manually refreshed.
**Solution:**
1. Used SWR `isLoading` parameter to modify the loading condition of the page.
2. Removed the deleted cycle from the store's data also.

fix: cycle delete & active cycle loading

---

web/components/issues/issue-layouts/spreadsheet/columns/assignee-column.tsx
web/components/issues/issue-layouts/spreadsheet/columns/attachment-column.tsx
web/components/issues/issue-layouts/spreadsheet/columns/created-on-column.tsx
web/components/issues/issue-layouts/spreadsheet/columns/due-date-column.tsx
web/components/issues/issue-layouts/spreadsheet/columns/estimate-column.tsx
web/components/issues/issue-layouts/spreadsheet/columns/label-column.tsx
web/components/issues/issue-layouts/spreadsheet/columns/link-column.tsx
web/components/issues/issue-layouts/spreadsheet/columns/priority-column.tsx
web/components/issues/issue-layouts/spreadsheet/columns/start-date-column.tsx
web/components/issues/issue-layouts/spreadsheet/columns/state-column.tsx
web/components/issues/issue-layouts/spreadsheet/columns/sub-issue-column.tsx
web/components/issues/issue-layouts/spreadsheet/columns/updated-on-column.tsx
web/components/issues/issue-layouts/spreadsheet/spreadsheet-column.tsx
web/hooks/use-sub-issue.tsx

**Problem:**
1. In the spreadsheet layout when expanding for sub-issues, the hover effect is applied to the parent issue as well.
2.  In the spreadsheet sub-issues property change is getting applied to the parent issue.
**Solution:**
1. Removed the hover effect from the outer component, and moved it to the inner component.
2. Removed default parent issue object parameter to update function, and now took the issue object from the child component.
**Before:**
https://github.com/makeplane/plane/assets/94619783/3040361e-ad71-47f1-a156-46e3c3556692
**After:**
https://github.com/makeplane/plane/assets/94619783/ebe36c0b-bf87-41f1-a317-779448a4c5bf

fix: spreadsheet layout sub-issues property update

---

README.md

The links to self-hosting docs in README were redirecting to an incomplete path, fixed it.

Fix: update self-host docs link in README

---

apiserver/plane/app/views/project.py
apiserver/plane/app/views/workspace.py

Problem:
- Users couldn't rejoin a project after leaving, only when invited back.
- Viewer cannot leave the project.
Solution:
- Now, users can successfully rejoin projects upon receiving an invite.
- Viewer can also leave a project

chore: workspace project reinvite 

---

CONTRIBUTING.md
apiserver/Dockerfile.dev
apiserver/bin/takeoff.local
docker-compose-local.yml
nginx/Dockerfile.dev
nginx/nginx-single-docker-image.conf
nginx/nginx.conf.dev
setup.sh
space/Dockerfile.dev
web/Dockerfile.dev

- remove environment configuration from local docker compose
- remove environment from `setup.sh`
- update contributing.md with new local setup
Fixes #3103

fix: environment file missing for space

---

web/components/cycles/sidebar.tsx
web/components/modules/sidebar-select/select-lead.tsx
web/components/modules/sidebar-select/select-members.tsx
web/components/modules/sidebar.tsx

**Problems related to cycle/module sidebar:**
1. The date range picker (in both the cycle & module sidebar) was showing the range with the current date if the start/end date was not selected.
2. The local state date before updating to API, was not shown in the sidebar.
3. The date range picker (in both the cycle & module sidebar) hover cursor was `cursor-default.`
4. The `lead/member` select popover in the module sidebar, hover cursor was `cursor-default`.
5. The `lead/member` select popover in the module sidebar, can be accessible by `viewer/guest`.
**Solution:**
1. Now, showing range only when either the `start/end` date is defined.
2. Now, rendering the local state date as soon as we select any date, with the help of form data.
3. Changed the  `cursor-default` to `cursor-pointer`.
4. …

fix: cycle & module sidebar date range picker

---

web/components/issues/issue-layouts/empty-states/cycle.tsx
web/components/issues/issue-layouts/empty-states/module.tsx

Users with viewer and guest roles were able to use the `add new or existing issue` functionality in cycle and modules empty state resulting in receiving error toast messages. 
Disabled both buttons for User with Viewer or Guest Role.

chore: `add new or existing issues` validation for guest & viewers in cycles and modules empty state.

---

web/constants/project.ts
web/helpers/state.helper.ts
web/store/project/project-state.store.ts

This PR includes fix for the sequence of state ordering in kanban and list layout.

chore: state ordering sequence in kanban and list layout

---

web/constants/swr-config.ts
web/lib/app-provider.tsx
web/store/issues/project-issues/cycle/filter.store.ts
web/store/issues/project-issues/module/filter.store.ts
web/store/issues/project-issues/project-view/filter.store.ts

1. Hitting `GET` requests in the catch blocks resulting in an infinite loop of API calls.
1. Remove all the `GET` requests from the catch blocks.
1. Added global SWRConfig with the following options-
- `refreshWhenHidden: false`
- `revalidateIfStale: false`
- `errorRetryCount: 3`

fix: remove get requests from the catch block

---

web/components/core/modals/link-modal.tsx

The current link modal lacks validation for accepted link formats, causing potential issues when handling links entered by users.
Implemented validation logic to accept only 'http://' and 'https://' in the link modal.

chore: link modal validation

---

web/constants/issue.ts

In issue layout when order by is set as priority its showing priority order in reverse.
To address this, I corrected it by modifying the parameter from "priority" to "-priority." I've included a preview for your reference.

chore: priority sorting order

---

apiserver/plane/app/serializers/__init__.py
apiserver/plane/app/serializers/project.py
apiserver/plane/app/serializers/workspace.py
apiserver/plane/app/urls/workspace.py
apiserver/plane/app/views/__init__.py
apiserver/plane/app/views/project.py
apiserver/plane/app/views/workspace.py

- Updated the workspace member endpoint payload by modifying the ID, member details, and roles.
- Adjusted the project member list endpoint payload to include member IDs, user IDs, and roles.
- Additionally, introduced a new endpoint to retrieve all projects associated with a user's membership.

feat: workspace and project members endpoint

---

web/pages/profile/activity.tsx
web/pages/profile/change-password.tsx
web/pages/profile/index.tsx
web/pages/profile/preferences.tsx

1. Profile settings pages have an unnecessary scroll even if the content occupies less height than the screen.
1. Replaced `margin-top` of the container with `padding-top`.
Before fix-
https://github.com/makeplane/plane/assets/65252264/3398879f-5ce3-4119-b4e8-bb781a2c9a91

fix: unnecessary overflow in the profile settings layout

---

web/components/issues/form.tsx

**Problem:**
- In the create issue modal, the project is getting selected & deselected in a second.
**Solution:**
- updated the `project ID` of form values in useEffect.

fix: create issue modal project deselecting

---

web/components/core/sidebar/sidebar-progress-stats.tsx
web/components/cycles/sidebar.tsx
web/components/modules/sidebar.tsx

The Filter options for `Assignee` and `Lables` were not working in cycles and modules sidebar. The implementation was commented out during the previous refactor.
Added proper implementation for updating the filters in the module and cycle sidebar. Also disabled the filter option if the cycle is completed.
https://github.com/makeplane/plane/assets/33979846/67ae6f0d-a717-46e2-a879-84e91c61fdee
https://github.com/makeplane/plane/assets/33979846/101337eb-d636-4bbe-9e4a-0c94ae296b43

fix: issue with `cycle` and `module` sidebar filter implementation.

---

web/components/core/modals/bulk-delete-issues-modal.tsx
web/components/issues/issue-layouts/roots/archived-issue-layout-root.tsx
web/components/issues/issue-layouts/roots/cycle-layout-root.tsx
web/components/issues/issue-layouts/roots/draft-issue-layout-root.tsx
web/components/issues/issue-layouts/roots/module-layout-root.tsx
web/components/issues/issue-layouts/roots/project-layout-root.tsx
web/components/issues/issue-layouts/roots/project-view-layout-root.tsx
web/layouts/auth-layout/project-wrapper.tsx
web/layouts/auth-layout/user-wrapper.tsx
web/layouts/auth-layout/workspace-wrapper.tsx
web/store/archived-issues/issue.store.ts
web/store/cycle/cycle_issue.store.ts
web/store/issue/issue.store.ts
web/store/issues/project-issues/archived/issue.store.ts
web/store/issues/project-issues/cycle/issue.store.ts
web/store/issues/project-issues/draft/issue.store.ts
web/store/issues/project-issues/module/issue.store.ts
web/store/issues/project-issues/project-view/issue.store.ts
web/store/issues/project-issues/project/issue.store.ts
web/store/module/module_issue.store.ts
web/store/profile-issues/issue_filters.store.ts

1. If a user doesn't have access to a workspace/project, API calls to fetch workspace/project related data were still being made.
1. Added `hasPermissionToWorkspace` flag to all the API calls in the workspace wrapper and `autorun` of workspace stores to check for permission before making the request.
2. Added `hasPermissionToProject` flag to all the API calls in the project wrapper and `autorun` of project stores to check for permission before making the request.
1. Removed type declarations for `router.query` at the declaration level.
2. Use `useSWRImmutable` to fetch user's instance admin status, disabling revalidation.

chore: disable API calls for un-authorized users

---

web/components/core/sidebar/links-list.tsx
web/components/issues/attachment/attachments.tsx
web/components/issues/description-form.tsx
web/components/issues/issue-layouts/calendar/issue-blocks.tsx
web/components/issues/issue-layouts/kanban/block.tsx
web/components/issues/main-content.tsx
web/components/issues/peek-overview/issue-detail.tsx

**Problems:**
1. The `viewer/guest` was able to interact with the issue `title/description`.
2. The `viewer/guest` could see the remove issue attachment option.
3. The `viewer/guest` could drag `kanban/calendar` blocks.
4. The `viewer/guest` is not able to see the `module/issue sidebar` links.
**Solution:**
- Added role validation at all the places.

chore: role restriction to issue detail & peek-overview

---

web/components/project/create-project-modal.tsx
web/components/project/form.tsx

This PR Fixes https://github.com/makeplane/plane/issues/2139
**Problem:**
- Project identifier rules are not consistent in the platform, somewhere shows 12 somewhere 5 characters limit.
**Solution:**
- Made it consistent with at most 6 characters long.
**Before:**
**After:**

chore: made project-identifier rule consistent

---

web/styles/globals.css

Firefox doesn't support prefixed versions of `writing-mode`:
We can add an unprefixed version though. This way it does work as intended:

Fix .vertical-lr in Firefox

---

web/components/issues/issue-layouts/calendar/issue-blocks.tsx
web/components/issues/issue-layouts/gantt/blocks.tsx
web/components/issues/issue-layouts/kanban/block.tsx
web/components/issues/issue-layouts/list/block.tsx
web/components/issues/issue-layouts/properties/assignee.tsx
web/components/issues/issue-layouts/properties/date.tsx
web/components/issues/issue-layouts/properties/estimates.tsx
web/components/issues/issue-layouts/properties/labels.tsx
web/components/issues/issue-layouts/properties/state.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/all-issue.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/archived-issue.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/cycle-issue.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/module-issue.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx
web/components/issues/issue-layouts/spreadsheet/columns/issue/issue-column.tsx
web/components/issues/issue-layouts/spreadsheet/columns/state-column.tsx
web/components/issues/peek-overview/view.tsx
web/components/issues/sub-issues/issue.tsx
web/components/project/priority-select.tsx

- Clicking on an issue didn't open it in a new tab.
- Only a part of the issue card was clickable, limiting user interaction.
- Users had to manually close the issue peek overview.
- Inability to open the issue peek overview for other issues while one was already open.
- Enabled opening issues in new tabs with Control Click.
- Expanded clickable area for the entire issue card for improved interaction.
- Integrated an outside click detector for the issue peek overview.
- Implemented quick switching functionality for issue peek overviews.
- Removed unused variables.
- Code Refactor.

chore: issue click & peek overview improvement

---

web/components/issues/issue-layouts/calendar/base-calendar-root.tsx
web/components/issues/issue-layouts/gantt/base-gantt-root.tsx
web/components/issues/issue-layouts/gantt/cycle-root.tsx
web/components/issues/issue-layouts/gantt/module-root.tsx
web/components/issues/issue-layouts/gantt/project-root.tsx
web/components/issues/issue-layouts/gantt/project-view-root.tsx
web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
web/components/issues/issue-layouts/list/base-list-root.tsx
web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
web/components/issues/peek-overview/root.tsx
web/components/issues/sub-issues/issue.tsx
web/components/issues/sub-issues/issues-list.tsx
web/components/issues/sub-issues/root.tsx
web/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx

**Problem:**
- Issue delete operation was not working from peek-overview.
**Solution:**
- Updated `handleIssue` callback in all the layouts.
- Added issue `update/delete` operation for `cycles/module/views` issues in Gantt layout.

fix: issue peek-overview delete functionality

---

apiserver/plane/app/views/project.py

- avoid sending request to s3 when minio is configured for the public covers and also update the path according to the domain and protocol configured.

fix: project cover endpoint

---

web/components/common/new-empty-state.tsx
web/components/issues/issue-layouts/empty-states/project.tsx
web/components/modules/modules-list-view.tsx
web/components/modules/sidebar.tsx
web/components/page-views/workspace-dashboard.tsx
web/components/pages/pages-list/list-view.tsx
web/components/pages/pages-list/recent-pages-list.tsx
web/components/project/card-list.tsx
web/components/views/views-list.tsx
web/components/workspace/views/header.tsx
web/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx

Multiple `Add [Issue/ Project/ Views/ Pages/ Link]` buttons were accessible to users with role of `guest or viewer` which was resulting in error messages when user tries access those buttons.
Added user role validation in all the places so that the button remain hidden from the guests/ viewers. 
These Buttons are removed for guests and viewers:

User role validation across workspace and projects.

---

web/components/instance/email-form.tsx

In this PR, I have added the `Email From Address` field in the Instance Admin Email Settings.

chore: add `email from address` in Instance Admin Email Settings.

---

web/components/issues/select/cycle.tsx
web/store/issues/global/issue.store.ts
web/store/issues/project-issues/cycle/issue.store.ts
web/store/issues/project-issues/draft/issue.store.ts
web/store/issues/project-issues/module/issue.store.ts
web/store/issues/project-issues/project-view/issue.store.ts
web/store/issues/project-issues/project/issue.store.ts

**Problem:**
1. on issue property update, `updated_at` is not updating.
2. in create issue modal, on changing the project, the cycle list was not updating.
**Solution:**
1. updated the issue in `store`, after the API call.
2. updating `cycle_list` with cycles of updated project.

fix: bug fixes & improvements

---

web/components/headers/cycle-issues.tsx
web/components/headers/module-issues.tsx
web/components/issues/issue-layouts/roots/cycle-layout-root.tsx
web/components/issues/select/cycle.tsx
web/components/issues/sidebar-select/module.tsx

The PR focuses on refactoring the code to use new cycle and modules store.

chore: use new cycle and module store.

---

web/components/issues/issue-layouts/calendar/roots/cycle-root.tsx
web/components/issues/issue-layouts/calendar/roots/module-root.tsx
web/components/issues/issue-layouts/gantt/cycle-root.tsx
web/components/issues/issue-layouts/gantt/module-root.tsx
web/components/issues/issue-layouts/kanban/roots/cycle-root.tsx
web/components/issues/issue-layouts/kanban/roots/module-root.tsx
web/components/issues/issue-layouts/list/roots/cycle-root.tsx
web/components/issues/issue-layouts/list/roots/module-root.tsx
web/components/issues/issue-layouts/spreadsheet/roots/cycle-root.tsx
web/components/issues/issue-layouts/spreadsheet/roots/module-root.tsx
web/components/issues/modal.tsx

When users execute any action on the Module & Cycle Page, the sidebar fails to update accordingly.
Address this issue by fetching module or cycle details after performing an action within the module and cycle pages.
[[PLE-105]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/7035c9d2-21f0-4b59-8d52-36e074db55e3)

chore: cycle and module sidebar mutation fix

---

web/components/page-views/workspace-dashboard.tsx
web/components/project/card-list.tsx

**Problem:**
- Admin & Member role not able access create project button in `dashboard` & `/projects` screen empty state.
**Solution:**
- Modified the condition used for role checking, and updated it with the `workspace role`.

fix: role authorization for create project button in project empty state

---

web/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx

- Fixes https://github.com/makeplane/plane/issues/3120
1. This PR adds fix to the duplicate_page function of the PageDetailsPage component, which allows users to duplicate a page even before they start typing in the editor i.e. if the current page's form does not have a `description_html` value yet i.e. on initialisation, it will be set to the default value from the pageDetails object fetched from the backend via SWR. The `formData` object is updated with the necessary values for duplication, including the new/updated page name and description.
2. Additionally to fix the patch call not being made on typing, the handleSubmit dependency of `pageDetails` is included in the useEffect hook to ensure proper form submission such that the `name` field is always updated for the `updatePage` …

fix: Resolved page not saving/not copying contents bug

---

web/components/common/new-empty-state.tsx
web/components/issues/issue-layouts/kanban/quick-add-issue-form.tsx
web/components/issues/modal.tsx

- When discarding an issue with an empty string or spaces from the create issue modal, it was incorrectly triggering draft issue confirmation modal. [[PLE-109]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/d729f7b3-31b0-4b0f-a103-af044f90712b)
- The Empty State page experienced a scroll issue, preventing the full display of its content. [[PLE-108]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/ecbb4550-062b-4d76-9a89-33d0e17ee2bb)
- When adding issues quickly in the Kanban layout, the width allocation for the input was insufficient. [[PLE-115]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/92fa6bd0-0c33-43be-a7bd-c7b9eea8e12b)
- Implemented validation in the saving process if the issue …

chore: bug fixes & improvement

---

web/components/profile/sidebar.tsx
web/components/workspace/send-workspace-invitation-modal.tsx

Problem:
1. Workspace invitation modal form values were not resetting after the invitation.
2. The user avatar in the profile sidebar, should contain the first letter of `first_name`, not the display name.
Solution:
1. Explicitly resetting the values.
2. replaced the first letter of `display_name` with `first_name`.

fix: bugs & improvements

---

web/components/project/create-project-modal.tsx

chore: allow non-latin characters to project identifier

---

web/lib/wrappers/posthog-wrapper.tsx

This PR contains the fix for PostHog events which are not getting triggered in staging and production.

fix: posthog events trigger in staging

---

packages/editor/core/src/styles/editor.css
packages/editor/core/src/ui/plugins/upload-image.tsx
packages/editor/extensions/src/extensions/slash-commands.tsx

This PR solves two issues: 
1. Fixes the bug where image was not being inserted in the cursor's current position.
2. Fixes CSS issues with Images during insert (content shift)
Also added better typescript support for Suggestions in Slash Command.

[fix] Image insertion position at cursor position and Updated placeholder text.

---

web/helpers/theme.helper.ts

New users encounter an application error when they attempt to switch to a custom theme. To reproduce this issue:
- Access profile settings.
- Navigate to preferences and select a custom theme, then reload or change the navigation.
The problem occurs from a recent code refactoring, causing the removal of necessary default values. I've rectified this by implementing a validation: if no palette is available, the theme won't be applied.
These issues are associated with [[PLE-154]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/c7eb51e0-721f-472e-9a80-389066136285)

fix: custom theme validation added

---

packages/editor/core/src/ui/extensions/index.tsx
web/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx

- Set the `revalidate` option to `false` in the `commonSwrOptions` object to fix issues with Locking, Archiving, etc.
- Add an `useEffect` hook that calls the `mutatePageDetails` function with specific options as temporary fix to update cache.
- Inside the `useEffect` hook, set `revalidate` to `true`, `populateCache` to `true` to update cache on component mount and define a rollback function for error handling.
- Added code support for `` markdown syntax

🔧 fix: Pages mutation on component mount

---

apiserver/plane/api/serializers/issue.py
apiserver/plane/api/serializers/module.py
apiserver/plane/api/views/issue.py
apiserver/plane/api/views/module.py

This PR resolve the issues mentioned in the #3238 
- project id and workspace id are passed as the context in the serializers so that the state of the issue can be updated.

fix: external api serializer

---

apiserver/plane/app/serializers/estimate.py
apiserver/plane/app/views/estimate.py
apiserver/plane/app/views/search.py
apiserver/plane/bgtasks/issue_activites_task.py
web/components/estimates/create-update-estimate-modal.tsx

This PR resolves the following issues:
**Backend:**
- Implemented a validation for estimate points, limiting the value to a maximum of 20 characters.
- Enforced that the sequence ID accepts only whole numbers, excluding decimals (in the search endpoint).
- Included a validation to verify the issue's parent ID.
**Frontend:**
- Added validation while creating/updating estimates, if estimate point characters are more than 20 characters, then toast will be shown with this message:  `Estimate point cannot have more than 20 characters.`

chore: estimates and issue parent id fixes

---

web/components/project/sidebar-list-item.tsx
web/components/workspace/issues-stats.tsx
web/components/workspace/sidebar-dropdown.tsx

**Problem:** 
Some of the redirections are not working as links instead working as buttons to redirect the user to different pages.
Replacing all button click editions with nextjs link tags to enables the browser functionalities like copy address

fix: replacing onclick redirections with link tag.

---

web/components/auth-screens/not-authorized-view.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/archived-issue.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/cycle-issue.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/module-issue.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx
web/hooks/use-sign-in-redirection.ts
web/hooks/use-user-auth.tsx
web/hooks/use-user.tsx
web/layouts/auth-layout/user-wrapper.tsx
web/pages/onboarding/index.tsx

- Experiencing a redirection loop problem while signing up with a new email. To replicate:
- Sign up using a new email address.
- Enter a unique code as prompted.
- Proceed to the "Set Up Workspace" feature.
- The copy issue link is malfunctioning.
- Inconsistent use of "next_url" and "next_path" in various locations.
- Lack of validation for the "next_path" URL poses a significant security vulnerability.
- Removed unnecessary hooks from the onboarding page, potentially eliminating the infinite loop & Implemented a try-catch block in the 'handleSignInRedirection' function for additional error handling.
- Rectify the copy issue link by removing the extra slash at the beginning.
- Ensure consistency by standardizing all references to "next_path."
- Implement validation for "next_path" …

fix: onboarding redirection loop and bug fixes

---

web/components/issues/sidebar-select/parent.tsx

When clicking the parent issue button area, the selection is cleared instead of opening the modal. Only the 'x' icon should deselect the selection.
Resolve this problem by designing two buttons within a div to function independently.
---
This issue is connected to the issue raised by GitHub user #3229 .

fix: issue parent select

---

nginx/nginx.conf.dev
nginx/nginx.conf.template

Since the proxy server is running with Nginx, it is recommended to add the relevant proxy header to use Web Socket. The relevant documentation is shared below.
Reference: [Nginx WebSocket Proxying documentation](https://nginx.org/en/docs/http/websocket.html)

fix websocket connection issue in docker makeplane/plane#3195

---

web/components/core/theme/theme-switch.tsx
web/components/issues/issue-layouts/roots/project-layout-root.tsx

1. When using custom theming, the Background color is breaking in the Kanban layout leading to bad user experience.
2. Theme Dropdown is overlapping with the color picker icons.
1. Added correct background color to the layout.
2. Fixed `z-index` issue within the dropdown.

Style: custom theme UI fixes

---

packages/editor/core/src/ui/extensions/table/table/table-view.tsx

Fixed error of table not being defined while getting getBoundingClientRect() and solved the following TS issues as well.
- Added ResolvedPos import from @tiptap/pm/model
- Updated setCellsBackgroundColor function parameter type to string
- Declared ToolboxItem type for toolbox items
- Modified columnsToolboxItems and rowsToolboxItems to use the ToolboxItem type
- Updated createToolbox function parameters to specify Element or null for triggerButton and ToolboxItem[] for items
- Added ts-expect-error comment above the toolbox variable declaration
- Updated update method parameter type to readonly Decoration[]
- Changed destructuring assignment of hoveredTable and hoveredCell in updateControls method to use Object.values and reduce method
- Added null check for this.table in updateControls …

[chore]: Fixed table not being defined in getBoundingClientRect() and better TS support for tables

---

apiserver/.env.example

fix: removing redundant env example variables from the .env.example file

---

web/components/project/create-project-modal.tsx

Steps to reproduce:
- Type an Identifier in the Project create modal
- Put the cursor in the beginning of the typed identifier
- Observe - it will automatically move to end if you type anything
The cursor is behaving weird when typing happens and user puts it at the beginning of the Identifier.
The issue occured because of using `toUpperCase` on every change mutated the entire identifier to uppercase, causing the cursor to move unexpectedly. To solve this, I removed all toUpperCase methods to prevent unintended changes. Instead, I applied the uppercase Tailwind class to visually display the identifier in uppercase for users. And before sending it to our API endpoint, we still convert the data to uppercase, ensuring consistency without disrupting user input. …

fix: project identifier cursor behaviour in create project modal.

---

web/components/estimates/estimates-list.tsx
web/store/estimate.store.ts

Following the update to version v0.14-dev, there's a bug affecting the order of estimates. Users have reported that despite setting estimates in a specific order, the system automatically reorders them alphabetically upon saving. This behavior is a deviation from previous versions where the user-defined order was maintained.
**Steps to Reproduce**:
1. Go to the estimates page.
2. Create a new estimate or edit an existing one.
3. Enter estimates in a non-alphabetical order (e.g., 1, 2, 3, 5, 8, 12).
4. Save the estimates.
5. Reopen or edit the estimates and observe the reordering has changed. (1, 12, 2, 3, 5, 8)
The issue was due to unsorted data in the create/ update modal. The backend sends estimate points in `{key, value}` pairs, with keys indicating order. To resolve it, I sorted these …

fix: estimate order not maintained in create/ update modal.

---

web/components/command-palette/actions/workspace-settings-actions.tsx
web/components/core/sidebar/progress-chart.tsx
web/components/cycles/active-cycle-details.tsx
web/components/headers/cycle-issues.tsx
web/components/headers/module-issues.tsx
web/components/headers/project-view-issues.tsx
web/components/notifications/notification-card.tsx
web/components/notifications/notification-popover.tsx
web/components/project/card.tsx
web/components/ui/empty-space.tsx
web/layouts/settings-layout/project/layout.tsx
web/pages/create-workspace.tsx
web/pages/workspace-invitations/index.tsx
web/store/cycle.store.ts

This PR fixes the error in creating a new cycle, restructure the active cycles inside cycles store and review and replace router.pushes

fix: breaking cycle issues and replacing router.push with Links

---

web/hooks/store/use-page.ts
web/store/page.store.ts

- Updated Recent Pages Computation based on `updated_at` instead of `created_at`.
- Updated `usePage` hook, to return `IPageStore` instead of the whole context.

[FIX] Pages Malfunctioning on Load and Recent Pages Computation

---

web/components/issues/issue-layouts/kanban/base-kanban-root.tsx

This PR addresses issues with the drag and delete functionality in kanban that wasn't working as expected. I've added the necessary changes to ensure they now function correctly.

fix: drag and delete issue

---

web/components/issues/peek-overview/view.tsx

This PR includes implementation of the ESC to close functionality for the Peek Overview.

chore: esc to close peek overview 

---

README.md

Fixes the link as it leads to a 404 at the moment in the documentation / readme.

fix: self-hosting docker-compose doc link update

---

package.json
turbo.json
yarn.lock

We have a number of explicit dependencies in our turbo.json, which isn't necessary to do as it'll get very difficulty to maintain as no of dependencies go up since turborepo automatically manages it using it's task dependency graph.
This PR uses the topological relationship provided by the `^` operator in `turbo.json`
```json
"build": {
"dependsOn": [
"^build"
],
},
```
The `^build` syntax means that when we run `turbo run build`, then this `build` command of a particular package (be it web/space/editor/ui, first run the `build` commands of their respective dependencies. 
I've done the same with `develop` command (that helps us run `yarn dev` to automatically run `turbo run develop` in web and space projects for better DX) and the `dev` command (for other packages) to automatically first …

[chore]: Removed explicit dependencies and cleaned up turbo config

---

web/components/issues/issue-layouts/calendar/roots/project-view-root.tsx
web/components/issues/issue-layouts/gantt/project-view-root.tsx
web/components/issues/issue-layouts/kanban/roots/project-view-root.tsx
web/components/issues/issue-layouts/list/roots/project-view-root.tsx
web/components/issues/issue-layouts/roots/project-view-layout-root.tsx
web/components/issues/issue-layouts/spreadsheet/roots/project-view-root.tsx
web/components/views/form.tsx
web/components/views/modal.tsx
web/store/project-view.store.ts

This PR contains multiple bug fixes related to mobx store refactor in project views:
1. [chore: remove debounce logic to fix create/ update view modal bugs.](https://github.com/makeplane/plane/commit/6a4dda353ffed57b41b217be5cf10eb72e71b35f)
2. [fix: bug in delete views not mutating the store.](https://github.com/makeplane/plane/commit/87da2e9e82c0729433fe963a2fbe88254211fbd4)
3. [chore: replace Project Empty State with Project Views Empty State.](https://github.com/makeplane/plane/commit/1ef13764fc11be825ad2846e3f8ba698dc780e7c)
4. [chore: add issue peek overview.](https://github.com/makeplane/plane/commit/1a6e5dc41904af6120ed1bf6021dcdb03e7d410e)
5. [refactor: issue update, delete actions for project views layout.](https://github.com/makeplane/plane/commit/748a8a7caab7aeb1755f4ad7cd7efee …

fix: project views bugs related to store refactor.

---

web/components/headers/workspace-active-cycle.tsx
web/components/workspace/sidebar-menu.tsx

In this PR, I added a beta tag to the workspace active cycles.
Light Mode:            |  Dark Mode:

chore: workspace active cycles improvement

---

web/components/integration/slack/select-channel.tsx

Slack's "Disable Integration" button wasn't working due to missing parameters in the `SLACK_CHANNEL_INFO` fetch key.
Fixed by adding `workspaceSlug` and `projectId` parameters to the fetch key, enabling the correct mutation and resolving the issue.

fix: stack integration disable button mutation issue in project settings.

---

packages/editor/core/src/ui/components/editor-container.tsx
packages/editor/extensions/src/extensions/drag-drop.tsx
packages/editor/rich-text-editor/src/ui/extensions/index.tsx
packages/editor/rich-text-editor/src/ui/index.tsx

This fix adds support for hiding the drag handle when the cursor leaves the editor container by figuring out a way to communicate between the Drag-Drop Plugin's native methods and our web app.
It improves the user experience by providing a cleaner interface and removing unnecessary visual elements especially while scrolling when the drag handle is visible at the wrong places even when your cursor is out of the container.
- Added `hideDragHandle` prop to `EditorContainer` component in `editor-container.tsx`.
- Implemented `onMouseLeave` event handler in `EditorContainer` to invoke `hideDragHandle` function that the Drag-Drop plugin exposes.
- Updated `DragAndDrop` extension in `drag-drop.tsx` to accept a `setHideDragHandle` function as an optional parameter.
- Pass the `setHideDragHandle` …

fix: Drag drop handle's behavior fixed on mouse leave

---

web/components/command-palette/command-palette.tsx
web/components/issues/issue-layouts/empty-states/module.tsx
web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
web/components/issues/issue-layouts/kanban/default.tsx
web/components/issues/issue-layouts/kanban/headers/group-by-card.tsx
web/components/issues/issue-layouts/kanban/roots/cycle-root.tsx
web/components/issues/issue-layouts/kanban/roots/module-root.tsx
web/components/issues/issue-layouts/kanban/roots/profile-issues-root.tsx
web/components/issues/issue-layouts/kanban/roots/project-root.tsx
web/components/issues/issue-layouts/kanban/roots/project-view-root.tsx
web/components/issues/issue-layouts/kanban/swimlanes.tsx
web/components/issues/issue-layouts/list/base-list-root.tsx
web/components/issues/issue-layouts/list/default.tsx
web/components/issues/issue-layouts/list/headers/group-by-card.tsx
web/components/issues/issue-layouts/list/roots/archived-issue-root.tsx
web/components/issues/issue-layouts/list/roots/cycle-root.tsx
web/components/issues/issue-layouts/list/roots/draft-issue-root.tsx
web/components/issues/issue-layouts/list/roots/module-root.tsx
web/components/issues/issue-layouts/list/roots/profile-issues-root.tsx
web/components/issues/issue-layouts/list/roots/project-root.tsx
web/components/issues/issue-layouts/list/roots/project-view-root.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/all-issue.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/cycle-issue.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/module-issue.tsx
web/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx
web/components/issues/issue-modal/form.tsx
web/components/issues/issue-modal/modal.tsx
web/store/issue/cycle/issue.store.ts
web/store/issue/module/issue.store.ts

This PR refactors the create/ update issue modal to use currently active store's methods to handle create/ update functionality instead of handling it manually for each task (add issue, add issue to cycle, add to issue to module, add issue to views). 
This allows us to handle adding issue to cycle/ module/ views at store level itself rather than handling it manually.

refactor: update `create/update issue` modal to use currently active store's create/update method.

---

web/store/issue/archived/filter.store.ts
web/store/issue/cycle/filter.store.ts
web/store/issue/draft/filter.store.ts
web/store/issue/module/filter.store.ts
web/store/issue/profile/filter.store.ts
web/store/issue/project-views/filter.store.ts
web/store/issue/project/filter.store.ts
web/store/issue/workspace/filter.store.ts

This PR includes improvements to the issue filter loader. Previously, there was a flickering issue when clearing applied filters, displaying an empty state for a fraction of a second. I've now included a loader to provide a smoother transition during the fetching process.

chore: issue filter loader improvement

---

web/components/command-palette/actions/workspace-settings-actions.tsx
web/components/headers/workspace-active-cycle.tsx
web/components/workspace/sidebar-menu.tsx
web/constants/dashboard.ts
web/constants/profile.ts
web/constants/project.ts
web/constants/workspace.ts
web/layouts/settings-layout/profile/sidebar.tsx
web/layouts/settings-layout/project/sidebar.tsx
web/layouts/settings-layout/workspace/sidebar.tsx

We faced inconsistency using Sidebar links locally across components, leading to issues when we needed the same links in places like the command pallet menu.
Centralized all link constants into their own file to ensure consistency and ease of use in different parts of the application. 
* Improved logic for links highlight and user role access.
* Fixed the display of the `Beta` label in the active cycle and removed it from the collapsed sidebar.

refactor: move all sidebar links to constant file.

---

web/components/account/o-auth/o-auth-options.tsx
web/store/project/project.store.ts

The existing implementation of the `workspaceProjectIds` and `searchedProjects` functions within the project store is not accurately filtering projects to match the current workspace. Instead, it retrieves all projects from the store.
Implemented a fix by adding the necessary filtering logic to ensure that only projects belonging to the current workspace are returned by the `workspaceProjectIds` and `searchedProjects` functions.

fix: project store computed function filtering logic

---

web/components/cycles/modal.tsx
web/components/issues/delete-issue-modal.tsx
web/components/issues/peek-overview/view.tsx
web/components/project/form.tsx

- Currently, two messages are displayed upon deleting an issue (Peek overview ), and the peek overview does not close automatically after deletion. [[PLE-282](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/af8ba608-8943-4760-82b1-b8bd97f95f61)]
- Following the creation of the cycle it should navigate to the "All Cycles" tab instead of  "Active Cycle" tab. [[PLE-278](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/61379a15-caf2-43dd-9601-a5ce8395cfd1)]
- Address issue deletion issue by removing extra toast alert from action and on delete close peek overview action added.
- Rectify the cycle creation problem by updating the navigation to switch to the "All Cycles" tab automatically after a cycle has been successfully created. …

chore: bug fixes and improvement

---

web/components/issues/peek-overview/root.tsx
web/components/project/card-list.tsx
web/store/project/project.store.ts

1. After creating a new project, user is not able to update issue properties from the peek overview until the app is refreshed.
1. 'workspaceProjectRole' observable needs to be updated after creating a new project.
1. Fixed the authorization for projects list empty state.
https://github.com/makeplane/plane/assets/65252264/aeecaeb6-06c5-425c-a0d6-168f04c255d9

chore: fix authorization for new projects in the peek overview

---

web/components/integration/delete-import-modal.tsx

Users couldn't delete imports because the confirmation input field in the delete import modal wasn't updating.
Fixed by removing `value=""` from the input, enabling proper input updates and allowing users to delete imports smoothly.

fix: input field value not changing in delete import modal.

---

packages/editor/core/package.json
packages/editor/core/src/lib/editor-commands.ts
packages/editor/core/src/ui/extensions/code-inline/index.tsx
packages/editor/core/src/ui/menus/menu-items/index.tsx

Inline code blocks are now exitable with the right arrow key and inclusive at the same time.
Key behaviours
1. Only recognises inline code blocks if typed in the format left prefix (backtick)--> inline code text --> right prefix(backtick), this is the intended behaviour incase as explained in https://github.com/makeplane/plane/pull/3318
2. Inline code blocks can be triggered by using the bubble menu on selecting text (regression) in Rich text editors.
3. To exit a code block, use the right arrow key and to get inside and start typing again use the left arrow key (backspace won't work as it's intended)
4. Added a behaviour in which-->
1. If you select any amounts of text and then click on the button for toggling code, then it'll make it inline code. 
2. If your cursor is just at some node …

fix: inline codes now exitable with right arrow key and inclusive

---

packages/editor/core/src/ui/components/editor-container.tsx

When a user tried to check/uncheck of a todo inside the editor, the whole todolist scroll till the position of the cursor.
https://github.com/makeplane/plane/assets/72302948/b44f54a2-1b60-4b2e-af27-c50f22438bfe
https://github.com/makeplane/plane/assets/72302948/3701f88d-63cf-4e0e-a2d7-7bd4abdb80b1

fix: fixed checklist scrolling on click

---

web/components/dropdowns/date.tsx

Date dropdown not getting closed on clicking outside.
Replaced `Popover` with `Combobox` for `ref` to work.
Before fix-
https://github.com/makeplane/plane/assets/65252264/8f174893-d1a0-4c8c-95da-ce8a83eba476
After fix-
https://github.com/makeplane/plane/assets/65252264/3cca762e-291b-466a-9ffe-657264c2036f

fix: date dropdown not getting closed on clicking outside

---

web/components/pages/pages-list/archived-pages-list.tsx
web/store/project-page.store.ts

There was a flickering effect observed in the empty state when reloading pages.
The problem stemmed from maintaining a single loader in the store for two fetch endpoints, resulting in the mentioned issue. This has been addressed by introducing a separate loader in the store.

fix: project pages loader

---

web/components/dashboard/widgets/issues-by-priority.tsx
web/components/dashboard/widgets/issues-by-state-group.tsx
web/components/dropdowns/cycle.tsx
web/components/dropdowns/date.tsx
web/components/dropdowns/estimate.tsx
web/components/dropdowns/member/buttons.tsx
web/components/dropdowns/member/project-member.tsx
web/components/dropdowns/member/workspace-member.tsx
web/components/dropdowns/module.tsx
web/components/dropdowns/priority.tsx
web/components/dropdowns/project.tsx
web/components/dropdowns/state.tsx
web/components/dropdowns/types.d.ts
web/components/issues/issue-layouts/properties/all-properties.tsx
web/public/empty-state/dashboard/light/overdue-issues.svg

Tooltips were missing from dropdown buttons, causing confusion in the list and kanban layouts.
Added an additional prop to toggle tooltip for the dropdown buttons to each dropdown component.
1. Dashboard widgets' empty state vertical alignment.

chore: added tooltip to dropdowns

---

web/components/core/modals/existing-issues-list-modal.tsx

Existing issues list modal not closing on pressing the Escape key or on clicking outside.
Added the missing `onClose` function to the `Dialog`.

fix: issues list modal not closing on escape key

---

web/components/issues/issue-detail/root.tsx
web/components/issues/issue-layouts/empty-states/cycle.tsx
web/components/issues/issue-layouts/empty-states/module.tsx
web/components/issues/peek-overview/root.tsx

There was an issue with mutations not being reflected in the issue peek overview, issue sidebar, and the empty state when adding existing buttons for the module and cycle.
This problem has been addressed by updating the corresponding issue in the store and subsequently fetching it immediately after the update.

fix: resolve module and cycle mutation issues in peek overview, issue sidebar and empty state

---

web/components/dropdowns/types.d.ts
web/store/issue/issue-details/issue.store.ts
web/store/issue/issue.store.ts

Fetching issue relations(which have minimal issue information) was replacing all the information related to that issue in the `issueMap`.
Update the `addIssue` function to only add issue to the `issueMap` if the issue doesn't exist already.

fix: add issue to store only if the issue doesn't exist

---

web/components/core/modals/existing-issues-list-modal.tsx
web/components/issues/issue-detail/label/create-label.tsx
web/components/issues/issue-layouts/filters/applied-filters/roots/profile-issues-root.tsx
web/components/issues/issue-layouts/roots/all-issue-layout-root.tsx
web/hooks/use-workspace-issue-properties.ts
web/lib/app-provider.tsx
web/store/estimate.store.ts
web/store/issue/workspace/filter.store.ts

This PR includes applying the following steps
1. Applying the query params from the URL to the issue filters in all issues
2. Typo file names and import updates
3. Labels loader and disable the input field in the peek overview and issue detail
4. Resolved while updating the relations in the issues modal the issue is reloading

chore: applying query params to the global issues filters in the global views

---

web/store/issue/archived/filter.store.ts
web/store/issue/cycle/filter.store.ts
web/store/issue/draft/filter.store.ts
web/store/issue/module/filter.store.ts
web/store/issue/profile/filter.store.ts
web/store/issue/project-views/filter.store.ts
web/store/issue/project/filter.store.ts
web/store/issue/workspace/filter.store.ts

- The spreadsheet layout exhibited repetitive child issues without a toggle option, unlike other layouts.
- To rectify this issue, I have configured show_sub_issue to false specifically for spreadsheet issues, aligning with the expected behavior.

chore: spreadsheet layout improvement

---

web/components/core/modals/existing-issues-list-modal.tsx
web/components/issues/issue-detail/relation-select.tsx
web/components/issues/issue-detail/root.tsx
web/components/issues/issue-layouts/empty-states/cycle.tsx
web/components/issues/issue-layouts/empty-states/module.tsx
web/components/issues/issue-layouts/kanban/headers/group-by-card.tsx
web/components/issues/issue-layouts/list/headers/group-by-card.tsx
web/components/issues/peek-overview/root.tsx
web/components/issues/sub-issues/root.tsx
web/store/issue/cycle/issue.store.ts
web/store/issue/module/issue.store.ts

- The "Add to cycle" and "Add to module" mutations were not working in the Issue Peek Overview and Issue Sidebar.
- The Issue Relation modal failed to render any issues within the workspace in the Issue Peek Overview.
- Rectified the issue by fixing the logic for mutating issues related to "Add to cycle" and "Add to module" functionalities in both Peek Overview and Issue Sidebar.
- Previously, the workspace slug and project ID were obtained from the router. This has been resolved by now passing the workspace slug and project ID as props.

chore: issue relation modal and issue peek overview mutation fix

---

web/components/issues/issue-modal/modal.tsx

This PR addresses the issue related to updating pre-loaded data for both cycles and modules in create update issue modal.

fix: issue preload data in issue create update modal

---

web/components/issues/issue-layouts/filters/header/filters/labels.tsx
web/components/issues/issue-layouts/filters/header/filters/project.tsx
web/components/issues/issue-layouts/kanban/block.tsx
web/components/issues/issue-layouts/kanban/blocks-list.tsx
web/store/issue/helpers/issue-filter-helper.store.ts
web/store/issue/workspace/filter.store.ts

This PR fixes the following issues,
- Fix mutation issues in filters for project and label filters
- Fix filters in all issues where state groups were not being applied
- Disable dnd in Kanban for guests and viewers

fix: Filters in all issues and enable dnd in kanban based on roles

---

web/components/notifications/notification-header.tsx
web/constants/issue.ts
web/hooks/use-user-notifications.tsx
web/store/issue/helpers/issue-filter-helper.store.ts

This PR fixes the missing project and subscriber filter params for the issue filter params and also adds a toast message for marking all notifications as read.

fix: Add missing project and subscriber filters to the list of filter params

---

web/components/cycles/form.tsx
web/components/cycles/modal.tsx

This PR fixes an issue where the project ID wasn't updating correctly when switching projects in the cycle modal. Added necessary logic for proper functionality during project changes.

fix: project id update in create update cycle modal

---

web/components/issues/issue-layouts/properties/all-properties.tsx

Assignee tooltip logic was inconsistent in list and Kanban layouts resulting in different kind of tooltip content being shown.
Removed the `tooltip` prop, which was responsible for showing combined tooltip with just total count instead of names of individual assignees.

chore: fix assignee tooltip logic in list and Kanban layout for consistency.

---

web/components/gantt-chart/blocks/blocks-display.tsx
web/components/gantt-chart/sidebar/sidebar.tsx
web/components/issues/issue-layouts/calendar/issue-blocks.tsx
web/components/issues/issue-layouts/kanban/block.tsx
web/components/issues/issue-layouts/kanban/blocks-list.tsx
web/components/issues/issue-layouts/kanban/default.tsx
web/components/issues/issue-layouts/kanban/kanban-group.tsx
web/components/issues/issue-layouts/list/block.tsx
web/components/issues/issue-layouts/list/blocks-list.tsx
web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
web/components/issues/issue-layouts/spreadsheet/spreadsheet-table.tsx

This PR introduces an issue highlighter feature for the list, kanban, calendar, spreadsheet, and gantt layouts. Now, whenever an issue is open, it will be visibly highlighted in the respective layout, providing a clear indication of the opened issue.
This enhancement is associated with the issue [[PLE-301]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/d7a8d1f1-6971-455f-ad41-6302d3d64c42).

feat: issue highlighting

---

web/constants/issue.ts

This PR fixes the custom views by defining issue filters for list in global issues. 
This had to be done because, the data of the custom views seems to be corrupted to show issue layout for some views as "list" instead of "spreadsheet". Adding this to fix it for now. 
By default when creating a new view it adds "spreadsheet" as issue layout as it should.

fix: all issues custom views by defining list layout for my-issue

---

web/components/issues/draft-issue-form.tsx

This PR addresses the focus issue in the draft issue modal, which was causing problems with the issue description. Now, when a user attempts to type the description, the focus no longer shifts to the title. This has been resolved by separating the focus and preload functionalities in the useEffect.

fix: draft issue modal

---

packages/editor/core/src/ui/mentions/custom.tsx
packages/editor/core/src/ui/mentions/suggestion.ts
packages/editor/lite-text-editor/src/ui/extensions/enter-key-extension.tsx
packages/editor/lite-text-editor/src/ui/extensions/index.tsx
web/components/issues/issue-detail/issue-activity/comments/comment-create.tsx

Added back the enter key extension at #2530, but this time working with Mentions
1. **Comment Editor's Features**
The enter key is now remapped to submit the comment, while the 'shift-enter' key is mapped to the default enter key behavior. The edge cases for the various data structures/scenarios present in the comment editor have been handled as follows:
1. **Code Blocks**: When the cursor is inside a code block, "Shift-Enter" inserts a newline character at the current cursor position, creating a new line within the code block.
2. **List Items**: When the cursor is inside a list item, "Shift-Enter" will split the list item at the current cursor position, creating a new list item below the current one.
End of Blocks: When the cursor is at the end of a block, "Shift-Enter" creates a new …

fix: Adding back enter key extension with mentions

---

web/components/integration/jira/give-details.tsx

1. Jira importer cloud hostname field should not contain `http://` or `https://`.
1.  Added validation to the cloud hostname input field to check for `http://` or `https://` at the beginning of the string.
1. Added proper error messages for all the other fields as well.
https://github.com/makeplane/plane/assets/65252264/1c75bbeb-7d9b-45b8-9b02-a5e030cd9556

chore: added validation to cloud hostname field

---

packages/ui/src/breadcrumbs/breadcrumbs.tsx
web/components/common/breadcrumb-link.tsx
web/components/common/index.ts
web/components/headers/cycle-issues.tsx
web/components/headers/cycles.tsx
web/components/headers/global-issues.tsx
web/components/headers/module-issues.tsx
web/components/headers/modules-list.tsx
web/components/headers/page-details.tsx
web/components/headers/pages.tsx
web/components/headers/profile-preferences.tsx
web/components/headers/profile-settings.tsx
web/components/headers/project-archived-issue-details.tsx
web/components/headers/project-archived-issues.tsx
web/components/headers/project-draft-issues.tsx
web/components/headers/project-inbox.tsx
web/components/headers/project-issue-details.tsx
web/components/headers/project-issues.tsx
web/components/headers/project-settings.tsx
web/components/headers/project-view-issues.tsx
web/components/headers/project-views.tsx
web/components/headers/projects.tsx
web/components/headers/user-profile.tsx
web/components/headers/workspace-active-cycles.tsx
web/components/headers/workspace-analytics.tsx
web/components/headers/workspace-dashboard.tsx
web/components/headers/workspace-settings.tsx
web/layouts/admin-layout/header.tsx

This PR introduces enhancements to the breadcrumb component. Previously, when navigating through nested routes and clicking on the breadcrumb to return, the page was reloading. I've implemented necessary adjustments and modifications to enhance the user experience, ensuring smoother navigation without the need for page reloads.

chore: breadcrumb component improvement

---

web/components/issues/issue-modal/modal.tsx

This PR addresses a bug reported by user #3543  related to project selection. The issue occurred when selecting a different project from the project menu, resulting in the unintended creation of an issue in the currently active project.
I have successfully resolved this issue and implemented the necessary changes to ensure a smooth project selection experience without the unintended creation of issues.

fix: create issue modal project select

---

packages/ui/src/icons/priority-icon.tsx
web/components/account/deactivate-account-modal.tsx
web/components/dashboard/widgets/dropdowns/duration-filter.tsx
web/components/dashboard/widgets/issue-panels/issues-list.tsx
web/components/dashboard/widgets/overview-stats.tsx
web/components/headers/workspace-dashboard.tsx
web/layouts/app-layout/sidebar.tsx

This PR contains the following fixes
1. Over all stats in dashboard styling fixes.
2. Priority icons padding fixes in dashboard.
3. Dashboard dropdown's overflowing fix.
https://github.com/makeplane/plane/assets/31303617/ce6e41c3-8e35-42ad-9934-1faa4152b3d4
https://github.com/makeplane/plane/assets/31303617/08115779-6ef5-43d4-b4fb-f01747850716

chore: responsive and styling fixes

---

apiserver/plane/api/views/cycle.py
apiserver/plane/api/views/issue.py
apiserver/plane/api/views/module.py
apiserver/plane/api/views/state.py

- Added validation for external source and external id in issue, cycle, module and states which will cause a validation error if the same external source and external id is already created with a status of `409 Conflict`.

dev: validation for external id and external source

---

apiserver/plane/app/views/cycle.py
apiserver/plane/app/views/module.py
packages/ui/src/icons/priority-icon.tsx
web/components/core/sidebar/progress-chart.tsx
web/components/cycles/sidebar.tsx
web/components/modules/sidebar.tsx
web/layouts/app-layout/sidebar.tsx
web/store/cycle.store.ts
web/store/issue/cycle/issue.store.ts
web/store/issue/module/issue.store.ts
web/store/module.store.ts

Resolved an issue where the graph was not instantly mutating in the Cycle and Module sidebar when an issue was updated, start or end date updated. Previously, users had to hard reload to see the changes. This has been addressed by updating the action in the store.
---
Rectified a issue where the sidebar stats incorrectly displayed zero for unassigned issues, even when some issues were not assigned to anyone (same with labels). The retrieval logic has been updated, along with necessary adjustments, to ensure accurate stats.
---
Implemented various enhancements to improve the overall functionality and user experience of the sidebar stats.
---
- Corrected the z-index of the app sidebar to ensure proper layering and display.
- Addressed the view box issue …

chore: cycle and module sidebar analytics improvement

---

apiserver/plane/db/models/user.py

- now for the new users the email notification will not be triggered by default

chore: email notification turned off for new users

---

deploy/selfhost/install.sh

Fixes for issues raised by community
- #3529 
- #3557

fix: APP_RELEASE default value handled

---

apiserver/plane/api/views/cycle.py
apiserver/plane/api/views/issue.py
apiserver/plane/api/views/module.py
apiserver/plane/api/views/state.py

chore:
- Remove `*_id` as the key and add a uniform `id` as the key for all entity types
**Before**
```
{
"error": "Issue with the same external id and external source already exists",
"issue_id": "d63d49c7-****-4309-9cc9-0434edcc****"
}
```
**After**
```
{
"error": "Issue with the same external id and external source already exists",
"id": "d63d49c7-****-4309-9cc9-0434edcc****"
}
```

chore: update api responses for conflict errors

---

web/components/headers/workspace-dashboard.tsx
web/components/workspace/workspace-active-cycles-upgrade.tsx

- Resolved Z-index issue in the dashboard header, preventing overlap with the profile dropdown.
- Enhanced responsiveness of the workspace active cycles upgrade page.

fix: dashboard header z index and workspace active cycles fix

---

web/components/command-palette/shortcuts-modal/modal.tsx
web/components/issues/issue-layouts/list/block.tsx
web/components/issues/issue-layouts/roots/draft-issue-layout-root.tsx
web/components/project/create-project-modal.tsx
web/components/views/modal.tsx
web/store/issue/draft/issue.store.ts

- Ensured consistency across project, view, and shortcut modal.
- Fixed list layout issue: bottom border missing for last issue when issue is highlighted.
- Resolved peek overview bug in draft issue and enabled inline editing for member and admin roles.

fix: draft issue peek overview

---

apiserver/plane/api/views/base.py
apiserver/plane/app/views/base.py
apiserver/plane/bgtasks/email_notification_task.py
apiserver/plane/bgtasks/notification_task.py
apiserver/plane/bgtasks/webhook_task.py
apiserver/plane/settings/common.py
apiserver/templates/emails/notifications/issue-updates.html
apiserver/templates/emails/notifications/webhook-deactivate.html

This PR addresses the following bugs:
- It corrects the payload structure for the mentioned user in the comment. Previously, Celery was encountering errors due to the incorrect structure generated for the mentioned user.
- It also resolves a bug where the issue no longer exists. If changes were made to an issue and then the issue was later deleted, Celery would throw an error stating that the issue does not exist. This occurred because email notifications were triggered every 5 minutes.
- When a webhook encounters a failure, it previously persisted in making requests using the retry mechanism. However, with this update, if the requests fail repeatedly for five times, the webhook's state will be automatically changed to 'disabled'. Additionally, an email notification will be sent to the …

chore: mention notification and webhook faliure

---

web/components/issues/issue-modal/form.tsx

This PR includes:
- Resolved an issue that when we click an enter on the issue create modal the issue has to be created.

fix: handled issue create modal submission on clicking enter key

---

web/components/analytics/custom-analytics/custom-analytics.tsx
web/components/analytics/custom-analytics/select-bar.tsx
web/components/analytics/custom-analytics/sidebar/projects-list.tsx
web/components/analytics/custom-analytics/sidebar/sidebar-header.tsx
web/components/analytics/custom-analytics/sidebar/sidebar.tsx
web/components/analytics/project-modal/main-content.tsx
web/components/headers/user-profile.tsx
web/components/headers/workspace-analytics.tsx
web/components/profile/sidebar.tsx
web/pages/[workspaceSlug]/analytics.tsx
web/store/application/theme.store.ts

This PR contains the following updates
1. Responsive workspace level analytics.
2. Responsive project level analytics.
3. Responsive cycle analytics.
4. Responsive module analytics.
https://github.com/makeplane/plane/assets/31303617/e0b0c769-4596-4ef0-8668-ffd1604fcd1a
https://github.com/makeplane/plane/assets/31303617/1a207e60-aa72-4093-a6c4-b16725e663a4
https://github.com/makeplane/plane/assets/31303617/9e461935-b0dd-41d1-9aff-13dd7a34d618
https://github.com/makeplane/plane/assets/31303617/3727ac36-668d-41a9-9136-a58a0d88efdf

style: responsive analytics

---

web/components/page-views/workspace-dashboard.tsx

1. The app tour modal is not visible to a new user until they are part of a project.
1. Moved the app tour modal outside of the required project condition in the dashboard component.

chore: show project tour modal before project creation

---

web/constants/issue.ts

The current sorting order for the `order_by` display filter set to `priority` is incorrect, displaying lowest/no priority issues at the top instead of the intended highest priority ones.
Updated the filter to sort it from `highest to lowest` priority.

fix: priority sort order in display filters.

---

docker-compose-local.yml

"The reason is values yes and no are evaluated as true or false. That is why you need to use double quotes so that it is interpreted as string."
Ref: [Stackoverflow answer](https://stackoverflow.com/a/46233453/5081894)

fix local development setup issue makeplane/plane#3641

---

web/components/gantt-chart/blocks/blocks-list.tsx

1. Scroll difference between the sidebar and the blocks container
| <video src="https://github.com/makeplane/plane/assets/65252264/3e933b5d-a941-4f96-9307-ec2cd009b40e" /> | <video src="https://github.com/makeplane/plane/assets/65252264/0dd5b890-8c8f-4e52-ba1c-d118d9e3d5b1" /> |

fix: scroll sync for the sidebar and blocks

---

packages/types/src/projects.d.ts
web/components/core/modals/existing-issues-list-modal.tsx
web/components/issues/issue-layouts/empty-states/module.tsx
web/components/issues/issue-layouts/kanban/headers/group-by-card.tsx
web/components/issues/issue-layouts/list/headers/group-by-card.tsx

This PR addresses a persistent issue within the "Add Existing Issue" modal, where API calls were erroneously triggered continuously. The problem occurred specifically when the modal was open, and an issue within the same module was displayed.

fix: add existing issue modal

---

web/components/issues/issue-layouts/kanban/utils.ts

This PR fixes manual sort order within the same list by using the modified list instead of destination list if the source and destination id is same.

fix: sort order in the same list for Kanban

---

web/components/profile/profile-issues.tsx
web/store/issue/profile/issue.store.ts
web/store/issue/workspace/issue.store.ts

This PR has changes to fix issue spillover while switching workspaces, changes include -
- use unique compound id to access global issues
- use unique compound id to access profile issues
- fix infinite loader in profile issues when issues are empty
- fix spillover of issues while views in profile views

fix: issue spillover on switching workspace

---

web/components/issues/issue-layouts/empty-states/cycle.tsx
web/components/issues/issue-layouts/empty-states/module.tsx
web/components/issues/issue-layouts/roots/cycle-layout-root.tsx
web/components/issues/issue-layouts/roots/module-layout-root.tsx

This PR includes enhancements for the module and cycle empty filter state. Previously, when applying a filter, if no issues were present with that filter, it displayed a "no issue" empty state instead of the intended empty filter state. I've rectified and resolved this issue.

chore: module & cycle empty state improvement

---

web/components/issues/description-form.tsx

This PR resolves the initial loading bug in the peek overview issue description. Previously, the issue description failed to load initially due to overlooked edge cases. I have addressed and made necessary changes to ensure it now functions as expected.

fix: peek overview issue description initial load bug

---

web/components/dropdowns/cycle.tsx
web/components/dropdowns/estimate.tsx
web/components/dropdowns/member/project-member.tsx
web/components/dropdowns/member/workspace-member.tsx
web/components/dropdowns/module.tsx
web/components/dropdowns/priority.tsx
web/components/dropdowns/project.tsx
web/components/dropdowns/state.tsx
web/components/issues/peek-overview/view.tsx
web/components/issues/select/label.tsx

1. The dropdown input search wasn't being focused on when the dropdown was opened.
2. In the peek overview dropdown, the positioning was not adjusting based on available space.
1. To address this, an autofocus logic has been implemented.
2. The issue occuring from redundant overflow classes applied to the parent div, resulting in improper positioning. Adjustments have been made to rectify this and ensure proper functionality.
Additionally, the logic for fetching dropdown options for  modules and cycles has been updated.

chore: dropdown and peek overview improvement

---

web/components/core/theme/custom-theme-selector.tsx

When users attempt to select a color in the profile theme settings, the color picker unintentionally modifies the background color of nearby input fields, causing confusion and potential interference with the intended customization process.
To address the issue of unintended style changes to input fields based on selected background and text colors in the theme settings, we propose implementing a more precise and controlled application of styles. This entails refining the styling mechanism to specifically target the desired elements without affecting adjacent input fields.
- Profile Theme Prefrences

fix: color pick background color on change effecting other input fields

---

web/components/issues/description-input.tsx
web/components/issues/issue-detail/inbox/main-content.tsx
web/components/issues/issue-detail/main-content.tsx
web/components/issues/issue-layouts/roots/archived-issue-layout-root.tsx
web/components/issues/peek-overview/header.tsx
web/components/issues/peek-overview/index.ts
web/components/issues/peek-overview/issue-detail.tsx
web/components/issues/peek-overview/view.tsx
web/components/issues/title-input.tsx

This update addresses two critical issues affecting the Issue Description Editor:
1. Editor Focus Loss: Previously, upon saving updates to the issue description, the focus on the editor was lost, disrupting the user experience. We've implemented a solution where the issue description component maintains its focus even after updates are saved, ensuring a smoother editing experience.
2. Persistent Data from Previous Issues: Moving between issues resulted in the persistence of old issue description data in the current issue, causing confusion and potential data errors. To mitigate this, we've revamped the issue description component to manage its state locally, preventing the retention of outdated data when navigating between issues.
Affected Places:
1. Issue Peek Overview
2. Issue Detail
3. …

fix: improved issue description editor focus and state management

---

packages/editor/rich-text-editor/src/ui/index.tsx
web/components/issues/description-input.tsx
web/components/issues/issue-detail/inbox/main-content.tsx
web/components/issues/issue-detail/main-content.tsx
web/components/issues/peek-overview/issue-detail.tsx

This update addresses a critical issue affecting the rendering of content within the Issue Description Editor when the description is empty.
Affected places:
1. Issue peek overview
2. issue detail
3. project inbox

fix: issue description empty state initial load in inbox and issue detail page

---

web/components/project/form.tsx
web/layouts/settings-layout/project/layout.tsx
web/layouts/settings-layout/project/sidebar.tsx
web/pages/[workspaceSlug]/projects/[projectId]/settings/index.tsx

1. Upon loading the general settings page of the project, if a user enters information into the description field immediately after the page loads, the description is being reset to its initial state.
1. A useEffect hook was causing this undesired reset behavior. As this useEffect was unnecessary, I made the necessary modifications to rectify the issue.
Additionally, project settings sidebar loader added.

fix: project description

---

web/components/workspace/sidebar-quick-action.tsx

In this PR, I've implemented validation for the "New Issue" button in the workspace sidebar, ensuring it's disabled when the user is not associated with any project.
This PR is linked to [[WEB-443]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/bcd67005-f05a-46cb-a52c-14a4aee8adb6).

chore: sidebar new issue button validation added

---

web/components/dashboard/widgets/recent-projects.tsx

This PR includes dashboard widget heading update from "Your projects" to "Recent projects", which is more descriptive of the widget.
This PR is linked to [[WEB-390]](https://app.plane.so/plane/projects/02c3e1d5-d7e2-401d-a773-45ecba45d745/issues/fd6594ab-522d-40b6-8280-e4a84f735ec7).

chore: dashboard widget heading updated

---

web/components/dropdowns/cycle.tsx

Problem:
Previously, the cycle dropdown presented users with a list of all cycles available in the project, leading to potential confusion and clutter, especially when numerous cycles were present.
Solution:
To enhance usability and clarity, we've implemented filtering within the cycle dropdown. Now, only cycles categorized as current, upcoming, and draft are displayed, streamlining the selection process and providing users with relevant options.
Affected Places:
1. Issue Creation Modal
2. Issue Peek Overview Modal
3. Issue Detail Page

[WEB-453]: rendering current, upcoming and draft cycles in the cycle dropdown
